.TH "scifir::size_2d< float >" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::size_2d< float >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsize_2d\fP (\fBconst\fP \fBsize_2d\fP< \fBfloat\fP > &x)"
.br
.ti -1c
.RI "\fBsize_2d\fP (\fBsize_2d\fP< \fBfloat\fP > &&x)"
.br
.ti -1c
.RI "\fBsize_2d\fP (\fBconst\fP \fBfloat\fP &\fBnew_width\fP, \fBconst\fP \fBfloat\fP &\fBnew_height\fP)"
.br
.ti -1c
.RI "\fBsize_2d\fP (\fBconst\fP \fBstring\fP &\fBnew_width\fP, \fBconst\fP \fBstring\fP &\fBnew_height\fP)"
.br
.ti -1c
.RI "\fBsize_2d\fP (\fBconst\fP \fBstring\fP &\fBinit_size_2d\fP)"
.br
.ti -1c
.RI "\fBsize_2d\fP< \fBfloat\fP > & \fBoperator=\fP (\fBconst\fP \fBsize_2d\fP< \fBfloat\fP > &x)"
.br
.ti -1c
.RI "\fBsize_2d\fP< \fBfloat\fP > & \fBoperator=\fP (\fBsize_2d\fP< \fBfloat\fP > &&x)"
.br
.ti -1c
.RI "\fBsize_2d\fP< \fBfloat\fP > \fBoperator+\fP (\fBconst\fP \fBsize_2d\fP< \fBfloat\fP > &x) \fBconst\fP"
.br
.ti -1c
.RI "\fBsize_2d\fP< \fBfloat\fP > \fBoperator\-\fP (\fBconst\fP \fBsize_2d\fP< \fBfloat\fP > &x) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator+=\fP (\fBconst\fP \fBsize_2d\fP< \fBfloat\fP > &x)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator\-=\fP (\fBconst\fP \fBsize_2d\fP< \fBfloat\fP > &x)"
.br
.ti -1c
.RI "\fBfloat\fP \fBget_area\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfloat\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBheight\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
