.TH "scifir::vector_unit_3d" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::vector_unit_3d
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBscifir::scalar_unit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvector_unit_3d\fP (\fBconst\fP \fBvector_unit_3d\fP &)"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP (\fBvector_unit_3d\fP &&)"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP (\fBfloat\fP, \fBconst\fP \fBstring\fP &, \fBfloat\fP, \fBfloat\fP)"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP (\fBfloat\fP, \fBconst\fP \fBstring\fP &, \fBconst\fP \fBangle\fP &, \fBconst\fP \fBangle\fP &)"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP (\fBfloat\fP, \fBconst\fP vector< \fBdimension\fP > &, \fBfloat\fP, \fBfloat\fP)"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP (\fBfloat\fP, \fBconst\fP vector< \fBdimension\fP > &, \fBconst\fP \fBangle\fP &, \fBconst\fP \fBangle\fP &)"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP (\fBconst\fP \fBscalar_unit\fP &, \fBfloat\fP, \fBfloat\fP)"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP (\fBconst\fP \fBscalar_unit\fP &, \fBconst\fP \fBangle\fP &, \fBconst\fP \fBangle\fP &)"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP (\fBconst\fP \fBstring\fP &, \fBfloat\fP, \fBfloat\fP)"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP (\fBconst\fP \fBstring\fP &, \fBconst\fP \fBangle\fP &, \fBconst\fP \fBangle\fP &)"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP (\fBconst\fP \fBstring\fP &)"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP & \fBoperator=\fP (\fBconst\fP \fBvector_unit_3d\fP &)"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP & \fBoperator=\fP (\fBvector_unit_3d\fP &&)"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP & \fBoperator=\fP (\fBconst\fP \fBscalar_unit\fP &)"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP & \fBoperator=\fP (\fBscalar_unit\fP &&)"
.br
.ti -1c
.RI "\fBvoid\fP \fBpoint_to\fP (direction::name)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator+=\fP (\fBconst\fP \fBvector_unit_3d\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator\-=\fP (\fBvector_unit_3d\fP)"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP \fBoperator+\fP (\fBconst\fP \fBvector_unit_3d\fP &) \fBconst\fP"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP \fBoperator\-\fP (\fBvector_unit_3d\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP \fBoperator*\fP (\fBconst\fP \fBscalar_unit\fP &) \fBconst\fP"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP \fBoperator/\fP (\fBconst\fP \fBscalar_unit\fP &) \fBconst\fP"
.br
.ti -1c
.RI "\fBvector_unit_3d\fP \fBoperator^\fP (\fBconst\fP \fBscalar_unit\fP &) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBU\fP , \fBtypename\fP  = typename enable_if<scifir::is_number<U>::value>::type> \fBvector_unit_3d\fP \fBoperator+\fP (\fBU\fP x) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBU\fP , \fBtypename\fP  = typename enable_if<scifir::is_number<U>::value>::type> \fBvector_unit_3d\fP \fBoperator\-\fP (\fBU\fP x) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBU\fP , \fBtypename\fP  = typename enable_if<scifir::is_number<U>::value>::type> \fBvector_unit_3d\fP \fBoperator*\fP (\fBU\fP x) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBU\fP , \fBtypename\fP  = typename enable_if<scifir::is_number<U>::value>::type> \fBvector_unit_3d\fP \fBoperator/\fP (\fBU\fP x) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBU\fP , \fBtypename\fP  = typename enable_if<is_integer_number<U>::value>::type> \fBvector_unit_3d\fP \fBoperator^\fP (\fBU\fP x) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBU\fP , \fBtypename\fP  = typename enable_if<scifir::is_number<U>::value>::type> \fBvoid\fP \fBoperator+=\fP (\fBU\fP y)"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBU\fP , \fBtypename\fP  = typename enable_if<scifir::is_number<U>::value>::type> \fBvoid\fP \fBoperator\-=\fP (\fBU\fP y)"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBU\fP , \fBtypename\fP  = typename enable_if<scifir::is_number<U>::value>::type> \fBvoid\fP \fBoperator*=\fP (\fBU\fP y)"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBU\fP , \fBtypename\fP  = typename enable_if<scifir::is_number<U>::value>::type> \fBvoid\fP \fBoperator/=\fP (\fBU\fP y)"
.br
.ti -1c
.RI "\fBscalar_unit\fP \fBx_projection\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBscalar_unit\fP \fBy_projection\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBscalar_unit\fP \fBz_projection\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBinvert\fP ()"
.br
.ti -1c
.RI "\fBstring\fP \fBvectorial_display\fP (\fBint\fP=2) \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBvectorial_derived_display\fP (\fBint\fP=2) \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBvectorial_custom_display\fP (\fBconst\fP \fBstring\fP &, \fBint\fP=2) \fBconst\fP"
.br
.in -1c

Public Member Functions inherited from \fBscifir::scalar_unit\fP
.in +1c
.ti -1c
.RI "\fBscalar_unit\fP (\fBconst\fP \fBscalar_unit\fP &)"
.br
.ti -1c
.RI "\fBscalar_unit\fP (\fBscalar_unit\fP &&)"
.br
.ti -1c
.RI "\fBscalar_unit\fP (\fBfloat\fP, \fBconst\fP \fBstring\fP &)"
.br
.ti -1c
.RI "\fBscalar_unit\fP (\fBdouble\fP, \fBconst\fP \fBstring\fP &)"
.br
.ti -1c
.RI "\fBscalar_unit\fP (\fBlong\fP \fBdouble\fP, \fBconst\fP \fBstring\fP &)"
.br
.ti -1c
.RI "\fBscalar_unit\fP (\fBfloat\fP, \fBconst\fP vector< \fBdimension\fP > &)"
.br
.ti -1c
.RI "\fBscalar_unit\fP (\fBdouble\fP, \fBconst\fP vector< \fBdimension\fP > &)"
.br
.ti -1c
.RI "\fBscalar_unit\fP (\fBlong\fP \fBdouble\fP, \fBconst\fP vector< \fBdimension\fP > &)"
.br
.ti -1c
.RI "\fBscalar_unit\fP (\fBconst\fP \fBstring\fP &)"
.br
.ti -1c
.RI "\fBscalar_unit\fP & \fBoperator=\fP (\fBconst\fP \fBscalar_unit\fP &)"
.br
.ti -1c
.RI "\fBscalar_unit\fP & \fBoperator=\fP (\fBscalar_unit\fP &&)"
.br
.ti -1c
.RI "\fBoperator float\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBscalar_unit\fP \fBoperator+\fP (\fBscalar_unit\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBscalar_unit\fP \fBoperator\-\fP (\fBscalar_unit\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBscalar_unit\fP \fBoperator*\fP (\fBscalar_unit\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBscalar_unit\fP \fBoperator/\fP (\fBscalar_unit\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBscalar_unit\fP \fBoperator^\fP (\fBconst\fP \fBscalar_unit\fP &) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator+=\fP (\fBscalar_unit\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator\-=\fP (\fBscalar_unit\fP)"
.br
.ti -1c
.RI "template<\fBtypename\fP T , \fBtypename\fP  = typename enable_if<scifir::is_number<T>::value>::type> \fBscalar_unit\fP \fBoperator+\fP (\fBconst\fP T y) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBtypename\fP T , \fBtypename\fP  = typename enable_if<scifir::is_number<T>::value>::type> \fBscalar_unit\fP \fBoperator\-\fP (\fBconst\fP T y) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBtypename\fP T , \fBtypename\fP  = typename enable_if<scifir::is_number<T>::value>::type> \fBscalar_unit\fP \fBoperator*\fP (\fBconst\fP T y) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBtypename\fP T , \fBtypename\fP  = typename enable_if<scifir::is_number<T>::value>::type> \fBscalar_unit\fP \fBoperator/\fP (\fBconst\fP T y) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBtypename\fP T , \fBtypename\fP  = typename enable_if<is_integer_number<T>::value>::type> \fBscalar_unit\fP \fBoperator^\fP (\fBconst\fP T y) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBtypename\fP T , \fBtypename\fP  = typename enable_if<scifir::is_number<T>::value>::type> \fBvoid\fP \fBoperator+=\fP (\fBconst\fP T y)"
.br
.ti -1c
.RI "template<\fBtypename\fP T , \fBtypename\fP  = typename enable_if<scifir::is_number<T>::value>::type> \fBvoid\fP \fBoperator\-=\fP (\fBconst\fP T y)"
.br
.ti -1c
.RI "template<\fBtypename\fP T , \fBtypename\fP  = typename enable_if<scifir::is_number<T>::value>::type> \fBvoid\fP \fBoperator*=\fP (\fBconst\fP T y)"
.br
.ti -1c
.RI "template<\fBtypename\fP T , \fBtypename\fP  = typename enable_if<scifir::is_number<T>::value>::type> \fBvoid\fP \fBoperator/=\fP (\fBconst\fP T y)"
.br
.ti -1c
.RI "\fBscalar_unit\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBscalar_unit\fP & \fBoperator++\fP (\fBint\fP)"
.br
.ti -1c
.RI "\fBscalar_unit\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "\fBscalar_unit\fP & \fBoperator\-\-\fP (\fBint\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBchange_dimensions\fP (\fBconst\fP \fBstring\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBchange_dimensions\fP (\fBconst\fP \fBscalar_unit\fP &)"
.br
.ti -1c
.RI "\fBbool\fP \fBhas_dimensions\fP (\fBconst\fP \fBstring\fP &) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBhas_dimensions\fP (\fBconst\fP vector< \fBdimension\fP > &) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBhas_dimensions\fP (\fBconst\fP \fBscalar_unit\fP &x) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBhas_empty_dimensions\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay_dimensions\fP () \fBconst\fP"
.br
.ti -1c
.RI "vector< \fBdimension\fP > \fBget_derived_dimensions\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP vector< \fBdimension\fP > & \fBget_dimensions\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBfloat\fP & \fBget_value\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay\fP (\fBint\fP=2, \fBbool\fP=\fBfalse\fP, \fBbool\fP=\fBfalse\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBderived_display\fP (\fBint\fP=2, \fBbool\fP=\fBfalse\fP, \fBbool\fP=\fBfalse\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBcustom_display\fP (\fBconst\fP \fBstring\fP &, \fBint\fP=2, \fBbool\fP=\fBfalse\fP) \fBconst\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvector_unit_3d\fP \fBcartesian_3d\fP (\fBconst\fP \fBstring\fP &\fBnew_dimensions\fP, \fBfloat\fP \fBnew_x\fP, \fBfloat\fP \fBnew_y\fP, \fBfloat\fP \fBnew_z\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvector_unit_3d\fP \fBcylindrical\fP (\fBconst\fP \fBstring\fP &\fBnew_dimensions\fP, \fBfloat\fP \fBnew_p\fP, \fBangle\fP \fBnew_theta\fP, \fBfloat\fP \fBnew_z\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBangle\fP \fBtheta\fP"
.br
.ti -1c
.RI "\fBangle\fP \fBphi\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBscifir::scalar_unit\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP \fBadd_dimension\fP (\fBconst\fP \fBdimension\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove_dimension\fP (\fBconst\fP \fBdimension\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_from_string\fP (\fBconst\fP \fBstring\fP &)"
.br
.in -1c

Protected Attributes inherited from \fBscifir::scalar_unit\fP
.in +1c
.ti -1c
.RI "vector< \fBdimension\fP > \fBdimensions\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
