.TH "scifir::direction" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::direction
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBname\fP : int8_t { \fBNONE\fP, \fBLEFT\fP, \fBRIGHT\fP, \fBTOP\fP, \fBBOTTOM\fP, \fBFRONT\fP, \fBBACK\fP, \fBLEFT_TOP\fP, \fBLEFT_BOTTOM\fP, \fBRIGHT_TOP\fP, \fBRIGHT_BOTTOM\fP, \fBLEFT_FRONT\fP, \fBLEFT_BACK\fP, \fBRIGHT_FRONT\fP, \fBRIGHT_BACK\fP, \fBTOP_FRONT\fP, \fBTOP_BACK\fP, \fBBOTTOM_FRONT\fP, \fBBOTTOM_BACK\fP, \fBLEFT_TOP_FRONT\fP, \fBLEFT_TOP_BACK\fP, \fBLEFT_BOTTOM_FRONT\fP, \fBLEFT_BOTTOM_BACK\fP, \fBRIGHT_TOP_FRONT\fP, \fBRIGHT_TOP_BACK\fP, \fBRIGHT_BOTTOM_FRONT\fP, \fBRIGHT_BOTTOM_BACK\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdirection\fP (\fBconst\fP \fBdirection\fP &)"
.br
.ti -1c
.RI "\fBdirection\fP (\fBdirection\fP &&)"
.br
.ti -1c
.RI "\fBdirection\fP (direction::name)"
.br
.ti -1c
.RI "\fBdirection\fP (\fBconst\fP \fBstring\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator=\fP (\fBconst\fP \fBdirection\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator=\fP (\fBdirection\fP &&)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator=\fP (direction::name)"
.br
.ti -1c
.RI "\fBvoid\fP \fBinvert\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "direction::name \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
