.TH "scifir::zid" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::zid
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBzid\fP (\fBconst\fP \fBzid\fP &)"
.br
.ti -1c
.RI "\fBzid\fP (\fBzid\fP &&)"
.br
.ti -1c
.RI "\fBzid\fP (\fBconst\fP \fBstring\fP &)"
.br
.ti -1c
.RI "\fBzid\fP & \fBoperator=\fP (\fBconst\fP \fBzid\fP &)"
.br
.ti -1c
.RI "\fBzid\fP & \fBoperator=\fP (\fBzid\fP &&)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBscifir::aid\fP \fBaid\fP"
.br
.ti -1c
.RI "vector< \fBstring\fP > \fBregions\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBcountry\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBzone\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
