# This file has been create by Scifir to get the Linux distribution, it uses for that purpose the data of the file /etc/os-release

if(${PLATFORM} MATCHES "linux")
	file(READ "/etc/os-release" ver)
	string(REGEX MATCH "ID=(\")?([a-z-]*)(\")?\n" _ ${ver})
	set(LINUX_DISTRIBUTION ${CMAKE_MATCH_2})
endif()

if(${LINUX_DISTRIBUTION} MATCHES "debian")
	set(LINUX_LIBRARY_DIR "/usr/lib/*")
elseif(${LINUX_DISTRIBUTION} MATCHES "ubuntu")
	set(LINUX_LIBRARY_DIR "/usr/lib/*")
elseif(${LINUX_DISTRIBUTION} MATCHES "neon")
	set(LINUX_LIBRARY_DIR "/usr/lib/*")
elseif(${LINUX_DISTRIBUTION} MATCHES "linuxmint")
	set(LINUX_LIBRARY_DIR "/usr/lib/*")
elseif(${LINUX_DISTRIBUTION} MATCHES "fedora")
	set(LINUX_LIBRARY_DIR "/usr/lib64")
elseif(${LINUX_DISTRIBUTION} MATCHES "centos")
	set(LINUX_LIBRARY_DIR "/usr/lib64")
elseif(${LINUX_DISTRIBUTION} MATCHES "arch")
	set(LINUX_LIBRARY_DIR "/usr/lib")
elseif(${LINUX_DISTRIBUTION} MATCHES "manjaro")
	set(LINUX_LIBRARY_DIR "/usr/lib")
elseif(${LINUX_DISTRIBUTION} MATCHES "opensuse-leap")
	set(LINUX_LIBRARY_DIR "/usr/lib64")
elseif(${LINUX_DISTRIBUTION} MATCHES "opensuse-tumbleweed")
	set(LINUX_LIBRARY_DIR "/usr/lib64")
elseif(${LINUX_DISTRIBUTION} MATCHES "gentoo")
	set(LINUX_LIBRARY_DIR "/usr/lib64")
endif()
