#include "atom.hpp"

#include <cmath>
#include <iostream>
#include <memory>
#include <sstream>
#include <string>
#include <vector>
using namespace std;

namespace chemistry
{
	vector<vector<int>> electronic_configuration_order
	{
		{1, atomic_orbital_s},
		{2, atomic_orbital_s},
		{2, atomic_orbital_p},
		{3, atomic_orbital_s},
		{3, atomic_orbital_p},
		{4, atomic_orbital_s},
		{3, atomic_orbital_d},
		{4, atomic_orbital_p},
		{5, atomic_orbital_s},
		{4, atomic_orbital_d},
		{5, atomic_orbital_p},
		{6, atomic_orbital_s},
		{4, atomic_orbital_f},
		{5, atomic_orbital_d},
		{6, atomic_orbital_p},
		{7, atomic_orbital_s},
		{5, atomic_orbital_f},
		{6, atomic_orbital_d},
		{7, atomic_orbital_p}
	};

	template<typename T>
	atom<T>* get_atom(string atom_specie)
	{
		/*switch(atom_specie)
		{
		case "H":
			return atom::H;
		case "He":
			return atom::He;
		case "Li":
			return atom::Li;
		case "Be":
			return atom::Be;
		case "B":
			return atom::B;
		case "C":
			return atom::C;
		case "N":
			return atom::N;
		case "O":
			return atom::O;
		case "F":
			return atom::F;
		case "Ne":
			return atom::Ne;
		case "Na":
			return atom::Na;
		case "Mg":
			return atom::Mg;
		case "Al":
			return atom::Al;
		case "Si":
			return atom::Si;
		case "P":
			return atom::P;
		case "S":
			return atom::S;
		case "Cl":
			return atom::Cl;
		case "Ar":
			return atom::Ar;
		case "K":
			return atom::K;
		case "Ca":
			return atom::Ca;
		case "Sc":
			return atom::Sc;
		case "Ti":
			return atom::Ti;
		case "V":
			return atom::V;
		case "Cr":
			return atom::Cr;
		case "Mn":
			return atom::Mn;
		case "Fe":
			return atom::Fe;
		case "Co":
			return atom::Co;
		case "Ni":
			return atom::Ni;
		case "Cu":
			return atom::Cu;
		case "Zn":
			return atom::Zn;
		case "Ga":
			return atom::Ga;
		case "Ge":
			return atom::Ge;
		case "As":
			return atom::As;
		case "Se":
			return atom::Se;
		case "Br":
			return atom::Br;
		case "Kr":
			return atom::Kr;
		case "Rb":
			return atom::Rb;
		case "Sr":
			return atom::Sr;
		case "Y":
			return atom::Y;
		case "Zr":
			return atom::Zr;
		case "Nb":
			return atom::Nb;
		case "Mo":
			return atom::Mo;
		case "Tc":
			return atom::Tc;
		case "Ru":
			return atom::Ru;
		case "Rh":
			return atom::Rh;
		case "Pd":
			return atom::Pd;
		case "Ag":
			return atom::Ag;
		case "Cd":
			return atom::Cd;
		case "In":
			return atom::In;
		case "Sn":
			return atom::Sn;
		case "Sb":
			return atom::Sb;
		case "Te":
			return atom::Te;
		case "I":
			return atom::I;
		case "Xe":
			return atom::Xe;
		case "Cs":
			return atom::Cs;
		case "Ba":
			return atom::Ba;
		case "La":
			return atom::La;
		case "Ce":
			return atom::Ce;
		case "Pr":
			return atom::Pr;
		case "Nd":
			return atom::Nd;
		case "Pm":
			return atom::Pm;
		case "Sm":
			return atom::Sm;
		case "Eu":
			return atom::Eu;
		case "Gd":
			return atom::Gd;
		case "Tb":
			return atom::Tb;
		case "Dy":
			return atom::Dy;
		case "Ho":
			return atom::Ho;
		case "Er":
			return atom::Er;
		case "Tm":
			return atom::Tm;
		case "Yb":
			return atom::Yb;
		case "Lu":
			return atom::Lu;
		case "Hf":
			return atom::Hf;
		case "Ta":
			return atom::Ta;
		case "W":
			return atom::W;
		case "Re":
			return atom::Re;
		case "Os":
			return atom::Os;
		case "Ir":
			return atom::Ir;
		case "Pt":
			return atom::Pt;
		case "Au":
			return atom::Au;
		case "Hg":
			return atom::Hg;
		case "Tl":
			return atom::Tl;
		case "Pb":
			return atom::Pb;
		case "Bi":
			return atom::Bi;
		case "Po":
			return atom::Po;
		case "At":
			return atom::At;
		case "Rn":
			return atom::Rn;
		case "Fr":
			return atom::Fr;
		case "Ra":
			return atom::Ra;
		case "Ac":
			return atom::Ac;
		case "Th":
			return atom::Th;
		case "Pa":
			return atom::Pa;
		case "U":
			return atom::U;
		case "Np":
			return atom::Np;
		case "Pu":
			return atom::Pu;
		case "Am":
			return atom::Am;
		case "Cm":
			return atom::Cm;
		case "Bk":
			return atom::Bk;
		case "Cf":
			return atom::Cf;
		case "Es":
			return atom::Es;
		case "Fm":
			return atom::Fm;
		case "Md":
			return atom::Md;
		case "No":
			return atom::No;
		case "Lr":
			return atom::Lr;
		case "Rf":
			return atom::Rf;
		case "Db":
			return atom::Db;
		case "Sg":
			return atom::Sg;
		case "Bh":
			return atom::Bh;
		case "Hs":
			return atom::Hs;
		case "Mt":
			return atom::Mt;
		case "Ds":
			return atom::Ds;
		case "Rg":
			return atom::Rg;
		case "Cn":
			return atom::Cn;
		case "Uut":
			return atom::Uut;
		case "Fl":
			return atom::Fl;
		case "Uup":
			return atom::Uup;
		case "Lv":
			return atom::Lv;
		case "Uus":
			return atom::Uus;
		case "Uuo":
			return atom::Uuo;
		}*/
	}
}
