#ifndef UNIT_ABBREVIATION_HPP_INCLUDED
#define UNIT_ABBREVIATION_HPP_INCLUDED

#include "unit.hpp"
#include "auto_unit.hpp"

#include "units.hpp"

using namespace physics::units;

frequency operator"" _YHz(unsigned long long int);
frequency operator"" _ZHz(unsigned long long int);
frequency operator"" _EHz(unsigned long long int);
frequency operator"" _PHz(unsigned long long int);
frequency operator"" _THz(unsigned long long int);
frequency operator"" _GHz(unsigned long long int);
frequency operator"" _MHz(unsigned long long int);
frequency operator"" _kHz(unsigned long long int);
frequency operator"" _hHz(unsigned long long int);
frequency operator"" _daHz(unsigned long long int);
frequency operator"" _Hz(unsigned long long int);
frequency operator"" _dHz(unsigned long long int);
frequency operator"" _cHz(unsigned long long int);
frequency operator"" _mHz(unsigned long long int);
frequency operator"" _uHz(unsigned long long int);
frequency operator"" _nHz(unsigned long long int);
frequency operator"" _pHz(unsigned long long int);
frequency operator"" _fHz(unsigned long long int);
frequency operator"" _aHz(unsigned long long int);
frequency operator"" _zHz(unsigned long long int);
frequency operator"" _yHz(unsigned long long int);

force operator"" _YN(unsigned long long int);
force operator"" _ZN(unsigned long long int);
force operator"" _EN(unsigned long long int);
force operator"" _PN(unsigned long long int);
force operator"" _TN(unsigned long long int);
force operator"" _GN(unsigned long long int);
force operator"" _MN(unsigned long long int);
force operator"" _kN(unsigned long long int);
force operator"" _hN(unsigned long long int);
force operator"" _daN(unsigned long long int);
force operator"" _N(unsigned long long int);
force operator"" _dN(unsigned long long int);
force operator"" _cN(unsigned long long int);
force operator"" _mN(unsigned long long int);
force operator"" _uN(unsigned long long int);
force operator"" _nN(unsigned long long int);
force operator"" _pN(unsigned long long int);
force operator"" _fN(unsigned long long int);
force operator"" _aN(unsigned long long int);
force operator"" _zN(unsigned long long int);
force operator"" _yN(unsigned long long int);

pressure operator"" _YPa(unsigned long long int);
pressure operator"" _ZPa(unsigned long long int);
pressure operator"" _EPa(unsigned long long int);
pressure operator"" _PPa(unsigned long long int);
pressure operator"" _TPa(unsigned long long int);
pressure operator"" _GPa(unsigned long long int);
pressure operator"" _MPa(unsigned long long int);
pressure operator"" _kPa(unsigned long long int);
pressure operator"" _hPa(unsigned long long int);
pressure operator"" _daPa(unsigned long long int);
pressure operator"" _Pa(unsigned long long int);
pressure operator"" _dPa(unsigned long long int);
pressure operator"" _cPa(unsigned long long int);
pressure operator"" _mPa(unsigned long long int);
pressure operator"" _uPa(unsigned long long int);
pressure operator"" _nPa(unsigned long long int);
pressure operator"" _pPa(unsigned long long int);
pressure operator"" _fPa(unsigned long long int);
pressure operator"" _aPa(unsigned long long int);
pressure operator"" _zPa(unsigned long long int);
pressure operator"" _yPa(unsigned long long int);

energy operator"" _YJ(unsigned long long int);
energy operator"" _ZJ(unsigned long long int);
energy operator"" _EJ(unsigned long long int);
energy operator"" _PJ(unsigned long long int);
energy operator"" _TJ(unsigned long long int);
energy operator"" _GJ(unsigned long long int);
energy operator"" _MJ(unsigned long long int);
energy operator"" _kJ(unsigned long long int);
energy operator"" _hJ(unsigned long long int);
energy operator"" _daJ(unsigned long long int);
energy operator"" _J(unsigned long long int);
energy operator"" _dJ(unsigned long long int);
energy operator"" _cJ(unsigned long long int);
energy operator"" _mJ(unsigned long long int);
energy operator"" _uJ(unsigned long long int);
energy operator"" _nJ(unsigned long long int);
energy operator"" _pJ(unsigned long long int);
energy operator"" _fJ(unsigned long long int);
energy operator"" _aJ(unsigned long long int);
energy operator"" _zJ(unsigned long long int);
energy operator"" _yJ(unsigned long long int);

power operator"" _YW(unsigned long long int);
power operator"" _ZW(unsigned long long int);
power operator"" _EW(unsigned long long int);
power operator"" _PW(unsigned long long int);
power operator"" _TW(unsigned long long int);
power operator"" _GW(unsigned long long int);
power operator"" _MW(unsigned long long int);
power operator"" _kW(unsigned long long int);
power operator"" _hW(unsigned long long int);
power operator"" _daW(unsigned long long int);
power operator"" _W(unsigned long long int);
power operator"" _dW(unsigned long long int);
power operator"" _cW(unsigned long long int);
power operator"" _mW(unsigned long long int);
power operator"" _uW(unsigned long long int);
power operator"" _nW(unsigned long long int);
power operator"" _pW(unsigned long long int);
power operator"" _fW(unsigned long long int);
power operator"" _aW(unsigned long long int);
power operator"" _zW(unsigned long long int);
power operator"" _yW(unsigned long long int);

electric_current operator"" _YA(unsigned long long int);
electric_current operator"" _ZA(unsigned long long int);
electric_current operator"" _EA(unsigned long long int);
electric_current operator"" _PA(unsigned long long int);
electric_current operator"" _TA(unsigned long long int);
electric_current operator"" _GA(unsigned long long int);
electric_current operator"" _MA(unsigned long long int);
electric_current operator"" _kA(unsigned long long int);
electric_current operator"" _hA(unsigned long long int);
electric_current operator"" _daA(unsigned long long int);
electric_current operator"" _A(unsigned long long int);
electric_current operator"" _dA(unsigned long long int);
electric_current operator"" _cA(unsigned long long int);
electric_current operator"" _mA(unsigned long long int);
electric_current operator"" _uA(unsigned long long int);
electric_current operator"" _nA(unsigned long long int);
electric_current operator"" _pA(unsigned long long int);
electric_current operator"" _fA(unsigned long long int);
electric_current operator"" _aA(unsigned long long int);
electric_current operator"" _zA(unsigned long long int);
electric_current operator"" _yA(unsigned long long int);

voltage operator"" _YV(unsigned long long int);
voltage operator"" _ZV(unsigned long long int);
voltage operator"" _EV(unsigned long long int);
voltage operator"" _PV(unsigned long long int);
voltage operator"" _TV(unsigned long long int);
voltage operator"" _GV(unsigned long long int);
voltage operator"" _MV(unsigned long long int);
voltage operator"" _kV(unsigned long long int);
voltage operator"" _hV(unsigned long long int);
voltage operator"" _daV(unsigned long long int);
voltage operator"" _V(unsigned long long int);
voltage operator"" _dV(unsigned long long int);
voltage operator"" _cV(unsigned long long int);
voltage operator"" _mV(unsigned long long int);
voltage operator"" _uV(unsigned long long int);
voltage operator"" _nV(unsigned long long int);
voltage operator"" _pV(unsigned long long int);
voltage operator"" _fV(unsigned long long int);
voltage operator"" _aV(unsigned long long int);
voltage operator"" _zV(unsigned long long int);
voltage operator"" _yV(unsigned long long int);

capacitance operator"" _YF(unsigned long long int);
capacitance operator"" _ZF(unsigned long long int);
capacitance operator"" _EF(unsigned long long int);
capacitance operator"" _PF(unsigned long long int);
capacitance operator"" _TF(unsigned long long int);
capacitance operator"" _GF(unsigned long long int);
capacitance operator"" _MF(unsigned long long int);
capacitance operator"" _kF(unsigned long long int);
capacitance operator"" _hF(unsigned long long int);
capacitance operator"" _daF(unsigned long long int);
capacitance operator"" _F(unsigned long long int);
capacitance operator"" _dF(unsigned long long int);
capacitance operator"" _cF(unsigned long long int);
capacitance operator"" _mF(unsigned long long int);
capacitance operator"" _uF(unsigned long long int);
capacitance operator"" _nF(unsigned long long int);
capacitance operator"" _pF(unsigned long long int);
capacitance operator"" _fF(unsigned long long int);
capacitance operator"" _aF(unsigned long long int);
capacitance operator"" _zF(unsigned long long int);
capacitance operator"" _yF(unsigned long long int);

electric_resistance operator"" _YOhm(unsigned long long int);
electric_resistance operator"" _ZOhm(unsigned long long int);
electric_resistance operator"" _EOhm(unsigned long long int);
electric_resistance operator"" _POhm(unsigned long long int);
electric_resistance operator"" _TOhm(unsigned long long int);
electric_resistance operator"" _GOhm(unsigned long long int);
electric_resistance operator"" _MOhm(unsigned long long int);
electric_resistance operator"" _kOhm(unsigned long long int);
electric_resistance operator"" _hOhm(unsigned long long int);
electric_resistance operator"" _daOhm(unsigned long long int);
electric_resistance operator"" _Ohm(unsigned long long int);
electric_resistance operator"" _dOhm(unsigned long long int);
electric_resistance operator"" _cOhm(unsigned long long int);
electric_resistance operator"" _mOhm(unsigned long long int);
electric_resistance operator"" _uOhm(unsigned long long int);
electric_resistance operator"" _nOhm(unsigned long long int);
electric_resistance operator"" _pOhm(unsigned long long int);
electric_resistance operator"" _fOhm(unsigned long long int);
electric_resistance operator"" _aOhm(unsigned long long int);
electric_resistance operator"" _zOhm(unsigned long long int);
electric_resistance operator"" _yOhm(unsigned long long int);

electric_conductance operator"" _YS(unsigned long long int);
electric_conductance operator"" _ZS(unsigned long long int);
electric_conductance operator"" _ES(unsigned long long int);
electric_conductance operator"" _PS(unsigned long long int);
electric_conductance operator"" _TS(unsigned long long int);
electric_conductance operator"" _GS(unsigned long long int);
electric_conductance operator"" _MS(unsigned long long int);
electric_conductance operator"" _kS(unsigned long long int);
electric_conductance operator"" _hS(unsigned long long int);
electric_conductance operator"" _daS(unsigned long long int);
electric_conductance operator"" _S(unsigned long long int);
electric_conductance operator"" _dS(unsigned long long int);
electric_conductance operator"" _cS(unsigned long long int);
electric_conductance operator"" _mS(unsigned long long int);
electric_conductance operator"" _uS(unsigned long long int);
electric_conductance operator"" _nS(unsigned long long int);
electric_conductance operator"" _pS(unsigned long long int);
electric_conductance operator"" _fS(unsigned long long int);
electric_conductance operator"" _aS(unsigned long long int);
electric_conductance operator"" _zS(unsigned long long int);
electric_conductance operator"" _yS(unsigned long long int);

magnetic_flux operator"" _YWb(unsigned long long int);
magnetic_flux operator"" _ZWb(unsigned long long int);
magnetic_flux operator"" _EWb(unsigned long long int);
magnetic_flux operator"" _PWb(unsigned long long int);
magnetic_flux operator"" _TWb(unsigned long long int);
magnetic_flux operator"" _GWb(unsigned long long int);
magnetic_flux operator"" _MWb(unsigned long long int);
magnetic_flux operator"" _kWb(unsigned long long int);
magnetic_flux operator"" _hWb(unsigned long long int);
magnetic_flux operator"" _daWb(unsigned long long int);
magnetic_flux operator"" _Wb(unsigned long long int);
magnetic_flux operator"" _dWb(unsigned long long int);
magnetic_flux operator"" _cWb(unsigned long long int);
magnetic_flux operator"" _mWb(unsigned long long int);
magnetic_flux operator"" _uWb(unsigned long long int);
magnetic_flux operator"" _nWb(unsigned long long int);
magnetic_flux operator"" _pWb(unsigned long long int);
magnetic_flux operator"" _fWb(unsigned long long int);
magnetic_flux operator"" _aWb(unsigned long long int);
magnetic_flux operator"" _zWb(unsigned long long int);
magnetic_flux operator"" _yWb(unsigned long long int);

magnetic_strength operator"" _YT(unsigned long long int);
magnetic_strength operator"" _ZT(unsigned long long int);
magnetic_strength operator"" _ET(unsigned long long int);
magnetic_strength operator"" _PT(unsigned long long int);
magnetic_strength operator"" _TT(unsigned long long int);
magnetic_strength operator"" _GT(unsigned long long int);
//magnetic_strength operator"" _MT(unsigned long long int);
magnetic_strength operator"" _kT(unsigned long long int);
magnetic_strength operator"" _hT(unsigned long long int);
magnetic_strength operator"" _daT(unsigned long long int);
magnetic_strength operator"" _T(unsigned long long int);
magnetic_strength operator"" _dT(unsigned long long int);
magnetic_strength operator"" _cT(unsigned long long int);
magnetic_strength operator"" _mT(unsigned long long int);
magnetic_strength operator"" _uT(unsigned long long int);
magnetic_strength operator"" _nT(unsigned long long int);
magnetic_strength operator"" _pT(unsigned long long int);
magnetic_strength operator"" _fT(unsigned long long int);
magnetic_strength operator"" _aT(unsigned long long int);
magnetic_strength operator"" _zT(unsigned long long int);
magnetic_strength operator"" _yT(unsigned long long int);

inductance operator"" _YH(unsigned long long int);
inductance operator"" _ZH(unsigned long long int);
inductance operator"" _EH(unsigned long long int);
inductance operator"" _PH(unsigned long long int);
inductance operator"" _TH(unsigned long long int);
inductance operator"" _GH(unsigned long long int);
inductance operator"" _MH(unsigned long long int);
inductance operator"" _kH(unsigned long long int);
inductance operator"" _hH(unsigned long long int);
inductance operator"" _daH(unsigned long long int);
inductance operator"" _H(unsigned long long int);
inductance operator"" _dH(unsigned long long int);
inductance operator"" _cH(unsigned long long int);
inductance operator"" _mH(unsigned long long int);
inductance operator"" _uH(unsigned long long int);
inductance operator"" _nH(unsigned long long int);
inductance operator"" _pH(unsigned long long int);
inductance operator"" _fH(unsigned long long int);
inductance operator"" _aH(unsigned long long int);
inductance operator"" _zH(unsigned long long int);
inductance operator"" _yH(unsigned long long int);

luminous_flux operator"" _Ylm(unsigned long long int);
luminous_flux operator"" _Zlm(unsigned long long int);
luminous_flux operator"" _Elm(unsigned long long int);
luminous_flux operator"" _Plm(unsigned long long int);
luminous_flux operator"" _Tlm(unsigned long long int);
luminous_flux operator"" _Glm(unsigned long long int);
luminous_flux operator"" _Mlm(unsigned long long int);
luminous_flux operator"" _klm(unsigned long long int);
luminous_flux operator"" _hlm(unsigned long long int);
luminous_flux operator"" _dalm(unsigned long long int);
luminous_flux operator"" _lm(unsigned long long int);
luminous_flux operator"" _dlm(unsigned long long int);
luminous_flux operator"" _clm(unsigned long long int);
luminous_flux operator"" _mlm(unsigned long long int);
luminous_flux operator"" _ulm(unsigned long long int);
luminous_flux operator"" _nlm(unsigned long long int);
luminous_flux operator"" _plm(unsigned long long int);
luminous_flux operator"" _flm(unsigned long long int);
luminous_flux operator"" _alm(unsigned long long int);
luminous_flux operator"" _zlm(unsigned long long int);
luminous_flux operator"" _ylm(unsigned long long int);

illuminance operator"" _Ylx(unsigned long long int);
illuminance operator"" _Zlx(unsigned long long int);
illuminance operator"" _Elx(unsigned long long int);
illuminance operator"" _Plx(unsigned long long int);
illuminance operator"" _Tlx(unsigned long long int);
illuminance operator"" _Glx(unsigned long long int);
illuminance operator"" _Mlx(unsigned long long int);
illuminance operator"" _klx(unsigned long long int);
illuminance operator"" _hlx(unsigned long long int);
illuminance operator"" _dalx(unsigned long long int);
illuminance operator"" _lx(unsigned long long int);
illuminance operator"" _dlx(unsigned long long int);
illuminance operator"" _clx(unsigned long long int);
illuminance operator"" _mlx(unsigned long long int);
illuminance operator"" _ulx(unsigned long long int);
illuminance operator"" _nlx(unsigned long long int);
illuminance operator"" _plx(unsigned long long int);
illuminance operator"" _flx(unsigned long long int);
illuminance operator"" _alx(unsigned long long int);
illuminance operator"" _zlx(unsigned long long int);
illuminance operator"" _ylx(unsigned long long int);

radioactivity operator"" _YBq(unsigned long long int);
radioactivity operator"" _ZBq(unsigned long long int);
radioactivity operator"" _EBq(unsigned long long int);
radioactivity operator"" _PBq(unsigned long long int);
radioactivity operator"" _TBq(unsigned long long int);
radioactivity operator"" _GBq(unsigned long long int);
radioactivity operator"" _MBq(unsigned long long int);
radioactivity operator"" _kBq(unsigned long long int);
radioactivity operator"" _hBq(unsigned long long int);
radioactivity operator"" _daBq(unsigned long long int);
radioactivity operator"" _Bq(unsigned long long int);
radioactivity operator"" _dBq(unsigned long long int);
radioactivity operator"" _cBq(unsigned long long int);
radioactivity operator"" _mBq(unsigned long long int);
radioactivity operator"" _uBq(unsigned long long int);
radioactivity operator"" _nBq(unsigned long long int);
radioactivity operator"" _pBq(unsigned long long int);
radioactivity operator"" _fBq(unsigned long long int);
radioactivity operator"" _aBq(unsigned long long int);
radioactivity operator"" _zBq(unsigned long long int);
radioactivity operator"" _yBq(unsigned long long int);

ionizing_radiation operator"" _YGy(unsigned long long int);
ionizing_radiation operator"" _ZGy(unsigned long long int);
ionizing_radiation operator"" _EGy(unsigned long long int);
ionizing_radiation operator"" _PGy(unsigned long long int);
ionizing_radiation operator"" _TGy(unsigned long long int);
ionizing_radiation operator"" _GGy(unsigned long long int);
ionizing_radiation operator"" _MGy(unsigned long long int);
ionizing_radiation operator"" _kGy(unsigned long long int);
ionizing_radiation operator"" _hGy(unsigned long long int);
ionizing_radiation operator"" _daGy(unsigned long long int);
ionizing_radiation operator"" _Gy(unsigned long long int);
ionizing_radiation operator"" _dGy(unsigned long long int);
ionizing_radiation operator"" _cGy(unsigned long long int);
ionizing_radiation operator"" _mGy(unsigned long long int);
ionizing_radiation operator"" _uGy(unsigned long long int);
ionizing_radiation operator"" _nGy(unsigned long long int);
ionizing_radiation operator"" _pGy(unsigned long long int);
ionizing_radiation operator"" _fGy(unsigned long long int);
ionizing_radiation operator"" _aGy(unsigned long long int);
ionizing_radiation operator"" _zGy(unsigned long long int);
ionizing_radiation operator"" _yGy(unsigned long long int);

ionizing_radiation operator"" _YSv(unsigned long long int);
ionizing_radiation operator"" _ZSv(unsigned long long int);
ionizing_radiation operator"" _ESv(unsigned long long int);
ionizing_radiation operator"" _PSv(unsigned long long int);
ionizing_radiation operator"" _TSv(unsigned long long int);
ionizing_radiation operator"" _GSv(unsigned long long int);
ionizing_radiation operator"" _MSv(unsigned long long int);
ionizing_radiation operator"" _kSv(unsigned long long int);
ionizing_radiation operator"" _hSv(unsigned long long int);
ionizing_radiation operator"" _daSv(unsigned long long int);
ionizing_radiation operator"" _Sv(unsigned long long int);
ionizing_radiation operator"" _dSv(unsigned long long int);
ionizing_radiation operator"" _cSv(unsigned long long int);
ionizing_radiation operator"" _mSv(unsigned long long int);
ionizing_radiation operator"" _uSv(unsigned long long int);
ionizing_radiation operator"" _nSv(unsigned long long int);
ionizing_radiation operator"" _pSv(unsigned long long int);
ionizing_radiation operator"" _fSv(unsigned long long int);
ionizing_radiation operator"" _aSv(unsigned long long int);
ionizing_radiation operator"" _zSv(unsigned long long int);
ionizing_radiation operator"" _ySv(unsigned long long int);

catalytic_activity operator"" _Ykat(unsigned long long int);
catalytic_activity operator"" _Zkat(unsigned long long int);
catalytic_activity operator"" _Ekat(unsigned long long int);
catalytic_activity operator"" _Pkat(unsigned long long int);
catalytic_activity operator"" _Tkat(unsigned long long int);
catalytic_activity operator"" _Gkat(unsigned long long int);
catalytic_activity operator"" _Mkat(unsigned long long int);
catalytic_activity operator"" _kkat(unsigned long long int);
catalytic_activity operator"" _hkat(unsigned long long int);
catalytic_activity operator"" _dakat(unsigned long long int);
catalytic_activity operator"" _kat(unsigned long long int);
catalytic_activity operator"" _dkat(unsigned long long int);
catalytic_activity operator"" _ckat(unsigned long long int);
catalytic_activity operator"" _mkat(unsigned long long int);
catalytic_activity operator"" _ukat(unsigned long long int);
catalytic_activity operator"" _nkat(unsigned long long int);
catalytic_activity operator"" _pkat(unsigned long long int);
catalytic_activity operator"" _fkat(unsigned long long int);
catalytic_activity operator"" _akat(unsigned long long int);
catalytic_activity operator"" _zkat(unsigned long long int);
catalytic_activity operator"" _ykat(unsigned long long int);

length operator"" _angstrom(unsigned long long int);

volume operator"" _L(unsigned long long int);
volume operator"" _mL(unsigned long long int);

physics::units::time operator"" _min(unsigned long long int);

physics::units::time operator"" _hour(unsigned long long int);

physics::units::time operator"" _day(unsigned long long int);

length operator"" _YAU(unsigned long long int);
length operator"" _ZAU(unsigned long long int);
length operator"" _EAU(unsigned long long int);
length operator"" _PAU(unsigned long long int);
length operator"" _TAU(unsigned long long int);
length operator"" _GAU(unsigned long long int);
length operator"" _MAU(unsigned long long int);
length operator"" _kAU(unsigned long long int);
length operator"" _hAU(unsigned long long int);
length operator"" _daAU(unsigned long long int);
length operator"" _AU(unsigned long long int);
length operator"" _dAU(unsigned long long int);
length operator"" _cAU(unsigned long long int);
length operator"" _mAU(unsigned long long int);
length operator"" _uAU(unsigned long long int);
length operator"" _nAU(unsigned long long int);
length operator"" _pAU(unsigned long long int);
length operator"" _fAU(unsigned long long int);
length operator"" _aAU(unsigned long long int);
length operator"" _zAU(unsigned long long int);
length operator"" _yAU(unsigned long long int);

length operator"" _Ypc(unsigned long long int);
length operator"" _Zpc(unsigned long long int);
length operator"" _Epc(unsigned long long int);
length operator"" _Ppc(unsigned long long int);
length operator"" _Tpc(unsigned long long int);
length operator"" _Gpc(unsigned long long int);
length operator"" _Mpc(unsigned long long int);
length operator"" _kpc(unsigned long long int);
length operator"" _hpc(unsigned long long int);
length operator"" _dapc(unsigned long long int);
length operator"" _pc(unsigned long long int);
length operator"" _dpc(unsigned long long int);
length operator"" _cpc(unsigned long long int);
length operator"" _mpc(unsigned long long int);
length operator"" _upc(unsigned long long int);
length operator"" _npc(unsigned long long int);
length operator"" _ppc(unsigned long long int);
length operator"" _fpc(unsigned long long int);
length operator"" _apc(unsigned long long int);
length operator"" _zpc(unsigned long long int);
length operator"" _ypc(unsigned long long int);

energy operator"" _YeV(unsigned long long int);
energy operator"" _ZeV(unsigned long long int);
energy operator"" _EeV(unsigned long long int);
energy operator"" _PeV(unsigned long long int);
energy operator"" _TeV(unsigned long long int);
energy operator"" _GeV(unsigned long long int);
energy operator"" _MeV(unsigned long long int);
energy operator"" _keV(unsigned long long int);
energy operator"" _heV(unsigned long long int);
energy operator"" _daeV(unsigned long long int);
energy operator"" _eV(unsigned long long int);
energy operator"" _deV(unsigned long long int);
energy operator"" _ceV(unsigned long long int);
energy operator"" _meV(unsigned long long int);
energy operator"" _ueV(unsigned long long int);
energy operator"" _neV(unsigned long long int);
energy operator"" _peV(unsigned long long int);
energy operator"" _feV(unsigned long long int);
energy operator"" _aeV(unsigned long long int);
energy operator"" _zeV(unsigned long long int);
energy operator"" _yeV(unsigned long long int);

mass operator"" _Da(unsigned long long int);

mass operator"" _amu(unsigned long long int);

area operator"" _Yb(unsigned long long int);
area operator"" _Zb(unsigned long long int);
area operator"" _Eb(unsigned long long int);
area operator"" _Pb(unsigned long long int);
area operator"" _Tb(unsigned long long int);
area operator"" _Gb(unsigned long long int);
area operator"" _Mb(unsigned long long int);
area operator"" _kb(unsigned long long int);
area operator"" _hb(unsigned long long int);
area operator"" _dab(unsigned long long int);
area operator"" _b(unsigned long long int);
area operator"" _db(unsigned long long int);
area operator"" _cb(unsigned long long int);
area operator"" _mb(unsigned long long int);
area operator"" _ub(unsigned long long int);
area operator"" _nb(unsigned long long int);
area operator"" _pb(unsigned long long int);
area operator"" _fb(unsigned long long int);
area operator"" _ab(unsigned long long int);
area operator"" _zb(unsigned long long int);
area operator"" _yb(unsigned long long int);

molarity operator"" _YM(unsigned long long int);
molarity operator"" _ZM(unsigned long long int);
molarity operator"" _EM(unsigned long long int);
molarity operator"" _PM(unsigned long long int);
molarity operator"" _TM(unsigned long long int);
molarity operator"" _GM(unsigned long long int);
molarity operator"" _MM(unsigned long long int);
molarity operator"" _kM(unsigned long long int);
molarity operator"" _hM(unsigned long long int);
molarity operator"" _daM(unsigned long long int);
molarity operator"" _M(unsigned long long int);
molarity operator"" _dM(unsigned long long int);
molarity operator"" _cM(unsigned long long int);
molarity operator"" _mM(unsigned long long int);
molarity operator"" _uM(unsigned long long int);
molarity operator"" _nM(unsigned long long int);
molarity operator"" _pM(unsigned long long int);
molarity operator"" _fM(unsigned long long int);
molarity operator"" _aM(unsigned long long int);
molarity operator"" _zM(unsigned long long int);
molarity operator"" _yM(unsigned long long int);

mole operator"" _particles(unsigned long long int);

frequency operator"" _YHz(long double);
frequency operator"" _ZHz(long double);
frequency operator"" _EHz(long double);
frequency operator"" _PHz(long double);
frequency operator"" _THz(long double);
frequency operator"" _GHz(long double);
frequency operator"" _MHz(long double);
frequency operator"" _kHz(long double);
frequency operator"" _hHz(long double);
frequency operator"" _daHz(long double);
frequency operator"" _Hz(long double);
frequency operator"" _dHz(long double);
frequency operator"" _cHz(long double);
frequency operator"" _mHz(long double);
frequency operator"" _uHz(long double);
frequency operator"" _nHz(long double);
frequency operator"" _pHz(long double);
frequency operator"" _fHz(long double);
frequency operator"" _aHz(long double);
frequency operator"" _zHz(long double);
frequency operator"" _yHz(long double);

force operator"" _YN(long double);
force operator"" _ZN(long double);
force operator"" _EN(long double);
force operator"" _PN(long double);
force operator"" _TN(long double);
force operator"" _GN(long double);
force operator"" _MN(long double);
force operator"" _kN(long double);
force operator"" _hN(long double);
force operator"" _daN(long double);
force operator"" _N(long double);
force operator"" _dN(long double);
force operator"" _cN(long double);
force operator"" _mN(long double);
force operator"" _uN(long double);
force operator"" _nN(long double);
force operator"" _pN(long double);
force operator"" _fN(long double);
force operator"" _aN(long double);
force operator"" _zN(long double);
force operator"" _yN(long double);

pressure operator"" _YPa(long double);
pressure operator"" _ZPa(long double);
pressure operator"" _EPa(long double);
pressure operator"" _PPa(long double);
pressure operator"" _TPa(long double);
pressure operator"" _GPa(long double);
pressure operator"" _MPa(long double);
pressure operator"" _kPa(long double);
pressure operator"" _hPa(long double);
pressure operator"" _daPa(long double);
pressure operator"" _Pa(long double);
pressure operator"" _dPa(long double);
pressure operator"" _cPa(long double);
pressure operator"" _mPa(long double);
pressure operator"" _uPa(long double);
pressure operator"" _nPa(long double);
pressure operator"" _pPa(long double);
pressure operator"" _fPa(long double);
pressure operator"" _aPa(long double);
pressure operator"" _zPa(long double);
pressure operator"" _yPa(long double);

energy operator"" _YJ(long double);
energy operator"" _ZJ(long double);
energy operator"" _EJ(long double);
energy operator"" _PJ(long double);
energy operator"" _TJ(long double);
energy operator"" _GJ(long double);
energy operator"" _MJ(long double);
energy operator"" _kJ(long double);
energy operator"" _hJ(long double);
energy operator"" _daJ(long double);
energy operator"" _J(long double);
energy operator"" _dJ(long double);
energy operator"" _cJ(long double);
energy operator"" _mJ(long double);
energy operator"" _uJ(long double);
energy operator"" _nJ(long double);
energy operator"" _pJ(long double);
energy operator"" _fJ(long double);
energy operator"" _aJ(long double);
energy operator"" _zJ(long double);
energy operator"" _yJ(long double);

power operator"" _YW(long double);
power operator"" _ZW(long double);
power operator"" _EW(long double);
power operator"" _PW(long double);
power operator"" _TW(long double);
power operator"" _GW(long double);
power operator"" _MW(long double);
power operator"" _kW(long double);
power operator"" _hW(long double);
power operator"" _daW(long double);
power operator"" _W(long double);
power operator"" _dW(long double);
power operator"" _cW(long double);
power operator"" _mW(long double);
power operator"" _uW(long double);
power operator"" _nW(long double);
power operator"" _pW(long double);
power operator"" _fW(long double);
power operator"" _aW(long double);
power operator"" _zW(long double);
power operator"" _yW(long double);

electric_current operator"" _YA(long double);
electric_current operator"" _ZA(long double);
electric_current operator"" _EA(long double);
electric_current operator"" _PA(long double);
electric_current operator"" _TA(long double);
electric_current operator"" _GA(long double);
electric_current operator"" _MA(long double);
electric_current operator"" _kA(long double);
electric_current operator"" _hA(long double);
electric_current operator"" _daA(long double);
electric_current operator"" _A(long double);
electric_current operator"" _dA(long double);
electric_current operator"" _cA(long double);
electric_current operator"" _mA(long double);
electric_current operator"" _uA(long double);
electric_current operator"" _nA(long double);
electric_current operator"" _pA(long double);
electric_current operator"" _fA(long double);
electric_current operator"" _aA(long double);
electric_current operator"" _zA(long double);
electric_current operator"" _yA(long double);

voltage operator"" _YV(long double);
voltage operator"" _ZV(long double);
voltage operator"" _EV(long double);
voltage operator"" _PV(long double);
voltage operator"" _TV(long double);
voltage operator"" _GV(long double);
voltage operator"" _MV(long double);
voltage operator"" _kV(long double);
voltage operator"" _hV(long double);
voltage operator"" _daV(long double);
voltage operator"" _V(long double);
voltage operator"" _dV(long double);
voltage operator"" _cV(long double);
voltage operator"" _mV(long double);
voltage operator"" _uV(long double);
voltage operator"" _nV(long double);
voltage operator"" _pV(long double);
voltage operator"" _fV(long double);
voltage operator"" _aV(long double);
voltage operator"" _zV(long double);
voltage operator"" _yV(long double);

capacitance operator"" _YF(long double);
capacitance operator"" _ZF(long double);
capacitance operator"" _EF(long double);
capacitance operator"" _PF(long double);
capacitance operator"" _TF(long double);
capacitance operator"" _GF(long double);
capacitance operator"" _MF(long double);
capacitance operator"" _kF(long double);
capacitance operator"" _hF(long double);
capacitance operator"" _daF(long double);
capacitance operator"" _F(long double);
capacitance operator"" _dF(long double);
capacitance operator"" _cF(long double);
capacitance operator"" _mF(long double);
capacitance operator"" _uF(long double);
capacitance operator"" _nF(long double);
capacitance operator"" _pF(long double);
capacitance operator"" _fF(long double);
capacitance operator"" _aF(long double);
capacitance operator"" _zF(long double);
capacitance operator"" _yF(long double);

electric_resistance operator"" _YOhm(long double);
electric_resistance operator"" _ZOhm(long double);
electric_resistance operator"" _EOhm(long double);
electric_resistance operator"" _POhm(long double);
electric_resistance operator"" _TOhm(long double);
electric_resistance operator"" _GOhm(long double);
electric_resistance operator"" _MOhm(long double);
electric_resistance operator"" _kOhm(long double);
electric_resistance operator"" _hOhm(long double);
electric_resistance operator"" _daOhm(long double);
electric_resistance operator"" _Ohm(long double);
electric_resistance operator"" _dOhm(long double);
electric_resistance operator"" _cOhm(long double);
electric_resistance operator"" _mOhm(long double);
electric_resistance operator"" _uOhm(long double);
electric_resistance operator"" _nOhm(long double);
electric_resistance operator"" _pOhm(long double);
electric_resistance operator"" _fOhm(long double);
electric_resistance operator"" _aOhm(long double);
electric_resistance operator"" _zOhm(long double);
electric_resistance operator"" _yOhm(long double);

electric_conductance operator"" _YS(long double);
electric_conductance operator"" _ZS(long double);
electric_conductance operator"" _ES(long double);
electric_conductance operator"" _PS(long double);
electric_conductance operator"" _TS(long double);
electric_conductance operator"" _GS(long double);
electric_conductance operator"" _MS(long double);
electric_conductance operator"" _kS(long double);
electric_conductance operator"" _hS(long double);
electric_conductance operator"" _daS(long double);
electric_conductance operator"" _S(long double);
electric_conductance operator"" _dS(long double);
electric_conductance operator"" _cS(long double);
electric_conductance operator"" _mS(long double);
electric_conductance operator"" _uS(long double);
electric_conductance operator"" _nS(long double);
electric_conductance operator"" _pS(long double);
electric_conductance operator"" _fS(long double);
electric_conductance operator"" _aS(long double);
electric_conductance operator"" _zS(long double);
electric_conductance operator"" _yS(long double);

magnetic_flux operator"" _YWb(long double);
magnetic_flux operator"" _ZWb(long double);
magnetic_flux operator"" _EWb(long double);
magnetic_flux operator"" _PWb(long double);
magnetic_flux operator"" _TWb(long double);
magnetic_flux operator"" _GWb(long double);
magnetic_flux operator"" _MWb(long double);
magnetic_flux operator"" _kWb(long double);
magnetic_flux operator"" _hWb(long double);
magnetic_flux operator"" _daWb(long double);
magnetic_flux operator"" _Wb(long double);
magnetic_flux operator"" _dWb(long double);
magnetic_flux operator"" _cWb(long double);
magnetic_flux operator"" _mWb(long double);
magnetic_flux operator"" _uWb(long double);
magnetic_flux operator"" _nWb(long double);
magnetic_flux operator"" _pWb(long double);
magnetic_flux operator"" _fWb(long double);
magnetic_flux operator"" _aWb(long double);
magnetic_flux operator"" _zWb(long double);
magnetic_flux operator"" _yWb(long double);

magnetic_strength operator"" _YT(long double);
magnetic_strength operator"" _ZT(long double);
magnetic_strength operator"" _ET(long double);
magnetic_strength operator"" _PT(long double);
magnetic_strength operator"" _TT(long double);
magnetic_strength operator"" _GT(long double);
//magnetic_strength operator"" _MT(long double);
magnetic_strength operator"" _kT(long double);
magnetic_strength operator"" _hT(long double);
magnetic_strength operator"" _daT(long double);
magnetic_strength operator"" _T(long double);
magnetic_strength operator"" _dT(long double);
magnetic_strength operator"" _cT(long double);
magnetic_strength operator"" _mT(long double);
magnetic_strength operator"" _uT(long double);
magnetic_strength operator"" _nT(long double);
magnetic_strength operator"" _pT(long double);
magnetic_strength operator"" _fT(long double);
magnetic_strength operator"" _aT(long double);
magnetic_strength operator"" _zT(long double);
magnetic_strength operator"" _yT(long double);

inductance operator"" _YH(long double);
inductance operator"" _ZH(long double);
inductance operator"" _EH(long double);
inductance operator"" _PH(long double);
inductance operator"" _TH(long double);
inductance operator"" _GH(long double);
inductance operator"" _MH(long double);
inductance operator"" _kH(long double);
inductance operator"" _hH(long double);
inductance operator"" _daH(long double);
inductance operator"" _H(long double);
inductance operator"" _dH(long double);
inductance operator"" _cH(long double);
inductance operator"" _mH(long double);
inductance operator"" _uH(long double);
inductance operator"" _nH(long double);
inductance operator"" _pH(long double);
inductance operator"" _fH(long double);
inductance operator"" _aH(long double);
inductance operator"" _zH(long double);
inductance operator"" _yH(long double);

luminous_flux operator"" _Ylm(long double);
luminous_flux operator"" _Zlm(long double);
luminous_flux operator"" _Elm(long double);
luminous_flux operator"" _Plm(long double);
luminous_flux operator"" _Tlm(long double);
luminous_flux operator"" _Glm(long double);
luminous_flux operator"" _Mlm(long double);
luminous_flux operator"" _klm(long double);
luminous_flux operator"" _hlm(long double);
luminous_flux operator"" _dalm(long double);
luminous_flux operator"" _lm(long double);
luminous_flux operator"" _dlm(long double);
luminous_flux operator"" _clm(long double);
luminous_flux operator"" _mlm(long double);
luminous_flux operator"" _ulm(long double);
luminous_flux operator"" _nlm(long double);
luminous_flux operator"" _plm(long double);
luminous_flux operator"" _flm(long double);
luminous_flux operator"" _alm(long double);
luminous_flux operator"" _zlm(long double);
luminous_flux operator"" _ylm(long double);

illuminance operator"" _Ylx(long double);
illuminance operator"" _Zlx(long double);
illuminance operator"" _Elx(long double);
illuminance operator"" _Plx(long double);
illuminance operator"" _Tlx(long double);
illuminance operator"" _Glx(long double);
illuminance operator"" _Mlx(long double);
illuminance operator"" _klx(long double);
illuminance operator"" _hlx(long double);
illuminance operator"" _dalx(long double);
illuminance operator"" _lx(long double);
illuminance operator"" _dlx(long double);
illuminance operator"" _clx(long double);
illuminance operator"" _mlx(long double);
illuminance operator"" _ulx(long double);
illuminance operator"" _nlx(long double);
illuminance operator"" _plx(long double);
illuminance operator"" _flx(long double);
illuminance operator"" _alx(long double);
illuminance operator"" _zlx(long double);
illuminance operator"" _ylx(long double);

radioactivity operator"" _YBq(long double);
radioactivity operator"" _ZBq(long double);
radioactivity operator"" _EBq(long double);
radioactivity operator"" _PBq(long double);
radioactivity operator"" _TBq(long double);
radioactivity operator"" _GBq(long double);
radioactivity operator"" _MBq(long double);
radioactivity operator"" _kBq(long double);
radioactivity operator"" _hBq(long double);
radioactivity operator"" _daBq(long double);
radioactivity operator"" _Bq(long double);
radioactivity operator"" _dBq(long double);
radioactivity operator"" _cBq(long double);
radioactivity operator"" _mBq(long double);
radioactivity operator"" _uBq(long double);
radioactivity operator"" _nBq(long double);
radioactivity operator"" _pBq(long double);
radioactivity operator"" _fBq(long double);
radioactivity operator"" _aBq(long double);
radioactivity operator"" _zBq(long double);
radioactivity operator"" _yBq(long double);

ionizing_radiation operator"" _YGy(long double);
ionizing_radiation operator"" _ZGy(long double);
ionizing_radiation operator"" _EGy(long double);
ionizing_radiation operator"" _PGy(long double);
ionizing_radiation operator"" _TGy(long double);
ionizing_radiation operator"" _GGy(long double);
ionizing_radiation operator"" _MGy(long double);
ionizing_radiation operator"" _kGy(long double);
ionizing_radiation operator"" _hGy(long double);
ionizing_radiation operator"" _daGy(long double);
ionizing_radiation operator"" _Gy(long double);
ionizing_radiation operator"" _dGy(long double);
ionizing_radiation operator"" _cGy(long double);
ionizing_radiation operator"" _mGy(long double);
ionizing_radiation operator"" _uGy(long double);
ionizing_radiation operator"" _nGy(long double);
ionizing_radiation operator"" _pGy(long double);
ionizing_radiation operator"" _fGy(long double);
ionizing_radiation operator"" _aGy(long double);
ionizing_radiation operator"" _zGy(long double);
ionizing_radiation operator"" _yGy(long double);

ionizing_radiation operator"" _YSv(long double);
ionizing_radiation operator"" _ZSv(long double);
ionizing_radiation operator"" _ESv(long double);
ionizing_radiation operator"" _PSv(long double);
ionizing_radiation operator"" _TSv(long double);
ionizing_radiation operator"" _GSv(long double);
ionizing_radiation operator"" _MSv(long double);
ionizing_radiation operator"" _kSv(long double);
ionizing_radiation operator"" _hSv(long double);
ionizing_radiation operator"" _daSv(long double);
ionizing_radiation operator"" _Sv(long double);
ionizing_radiation operator"" _dSv(long double);
ionizing_radiation operator"" _cSv(long double);
ionizing_radiation operator"" _mSv(long double);
ionizing_radiation operator"" _uSv(long double);
ionizing_radiation operator"" _nSv(long double);
ionizing_radiation operator"" _pSv(long double);
ionizing_radiation operator"" _fSv(long double);
ionizing_radiation operator"" _aSv(long double);
ionizing_radiation operator"" _zSv(long double);
ionizing_radiation operator"" _ySv(long double);

catalytic_activity operator"" _Ykat(long double);
catalytic_activity operator"" _Zkat(long double);
catalytic_activity operator"" _Ekat(long double);
catalytic_activity operator"" _Pkat(long double);
catalytic_activity operator"" _Tkat(long double);
catalytic_activity operator"" _Gkat(long double);
catalytic_activity operator"" _Mkat(long double);
catalytic_activity operator"" _kkat(long double);
catalytic_activity operator"" _hkat(long double);
catalytic_activity operator"" _dakat(long double);
catalytic_activity operator"" _kat(long double);
catalytic_activity operator"" _dkat(long double);
catalytic_activity operator"" _ckat(long double);
catalytic_activity operator"" _mkat(long double);
catalytic_activity operator"" _ukat(long double);
catalytic_activity operator"" _nkat(long double);
catalytic_activity operator"" _pkat(long double);
catalytic_activity operator"" _fkat(long double);
catalytic_activity operator"" _akat(long double);
catalytic_activity operator"" _zkat(long double);
catalytic_activity operator"" _ykat(long double);

length operator"" _angstrom(long double);

volume operator"" _L(long double);
volume operator"" _mL(long double);

physics::units::time operator"" _min(long double);

physics::units::time operator"" _hour(long double);

physics::units::time operator"" _day(long double);

length operator"" _YAU(long double);
length operator"" _ZAU(long double);
length operator"" _EAU(long double);
length operator"" _PAU(long double);
length operator"" _TAU(long double);
length operator"" _GAU(long double);
length operator"" _MAU(long double);
length operator"" _kAU(long double);
length operator"" _hAU(long double);
length operator"" _daAU(long double);
length operator"" _AU(long double);
length operator"" _dAU(long double);
length operator"" _cAU(long double);
length operator"" _mAU(long double);
length operator"" _uAU(long double);
length operator"" _nAU(long double);
length operator"" _pAU(long double);
length operator"" _fAU(long double);
length operator"" _aAU(long double);
length operator"" _zAU(long double);
length operator"" _yAU(long double);

length operator"" _Ypc(long double);
length operator"" _Zpc(long double);
length operator"" _Epc(long double);
length operator"" _Ppc(long double);
length operator"" _Tpc(long double);
length operator"" _Gpc(long double);
length operator"" _Mpc(long double);
length operator"" _kpc(long double);
length operator"" _hpc(long double);
length operator"" _dapc(long double);
length operator"" _pc(long double);
length operator"" _dpc(long double);
length operator"" _cpc(long double);
length operator"" _mpc(long double);
length operator"" _upc(long double);
length operator"" _npc(long double);
length operator"" _ppc(long double);
length operator"" _fpc(long double);
length operator"" _apc(long double);
length operator"" _zpc(long double);
length operator"" _ypc(long double);

energy operator"" _YeV(long double);
energy operator"" _ZeV(long double);
energy operator"" _EeV(long double);
energy operator"" _PeV(long double);
energy operator"" _TeV(long double);
energy operator"" _GeV(long double);
energy operator"" _MeV(long double);
energy operator"" _keV(long double);
energy operator"" _heV(long double);
energy operator"" _daeV(long double);
energy operator"" _eV(long double);
energy operator"" _deV(long double);
energy operator"" _ceV(long double);
energy operator"" _meV(long double);
energy operator"" _ueV(long double);
energy operator"" _neV(long double);
energy operator"" _peV(long double);
energy operator"" _feV(long double);
energy operator"" _aeV(long double);
energy operator"" _zeV(long double);
energy operator"" _yeV(long double);

mass operator"" _Da(long double);

mass operator"" _amu(long double);

area operator"" _Yb(long double);
area operator"" _Zb(long double);
area operator"" _Eb(long double);
area operator"" _Pb(long double);
area operator"" _Tb(long double);
area operator"" _Gb(long double);
area operator"" _Mb(long double);
area operator"" _kb(long double);
area operator"" _hb(long double);
area operator"" _dab(long double);
area operator"" _b(long double);
area operator"" _db(long double);
area operator"" _cb(long double);
area operator"" _mb(long double);
area operator"" _ub(long double);
area operator"" _nb(long double);
area operator"" _pb(long double);
area operator"" _fb(long double);
area operator"" _ab(long double);
area operator"" _zb(long double);
area operator"" _yb(long double);

molarity operator"" _YM(long double);
molarity operator"" _ZM(long double);
molarity operator"" _EM(long double);
molarity operator"" _PM(long double);
molarity operator"" _TM(long double);
molarity operator"" _GM(long double);
molarity operator"" _MM(long double);
molarity operator"" _kM(long double);
molarity operator"" _hM(long double);
molarity operator"" _daM(long double);
molarity operator"" _M(long double);
molarity operator"" _dM(long double);
molarity operator"" _cM(long double);
molarity operator"" _mM(long double);
molarity operator"" _uM(long double);
molarity operator"" _nM(long double);
molarity operator"" _pM(long double);
molarity operator"" _fM(long double);
molarity operator"" _aM(long double);
molarity operator"" _zM(long double);
molarity operator"" _yM(long double);

#endif // UNIT_ABBREVIATION_HPP_INCLUDED
