.TH "units Directory Reference" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconversion\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconversion\&.hpp\fP"
.br
.ti -1c
.RI "file \fBdimension\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdimension\&.hpp\fP"
.br
.ti -1c
.RI "file \fBprefix\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprefix\&.hpp\fP"
.br
.ti -1c
.RI "file \fBscalar_unit\&.cpp\fP"
.br
.ti -1c
.RI "file \fBscalar_unit\&.hpp\fP"
.br
.ti -1c
.RI "file \fBunit_abbreviation\&.cpp\fP"
.br
.ti -1c
.RI "file \fBunit_abbreviation\&.hpp\fP"
.br
.ti -1c
.RI "file \fBunit_basic\&.cpp\fP"
.br
.ti -1c
.RI "file \fBunit_basic\&.hpp\fP"
.br
.ti -1c
.RI "file \fBvector_unit_2d\&.cpp\fP"
.br
.ti -1c
.RI "file \fBvector_unit_2d\&.hpp\fP"
.br
.ti -1c
.RI "file \fBvector_unit_3d\&.cpp\fP"
.br
.ti -1c
.RI "file \fBvector_unit_3d\&.hpp\fP"
.br
.ti -1c
.RI "file \fBvector_unit_nd\&.cpp\fP"
.br
.ti -1c
.RI "file \fBvector_unit_nd\&.hpp\fP"
.br
.in -1c
