.TH "topology Directory Reference" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
topology Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconstants\&.hpp\fP"
.br
.ti -1c
.RI "file \fBdirection\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdirection\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpoint_1d\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpoint_1d\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpoint_1d_impl\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpoint_2d\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpoint_2d\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpoint_2d_impl\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpoint_3d\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpoint_3d\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpoint_3d_impl\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpoint_nd\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpoint_nd\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpoint_nd_impl\&.hpp\fP"
.br
.in -1c
