.TH "util Directory Reference" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBis_number\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmatrix\&.hpp\fP"
.br
.ti -1c
.RI "file \fBtypes\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtypes\&.hpp\fP"
.br
.in -1c
