.TH "meca_number/angle.hpp" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
meca_number/angle.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./topology/constants\&.hpp'\fP
.br
\fC#include '\&.\&./util/is_number\&.hpp'\fP
.br
\fC#include '\&.\&./units/scalar_unit\&.hpp'\fP
.br
\fC#include 'boost/math/constants/constants\&.hpp'\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBscifir::angle\fP"
.br
.RI "Class that allows to work with angles\&. Each angle sizes 4 bytes\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBscifir\fP"
.br
.RI "The namespace scifir contains all scifir-units, excepting the string literals, which are outside\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBscifir::radian_to_degree\fP (float x)"
.br
.RI "Converts a radian to degree\&. "
.ti -1c
.RI "float \fBscifir::degree_to_radian\fP (float x)"
.br
.RI "Converts a degree to a radian\&. "
.ti -1c
.RI "string \fBscifir::to_string\fP (const angle &x)"
.br
.RI "Converts an angle to their string representation\&. "
.ti -1c
.RI "bool \fBscifir::is_angle\fP (const string &init_angle)"
.br
.RI "Checks if some string is an initialization string of an angle\&. "
.ti -1c
.RI "bool \fBscifir::parallel\fP (const angle &x, const angle &y)"
.br
.RI "Checks if two angles in a 2D correspond to parallel lines (or parallel vectors)\&. "
.ti -1c
.RI "bool \fBscifir::orthogonal\fP (const angle &x, const angle &y)"
.br
.RI "Checks if two angles in a 2D correspond to orthogonal lines (or orthogonal vectors)\&. "
.ti -1c
.RI "angle \fBscifir::sqrt\fP (const angle &x)"
.br
.RI "Calculates the square root of the angle x and returns that new angle\&. "
.ti -1c
.RI "angle \fBscifir::sqrt_nth\fP (const angle &x, int index)"
.br
.RI "Calculates the nth root of the angle x and returns that new angle\&. "
.ti -1c
.RI "float \fBscifir::sin\fP (const angle &x)"
.br
.RI "Calculates the sin of angle x\&. It uses the \fBsin()\fP function of the standard library of C++, the difference is that angle is in degrees, not in radians\&. "
.ti -1c
.RI "float \fBscifir::cos\fP (const angle &x)"
.br
.RI "Calculates the cos of angle x\&. It uses the \fBcos()\fP function of the standard library of C++, the difference is that angle is in degrees, not in radians\&. "
.ti -1c
.RI "float \fBscifir::tan\fP (const angle &x)"
.br
.RI "Calculates the tan of angle x\&. It uses the \fBtan()\fP function of the standard library of C++, the difference is that angle is in degrees, not in radians\&. "
.ti -1c
.RI "angle \fBscifir::asin\fP (float x)"
.br
.RI "Calculates the asin of some value x and returns the result as angle in degrees\&. "
.ti -1c
.RI "angle \fBscifir::acos\fP (float x)"
.br
.RI "Calculates the acos of some value x and returns the result as angle in degrees\&. "
.ti -1c
.RI "angle \fBscifir::atan\fP (float x)"
.br
.RI "Calculates the atan of some value x and returns the result as angle in degrees\&. "
.ti -1c
.RI "float \fBscifir::sinh\fP (const angle &x)"
.br
.RI "Calculates the sinh of angle x\&. It uses the \fBsinh()\fP function of the standard library of C++, the difference is that angle is in degrees, not in radians\&. "
.ti -1c
.RI "float \fBscifir::cosh\fP (const angle &x)"
.br
.RI "Calculates the cosh of angle x\&. It uses the \fBcosh()\fP function of the standard library of C++, the difference is that angle is in degrees, not in radians\&. "
.ti -1c
.RI "float \fBscifir::tanh\fP (const angle &x)"
.br
.RI "Calculates the tanh of angle x\&. It uses the \fBtanh()\fP function of the standard library of C++, the difference is that angle is in degrees, not in radians\&. "
.ti -1c
.RI "angle \fBscifir::asinh\fP (float x)"
.br
.RI "Calculates the asinh of some value x and returns the result as angle in degrees\&. "
.ti -1c
.RI "angle \fBscifir::acosh\fP (float x)"
.br
.RI "Calculates the acosh of some value x and returns the result as angle in degrees\&. "
.ti -1c
.RI "angle \fBscifir::atanh\fP (float x)"
.br
.RI "Calculates the atanh of some value x and returns the result as angle in degrees\&. "
.ti -1c
.RI "float \fBscifir::asin_degree\fP (float x)"
.br
.RI "Calculates the asin receiving x in degrees\&. It uses the \fBasin()\fP function of the standard library of C++, but the difference is that the argument is in degrees, not in radians\&. "
.ti -1c
.RI "float \fBscifir::acos_degree\fP (float x)"
.br
.RI "Calculates the acos receiving x in degrees\&. It uses the \fBacos()\fP function of the standard library of C++, but the difference is that the argument is in degrees, not in radians\&. "
.ti -1c
.RI "float \fBscifir::atan_degree\fP (float x)"
.br
.RI "Calculates the atan receiving x in degrees\&. It uses the \fBatan()\fP function of the standard library of C++, but the difference is that the argument is in degrees, not in radians\&. "
.ti -1c
.RI "float \fBscifir::asinh_degree\fP (float x)"
.br
.RI "Calculates the asinh receiving x in degrees\&. It uses the \fBasinh()\fP function of the standard library of C++, but the difference is that the argument is in degrees, not in radians\&. "
.ti -1c
.RI "float \fBscifir::acosh_degree\fP (float x)"
.br
.RI "Calculates the acosh receiving x in degrees\&. It uses the \fBacosh()\fP function of the standard library of C++, but the difference is that the argument is in degrees, not in radians\&. "
.ti -1c
.RI "float \fBscifir::atanh_degree\fP (float x)"
.br
.RI "Calculates the atanh receiving x in degrees\&. It uses the \fBatanh()\fP function of the standard library of C++, but the difference is that the argument is in degrees, not in radians\&. "
.ti -1c
.RI "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> \fBscifir::angle\fP \fBoperator+\fP (T x, const \fBscifir::angle\fP &y)"
.br
.RI "Creates a new angle as the sum of a numeric type with the value of this angle\&. "
.ti -1c
.RI "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> \fBscifir::angle\fP \fBoperator\-\fP (T x, const \fBscifir::angle\fP &y)"
.br
.RI "Creates a new angle as the substraction of the numeric type with the value of this angle\&. "
.ti -1c
.RI "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> \fBscifir::angle\fP \fBoperator*\fP (T x, const \fBscifir::angle\fP &y)"
.br
.RI "Creates a new angle as the multiplication of a numeric type with the value of this angle\&. "
.ti -1c
.RI "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> \fBscifir::angle\fP \fBoperator/\fP (T x, const \fBscifir::angle\fP &y)"
.br
.RI "Creates a new angle as the division of the value of this angle with the numeric type\&. "
.ti -1c
.RI "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> \fBscifir::angle\fP \fBoperator^\fP (T x, const \fBscifir::angle\fP &y)"
.br
.RI "Creates a new angle as the power of a numeric type with the value of this angle\&. "
.ti -1c
.RI "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool \fBoperator==\fP (T x, const \fBscifir::angle\fP &y)"
.br
.RI "Checks if the value of angle y is equal to a numeric type x\&. "
.ti -1c
.RI "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool \fBoperator!=\fP (T x, const \fBscifir::angle\fP &y)"
.br
.RI "Checks if the value of angle y is not equal to a numeric type x\&. "
.ti -1c
.RI "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool \fBoperator<\fP (T x, const \fBscifir::angle\fP &y)"
.br
.RI "Checks if the value of angle y is greather to a numeric type x\&. "
.ti -1c
.RI "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool \fBoperator>\fP (T x, const \fBscifir::angle\fP &y)"
.br
.RI "Checks if the value of angle y is lower to a numeric type x\&. "
.ti -1c
.RI "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool \fBoperator<=\fP (T x, const \fBscifir::angle\fP &y)"
.br
.RI "Checks if the value of angle y is equal or greather than a numeric type x\&. "
.ti -1c
.RI "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool \fBoperator>=\fP (T x, const \fBscifir::angle\fP &y)"
.br
.RI "Checks if the value of angle y is lower or equal than a numeric type x\&. "
.ti -1c
.RI "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool \fBoperator==\fP (const \fBscifir::angle\fP &y, T x)"
.br
.RI "Checks if the value of angle y is equal to a numeric type x\&. "
.ti -1c
.RI "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool \fBoperator!=\fP (const \fBscifir::angle\fP &y, T x)"
.br
.RI "Checks if the value of angle y is not equal to a numeric type x\&. "
.ti -1c
.RI "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool \fBoperator<\fP (const \fBscifir::angle\fP &y, T x)"
.br
.RI "Checks if the value of angle y is lower to a numeric type x\&. "
.ti -1c
.RI "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool \fBoperator>\fP (const \fBscifir::angle\fP &y, T x)"
.br
.RI "Checks if the value of angle y is greather to a numeric type x\&. "
.ti -1c
.RI "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool \fBoperator<=\fP (const \fBscifir::angle\fP &y, T x)"
.br
.RI "Checks if the value of angle y is lower or equal than a numeric type x\&. "
.ti -1c
.RI "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool \fBoperator>=\fP (const \fBscifir::angle\fP &y, T x)"
.br
.RI "Checks if the value of angle y is equal or greather than a numeric type x\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBscifir::angle\fP &x, const \fBscifir::angle\fP &y)"
.br
.RI "Checks if two angles have equal value\&. "
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBscifir::angle\fP &x, const \fBscifir::angle\fP &y)"
.br
.RI "Checks if two angles have not equal value\&. "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBscifir::angle\fP &x, const \fBscifir::angle\fP &y)"
.br
.RI "Checks if the value of angle x is lower than the value of angle y\&. "
.ti -1c
.RI "bool \fBoperator>\fP (const \fBscifir::angle\fP &x, const \fBscifir::angle\fP &y)"
.br
.RI "Checks if the value of angle x is greather than the value of angle y\&. "
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBscifir::angle\fP &x, const \fBscifir::angle\fP &y)"
.br
.RI "Checks if the value of angle x is lower or equal than the value of angle y\&. "
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBscifir::angle\fP &x, const \fBscifir::angle\fP &y)"
.br
.RI "Checks if the value of angle x is equal or greather than the value of angle y\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBscifir::angle\fP &x, const string &init_angle)"
.br
.RI "Checks if the angle x is equal than the angle initialized with the initialization string of angle init_angle\&. "
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBscifir::angle\fP &x, const string &init_angle)"
.br
.RI "Checks if the angle x is not equal than the angle initialized with the initialization string of angle init_angle\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const string &init_angle, const \fBscifir::angle\fP &x)"
.br
.RI "Checks if the angle x is equal than the angle initialized with the initialization string of angle init_angle\&. "
.ti -1c
.RI "bool \fBoperator!=\fP (const string &init_angle, const \fBscifir::angle\fP &x)"
.br
.RI "Checks if the angle x is not equal than the angle initialized with the initialization string of angle init_angle\&. "
.ti -1c
.RI "void \fBoperator+=\fP (string &x, const \fBscifir::angle\fP &y)"
.br
.RI "Concatenates to string x the string representation of angle y\&. "
.ti -1c
.RI "string \fBoperator+\fP (const string &x, const \fBscifir::angle\fP &y)"
.br
.RI "Concatenates the string x with the string representation of angle y into a new string\&. "
.ti -1c
.RI "string \fBoperator+\fP (const \fBscifir::angle\fP &y, const string &x)"
.br
.RI "Concatenates the string x with the string representation of angle y into a new string\&. "
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBscifir::angle\fP &x)"
.br
.RI "Sends the string representation of angle x to an output stream\&. "
.ti -1c
.RI "istream & \fBoperator>>\fP (istream &is, \fBscifir::angle\fP &x)"
.br
.RI "Initializes an angle with an initialization string obtained from an input stream\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool operator!= (const \fBscifir::angle\fP & x, const \fBscifir::angle\fP & y)"

.PP
Checks if two angles have not equal value\&. 
.PP
Definition at line 419 of file angle\&.cpp\&.
.PP
.nf
420 {
421     return !(x == y);
422 }
.fi
.SS "bool operator!= (const \fBscifir::angle\fP & x, const string & init_angle)"

.PP
Checks if the angle x is not equal than the angle initialized with the initialization string of angle init_angle\&. 
.PP
Definition at line 464 of file angle\&.cpp\&.
.PP
.nf
465 {
466     return !(x == init_angle);
467 }
.fi
.SS "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool operator!= (const \fBscifir::angle\fP & y, T x)"

.PP
Checks if the value of angle y is not equal to a numeric type x\&. 
.PP
Definition at line 292 of file angle\&.hpp\&.
.PP
.nf
293 {
294     return (x != y\&.get_value());
295 }
.fi
.SS "bool operator!= (const string & init_angle, const \fBscifir::angle\fP & x)"

.PP
Checks if the angle x is not equal than the angle initialized with the initialization string of angle init_angle\&. 
.PP
Definition at line 475 of file angle\&.cpp\&.
.PP
.nf
476 {
477     return !(init_angle == x);
478 }
.fi
.SS "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool operator!= (T x, const \fBscifir::angle\fP & y)"

.PP
Checks if the value of angle y is not equal to a numeric type x\&. 
.PP
Definition at line 256 of file angle\&.hpp\&.
.PP
.nf
257 {
258     return (x != y\&.get_value());
259 }
.fi
.SS "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> \fBscifir::angle\fP operator* (T x, const \fBscifir::angle\fP & y)"

.PP
Creates a new angle as the multiplication of a numeric type with the value of this angle\&. 
.PP
Definition at line 232 of file angle\&.hpp\&.
.PP
.nf
233 {
234     return scifir::angle(x * y\&.get_value());
235 }
.fi
.SS "string operator+ (const \fBscifir::angle\fP & y, const string & x)"

.PP
Concatenates the string x with the string representation of angle y into a new string\&. 
.PP
Definition at line 495 of file angle\&.cpp\&.
.PP
.nf
496 {
497     ostringstream output;
498     output << y;
499     output << x;
500     return output\&.str();
501 }
.fi
.SS "string operator+ (const string & x, const \fBscifir::angle\fP & y)"

.PP
Concatenates the string x with the string representation of angle y into a new string\&. 
.PP
Definition at line 487 of file angle\&.cpp\&.
.PP
.nf
488 {
489     ostringstream output;
490     output << x;
491     output << y;
492     return output\&.str();
493 }
.fi
.SS "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> \fBscifir::angle\fP operator+ (T x, const \fBscifir::angle\fP & y)"

.PP
Creates a new angle as the sum of a numeric type with the value of this angle\&. 
.PP
Definition at line 220 of file angle\&.hpp\&.
.PP
.nf
221 {
222     return scifir::angle(x + y\&.get_value());
223 }
.fi
.SS "void operator+= (string & x, const \fBscifir::angle\fP & y)"

.PP
Concatenates to string x the string representation of angle y\&. 
.PP
Definition at line 480 of file angle\&.cpp\&.
.PP
.nf
481 {
482     ostringstream output;
483     output << y;
484     x += output\&.str();
485 }
.fi
.SS "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> \fBscifir::angle\fP operator\- (T x, const \fBscifir::angle\fP & y)"

.PP
Creates a new angle as the substraction of the numeric type with the value of this angle\&. 
.PP
Definition at line 226 of file angle\&.hpp\&.
.PP
.nf
227 {
228     return scifir::angle(x - y\&.get_value());
229 }
.fi
.SS "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> \fBscifir::angle\fP operator/ (T x, const \fBscifir::angle\fP & y)"

.PP
Creates a new angle as the division of the value of this angle with the numeric type\&. 
.PP
Definition at line 238 of file angle\&.hpp\&.
.PP
.nf
239 {
240     return scifir::angle(x / y\&.get_value());
241 }
.fi
.SS "bool operator< (const \fBscifir::angle\fP & x, const \fBscifir::angle\fP & y)"

.PP
Checks if the value of angle x is lower than the value of angle y\&. 
.PP
Definition at line 424 of file angle\&.cpp\&.
.PP
.nf
425 {
426     if(x\&.get_value() < y\&.get_value())
427     {
428         return true;
429     }
430     else
431     {
432         return false;
433     }
434 }
.fi
.SS "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool operator< (const \fBscifir::angle\fP & y, T x)"

.PP
Checks if the value of angle y is lower to a numeric type x\&. 
.PP
Definition at line 298 of file angle\&.hpp\&.
.PP
.nf
299 {
300     return (y\&.get_value() < x);
301 }
.fi
.SS "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool operator< (T x, const \fBscifir::angle\fP & y)"

.PP
Checks if the value of angle y is greather to a numeric type x\&. 
.PP
Definition at line 262 of file angle\&.hpp\&.
.PP
.nf
263 {
264     return (x < y\&.get_value());
265 }
.fi
.SS "ostream& operator<< (ostream & os, const \fBscifir::angle\fP & x)"

.PP
Sends the string representation of angle x to an output stream\&. 
.PP
Definition at line 503 of file angle\&.cpp\&.
.PP
.nf
504 {
505     return os << to_string(x);
506 }
.fi
.SS "bool operator<= (const \fBscifir::angle\fP & x, const \fBscifir::angle\fP & y)"

.PP
Checks if the value of angle x is lower or equal than the value of angle y\&. 
.PP
Definition at line 448 of file angle\&.cpp\&.
.PP
.nf
449 {
450     return !(x > y);
451 }
.fi
.SS "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool operator<= (const \fBscifir::angle\fP & y, T x)"

.PP
Checks if the value of angle y is lower or equal than a numeric type x\&. 
.PP
Definition at line 310 of file angle\&.hpp\&.
.PP
.nf
311 {
312     return (y\&.get_value() <= x);
313 }
.fi
.SS "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool operator<= (T x, const \fBscifir::angle\fP & y)"

.PP
Checks if the value of angle y is equal or greather than a numeric type x\&. 
.PP
Definition at line 274 of file angle\&.hpp\&.
.PP
.nf
275 {
276     return (x <= y\&.get_value());
277 }
.fi
.SS "bool operator== (const \fBscifir::angle\fP & x, const \fBscifir::angle\fP & y)"

.PP
Checks if two angles have equal value\&. 
.PP
Definition at line 407 of file angle\&.cpp\&.
.PP
.nf
408 {
409     if(x\&.get_value() == y\&.get_value())
410     {
411         return true;
412     }
413     else
414     {
415         return false;
416     }
417 }
.fi
.SS "bool operator== (const \fBscifir::angle\fP & x, const string & init_angle)"

.PP
Checks if the angle x is equal than the angle initialized with the initialization string of angle init_angle\&. 
.PP
Definition at line 458 of file angle\&.cpp\&.
.PP
.nf
459 {
460     scifir::angle y = scifir::angle(init_angle);
461     return (x == y);
462 }
.fi
.SS "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool operator== (const \fBscifir::angle\fP & y, T x)"

.PP
Checks if the value of angle y is equal to a numeric type x\&. 
.PP
Definition at line 286 of file angle\&.hpp\&.
.PP
.nf
287 {
288     return (x == y\&.get_value());
289 }
.fi
.SS "bool operator== (const string & init_angle, const \fBscifir::angle\fP & x)"

.PP
Checks if the angle x is equal than the angle initialized with the initialization string of angle init_angle\&. 
.PP
Definition at line 469 of file angle\&.cpp\&.
.PP
.nf
470 {
471     scifir::angle y = scifir::angle(init_angle);
472     return (x == y);
473 }
.fi
.SS "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool operator== (T x, const \fBscifir::angle\fP & y)"

.PP
Checks if the value of angle y is equal to a numeric type x\&. 
.PP
Definition at line 250 of file angle\&.hpp\&.
.PP
.nf
251 {
252     return (x == y\&.get_value());
253 }
.fi
.SS "bool operator> (const \fBscifir::angle\fP & x, const \fBscifir::angle\fP & y)"

.PP
Checks if the value of angle x is greather than the value of angle y\&. 
.PP
Definition at line 436 of file angle\&.cpp\&.
.PP
.nf
437 {
438     if(x\&.get_value() > y\&.get_value())
439     {
440         return true;
441     }
442     else
443     {
444         return false;
445     }
446 }
.fi
.SS "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool operator> (const \fBscifir::angle\fP & y, T x)"

.PP
Checks if the value of angle y is greather to a numeric type x\&. 
.PP
Definition at line 304 of file angle\&.hpp\&.
.PP
.nf
305 {
306     return (y\&.get_value() > x);
307 }
.fi
.SS "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool operator> (T x, const \fBscifir::angle\fP & y)"

.PP
Checks if the value of angle y is lower to a numeric type x\&. 
.PP
Definition at line 268 of file angle\&.hpp\&.
.PP
.nf
269 {
270     return (x > y\&.get_value());
271 }
.fi
.SS "bool operator>= (const \fBscifir::angle\fP & x, const \fBscifir::angle\fP & y)"

.PP
Checks if the value of angle x is equal or greather than the value of angle y\&. 
.PP
Definition at line 453 of file angle\&.cpp\&.
.PP
.nf
454 {
455     return !(x < y);
456 }
.fi
.SS "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool operator>= (const \fBscifir::angle\fP & y, T x)"

.PP
Checks if the value of angle y is equal or greather than a numeric type x\&. 
.PP
Definition at line 316 of file angle\&.hpp\&.
.PP
.nf
317 {
318     return (y\&.get_value() >= x);
319 }
.fi
.SS "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> bool operator>= (T x, const \fBscifir::angle\fP & y)"

.PP
Checks if the value of angle y is lower or equal than a numeric type x\&. 
.PP
Definition at line 280 of file angle\&.hpp\&.
.PP
.nf
281 {
282     return (x >= y\&.get_value());
283 }
.fi
.SS "istream& operator>> (istream & is, \fBscifir::angle\fP & x)"

.PP
Initializes an angle with an initialization string obtained from an input stream\&. 
.PP
Definition at line 508 of file angle\&.cpp\&.
.PP
.nf
509 {
510     char a[256];
511     is\&.getline(a, 256);
512     string b(a);
513     boost::trim(b);
514     x = scifir::angle(b);
515     return is;
516 }
.fi
.SS "template<typename T , typename  = typename enable_if<scifir::is_number<T>::value>::type> \fBscifir::angle\fP operator^ (T x, const \fBscifir::angle\fP & y)"

.PP
Creates a new angle as the power of a numeric type with the value of this angle\&. 
.PP
Definition at line 244 of file angle\&.hpp\&.
.PP
.nf
245 {
246     return scifir::angle(pow(x, y\&.get_value()));
247 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
