.TH "predefined_units/chemistry_units.hpp" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
predefined_units/chemistry_units.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./units/scalar_unit\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBscifir::cas_number\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBscifir\fP"
.br
.RI "The namespace scifir contains all scifir-units, excepting the string literals, which are outside\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (density)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (viscosity)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (specific_volume)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (specific_heat_capacity)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (specific_entropy)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (specific_energy)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (molar_volume)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (molar_mass)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (molar_heat_capacity)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (molar_enthalpy)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (molar_entropy)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (molar_energy)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (molar_conductivity)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (energy_density)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (catalytic_efficiency)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (molarity)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (molality)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (linear_mass_density)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (area_density)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (dynamic_viscosity)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (mass_flow_rate)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (catalytic_activity)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
