.TH "predefined_units/chemistry_units.hpp" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
predefined_units/chemistry_units.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./units/scalar_unit\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBscifir::cas_number\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBscifir\fP"
.br
.RI "The namespace scifir contains all scifir-units, excepting the string literals, which are outside\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBdensity\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBviscosity\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBspecific_volume\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBspecific_heat_capacity\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBspecific_entropy\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBspecific_energy\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBmolar_volume\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBmolar_mass\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBmolar_heat_capacity\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBmolar_enthalpy\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBmolar_entropy\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBmolar_energy\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBmolar_conductivity\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBenergy_density\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBcatalytic_efficiency\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBmolarity\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBmolality\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBlinear_mass_density\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBarea_density\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBdynamic_viscosity\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBmass_flow_rate\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBcatalytic_activity\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
