.TH "predefined_units/chemistry_units.cpp" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
predefined_units/chemistry_units.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&./chemistry_units\&.hpp'\fP
.br
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBscifir\fP"
.br
.RI "The namespace scifir contains all scifir-units, excepting the string literals, which are outside\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBdensity\fP,'g/\fBm3'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBviscosity\fP,'m2/\fBs'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBspecific_volume\fP,'m3/\fBg'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBspecific_heat_capacity\fP,'m2/\fBs2\fP*\fBK'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBspecific_entropy\fP,'m2/\fBs2\fP*\fBK'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBspecific_energy\fP,'m2/\fBs2'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBmolar_volume\fP,'m3/\fBmol'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBmolar_mass\fP,'g/\fBmol'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBmolar_heat_capacity\fP,'m2*g/\fBs2\fP*K*\fBmol'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBmolar_enthalpy\fP,'m2*g/\fBs2\fP*\fBmol'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBmolar_entropy\fP,'m2*g/\fBs2\fP*K*\fBmol'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBmolar_energy\fP,'m2*g/\fBs2\fP*\fBmol'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBmolar_conductivity\fP,'s3*\fBA2\fP/g*\fBmol'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBenergy_density\fP,'g/m*\fBs2'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBcatalytic_efficiency\fP,'m3/s*\fBmol'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBmolarity\fP,'mol/\fBm3'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBmolality\fP,'mol/\fBg'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBlinear_mass_density\fP,'g/\fBm'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBarea_density\fP,'g/\fBm2'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBdynamic_viscosity\fP,'g/m*\fBs'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBmass_flow_rate\fP,'g/\fBs'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBcatalytic_activity\fP,'kat')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
