.TH "units/conversion.cpp" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units/conversion.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&./conversion\&.hpp'\fP
.br
\fC#include '\&./dimension\&.hpp'\fP
.br
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBscifir\fP"
.br
.RI "The namespace scifir contains all scifir-units, excepting the string literals, which are outside\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "map< string, conversion > \fBscifir::get_conversion\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
