.TH "coordinates/coordinates_nd.cpp" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coordinates/coordinates_nd.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&./coordinates_nd\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBscifir\fP"
.br
.RI "The namespace scifir contains all scifir-units, excepting the string literals, which are outside\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "string \fBscifir::to_string\fP (const coordinates_nd< float > &x)"
.br
.ti -1c
.RI "float \fBscifir::distance\fP (const coordinates_nd< float > &x, const coordinates_nd< float > &y)"
.br
.ti -1c
.RI "float \fBscifir::distance\fP (const coordinates_nd< float > &x, const point_nd< float > &y)"
.br
.ti -1c
.RI "float \fBscifir::distance\fP (const point_nd< float > &x, const coordinates_nd< float > &y)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBscifir::coordinates_nd\fP< float > &x)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & os, const \fBscifir::coordinates_nd\fP< float > & x)"

.PP
Definition at line 82 of file coordinates_nd\&.cpp\&.
.PP
.nf
83 {
84     return os << scifir::to_string(x);
85 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
