.TH "predefined_units/electronics_units.cpp" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
predefined_units/electronics_units.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&./electronics_units\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBscifir\fP"
.br
.RI "The namespace scifir contains all scifir-units, excepting the string literals, which are outside\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (electrical_conductivity,'A2*s3/kg*m3')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (resistance,'kg*m2/A2*s3')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (electric_conductance,'A2*s3/kg*m2')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (capacitance,'A2*s4/m2*kg')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (permittivity,'A2*s4/kg*m3')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (resistivity,'kg*m3/A2*s3')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (linear_charge_density,'A*s/m')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (frequency_drift,'1/s2')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
