.TH "predefined_units/informatics_units.cpp" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
predefined_units/informatics_units.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&./informatics_units\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBscifir\fP"
.br
.RI "The namespace scifir contains all scifir-units, excepting the string literals, which are outside\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBtransfer_speed\fP,'B/\fBs'\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
