.TH "md_INSTALL" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_INSTALL \- Installation 
.PP
 To install \fBscifir-units\fP you have to use \fBCMake\fP and \fBmake\fP\&. The library is called scifir-units, the other scifir libraries aren't yet published in the web\&. The commands to install it are the following:
.PP
.PP
.nf
cmake \&.
make
make install
.fi
.PP
 
