.TH "predefined_units/physics_units.cpp" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
predefined_units/physics_units.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&./physics_units\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBscifir\fP"
.br
.RI "The namespace scifir contains all scifir-units, excepting the string literals, which are outside\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_2D_CPP\fP (displacement,'m')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_3D_CPP\fP (displacement,'m')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_ND_CPP\fP (displacement,'m')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (velocity,'m/s')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (acceleration,'m/s2')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (jerk,'m/s3')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (snap,'m/s4')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (angular_velocity,'rad/s')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (angular_acceleration,'rad/s2')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (angular_momentum,'m2*kg/s')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (impulse,'m*kg/s')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (force,'kg*m/s2')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (torque,'kg*m2/s2')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (pressure,'kg/m*s2')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (surface_tension,'kg/s2')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (stiffness,'kg/s2')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (moment_of_inertia,'m2*kg')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (electric_current,'A')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (voltage,'V')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (electric_displacement_field,'A*s/m2')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (electric_charge_density,'A*s/m3')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (electric_current_density,'A/m2')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (electric_field_strength,'kg*m/A*s3')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (electron_mobility,'A*s2/kg')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (inductance,'H')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (volumetric_flow,'m3/s')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (diffusion_coefficient,'m2/s')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (compressibility,'m*s2/kg')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (polarization_density,'A*s/m2')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (magnetic_permeability,'A2*s2/kg*m')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (magnetization,'A/m')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (magnetic_flux,'Wb')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (magnetic_strength,'Wb/m2')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (magnetic_moment,'A*m2')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (magnetic_reluctance,'A2*s2/kg*m2')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (magnetic_vector_potential,'kg*m/A*s2')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (magnetic_rigidity,'kg*m/A*s2')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (magnetomotive_force,'A')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (magnetic_susceptibility,'A2*s2/kg*m')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (optical_power,'1/m')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (luminance,'cd/m2')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (illuminance,'lx')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (luminous_flux,'lm')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (luminous_energy,'cd*sr*s')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (luminous_exposure,'cd*sr*s/m2')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (luminous_efficacy,'lm/W')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (ionizing_radiation,'A*s/kg')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (absorbed_dose,'m2/s3')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (energy,'kg*m2/s2')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (action,'kg*m2/s')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (power,'kg*m2/s3')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (power_density,'kg/m*s3')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (enthalpy,'kg*m2/s2')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (entropy,'kg*m2/K*s2')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (heat_capacity,'kg*m2/K*s2')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (heat_flux_density,'kg/s3')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (thermal_conductivity,'kg*m/K*s3')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (thermal_diffusivity,'m2/s')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (thermal_resistance,'K*s3/kg*m2')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (thermal_expansion_coefficient,'1/K')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (temperature_gradient,'K/m')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (energy_flux_density,'kg/s3')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (wavenumber,'1/m')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (frequency,'1/s')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
