.TH "predefined_units/physics_units.cpp" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
predefined_units/physics_units.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&./physics_units\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBscifir\fP"
.br
.RI "The namespace scifir contains all scifir-units, excepting the string literals, which are outside\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_2D_CPP\fP (\fBdisplacement\fP,'m')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_3D_CPP\fP (\fBdisplacement\fP,'m')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_ND_CPP\fP (\fBdisplacement\fP,'m')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBvelocity\fP,'m/\fBs'\fP)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBacceleration\fP,'m/\fBs2'\fP)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBjerk\fP,'m/\fBs3'\fP)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBsnap\fP,'m/\fBs4'\fP)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBangular_velocity\fP,'rad/\fBs'\fP)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBangular_acceleration\fP,'rad/\fBs2'\fP)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBangular_momentum\fP,'m2*\fBkg\fP/\fBs'\fP)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBimpulse\fP,'m*\fBkg\fP/\fBs'\fP)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBforce\fP,'kg*m/\fBs2'\fP)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBtorque\fP,'kg*\fBm2\fP/\fBs2'\fP)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBpressure\fP,'kg/m*\fBs2'\fP)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBsurface_tension\fP,'kg/\fBs2'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBstiffness\fP,'kg/\fBs2'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBmoment_of_inertia\fP,'m2*\fBkg'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBelectric_current\fP,'A')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBvoltage\fP,'V')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBelectric_displacement_field\fP,'A*s/\fBm2'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBelectric_charge_density\fP,'A*s/\fBm3'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBelectric_current_density\fP,'A/\fBm2'\fP)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBelectric_field_strength\fP,'kg*m/A*\fBs3'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBelectron_mobility\fP,'A*\fBs2\fP/\fBkg'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBinductance\fP,'H')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBvolumetric_flow\fP,'m3/\fBs'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBdiffusion_coefficient\fP,'m2/\fBs'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBcompressibility\fP,'m*\fBs2\fP/\fBkg'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBpolarization_density\fP,'A*s/\fBm2'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBmagnetic_permeability\fP,'A2*\fBs2\fP/\fBkg\fP*\fBm'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBmagnetization\fP,'A/\fBm'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBmagnetic_flux\fP,'Wb')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBmagnetic_strength\fP,'Wb/\fBm2'\fP)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBmagnetic_moment\fP,'A*\fBm2'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBmagnetic_reluctance\fP,'A2*\fBs2\fP/\fBkg\fP*\fBm2'\fP)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBmagnetic_vector_potential\fP,'kg*m/A*\fBs2'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBmagnetic_rigidity\fP,'kg*m/A*\fBs2'\fP)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBmagnetomotive_force\fP,'A')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBmagnetic_susceptibility\fP,'A2*\fBs2\fP/\fBkg\fP*\fBm'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBoptical_power\fP,'1/m')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBluminance\fP,'cd/\fBm2'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBilluminance\fP,'lx')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBluminous_flux\fP,'lm')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBluminous_energy\fP,'cd*\fBsr\fP*\fBs'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBluminous_exposure\fP,'cd*\fBsr\fP*s/\fBm2'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBluminous_efficacy\fP,'lm/\fBW'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBionizing_radiation\fP,'A*s/\fBkg'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBabsorbed_dose\fP,'m2/\fBs3'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBenergy\fP,'kg*\fBm2\fP/\fBs2'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBaction\fP,'kg*\fBm2\fP/\fBs'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBpower\fP,'kg*\fBm2\fP/\fBs3'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBpower_density\fP,'kg/m*\fBs3'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBenthalpy\fP,'kg*\fBm2\fP/\fBs2'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBentropy\fP,'kg*\fBm2\fP/K*\fBs2'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBheat_capacity\fP,'kg*\fBm2\fP/K*\fBs2'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBheat_flux_density\fP,'kg/\fBs3'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBthermal_conductivity\fP,'kg*m/K*\fBs3'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBthermal_diffusivity\fP,'m2/\fBs'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBthermal_resistance\fP,'K*\fBs3\fP/\fBkg\fP*\fBm2'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBthermal_expansion_coefficient\fP,'1/K')"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_CPP\fP (\fBtemperature_gradient\fP,'K/\fBm'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBenergy_flux_density\fP,'kg/\fBs3'\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBwavenumber\fP,'1/m')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (\fBfrequency\fP,'1/s')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
