.TH "predefined_units/physics_units.hpp" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
predefined_units/physics_units.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./units/scalar_unit\&.hpp'\fP
.br
\fC#include '\&.\&./units/vector_unit_2d\&.hpp'\fP
.br
\fC#include '\&.\&./units/vector_unit_3d\&.hpp'\fP
.br
\fC#include '\&.\&./units/unit_basic\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBscifir\fP"
.br
.RI "The namespace scifir contains all scifir-units, excepting the string literals, which are outside\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef length \fBscifir::wavelength\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_2D_HPP\fP (displacement)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_3D_HPP\fP (displacement)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_ND_HPP\fP (displacement)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (velocity)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (acceleration)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (jerk)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (snap)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (angular_velocity)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (angular_acceleration)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (angular_momentum)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (impulse)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (force)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (torque)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (pressure)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (surface_tension)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (stiffness)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (moment_of_inertia)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (electric_current)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (voltage)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (electric_displacement_field)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (electric_charge_density)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (electric_current_density)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (electric_field_strength)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (electron_mobility)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (inductance)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (volumetric_flow)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (diffusion_coefficient)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (compressibility)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (polarization_density)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (magnetic_permeability)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (magnetization)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (magnetic_flux)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (magnetic_strength)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (magnetic_moment)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (magnetic_reluctance)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (magnetic_vector_potential)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (magnetic_rigidity)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (magnetomotive_force)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (magnetic_susceptibility)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (optical_power)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (luminance)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (illuminance)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (luminous_flux)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (luminous_energy)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (luminous_exposure)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (luminous_efficacy)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (ionizing_radiation)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (absorbed_dose)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (energy)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (action)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (power)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (power_density)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (enthalpy)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (entropy)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (heat_capacity)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (heat_flux_density)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (thermal_conductivity)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (thermal_diffusivity)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (thermal_resistance)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (thermal_expansion_coefficient)"
.br
.ti -1c
.RI "\fBscifir::VECTOR_UNIT_HPP\fP (temperature_gradient)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (energy_flux_density)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (wavenumber)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (frequency)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
