.TH "topology/point_2d.cpp" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
topology/point_2d.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&./point_2d\&.hpp'\fP
.br
\fC#include '\&.\&./coordinates/coordinates_2d\&.hpp'\fP
.br
\fC#include '\&.\&./util/types\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBscifir\fP"
.br
.RI "The namespace scifir contains all scifir-units, excepting the string literals, which are outside\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "string \fBscifir::to_string\fP (const point_2d< float > &x)"
.br
.ti -1c
.RI "float \fBscifir::distance\fP (const point_2d< float > &x, const point_2d< float > &y)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBscifir::point_2d\fP< float > &x)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & os, const \fBscifir::point_2d\fP< float > & x)"

.PP
Definition at line 41 of file point_2d\&.cpp\&.
.PP
.nf
42 {
43     return os << scifir::to_string(x);
44 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
