.TH "scifir::material_vector_unit_2d< T, U >" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::material_vector_unit_2d< T, U >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <material_vector_unit_2d\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmaterial_vector_unit_2d\fP ()"
.br
.ti -1c
.RI "\fBmaterial_vector_unit_2d\fP (\fBconst\fP \fBmaterial_vector_unit_2d\fP< T, \fBU\fP > &x)"
.br
.ti -1c
.RI "\fBmaterial_vector_unit_2d\fP (\fBmaterial_vector_unit_2d\fP< T, \fBU\fP > &&x)"
.br
.ti -1c
.RI "\fBmaterial_vector_unit_2d\fP (\fBconst\fP T &\fBx_vector\fP, \fBconst\fP \fBcoordinates_2d\fP< \fBU\fP > &\fBx_coordinates\fP)"
.br
.ti -1c
.RI "\fBmaterial_vector_unit_2d\fP (\fBconst\fP \fBstring\fP &\fBinit_material_vector_unit_2d\fP)"
.br
.ti -1c
.RI "\fBmaterial_vector_unit_2d\fP< T, \fBU\fP > & \fBoperator=\fP (\fBconst\fP \fBmaterial_vector_unit_2d\fP< T, \fBU\fP > &x)"
.br
.ti -1c
.RI "\fBmaterial_vector_unit_2d\fP< T, \fBU\fP > & \fBoperator=\fP (\fBmaterial_vector_unit_2d\fP< T, \fBU\fP > &&x)"
.br
.ti -1c
.RI "\fBmaterial_vector_unit_2d\fP< T, \fBU\fP > & \fBoperator=\fP (\fBconst\fP \fBstring\fP &\fBinit_material_vector_unit_2d\fP)"
.br
.ti -1c
.RI "\fBstring\fP \fBvectorial_display\fP (\fBint\fP \fBnumber_of_decimals\fP=2) \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBvectorial_derived_display\fP (\fBint\fP \fBnumber_of_decimals\fP=2) \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBvectorial_custom_display\fP (\fBconst\fP \fBstring\fP &\fBinit_dimensions\fP, \fBint\fP \fBnumber_of_decimals\fP=2) \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBvector\fP"
.br
.ti -1c
.RI "\fBcoordinates_2d\fP< \fBU\fP > \fBcoordinates\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBinitialize_from_string\fP (\fBstring\fP \fBinit_material_vector_unit_2d\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<\fBtypename\fP T, \fBtypename\fP \fBU\fP = length>
.br
class scifir::material_vector_unit_2d< T, U >"
.PP
Definition at line \fB15\fP of file \fBmaterial_vector_unit_2d\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP T , \fBtypename\fP \fBU\fP  = length> \fBscifir::material_vector_unit_2d\fP< T, \fBU\fP >::material_vector_unit_2d ()\fC [inline]\fP"

.PP
Definition at line \fB18\fP of file \fBmaterial_vector_unit_2d\&.hpp\fP\&..PP
.nf
18                                       : vector(),coordinates()
19             {}
.fi

.SS "template<\fBtypename\fP T , \fBtypename\fP \fBU\fP  = length> \fBscifir::material_vector_unit_2d\fP< T, \fBU\fP >::material_vector_unit_2d (\fBconst\fP \fBmaterial_vector_unit_2d\fP< T, \fBU\fP > & x)\fC [inline]\fP"

.PP
Definition at line \fB21\fP of file \fBmaterial_vector_unit_2d\&.hpp\fP\&..PP
.nf
21                                                                            : vector(x\&.vector),coordinates(x\&.coordinates)
22             {}
.fi

.SS "template<\fBtypename\fP T , \fBtypename\fP \fBU\fP  = length> \fBscifir::material_vector_unit_2d\fP< T, \fBU\fP >::material_vector_unit_2d (\fBmaterial_vector_unit_2d\fP< T, \fBU\fP > && x)\fC [inline]\fP"

.PP
Definition at line \fB24\fP of file \fBmaterial_vector_unit_2d\&.hpp\fP\&..PP
.nf
24                                                                       : vector(std::move(x\&.vector)),coordinates(std::move(x\&.coordinates))
25             {}
.fi

.SS "template<\fBtypename\fP T , \fBtypename\fP \fBU\fP  = length> \fBscifir::material_vector_unit_2d\fP< T, \fBU\fP >::material_vector_unit_2d (\fBconst\fP T & x_vector, \fBconst\fP \fBcoordinates_2d\fP< \fBU\fP > & x_coordinates)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line \fB27\fP of file \fBmaterial_vector_unit_2d\&.hpp\fP\&..PP
.nf
27                                                                                                         : vector(x_vector),coordinates(x_coordinates)
28             {}
.fi

.SS "template<\fBtypename\fP T , \fBtypename\fP \fBU\fP  = length> \fBscifir::material_vector_unit_2d\fP< T, \fBU\fP >::material_vector_unit_2d (\fBconst\fP \fBstring\fP & init_material_vector_unit_2d)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line \fB30\fP of file \fBmaterial_vector_unit_2d\&.hpp\fP\&..PP
.nf
30                                                                                          : material_vector_unit_2d<T,U>()
31             {
32                 initialize_from_string(init_material_vector_unit_2d);
33             }
.fi

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP T , \fBtypename\fP \fBU\fP  = length> \fBvoid\fP \fBscifir::material_vector_unit_2d\fP< T, \fBU\fP >::initialize_from_string (\fBstring\fP init_material_vector_unit_2d)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line \fB80\fP of file \fBmaterial_vector_unit_2d\&.hpp\fP\&..PP
.nf
81             {
82                 vector<string> values;
83                 boost::split(values,init_material_vector_unit_2d,boost::is_any_of(";"));
84                 if (values\&.size() > 0)
85                 {
86                     vector = T(values[0]);
87                     coordinates = coordinates_2d<U>(values[1]);
88                 }
89             }
.fi

.SS "template<\fBtypename\fP T , \fBtypename\fP \fBU\fP  = length> \fBmaterial_vector_unit_2d\fP< T, \fBU\fP > & \fBscifir::material_vector_unit_2d\fP< T, \fBU\fP >::operator= (\fBconst\fP \fBmaterial_vector_unit_2d\fP< T, \fBU\fP > & x)\fC [inline]\fP"

.PP
Definition at line \fB35\fP of file \fBmaterial_vector_unit_2d\&.hpp\fP\&..PP
.nf
36             {
37                 vector = x\&.vector;
38                 coordinates = x\&.coordinates;
39                 return *this;
40             }
.fi

.SS "template<\fBtypename\fP T , \fBtypename\fP \fBU\fP  = length> \fBmaterial_vector_unit_2d\fP< T, \fBU\fP > & \fBscifir::material_vector_unit_2d\fP< T, \fBU\fP >::operator= (\fBconst\fP \fBstring\fP & init_material_vector_unit_2d)\fC [inline]\fP"

.PP
Definition at line \fB49\fP of file \fBmaterial_vector_unit_2d\&.hpp\fP\&..PP
.nf
50             {
51                 initialize_from_string(init_material_vector_unit_2d);
52                 return *this;
53             }
.fi

.SS "template<\fBtypename\fP T , \fBtypename\fP \fBU\fP  = length> \fBmaterial_vector_unit_2d\fP< T, \fBU\fP > & \fBscifir::material_vector_unit_2d\fP< T, \fBU\fP >::operator= (\fBmaterial_vector_unit_2d\fP< T, \fBU\fP > && x)\fC [inline]\fP"

.PP
Definition at line \fB42\fP of file \fBmaterial_vector_unit_2d\&.hpp\fP\&..PP
.nf
43             {
44                 vector = std::move(x\&.vector);
45                 coordinates = std::move(x\&.coordinates);
46                 return *this;
47             }
.fi

.SS "template<\fBtypename\fP T , \fBtypename\fP \fBU\fP  = length> \fBstring\fP \fBscifir::material_vector_unit_2d\fP< T, \fBU\fP >::vectorial_custom_display (\fBconst\fP \fBstring\fP & init_dimensions, \fBint\fP number_of_decimals = \fC2\fP) const\fC [inline]\fP"

.PP
Definition at line \fB69\fP of file \fBmaterial_vector_unit_2d\&.hpp\fP\&..PP
.nf
70             {
71                 ostringstream out;
72                 out << vector\&.vectorial_derived_display(init_dimensions,number_of_decimals) << ";" << coordinates\&.x << "," << coordinates\&.y;
73                 return out\&.str();
74             }
.fi

.SS "template<\fBtypename\fP T , \fBtypename\fP \fBU\fP  = length> \fBstring\fP \fBscifir::material_vector_unit_2d\fP< T, \fBU\fP >::vectorial_derived_display (\fBint\fP number_of_decimals = \fC2\fP) const\fC [inline]\fP"

.PP
Definition at line \fB62\fP of file \fBmaterial_vector_unit_2d\&.hpp\fP\&..PP
.nf
63             {
64                 ostringstream out;
65                 out << vector\&.vectorial_derived_display(number_of_decimals) << ";" << coordinates\&.x << "," << coordinates\&.y;
66                 return out\&.str();
67             }
.fi

.SS "template<\fBtypename\fP T , \fBtypename\fP \fBU\fP  = length> \fBstring\fP \fBscifir::material_vector_unit_2d\fP< T, \fBU\fP >::vectorial_display (\fBint\fP number_of_decimals = \fC2\fP) const\fC [inline]\fP"

.PP
Definition at line \fB55\fP of file \fBmaterial_vector_unit_2d\&.hpp\fP\&..PP
.nf
56             {
57                 ostringstream out;
58                 out << vector\&.vectorial_display(number_of_decimals) << ";" << coordinates\&.x << "," << coordinates\&.y;
59                 return out\&.str();
60             }
.fi

.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP T , \fBtypename\fP \fBU\fP  = length> \fBcoordinates_2d\fP<\fBU\fP> \fBscifir::material_vector_unit_2d\fP< T, \fBU\fP >::coordinates"

.PP
Definition at line \fB77\fP of file \fBmaterial_vector_unit_2d\&.hpp\fP\&.
.SS "template<\fBtypename\fP T , \fBtypename\fP \fBU\fP  = length> T \fBscifir::material_vector_unit_2d\fP< T, \fBU\fP >::vector"

.PP
Definition at line \fB76\fP of file \fBmaterial_vector_unit_2d\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
