.TH "scifir::coordinates_ndr< float >" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::coordinates_ndr< float >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcoordinates_ndr\fP (\fBconst\fP \fBcoordinates_ndr\fP< \fBfloat\fP > &x)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP (\fBcoordinates_ndr\fP< \fBfloat\fP > &&x)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP (\fBconst\fP vector< \fBfloat\fP > &\fBnew_values\fP, \fBconst\fP vector< \fBfloat\fP > &\fBnew_angles\fP)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP (\fBconst\fP vector< \fBfloat\fP > &\fBnew_values\fP, \fBconst\fP vector< \fBangle\fP > &\fBnew_angles\fP)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP (\fBconst\fP \fBfloat\fP &\fBnew_x\fP)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP (\fBconst\fP \fBfloat\fP &\fBnew_x\fP, \fBconst\fP \fBfloat\fP &\fBnew_y\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP (\fBconst\fP \fBfloat\fP &\fBnew_p\fP, \fBconst\fP \fBangle\fP &\fBnew_polar_theta\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP (\fBconst\fP \fBfloat\fP &\fBnew_x\fP, \fBconst\fP \fBfloat\fP &\fBnew_y\fP, \fBconst\fP \fBfloat\fP &\fBnew_z\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP, \fBconst\fP \fBangle\fP &\fBnew_phi\fP)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP (\fBconst\fP \fBfloat\fP &\fBnew_p\fP, \fBconst\fP \fBangle\fP &\fBnew_cylindrical_theta\fP, \fBconst\fP \fBfloat\fP &\fBnew_z\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP, \fBconst\fP \fBangle\fP &\fBnew_phi\fP)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP (\fBconst\fP \fBfloat\fP &\fBnew_r\fP, \fBconst\fP \fBangle\fP &\fBnew_spherical_theta\fP, \fBconst\fP \fBangle\fP &\fBnew_spherical_phi\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP, \fBconst\fP \fBangle\fP &\fBnew_phi\fP)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP (\fBconst\fP \fBangle\fP &\fBnew_latitude\fP, \fBconst\fP \fBangle\fP &\fBnew_longitude\fP, \fBconst\fP \fBfloat\fP &\fBnew_altitude\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP, \fBconst\fP \fBangle\fP &\fBnew_phi\fP)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP (\fBconst\fP \fBpoint_nd\fP< \fBfloat\fP > &\fBnew_point\fP, \fBconst\fP vector< \fBfloat\fP > &\fBnew_angles\fP)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP (\fBconst\fP \fBpoint_nd\fP< \fBfloat\fP > &\fBnew_point\fP, \fBconst\fP vector< \fBangle\fP > &\fBnew_angles\fP)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP (\fBconst\fP \fBcoordinates_nd\fP< \fBfloat\fP > &\fBnew_coordinates\fP, \fBconst\fP vector< \fBfloat\fP > &\fBnew_angles\fP)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP (\fBconst\fP \fBcoordinates_nd\fP< \fBfloat\fP > &\fBnew_coordinates\fP, \fBconst\fP vector< \fBangle\fP > &\fBnew_angles\fP)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP (\fBstring\fP \fBinit_coordinates_ndr\fP)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP< \fBfloat\fP > & \fBoperator=\fP (\fBconst\fP \fBcoordinates_ndr\fP< \fBfloat\fP > &\fBx_coordinates\fP)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP< \fBfloat\fP > & \fBoperator=\fP (\fBcoordinates_ndr\fP< \fBfloat\fP > &&\fBx_coordinates\fP)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP< \fBfloat\fP > & \fBoperator=\fP (\fBconst\fP \fBpoint_nd\fP< \fBfloat\fP > &\fBx_point\fP)"
.br
.ti -1c
.RI "\fBcoordinates_ndr\fP< \fBfloat\fP > & \fBoperator=\fP (\fBconst\fP \fBcoordinates_nd\fP< \fBfloat\fP > &\fBx_coordinates\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBis_nd\fP (\fBunsigned\fP \fBint\fP \fBi\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBint\fP \fBget_nd\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBchange_nd\fP (\fBunsigned\fP \fBint\fP \fBi\fP, \fBconst\fP vector< \fBfloat\fP > &\fBnew_values\fP, \fBconst\fP vector< \fBfloat\fP > &\fBnew_angles\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBchange_nd\fP (\fBunsigned\fP \fBint\fP \fBi\fP, \fBconst\fP vector< \fBfloat\fP > &\fBnew_values\fP, \fBconst\fP vector< \fBangle\fP > &\fBnew_angles\fP)"
.br
.ti -1c
.RI "\fBconst\fP vector< \fBfloat\fP > & \fBget_values\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_values\fP (\fBconst\fP vector< \fBfloat\fP > &\fBnew_values\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBfloat\fP & \fBget_value\fP (\fBunsigned\fP \fBint\fP \fBi\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBfloat\fP & \fBget_value\fP (\fBunsigned\fP \fBint\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBconst\fP vector< \fBangle\fP > & \fBget_angles\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_angles\fP (\fBconst\fP vector< \fBfloat\fP > &\fBnew_angles\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_angles\fP (\fBconst\fP vector< \fBangle\fP > &\fBnew_angles\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBangle\fP & \fBget_angle\fP (\fBunsigned\fP \fBint\fP \fBi\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBangle\fP & \fBget_angle\fP (\fBunsigned\fP \fBint\fP \fBi\fP)"
.br
.ti -1c
.RI "\fBfloat\fP \fBget_p\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBangle\fP \fBget_spherical_theta\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBget_r\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBangle\fP \fBget_spherical_phi\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBangle\fP \fBget_latitude\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBangle\fP \fBget_longitude\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBget_altitude\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBpoint_to\fP (direction::name x)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_position\fP (\fBconst\fP \fBfloat\fP &\fBnew_x\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_position\fP (\fBconst\fP \fBfloat\fP &\fBnew_x\fP, \fBconst\fP \fBfloat\fP &\fBnew_y\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_position\fP (\fBconst\fP \fBfloat\fP &\fBnew_p\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_position\fP (\fBconst\fP \fBfloat\fP &\fBnew_x\fP, \fBconst\fP \fBfloat\fP &\fBnew_y\fP, \fBconst\fP \fBfloat\fP &\fBnew_z\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_position\fP (\fBconst\fP \fBfloat\fP &\fBnew_p\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP, \fBconst\fP \fBfloat\fP &\fBnew_z\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_position\fP (\fBconst\fP \fBfloat\fP &\fBnew_r\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP, \fBconst\fP \fBangle\fP &\fBnew_phi\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_position\fP (\fBconst\fP \fBangle\fP &\fBnew_latitude\fP, \fBconst\fP \fBangle\fP &\fBnew_longitude\fP, \fBconst\fP \fBfloat\fP &\fBnew_altitude\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_position\fP (\fBconst\fP vector< \fBfloat\fP > &\fBnew_values\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBrotate\fP (\fBint\fP \fBdimension_number\fP, \fBint\fP \fBaxis\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBconst\fP \fBfloat\fP &\fBnew_x\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBconst\fP \fBdisplacement_2d\fP &\fBx_displacement\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBconst\fP \fBfloat\fP &\fBnew_x\fP, \fBconst\fP \fBfloat\fP &\fBnew_y\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBconst\fP \fBfloat\fP &\fBnew_p\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBconst\fP \fBdisplacement_3d\fP &\fBx_displacement\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBconst\fP \fBfloat\fP &\fBnew_x\fP, \fBconst\fP \fBfloat\fP &\fBnew_y\fP, \fBconst\fP \fBfloat\fP &\fBnew_z\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBconst\fP \fBfloat\fP &\fBnew_p\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP, \fBconst\fP \fBfloat\fP &\fBnew_z\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBconst\fP \fBfloat\fP &\fBnew_r\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP, \fBconst\fP \fBangle\fP &\fBnew_phi\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBconst\fP \fBdisplacement_nd\fP &\fBx_displacement\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBconst\fP \fBfloat\fP &\fBnew_r\fP, \fBconst\fP vector< \fBangle\fP > &\fBnew_angles\fP)"
.br
.ti -1c
.RI "\fBfloat\fP \fBdistance_to_origin\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay_polar\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay_cylindrical\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay_spherical\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay_geographical\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< \fBfloat\fP > \fBvalues\fP"
.br
.ti -1c
.RI "vector< \fBangle\fP > \fBangles\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBfloat\fP \fBno_value\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
