.TH "scifir::dimension" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::dimension
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBtype\fP : int8_t { \fBNONE\fP, \fBm\fP, \fBgrade\fP, \fBradian\fP, \fBsteradian\fP, \fBs\fP, \fBg\fP, \fBC\fP, \fBK\fP, \fBmol\fP, \fBcd\fP, \fBB\fP, \fBHz\fP, \fBN\fP, \fBPa\fP, \fBJ\fP, \fBW\fP, \fBA\fP, \fBV\fP, \fBF\fP, \fBOhm\fP, \fBS\fP, \fBWb\fP, \fBT\fP, \fBH\fP, \fBlm\fP, \fBlx\fP, \fBBq\fP, \fBGy\fP, \fBSv\fP, \fBkat\fP, \fBangstrom\fP, \fBL\fP, \fBminute\fP, \fBh\fP, \fBd\fP, \fBly\fP, \fBAU\fP, \fBpc\fP, \fBeV\fP, \fBDa\fP, \fBamu\fP, \fBbarn\fP, \fBM\fP, \fBparticles\fP, \fBcustom\fP, \fBcustom_basic\fP, \fBcustom_full_symbol\fP, \fBmoney\fP, \fBpixel\fP, \fBmemo\fP }"
.br
.ti -1c
.RI "enum \fBposition\fP : int8_t { \fBNO_POSITION\fP, \fBNUMERATOR\fP, \fBDENOMINATOR\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdimension\fP (\fBconst\fP \fBdimension\fP &x)"
.br
.ti -1c
.RI "\fBdimension\fP (\fBdimension\fP &&x)"
.br
.ti -1c
.RI "\fBdimension\fP (dimension::type \fBnew_dimension_type\fP, scifir::prefix::type \fBnew_prefix\fP, dimension::position \fBnew_sign\fP)"
.br
.ti -1c
.RI "\fBdimension\fP (dimension::type \fBnew_dimension_type\fP, \fBconst\fP \fBscifir::prefix\fP &\fBnew_prefix\fP, dimension::position \fBnew_sign\fP)"
.br
.ti -1c
.RI "\fBdimension\fP (\fBconst\fP \fBstring\fP &\fBinit_dimension\fP, dimension::position \fBnew_sign\fP)"
.br
.ti -1c
.RI "\fBdimension\fP & \fBoperator=\fP (\fBconst\fP \fBdimension\fP &x)"
.br
.ti -1c
.RI "\fBdimension\fP & \fBoperator=\fP (\fBdimension\fP &&x)"
.br
.ti -1c
.RI "\fBstring\fP \fBget_name\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBget_symbol\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBlong\fP \fBdouble\fP \fBget_conversion_factor\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBlong\fP \fBdouble\fP \fBprefix_math\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBlong\fP \fBdouble\fP \fBprefix_math\fP (\fBconst\fP \fBprefix\fP &\fBx_prefix\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_simple_dimension\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_basic_dimension\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_derived_dimension\fP () \fBconst\fP"
.br
.ti -1c
.RI "vector< \fBdimension\fP > \fBget_basic_dimensions\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBinvert\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBcreate_custom_dimension\fP (\fBconst\fP \fBstring\fP &\fBnew_symbol\fP, \fBconst\fP \fBstring\fP &\fBinit_dimensions\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBchar\fP * \fBcreate_full_symbol\fP (\fBconst\fP \fBstring\fP &\fBfull_symbol\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBstring\fP \fBget_full_symbol\fP (\fBconst\fP \fBchar\fP *\fBx_symbol\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBscifir::prefix\fP \fBprefix\fP"
.br
.ti -1c
.RI "dimension::type \fBdimension_type\fP"
.br
.ti -1c
.RI "dimension::position \fBdimension_sign\fP"
.br
.ti -1c
.RI "\fBchar\fP \fBsymbol\fP [3]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
