.TH "scifir::complex_number< T >" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::complex_number< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <complex_number\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcomplex_number\fP ()"
.br
.ti -1c
.RI "\fBcomplex_number\fP (const \fBcomplex_number\fP< T > &x)"
.br
.ti -1c
.RI "\fBcomplex_number\fP (\fBcomplex_number\fP< T > &&x)"
.br
.ti -1c
.RI "\fBcomplex_number\fP (const T &x, const T &y)"
.br
.ti -1c
.RI "\fBcomplex_number\fP (const string &x, const string &y)"
.br
.ti -1c
.RI "\fBcomplex_number\fP (const string &init_complex_number)"
.br
.ti -1c
.RI "\fBcomplex_number\fP< T > & \fBoperator=\fP (const \fBcomplex_number\fP< T > &x)"
.br
.ti -1c
.RI "\fBcomplex_number\fP< T > & \fBoperator=\fP (\fBcomplex_number\fP< T > &&x)"
.br
.ti -1c
.RI "\fBcomplex_number\fP< T > \fBoperator+\fP (const \fBcomplex_number\fP< T > &x) const"
.br
.ti -1c
.RI "\fBcomplex_number\fP< T > \fBoperator\-\fP (const \fBcomplex_number\fP< T > &x) const"
.br
.ti -1c
.RI "template<typename U > \fBcomplex_number\fP< \fBscalar_unit\fP > \fBoperator*\fP (const \fBcomplex_number\fP< U > &x) const"
.br
.ti -1c
.RI "template<typename U > \fBcomplex_number\fP< \fBscalar_unit\fP > \fBoperator/\fP (const \fBcomplex_number\fP< U > &x) const"
.br
.ti -1c
.RI "void \fBoperator+=\fP (const \fBcomplex_number\fP< T > &x)"
.br
.ti -1c
.RI "void \fBoperator\-=\fP (const \fBcomplex_number\fP< T > &x)"
.br
.ti -1c
.RI "\fBcomplex_number\fP< T > \fBget_conjugate\fP () const"
.br
.ti -1c
.RI "T \fBget_r\fP () const"
.br
.ti -1c
.RI "\fBangle\fP \fBget_argument\fP () const"
.br
.ti -1c
.RI "\fBcomplex_number\fP< \fBscalar_unit\fP > \fBget_reciprocal\fP () const"
.br
.ti -1c
.RI "string \fBdisplay\fP (int number_of_decimals=2) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBreal\fP"
.br
.ti -1c
.RI "T \fBimaginary\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class scifir::complex_number< T >"

.PP
Definition at line 19 of file complex_number\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBscifir::complex_number\fP< T >::\fBcomplex_number\fP ()\fC [inline]\fP"

.PP
Definition at line 22 of file complex_number\&.hpp\&.
.PP
.nf
22                              : real(),imaginary()
23             {}
.fi
.SS "template<typename T > \fBscifir::complex_number\fP< T >::\fBcomplex_number\fP (const \fBcomplex_number\fP< T > & x)\fC [inline]\fP"

.PP
Definition at line 25 of file complex_number\&.hpp\&.
.PP
.nf
25                                                        : real(x\&.real),imaginary(x\&.imaginary)
26             {}
.fi
.SS "template<typename T > \fBscifir::complex_number\fP< T >::\fBcomplex_number\fP (\fBcomplex_number\fP< T > && x)\fC [inline]\fP"

.PP
Definition at line 28 of file complex_number\&.hpp\&.
.PP
.nf
28                                                   : real(std::move(x\&.real)),imaginary(std::move(x\&.imaginary))
29             {}
.fi
.SS "template<typename T > \fBscifir::complex_number\fP< T >::\fBcomplex_number\fP (const T & x, const T & y)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 31 of file complex_number\&.hpp\&.
.PP
.nf
31                                                            : real(x),imaginary(y)
32             {}
.fi
.SS "template<typename T > \fBscifir::complex_number\fP< T >::\fBcomplex_number\fP (const string & x, const string & y)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 34 of file complex_number\&.hpp\&.
.PP
.nf
34                                                                      : real(x),imaginary(y)
35             {}
.fi
.SS "template<typename T > \fBscifir::complex_number\fP< T >::\fBcomplex_number\fP (const string & init_complex_number)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 37 of file complex_number\&.hpp\&.
.PP
.nf
38             {
39                 if (init_complex_number\&.find("+") != string::npos or init_complex_number\&.find("-") != string::npos)
40                 {
41                     vector<string> numbers;
42                     boost::split(numbers,init_complex_number,boost::is_any_of("+-"));
43                     if (numbers\&.size() == 2)
44                     {
45                         boost::trim(numbers[0]);
46                         boost::trim(numbers[1]);
47                         if (numbers[1]\&.substr(numbers[1]\&.length() - 3) == "(i)")
48                         {
49                             real = scalar_unit(numbers[0]);
50                             imaginary = scalar_unit(numbers[1]\&.substr(0,numbers[1]\&.length() - 3));
51                             if (init_complex_number\&.find("-") != string::npos)
52                             {
53                                 imaginary *= -1;
54                             }
55                         }
56                         else
57                         {
58                             real = T();
59                             imaginary = T();
60                         }
61                     }
62                 }
63                 else
64                 {
65                     real = T();
66                     imaginary = T();
67                 }
68             }
.fi
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > string \fBscifir::complex_number\fP< T >::display (int number_of_decimals = \fC2\fP) const\fC [inline]\fP"

.PP
Definition at line 153 of file complex_number\&.hpp\&.
.PP
.nf
154             {
155                 ostringstream output;
156                 output << real\&.display(number_of_decimals);
157                 if (imaginary >= 0)
158                 {
159                     output << " + ";
160                 }
161                 else
162                 {
163                     output << " - ";
164                 }
165                 output << display_float(std::abs(imaginary\&.get_value()),number_of_decimals) << " " << imaginary\&.display_dimensions() << "(i)";
166                 return output\&.str();
167             }
.fi
.SS "template<typename T > \fBangle\fP \fBscifir::complex_number\fP< T >::get_argument () const\fC [inline]\fP"

.PP
Definition at line 130 of file complex_number\&.hpp\&.
.PP
.nf
131             {
132                 if (imaginary != 0 and real > 0)
133                 {
134                     return angle(2 * scifir::atan(float(imaginary / (real + (scifir::sqrt((real^2) + (imaginary^2)))))));
135                 }
136                 else if (real < 0 and imaginary == 0)
137                 {
138                     return angle(180\&.0f);
139                 }
140                 else
141                 {
142                     return angle();
143                 }
144             }
.fi
.SS "template<typename T > \fBcomplex_number\fP<T> \fBscifir::complex_number\fP< T >::get_conjugate () const\fC [inline]\fP"

.PP
Definition at line 120 of file complex_number\&.hpp\&.
.PP
.nf
121             {
122                 return complex_number<T>(real,imaginary * -1);
123             }
.fi
.SS "template<typename T > T \fBscifir::complex_number\fP< T >::get_r () const\fC [inline]\fP"

.PP
Definition at line 125 of file complex_number\&.hpp\&.
.PP
.nf
126             {
127                 return scifir::sqrt((real^2) + (imaginary^2));
128             }
.fi
.SS "template<typename T > \fBcomplex_number\fP<\fBscalar_unit\fP> \fBscifir::complex_number\fP< T >::get_reciprocal () const\fC [inline]\fP"

.PP
Definition at line 146 of file complex_number\&.hpp\&.
.PP
.nf
147             {
148                 scalar_unit new_real = real / ((real^2) + (imaginary^2));
149                 scalar_unit new_imaginary = (-1 * imaginary) / ((real^2) + (imaginary^2));
150                 return complex_number<scalar_unit>(new_real,new_imaginary);
151             }
.fi
.SS "template<typename T > template<typename U > \fBcomplex_number\fP<\fBscalar_unit\fP> \fBscifir::complex_number\fP< T >::operator* (const \fBcomplex_number\fP< U > & x) const\fC [inline]\fP"

.PP
Definition at line 95 of file complex_number\&.hpp\&.
.PP
.nf
96             {
97                 return complex_number<scalar_unit>(real * x\&.real - imaginary * x\&.imaginary,real * x\&.imaginary + imaginary * x\&.real);
98             }
.fi
.SS "template<typename T > \fBcomplex_number\fP<T> \fBscifir::complex_number\fP< T >::operator+ (const \fBcomplex_number\fP< T > & x) const\fC [inline]\fP"

.PP
Definition at line 84 of file complex_number\&.hpp\&.
.PP
.nf
85             {
86                 return complex_number<T>(real + x\&.real,imaginary + x\&.imaginary);
87             }
.fi
.SS "template<typename T > void \fBscifir::complex_number\fP< T >::operator+= (const \fBcomplex_number\fP< T > & x)\fC [inline]\fP"

.PP
Definition at line 108 of file complex_number\&.hpp\&.
.PP
.nf
109             {
110                 real += x\&.real;
111                 imaginary += x\&.imaginary;
112             }
.fi
.SS "template<typename T > \fBcomplex_number\fP<T> \fBscifir::complex_number\fP< T >::operator\- (const \fBcomplex_number\fP< T > & x) const\fC [inline]\fP"

.PP
Definition at line 89 of file complex_number\&.hpp\&.
.PP
.nf
90             {
91                 return complex_number<T>(real - x\&.real,imaginary - x\&.imaginary);
92             }
.fi
.SS "template<typename T > void \fBscifir::complex_number\fP< T >::operator\-= (const \fBcomplex_number\fP< T > & x)\fC [inline]\fP"

.PP
Definition at line 114 of file complex_number\&.hpp\&.
.PP
.nf
115             {
116                 real -= x\&.real;
117                 imaginary -= x\&.imaginary;
118             }
.fi
.SS "template<typename T > template<typename U > \fBcomplex_number\fP<\fBscalar_unit\fP> \fBscifir::complex_number\fP< T >::operator/ (const \fBcomplex_number\fP< U > & x) const\fC [inline]\fP"

.PP
Definition at line 101 of file complex_number\&.hpp\&.
.PP
.nf
102             {
103                 scalar_unit new_real = (real * x\&.real + x\&.imaginary * imaginary) / ((real^2) + (imaginary^2));
104                 scalar_unit new_imaginary = (x\&.imaginary * real - x\&.real * imaginary) / ((real^2) + (imaginary^2));
105                 return complex_number<scalar_unit>(new_real,new_imaginary);
106             }
.fi
.SS "template<typename T > \fBcomplex_number\fP<T>& \fBscifir::complex_number\fP< T >::operator= (\fBcomplex_number\fP< T > && x)\fC [inline]\fP"

.PP
Definition at line 77 of file complex_number\&.hpp\&.
.PP
.nf
78             {
79                 real = std::move(x\&.real);
80                 imaginary = std::move(x\&.imaginary);
81                 return *this;
82             }
.fi
.SS "template<typename T > \fBcomplex_number\fP<T>& \fBscifir::complex_number\fP< T >::operator= (const \fBcomplex_number\fP< T > & x)\fC [inline]\fP"

.PP
Definition at line 70 of file complex_number\&.hpp\&.
.PP
.nf
71             {
72                 real = x\&.real;
73                 imaginary = x\&.imaginary;
74                 return *this;
75             }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<typename T > T \fBscifir::complex_number\fP< T >::imaginary"

.PP
Definition at line 170 of file complex_number\&.hpp\&.
.SS "template<typename T > T \fBscifir::complex_number\fP< T >::real"

.PP
Definition at line 169 of file complex_number\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
