.TH "scifir::point_1d< float >" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::point_1d< float >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpoint_1d\fP (\fBconst\fP \fBpoint_1d\fP< \fBfloat\fP > &\fBx_point\fP)"
.br
.ti -1c
.RI "\fBpoint_1d\fP (\fBpoint_1d\fP< \fBfloat\fP > &&\fBx_point\fP)"
.br
.ti -1c
.RI "\fBpoint_1d\fP (\fBfloat\fP \fBnew_x\fP)"
.br
.ti -1c
.RI "\fBpoint_1d\fP (\fBconst\fP \fBcoordinates_1d\fP< \fBfloat\fP > &\fBx_coordinates\fP)"
.br
.ti -1c
.RI "\fBpoint_1d\fP (\fBcoordinates_1d\fP< \fBfloat\fP > &&\fBx_coordinates\fP)"
.br
.ti -1c
.RI "\fBpoint_1d\fP (\fBconst\fP \fBstring\fP &\fBinit_point_1d\fP)"
.br
.ti -1c
.RI "\fBpoint_1d\fP< \fBfloat\fP > & \fBoperator=\fP (\fBconst\fP \fBpoint_1d\fP< \fBfloat\fP > &\fBx_point\fP)"
.br
.ti -1c
.RI "\fBpoint_1d\fP< \fBfloat\fP > & \fBoperator=\fP (\fBpoint_1d\fP< \fBfloat\fP > &&\fBx_point\fP)"
.br
.ti -1c
.RI "\fBpoint_1d\fP< \fBfloat\fP > & \fBoperator=\fP (\fBconst\fP \fBcoordinates_1d\fP< \fBfloat\fP > &)"
.br
.ti -1c
.RI "\fBpoint_1d\fP< \fBfloat\fP > & \fBoperator=\fP (\fBcoordinates_1d\fP< \fBfloat\fP > &&)"
.br
.ti -1c
.RI "\fBpoint_1d\fP< \fBfloat\fP > & \fBoperator=\fP (\fBconst\fP \fBstring\fP &\fBinit_point_1d\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_position\fP (\fBconst\fP \fBfloat\fP &\fBnew_x\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBfloat\fP \fBx_value\fP)"
.br
.ti -1c
.RI "\fBfloat\fP \fBdistance_to_origin\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay_cartesian\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfloat\fP \fBx\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
