.TH "scifir::size_2d< float >" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::size_2d< float >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <size_2d\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsize_2d\fP ()"
.br
.ti -1c
.RI "\fBsize_2d\fP (const \fBsize_2d\fP< float > &x)"
.br
.ti -1c
.RI "\fBsize_2d\fP (\fBsize_2d\fP< float > &&x)"
.br
.ti -1c
.RI "\fBsize_2d\fP (const float &new_width, const float &new_height)"
.br
.ti -1c
.RI "\fBsize_2d\fP (const string &new_width, const string &new_height)"
.br
.ti -1c
.RI "\fBsize_2d\fP (const string &init_size_2d)"
.br
.ti -1c
.RI "\fBsize_2d\fP< float > & \fBoperator=\fP (const \fBsize_2d\fP< float > &x)"
.br
.ti -1c
.RI "\fBsize_2d\fP< float > & \fBoperator=\fP (\fBsize_2d\fP< float > &&x)"
.br
.ti -1c
.RI "\fBsize_2d\fP< float > & \fBoperator=\fP (const string &init_size_2d)"
.br
.ti -1c
.RI "\fBsize_2d\fP< float > \fBoperator+\fP (const \fBsize_2d\fP< float > &x) const"
.br
.ti -1c
.RI "\fBsize_2d\fP< float > \fBoperator\-\fP (const \fBsize_2d\fP< float > &x) const"
.br
.ti -1c
.RI "void \fBoperator+=\fP (const \fBsize_2d\fP< float > &x)"
.br
.ti -1c
.RI "void \fBoperator\-=\fP (const \fBsize_2d\fP< float > &x)"
.br
.ti -1c
.RI "float \fBget_area\fP () const"
.br
.ti -1c
.RI "string \fBdisplay\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBwidth\fP"
.br
.ti -1c
.RI "float \fBheight\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize_from_string\fP (const string &init_size_2d)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 112 of file size_2d\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBscifir::size_2d\fP< float >::\fBsize_2d\fP ()\fC [inline]\fP"

.PP
Definition at line 115 of file size_2d\&.hpp\&.
.PP
.nf
115                       : width(),height()
116             {}
.fi
.SS "\fBscifir::size_2d\fP< float >::\fBsize_2d\fP (const \fBsize_2d\fP< float > & x)\fC [inline]\fP"

.PP
Definition at line 118 of file size_2d\&.hpp\&.
.PP
.nf
118                                              : width(x\&.width),height(x\&.height)
119             {}
.fi
.SS "\fBscifir::size_2d\fP< float >::\fBsize_2d\fP (\fBsize_2d\fP< float > && x)\fC [inline]\fP"

.PP
Definition at line 121 of file size_2d\&.hpp\&.
.PP
.nf
121                                         : width(std::move(x\&.width)),height(std::move(x\&.height))
122             {}
.fi
.SS "\fBscifir::size_2d\fP< float >::\fBsize_2d\fP (const float & new_width, const float & new_height)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 124 of file size_2d\&.hpp\&.
.PP
.nf
124                                                                              : width(new_width),height(new_height)
125             {}
.fi
.SS "\fBscifir::size_2d\fP< float >::\fBsize_2d\fP (const string & new_width, const string & new_height)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 127 of file size_2d\&.hpp\&.
.PP
.nf
127                                                                                : width(stof(new_width)),height(stof(new_height))
128             {}
.fi
.SS "\fBscifir::size_2d\fP< float >::\fBsize_2d\fP (const string & init_size_2d)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 130 of file size_2d\&.hpp\&.
.PP
.nf
130                                                          : size_2d()
131             {
132                 initialize_from_string(init_size_2d);
133             }
.fi
.SH "Member Function Documentation"
.PP 
.SS "string \fBscifir::size_2d\fP< float >::display () const\fC [inline]\fP"

.PP
Definition at line 182 of file size_2d\&.hpp\&.
.PP
.nf
183             {
184                 ostringstream output;
185                 output << display_float(width,2) << " * " << display_float(height,2);
186                 return output\&.str();
187             }
.fi
.SS "float \fBscifir::size_2d\fP< float >::get_area () const\fC [inline]\fP"

.PP
Definition at line 177 of file size_2d\&.hpp\&.
.PP
.nf
178             {
179                 return width * height;
180             }
.fi
.SS "void \fBscifir::size_2d\fP< float >::initialize_from_string (const string & init_size_2d)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line 193 of file size_2d\&.hpp\&.
.PP
.nf
194             {
195                 vector<string> widths;
196                 boost::split(widths,init_size_2d,boost::is_any_of("*"));
197                 if (widths\&.size() == 2)
198                 {
199                     boost::trim(widths[0]);
200                     boost::trim(widths[1]);
201                     width = stof(widths[0]);
202                     height = stof(widths[1]);
203                 }
204             }
.fi
.SS "\fBsize_2d\fP<float> \fBscifir::size_2d\fP< float >::operator+ (const \fBsize_2d\fP< float > & x) const\fC [inline]\fP"

.PP
Definition at line 155 of file size_2d\&.hpp\&.
.PP
.nf
156             {
157                 return size_2d<float>(width + x\&.width,height + x\&.height);
158             }
.fi
.SS "void \fBscifir::size_2d\fP< float >::operator+= (const \fBsize_2d\fP< float > & x)\fC [inline]\fP"

.PP
Definition at line 165 of file size_2d\&.hpp\&.
.PP
.nf
166             {
167                 width += x\&.width;
168                 height += x\&.height;
169             }
.fi
.SS "\fBsize_2d\fP<float> \fBscifir::size_2d\fP< float >::operator\- (const \fBsize_2d\fP< float > & x) const\fC [inline]\fP"

.PP
Definition at line 160 of file size_2d\&.hpp\&.
.PP
.nf
161             {
162                 return size_2d<float>(width - x\&.width,height - x\&.height);
163             }
.fi
.SS "void \fBscifir::size_2d\fP< float >::operator\-= (const \fBsize_2d\fP< float > & x)\fC [inline]\fP"

.PP
Definition at line 171 of file size_2d\&.hpp\&.
.PP
.nf
172             {
173                 width -= x\&.width;
174                 height -= x\&.height;
175             }
.fi
.SS "\fBsize_2d\fP<float>& \fBscifir::size_2d\fP< float >::operator= (const \fBsize_2d\fP< float > & x)\fC [inline]\fP"

.PP
Definition at line 135 of file size_2d\&.hpp\&.
.PP
.nf
136             {
137                 width = x\&.width;
138                 height = x\&.height;
139                 return *this;
140             }
.fi
.SS "\fBsize_2d\fP<float>& \fBscifir::size_2d\fP< float >::operator= (const string & init_size_2d)\fC [inline]\fP"

.PP
Definition at line 149 of file size_2d\&.hpp\&.
.PP
.nf
150             {
151                 initialize_from_string(init_size_2d);
152                 return *this;
153             }
.fi
.SS "\fBsize_2d\fP<float>& \fBscifir::size_2d\fP< float >::operator= (\fBsize_2d\fP< float > && x)\fC [inline]\fP"

.PP
Definition at line 142 of file size_2d\&.hpp\&.
.PP
.nf
143             {
144                 width = std::move(x\&.width);
145                 height = std::move(x\&.height);
146                 return *this;
147             }
.fi
.SH "Member Data Documentation"
.PP 
.SS "float \fBscifir::size_2d\fP< float >::height"

.PP
Definition at line 190 of file size_2d\&.hpp\&.
.SS "float \fBscifir::size_2d\fP< float >::width"

.PP
Definition at line 189 of file size_2d\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
