.TH "scifir::point_1d< T >" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::point_1d< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <point_1d\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpoint_1d\fP ()"
.br
.ti -1c
.RI "\fBpoint_1d\fP (\fBconst\fP \fBpoint_1d\fP< T > &\fBx_point\fP)"
.br
.ti -1c
.RI "\fBpoint_1d\fP (\fBpoint_1d\fP< T > &&\fBx_point\fP)"
.br
.ti -1c
.RI "\fBpoint_1d\fP (\fBconst\fP T &\fBnew_x\fP)"
.br
.ti -1c
.RI "\fBpoint_1d\fP (\fBconst\fP \fBcoordinates_1d\fP< T > &\fBx_coordinates\fP)"
.br
.ti -1c
.RI "\fBpoint_1d\fP (\fBcoordinates_1d\fP< T > &&\fBx_coordinates\fP)"
.br
.ti -1c
.RI "\fBpoint_1d\fP (\fBconst\fP \fBstring\fP &\fBinit_point_1d\fP)"
.br
.ti -1c
.RI "\fBpoint_1d\fP< T > & \fBoperator=\fP (\fBconst\fP \fBpoint_1d\fP< T > &\fBx_point\fP)"
.br
.ti -1c
.RI "\fBpoint_1d\fP< T > & \fBoperator=\fP (\fBpoint_1d\fP< T > &&\fBx_point\fP)"
.br
.ti -1c
.RI "\fBpoint_1d\fP< T > & \fBoperator=\fP (\fBconst\fP \fBcoordinates_1d\fP< T > &)"
.br
.ti -1c
.RI "\fBpoint_1d\fP< T > & \fBoperator=\fP (\fBcoordinates_1d\fP< T > &&)"
.br
.ti -1c
.RI "\fBpoint_1d\fP< T > & \fBoperator=\fP (\fBconst\fP \fBstring\fP &\fBinit_point_1d\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_position\fP (\fBconst\fP T &\fBnew_x\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBconst\fP T &\fBx_value\fP)"
.br
.ti -1c
.RI "T \fBdistance_to_origin\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay_cartesian\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBx\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBinitialize_from_string\fP (\fBstring\fP \fBinit_point_1d\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<\fBtypename\fP T = length>
.br
class scifir::point_1d< T >"
.PP
Definition at line \fB19\fP of file \fBpoint_1d\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP T  = length> \fBscifir::point_1d\fP< T >::point_1d ()\fC [inline]\fP"

.PP
Definition at line \fB22\fP of file \fBpoint_1d\&.hpp\fP\&..PP
.nf
22                        : x()
23             {}
.fi

.SS "template<\fBtypename\fP T  = length> \fBscifir::point_1d\fP< T >::point_1d (\fBconst\fP \fBpoint_1d\fP< T > & x_point)\fC [inline]\fP"

.PP
Definition at line \fB25\fP of file \fBpoint_1d\&.hpp\fP\&..PP
.nf
25                                                  : x(x_point\&.x)
26             {}
.fi

.SS "template<\fBtypename\fP T  = length> \fBscifir::point_1d\fP< T >::point_1d (\fBpoint_1d\fP< T > && x_point)\fC [inline]\fP"

.PP
Definition at line \fB28\fP of file \fBpoint_1d\&.hpp\fP\&..PP
.nf
28                                             : x(std::move(x_point\&.x))
29             {}
.fi

.SS "template<\fBtypename\fP T  = length> \fBscifir::point_1d\fP< T >::point_1d (\fBconst\fP T & new_x)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line \fB31\fP of file \fBpoint_1d\&.hpp\fP\&..PP
.nf
31                                               : x(new_x)
32             {}
.fi

.SS "template<\fBtypename\fP T > \fBscifir::point_1d\fP< T >::point_1d (\fBconst\fP \fBcoordinates_1d\fP< T > & x_coordinates)\fC [explicit]\fP"

.PP
Definition at line \fB13\fP of file \fBpoint_1d_impl\&.hpp\fP\&..PP
.nf
13                                                                 : x(x_coordinates\&.x)
14     {}
.fi

.SS "template<\fBtypename\fP T > \fBscifir::point_1d\fP< T >::point_1d (\fBcoordinates_1d\fP< T > && x_coordinates)\fC [explicit]\fP"

.PP
Definition at line \fB17\fP of file \fBpoint_1d_impl\&.hpp\fP\&..PP
.nf
17                                                            : x(std::move(x_coordinates\&.x))
18     {}
.fi

.SS "template<\fBtypename\fP T  = length> \fBscifir::point_1d\fP< T >::point_1d (\fBconst\fP \fBstring\fP & init_point_1d)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line \fB38\fP of file \fBpoint_1d\&.hpp\fP\&..PP
.nf
38                                                            : point_1d()
39             {
40                 initialize_from_string(init_point_1d);
41             }
.fi

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP T  = length> \fBstring\fP \fBscifir::point_1d\fP< T >::display_cartesian () const\fC [inline]\fP"

.PP
Definition at line \fB80\fP of file \fBpoint_1d\&.hpp\fP\&..PP
.nf
81             {
82                 ostringstream out;
83                 out << "(" << x << ")";
84                 return out\&.str();
85             }
.fi

.SS "template<\fBtypename\fP T  = length> T \fBscifir::point_1d\fP< T >::distance_to_origin () const\fC [inline]\fP"

.PP
Definition at line \fB75\fP of file \fBpoint_1d\&.hpp\fP\&..PP
.nf
76             {
77                 return T(std::abs(x\&.get_value()),x\&.get_dimensions());
78             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBvoid\fP \fBscifir::point_1d\fP< T >::initialize_from_string (\fBstring\fP init_point_1d)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line \fB90\fP of file \fBpoint_1d\&.hpp\fP\&..PP
.nf
91             {
92                 if (init_point_1d\&.front() == '(')
93                 {
94                     init_point_1d\&.erase(0,1);
95                 }
96                 if (init_point_1d\&.back() == ')')
97                 {
98                     init_point_1d\&.erase(init_point_1d\&.size()\-1,1);
99                 }
100                 x = T(init_point_1d);
101             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBvoid\fP \fBscifir::point_1d\fP< T >::move (\fBconst\fP T & x_value)\fC [inline]\fP"

.PP
Definition at line \fB70\fP of file \fBpoint_1d\&.hpp\fP\&..PP
.nf
71             {
72                 x += x_value;
73             }
.fi

.SS "template<\fBtypename\fP T > \fBpoint_1d\fP< T > & \fBscifir::point_1d\fP< T >::operator= (\fBconst\fP \fBcoordinates_1d\fP< T > & x_coordinates)"

.PP
Definition at line \fB21\fP of file \fBpoint_1d_impl\&.hpp\fP\&..PP
.nf
22     {
23         x = x_coordinates\&.x;
24         return *this;
25     }
.fi

.SS "template<\fBtypename\fP T  = length> \fBpoint_1d\fP< T > & \fBscifir::point_1d\fP< T >::operator= (\fBconst\fP \fBpoint_1d\fP< T > & x_point)\fC [inline]\fP"

.PP
Definition at line \fB43\fP of file \fBpoint_1d\&.hpp\fP\&..PP
.nf
44             {
45                 x = x_point\&.x;
46                 return *this;
47             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBpoint_1d\fP< T > & \fBscifir::point_1d\fP< T >::operator= (\fBconst\fP \fBstring\fP & init_point_1d)\fC [inline]\fP"

.PP
Definition at line \fB59\fP of file \fBpoint_1d\&.hpp\fP\&..PP
.nf
60             {
61                 initialize_from_string(init_point_1d);
62                 return *this;
63             }
.fi

.SS "template<\fBtypename\fP T > \fBpoint_1d\fP< T > & \fBscifir::point_1d\fP< T >::operator= (\fBcoordinates_1d\fP< T > && x_coordinates)"

.PP
Definition at line \fB28\fP of file \fBpoint_1d_impl\&.hpp\fP\&..PP
.nf
29     {
30         x = std::move(x_coordinates\&.x);
31         return *this;
32     }
.fi

.SS "template<\fBtypename\fP T  = length> \fBpoint_1d\fP< T > & \fBscifir::point_1d\fP< T >::operator= (\fBpoint_1d\fP< T > && x_point)\fC [inline]\fP"

.PP
Definition at line \fB49\fP of file \fBpoint_1d\&.hpp\fP\&..PP
.nf
50             {
51                 x = std::move(x_point\&.x);
52                 return *this;
53             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBvoid\fP \fBscifir::point_1d\fP< T >::set_position (\fBconst\fP T & new_x)\fC [inline]\fP"

.PP
Definition at line \fB65\fP of file \fBpoint_1d\&.hpp\fP\&..PP
.nf
66             {
67                 x = new_x;
68             }
.fi

.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP T  = length> T \fBscifir::point_1d\fP< T >::x"

.PP
Definition at line \fB87\fP of file \fBpoint_1d\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
