.TH "scifir::color" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::color
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcolor\fP (\fBint\fP, \fBint\fP, \fBint\fP, \fBint\fP=255)"
.br
.ti -1c
.RI "\fBconst\fP \fBint\fP & \fBget_red\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBint\fP & \fBget_green\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBint\fP & \fBget_blue\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBint\fP & \fBget_alpha\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_opaque\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_transparent\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_full_transparent\fP () \fBconst\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
