.TH "scifir::size_nd< float >" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::size_nd< float >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsize_nd\fP (\fBconst\fP \fBsize_nd\fP< \fBfloat\fP > &x)"
.br
.ti -1c
.RI "\fBsize_nd\fP (\fBsize_nd\fP< \fBfloat\fP > &&x)"
.br
.ti -1c
.RI "\fBsize_nd\fP (\fBconst\fP vector< \fBfloat\fP > &\fBnew_widths\fP)"
.br
.ti -1c
.RI "\fBsize_nd\fP (\fBconst\fP vector< \fBstring\fP > &\fBnew_widths\fP)"
.br
.ti -1c
.RI "\fBsize_nd\fP (\fBconst\fP \fBstring\fP &\fBinit_size_nd\fP)"
.br
.ti -1c
.RI "\fBsize_nd\fP< \fBfloat\fP > & \fBoperator=\fP (\fBconst\fP \fBsize_nd\fP< \fBfloat\fP > &x)"
.br
.ti -1c
.RI "\fBsize_nd\fP< \fBfloat\fP > & \fBoperator=\fP (\fBsize_nd\fP< \fBfloat\fP > &&x)"
.br
.ti -1c
.RI "\fBsize_nd\fP< \fBfloat\fP > & \fBoperator=\fP (\fBconst\fP \fBstring\fP &\fBinit_size_nd\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBis_nd\fP (\fBunsigned\fP \fBint\fP \fBi\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBint\fP \fBget_nd\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsize_nd\fP< \fBfloat\fP > \fBoperator+\fP (\fBconst\fP \fBsize_nd\fP< \fBfloat\fP > &x) \fBconst\fP"
.br
.ti -1c
.RI "\fBsize_nd\fP< \fBfloat\fP > \fBoperator\-\fP (\fBconst\fP \fBsize_nd\fP< \fBfloat\fP > &x) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator+=\fP (\fBconst\fP \fBsize_nd\fP< \fBfloat\fP > &x)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator\-=\fP (\fBconst\fP \fBsize_nd\fP< \fBfloat\fP > &x)"
.br
.ti -1c
.RI "\fBfloat\fP \fBget_volume_nd\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< \fBfloat\fP > \fBwidths\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
