.TH "scifir::size_2d< T >" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::size_2d< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsize_2d\fP (\fBconst\fP \fBsize_2d\fP< T > &x)"
.br
.ti -1c
.RI "\fBsize_2d\fP (\fBsize_2d\fP< T > &&x)"
.br
.ti -1c
.RI "\fBsize_2d\fP (\fBconst\fP T &\fBnew_width\fP, \fBconst\fP T &\fBnew_height\fP)"
.br
.ti -1c
.RI "\fBsize_2d\fP (\fBconst\fP \fBstring\fP &\fBnew_width\fP, \fBconst\fP \fBstring\fP &\fBnew_height\fP)"
.br
.ti -1c
.RI "\fBsize_2d\fP (\fBconst\fP \fBstring\fP &\fBinit_size_2d\fP)"
.br
.ti -1c
.RI "\fBsize_2d\fP< T > & \fBoperator=\fP (\fBconst\fP \fBsize_2d\fP< T > &x)"
.br
.ti -1c
.RI "\fBsize_2d\fP< T > & \fBoperator=\fP (\fBsize_2d\fP< T > &&x)"
.br
.ti -1c
.RI "\fBsize_2d\fP< T > & \fBoperator=\fP (\fBconst\fP \fBstring\fP &\fBinit_size_2d\fP)"
.br
.ti -1c
.RI "\fBsize_2d\fP< T > \fBoperator+\fP (\fBconst\fP \fBsize_2d\fP< T > &x) \fBconst\fP"
.br
.ti -1c
.RI "\fBsize_2d\fP< T > \fBoperator\-\fP (\fBconst\fP \fBsize_2d\fP< T > &x) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator+=\fP (\fBconst\fP \fBsize_2d\fP< T > &x)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator\-=\fP (\fBconst\fP \fBsize_2d\fP< T > &x)"
.br
.ti -1c
.RI "\fBscalar_unit\fP \fBget_area\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBwidth\fP"
.br
.ti -1c
.RI "T \fBheight\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
