.TH "scifir::size_nd< float >" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::size_nd< float >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <size_nd\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsize_nd\fP ()"
.br
.ti -1c
.RI "\fBsize_nd\fP (const \fBsize_nd\fP< float > &x)"
.br
.ti -1c
.RI "\fBsize_nd\fP (\fBsize_nd\fP< float > &&x)"
.br
.ti -1c
.RI "\fBsize_nd\fP (const vector< float > &new_widths)"
.br
.ti -1c
.RI "\fBsize_nd\fP (const vector< string > &new_widths)"
.br
.ti -1c
.RI "\fBsize_nd\fP (const string &init_size_nd)"
.br
.ti -1c
.RI "\fBsize_nd\fP< float > & \fBoperator=\fP (const \fBsize_nd\fP< float > &x)"
.br
.ti -1c
.RI "\fBsize_nd\fP< float > & \fBoperator=\fP (\fBsize_nd\fP< float > &&x)"
.br
.ti -1c
.RI "\fBsize_nd\fP< float > & \fBoperator=\fP (const string &init_size_nd)"
.br
.ti -1c
.RI "bool \fBis_nd\fP (unsigned int i) const"
.br
.ti -1c
.RI "int \fBget_nd\fP () const"
.br
.ti -1c
.RI "\fBsize_nd\fP< float > \fBoperator+\fP (const \fBsize_nd\fP< float > &x) const"
.br
.ti -1c
.RI "\fBsize_nd\fP< float > \fBoperator\-\fP (const \fBsize_nd\fP< float > &x) const"
.br
.ti -1c
.RI "void \fBoperator+=\fP (const \fBsize_nd\fP< float > &x)"
.br
.ti -1c
.RI "void \fBoperator\-=\fP (const \fBsize_nd\fP< float > &x)"
.br
.ti -1c
.RI "float \fBget_volume_nd\fP () const"
.br
.ti -1c
.RI "string \fBdisplay\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< float > \fBwidths\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize_from_string\fP (const string &init_size_nd)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 175 of file size_nd\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBscifir::size_nd\fP< float >::\fBsize_nd\fP ()\fC [inline]\fP"

.PP
Definition at line 178 of file size_nd\&.hpp\&.
.PP
.nf
178                       : widths()
179             {}
.fi
.SS "\fBscifir::size_nd\fP< float >::\fBsize_nd\fP (const \fBsize_nd\fP< float > & x)\fC [inline]\fP"

.PP
Definition at line 181 of file size_nd\&.hpp\&.
.PP
.nf
181                                              : widths(x\&.widths)
182             {}
.fi
.SS "\fBscifir::size_nd\fP< float >::\fBsize_nd\fP (\fBsize_nd\fP< float > && x)\fC [inline]\fP"

.PP
Definition at line 184 of file size_nd\&.hpp\&.
.PP
.nf
184                                         : widths(std::move(x\&.widths))
185             {}
.fi
.SS "\fBscifir::size_nd\fP< float >::\fBsize_nd\fP (const vector< float > & new_widths)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 187 of file size_nd\&.hpp\&.
.PP
.nf
187                                                               : widths(new_widths)
188             {}
.fi
.SS "\fBscifir::size_nd\fP< float >::\fBsize_nd\fP (const vector< string > & new_widths)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 190 of file size_nd\&.hpp\&.
.PP
.nf
190                                                                : widths()
191             {
192                 for (const string& new_width : new_widths)
193                 {
194                     widths\&.push_back(stof(new_width));
195                 }
196             }
.fi
.SS "\fBscifir::size_nd\fP< float >::\fBsize_nd\fP (const string & init_size_nd)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 198 of file size_nd\&.hpp\&.
.PP
.nf
198                                                          : size_nd()
199             {
200                 initialize_from_string(init_size_nd);
201             }
.fi
.SH "Member Function Documentation"
.PP 
.SS "string \fBscifir::size_nd\fP< float >::display () const\fC [inline]\fP"

.PP
Definition at line 297 of file size_nd\&.hpp\&.
.PP
.nf
298             {
299                 if (widths\&.size() > 0)
300                 {
301                     ostringstream output;
302                     output << display_float(widths[0],2);
303                     for (unsigned int i = 1; i < widths\&.size(); i++)
304                     {
305                         output << " * " << display_float(widths[i],2);
306                     }
307                     return output\&.str();
308                 }
309                 else
310                 {
311                     return "[empty]";
312                 }
313             }
.fi
.SS "int \fBscifir::size_nd\fP< float >::get_nd () const\fC [inline]\fP"

.PP
Definition at line 226 of file size_nd\&.hpp\&.
.PP
.nf
227             {
228                 return int(widths\&.size());
229             }
.fi
.SS "float \fBscifir::size_nd\fP< float >::get_volume_nd () const\fC [inline]\fP"

.PP
Definition at line 287 of file size_nd\&.hpp\&.
.PP
.nf
288             {
289                 float new_value = 1;
290                 for (unsigned int i = 0; i < widths\&.size(); i++)
291                 {
292                     new_value *= widths[i];
293                 }
294                 return new_value;
295             }
.fi
.SS "void \fBscifir::size_nd\fP< float >::initialize_from_string (const string & init_size_nd)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line 318 of file size_nd\&.hpp\&.
.PP
.nf
319             {
320                 widths\&.clear();
321                 vector<string> new_widths;
322                 boost::split(new_widths,init_size_nd,boost::is_any_of("*"));
323                 for (string& new_width : new_widths)
324                 {
325                     boost::trim(new_width);
326                     widths\&.push_back(stof(new_width));
327                 }
328             }
.fi
.SS "bool \fBscifir::size_nd\fP< float >::is_nd (unsigned int i) const\fC [inline]\fP"

.PP
Definition at line 221 of file size_nd\&.hpp\&.
.PP
.nf
222             {
223                 return widths\&.size() == i;
224             }
.fi
.SS "\fBsize_nd\fP<float> \fBscifir::size_nd\fP< float >::operator+ (const \fBsize_nd\fP< float > & x) const\fC [inline]\fP"

.PP
Definition at line 231 of file size_nd\&.hpp\&.
.PP
.nf
232             {
233                 if (get_nd() == x\&.get_nd())
234                 {
235                     vector<float> new_widths = widths;
236                     for (unsigned int i = 0; i < new_widths\&.size(); i++)
237                     {
238                         new_widths[i] += x\&.widths[i];
239                     }
240                     return size_nd<float>(new_widths);
241                 }
242                 else
243                 {
244                     return size_nd<float>();
245                 }
246             }
.fi
.SS "void \fBscifir::size_nd\fP< float >::operator+= (const \fBsize_nd\fP< float > & x)\fC [inline]\fP"

.PP
Definition at line 265 of file size_nd\&.hpp\&.
.PP
.nf
266             {
267                 if (get_nd() == x\&.get_nd())
268                 {
269                     for (unsigned int i = 0; i < widths\&.size(); i++)
270                     {
271                         widths[i] += x\&.widths[i];
272                     }
273                 }
274             }
.fi
.SS "\fBsize_nd\fP<float> \fBscifir::size_nd\fP< float >::operator\- (const \fBsize_nd\fP< float > & x) const\fC [inline]\fP"

.PP
Definition at line 248 of file size_nd\&.hpp\&.
.PP
.nf
249             {
250                 if (get_nd() == x\&.get_nd())
251                 {
252                     vector<float> new_widths = widths;
253                     for (unsigned int i = 0; i < new_widths\&.size(); i++)
254                     {
255                         new_widths[i] -= x\&.widths[i];
256                     }
257                     return size_nd<float>(new_widths);
258                 }
259                 else
260                 {
261                     return size_nd<float>();
262                 }
263             }
.fi
.SS "void \fBscifir::size_nd\fP< float >::operator\-= (const \fBsize_nd\fP< float > & x)\fC [inline]\fP"

.PP
Definition at line 276 of file size_nd\&.hpp\&.
.PP
.nf
277             {
278                 if (get_nd() == x\&.get_nd())
279                 {
280                     for (unsigned int i = 0; i < widths\&.size(); i++)
281                     {
282                         widths[i] -= x\&.widths[i];
283                     }
284                 }
285             }
.fi
.SS "\fBsize_nd\fP<float>& \fBscifir::size_nd\fP< float >::operator= (const \fBsize_nd\fP< float > & x)\fC [inline]\fP"

.PP
Definition at line 203 of file size_nd\&.hpp\&.
.PP
.nf
204             {
205                 widths = x\&.widths;
206                 return *this;
207             }
.fi
.SS "\fBsize_nd\fP<float>& \fBscifir::size_nd\fP< float >::operator= (const string & init_size_nd)\fC [inline]\fP"

.PP
Definition at line 215 of file size_nd\&.hpp\&.
.PP
.nf
216             {
217                 initialize_from_string(init_size_nd);
218                 return *this;
219             }
.fi
.SS "\fBsize_nd\fP<float>& \fBscifir::size_nd\fP< float >::operator= (\fBsize_nd\fP< float > && x)\fC [inline]\fP"

.PP
Definition at line 209 of file size_nd\&.hpp\&.
.PP
.nf
210             {
211                 widths = std::move(x\&.widths);
212                 return *this;
213             }
.fi
.SH "Member Data Documentation"
.PP 
.SS "vector<float> \fBscifir::size_nd\fP< float >::widths"

.PP
Definition at line 315 of file size_nd\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
