.TH "scifir::point_nd< float >" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::point_nd< float >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <point_nd\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpoint_nd\fP ()"
.br
.ti -1c
.RI "\fBpoint_nd\fP (const \fBpoint_nd\fP< float > &x)"
.br
.ti -1c
.RI "\fBpoint_nd\fP (\fBpoint_nd\fP< float > &&x)"
.br
.ti -1c
.RI "\fBpoint_nd\fP (const vector< float > &new_values)"
.br
.ti -1c
.RI "\fBpoint_nd\fP (float new_x)"
.br
.ti -1c
.RI "\fBpoint_nd\fP (float new_x, float new_y)"
.br
.ti -1c
.RI "\fBpoint_nd\fP (float new_p, const \fBangle\fP &new_theta)"
.br
.ti -1c
.RI "\fBpoint_nd\fP (float new_x, float new_y, float new_z)"
.br
.ti -1c
.RI "\fBpoint_nd\fP (float new_p, const \fBangle\fP &new_theta, float new_z)"
.br
.ti -1c
.RI "\fBpoint_nd\fP (float new_r, const \fBangle\fP &new_theta, const \fBangle\fP &new_phi)"
.br
.ti -1c
.RI "\fBpoint_nd\fP (const \fBangle\fP &new_latitude, const \fBangle\fP &new_longitude, float new_altitude)"
.br
.ti -1c
.RI "\fBpoint_nd\fP (const \fBcoordinates_nd\fP< float > &x_coordinates)"
.br
.ti -1c
.RI "\fBpoint_nd\fP (\fBcoordinates_nd\fP< float > &&x_coordinates)"
.br
.ti -1c
.RI "\fBpoint_nd\fP (const string &init_point_nd)"
.br
.ti -1c
.RI "\fBpoint_nd\fP< float > & \fBoperator=\fP (const \fBpoint_nd\fP< float > &x_point)"
.br
.ti -1c
.RI "\fBpoint_nd\fP< float > & \fBoperator=\fP (\fBpoint_nd\fP< float > &&x_point)"
.br
.ti -1c
.RI "\fBpoint_nd\fP< float > & \fBoperator=\fP (const \fBcoordinates_nd\fP< float > &)"
.br
.ti -1c
.RI "\fBpoint_nd\fP< float > & \fBoperator=\fP (\fBcoordinates_nd\fP< float > &&)"
.br
.ti -1c
.RI "\fBpoint_nd\fP< float > & \fBoperator=\fP (const string &init_point_nd)"
.br
.ti -1c
.RI "bool \fBis_nd\fP (unsigned int i) const"
.br
.ti -1c
.RI "int \fBget_nd\fP () const"
.br
.ti -1c
.RI "float \fBget_p\fP () const"
.br
.ti -1c
.RI "\fBangle\fP \fBget_theta\fP () const"
.br
.ti -1c
.RI "float \fBget_r\fP () const"
.br
.ti -1c
.RI "\fBangle\fP \fBget_phi\fP () const"
.br
.ti -1c
.RI "\fBangle\fP \fBget_latitude\fP () const"
.br
.ti -1c
.RI "\fBangle\fP \fBget_longitude\fP () const"
.br
.ti -1c
.RI "float \fBget_altitude\fP () const"
.br
.ti -1c
.RI "void \fBset_position\fP (float new_x)"
.br
.ti -1c
.RI "void \fBset_position\fP (float new_x, float new_y)"
.br
.ti -1c
.RI "void \fBset_position\fP (float new_p, const \fBangle\fP &new_theta)"
.br
.ti -1c
.RI "void \fBset_position\fP (float new_x, float new_y, float new_z)"
.br
.ti -1c
.RI "void \fBset_position\fP (float new_p, const \fBangle\fP &new_theta, float new_z)"
.br
.ti -1c
.RI "void \fBset_position\fP (float new_r, const \fBangle\fP &new_theta, const \fBangle\fP &new_phi)"
.br
.ti -1c
.RI "void \fBset_position\fP (const \fBangle\fP &new_latitude, const \fBangle\fP &new_longitude, float new_altitude)"
.br
.ti -1c
.RI "void \fBset_position\fP (const vector< float > &new_values)"
.br
.ti -1c
.RI "void \fBrotate_in_2d\fP (const \fBangle\fP &new_theta)"
.br
.ti -1c
.RI "void \fBrotate_in_3d\fP (int axis, const \fBangle\fP &new_theta)"
.br
.ti -1c
.RI "void \fBmove\fP (float new_x)"
.br
.ti -1c
.RI "void \fBmove\fP (const displacement_2d &x_displacement)"
.br
.ti -1c
.RI "void \fBmove\fP (float new_x, float new_y)"
.br
.ti -1c
.RI "void \fBmove\fP (float new_p, const \fBangle\fP &new_theta)"
.br
.ti -1c
.RI "void \fBmove\fP (const displacement_3d &x_displacement)"
.br
.ti -1c
.RI "void \fBmove\fP (float new_x, float new_y, float new_z)"
.br
.ti -1c
.RI "void \fBmove\fP (float new_p, const \fBangle\fP &new_theta, float new_z)"
.br
.ti -1c
.RI "void \fBmove\fP (float new_r, const \fBangle\fP &new_theta, const \fBangle\fP &new_phi)"
.br
.ti -1c
.RI "void \fBmove\fP (const displacement_nd &x_displacement)"
.br
.ti -1c
.RI "void \fBmove\fP (float new_r, const vector< \fBangle\fP > &new_angles)"
.br
.ti -1c
.RI "float \fBdistance_to_origin\fP () const"
.br
.ti -1c
.RI "string \fBdisplay_cartesian_2d\fP () const"
.br
.ti -1c
.RI "string \fBdisplay_polar\fP () const"
.br
.ti -1c
.RI "string \fBdisplay_cartesian_3d\fP () const"
.br
.ti -1c
.RI "string \fBdisplay_cylindrical\fP () const"
.br
.ti -1c
.RI "string \fBdisplay_spherical\fP () const"
.br
.ti -1c
.RI "string \fBdisplay_geographical\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< float > \fBvalues\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize_from_string\fP (string init_point_nd)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 535 of file point_nd\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBscifir::point_nd\fP< float >::\fBpoint_nd\fP ()\fC [inline]\fP"

.PP
Definition at line 538 of file point_nd\&.hpp\&.
.PP
.nf
538                        : values()
539             {}
.fi
.SS "\fBscifir::point_nd\fP< float >::\fBpoint_nd\fP (const \fBpoint_nd\fP< float > & x)\fC [inline]\fP"

.PP
Definition at line 541 of file point_nd\&.hpp\&.
.PP
.nf
541                                                : values(x\&.values)
542             {}
.fi
.SS "\fBscifir::point_nd\fP< float >::\fBpoint_nd\fP (\fBpoint_nd\fP< float > && x)\fC [inline]\fP"

.PP
Definition at line 544 of file point_nd\&.hpp\&.
.PP
.nf
544                                           : values(std::move(x\&.values))
545             {}
.fi
.SS "\fBscifir::point_nd\fP< float >::\fBpoint_nd\fP (const vector< float > & new_values)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 547 of file point_nd\&.hpp\&.
.PP
.nf
547                                                                : values(new_values)
548             {}
.fi
.SS "\fBscifir::point_nd\fP< float >::\fBpoint_nd\fP (float new_x)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 550 of file point_nd\&.hpp\&.
.PP
.nf
550                                            : values()
551             {
552                 values\&.push_back(new_x);
553             }
.fi
.SS "\fBscifir::point_nd\fP< float >::\fBpoint_nd\fP (float new_x, float new_y)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 555 of file point_nd\&.hpp\&.
.PP
.nf
555                                                        : values()
556             {
557                 values\&.push_back(new_x);
558                 values\&.push_back(new_y);
559             }
.fi
.SS "\fBscifir::point_nd\fP< float >::\fBpoint_nd\fP (float new_p, const \fBangle\fP & new_theta)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 561 of file point_nd\&.hpp\&.
.PP
.nf
561                                                                   : values()
562             {
563                 set_position(new_p,new_theta);
564             }
.fi
.SS "\fBscifir::point_nd\fP< float >::\fBpoint_nd\fP (float new_x, float new_y, float new_z)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 566 of file point_nd\&.hpp\&.
.PP
.nf
566                                                                    : values()
567             {
568                 values\&.push_back(new_x);
569                 values\&.push_back(new_y);
570                 values\&.push_back(new_z);
571             }
.fi
.SS "\fBscifir::point_nd\fP< float >::\fBpoint_nd\fP (float new_p, const \fBangle\fP & new_theta, float new_z)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 573 of file point_nd\&.hpp\&.
.PP
.nf
573                                                                               : values()
574             {
575                 set_position(new_p,new_theta,new_z);
576             }
.fi
.SS "\fBscifir::point_nd\fP< float >::\fBpoint_nd\fP (float new_r, const \fBangle\fP & new_theta, const \fBangle\fP & new_phi)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 578 of file point_nd\&.hpp\&.
.PP
.nf
578                                                                                        : values()
579             {
580                 set_position(new_r,new_theta,new_phi);
581             }
.fi
.SS "\fBscifir::point_nd\fP< float >::\fBpoint_nd\fP (const \fBangle\fP & new_latitude, const \fBangle\fP & new_longitude, float new_altitude)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 583 of file point_nd\&.hpp\&.
.PP
.nf
583                                                                                                        : values()
584             {
585                 set_position(new_latitude,new_longitude,new_altitude);
586             }
.fi
.SS "\fBscifir::point_nd\fP< float >::\fBpoint_nd\fP (const \fBcoordinates_nd\fP< float > & x_coordinates)\fC [explicit]\fP"

.PP
Definition at line 10 of file point_nd\&.cpp\&.
.PP
.nf
10                                                                         : values(x_coordinates\&.values)
11     {}
.fi
.SS "\fBscifir::point_nd\fP< float >::\fBpoint_nd\fP (\fBcoordinates_nd\fP< float > && x_coordinates)\fC [explicit]\fP"

.PP
Definition at line 13 of file point_nd\&.cpp\&.
.PP
.nf
13                                                                    : values(std::move(x_coordinates\&.values))
14     {}
.fi
.SS "\fBscifir::point_nd\fP< float >::\fBpoint_nd\fP (const string & init_point_nd)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 592 of file point_nd\&.hpp\&.
.PP
.nf
592                                                            : values()
593             {
594                 initialize_from_string(init_point_nd);
595             }
.fi
.SH "Member Function Documentation"
.PP 
.SS "string \fBscifir::point_nd\fP< float >::display_cartesian_2d () const\fC [inline]\fP"

.PP
Definition at line 891 of file point_nd\&.hpp\&.
.PP
.nf
892             {
893                 if (values\&.size() == 2)
894                 {
895                     ostringstream out;
896                     out << "(" << display_float(values[0]) << "," << display_float(values[1]) << ")";
897                     return out\&.str();
898                 }
899                 else
900                 {
901                     return "[no-2d]";
902                 }
903             }
.fi
.SS "string \fBscifir::point_nd\fP< float >::display_cartesian_3d () const\fC [inline]\fP"

.PP
Definition at line 919 of file point_nd\&.hpp\&.
.PP
.nf
920             {
921                 if (values\&.size() == 3)
922                 {
923                     ostringstream out;
924                     out << "(" << display_float(values[0]) << "," << display_float(values[1]) << "," << display_float(values[2]) << ")";
925                     return out\&.str();
926                 }
927                 else
928                 {
929                     return "[no-3d]";
930                 }
931             }
.fi
.SS "string \fBscifir::point_nd\fP< float >::display_cylindrical () const\fC [inline]\fP"

.PP
Definition at line 933 of file point_nd\&.hpp\&.
.PP
.nf
934             {
935                 if (values\&.size() == 3)
936                 {
937                     ostringstream out;
938                     out << "(" << display_float(get_p()) << "," << get_theta() << "," << display_float(values[2]) << ")";
939                     return out\&.str();
940                 }
941                 else
942                 {
943                     return "[no-3d]";
944                 }
945             }
.fi
.SS "string \fBscifir::point_nd\fP< float >::display_geographical () const\fC [inline]\fP"

.PP
Definition at line 961 of file point_nd\&.hpp\&.
.PP
.nf
962             {
963                 if (values\&.size() == 3)
964                 {                   
965                     ostringstream out;
966                     out << "(" << get_latitude() << "," << get_longitude() << "," << display_float(get_altitude()) << ")";
967                     return out\&.str();
968                 }
969                 else
970                 {
971                     return "[no-3d]";
972                 }
973             }
.fi
.SS "string \fBscifir::point_nd\fP< float >::display_polar () const\fC [inline]\fP"

.PP
Definition at line 905 of file point_nd\&.hpp\&.
.PP
.nf
906             {
907                 if (values\&.size() == 2)
908                 {
909                     ostringstream out;
910                     out << "(" << display_float(get_p()) << "," << get_theta() << ")";
911                     return out\&.str();
912                 }
913                 else
914                 {
915                     return "[no-2d]";
916                 }
917             }
.fi
.SS "string \fBscifir::point_nd\fP< float >::display_spherical () const\fC [inline]\fP"

.PP
Definition at line 947 of file point_nd\&.hpp\&.
.PP
.nf
948             {
949                 if (values\&.size() == 3)
950                 {
951                     ostringstream out;
952                     out << "(" << display_float(get_r()) << "," << get_theta() << "," << get_phi() << ")";
953                     return out\&.str();
954                 }
955                 else
956                 {
957                     return "[no-3d]";
958                 }
959             }
.fi
.SS "float \fBscifir::point_nd\fP< float >::distance_to_origin () const\fC [inline]\fP"

.PP
Definition at line 881 of file point_nd\&.hpp\&.
.PP
.nf
882             {
883                 float x_T = 0;
884                 for (unsigned int i = 0; i < values\&.size(); i++)
885                 {
886                     x_T += float(std::pow(values[i],2));
887                 }
888                 return std::sqrt(x_T);
889             }
.fi
.SS "float \fBscifir::point_nd\fP< float >::get_altitude () const\fC [inline]\fP"

.PP
Definition at line 687 of file point_nd\&.hpp\&.
.PP
.nf
688             {
689                 return float();
690             }
.fi
.SS "\fBangle\fP \fBscifir::point_nd\fP< float >::get_latitude () const\fC [inline]\fP"

.PP
Definition at line 677 of file point_nd\&.hpp\&.
.PP
.nf
678             {
679                 return scifir::asin(float(values[2]/6317));
680             }
.fi
.SS "\fBangle\fP \fBscifir::point_nd\fP< float >::get_longitude () const\fC [inline]\fP"

.PP
Definition at line 682 of file point_nd\&.hpp\&.
.PP
.nf
683             {
684                 return scifir::atan(float(values[1]/values[0]));
685             }
.fi
.SS "int \fBscifir::point_nd\fP< float >::get_nd () const\fC [inline]\fP"

.PP
Definition at line 624 of file point_nd\&.hpp\&.
.PP
.nf
625             {
626                 return int(values\&.size());
627             }
.fi
.SS "float \fBscifir::point_nd\fP< float >::get_p () const\fC [inline]\fP"

.PP
Definition at line 629 of file point_nd\&.hpp\&.
.PP
.nf
630             {
631                 if (get_nd() == 2 or get_nd() == 3)
632                 {
633                     return float(std::sqrt(std::pow(values[0],2) + std::pow(values[1],2)));
634                 }
635                 else
636                 {
637                     return float();
638                 }
639             }
.fi
.SS "\fBangle\fP \fBscifir::point_nd\fP< float >::get_phi () const\fC [inline]\fP"

.PP
Definition at line 665 of file point_nd\&.hpp\&.
.PP
.nf
666             {
667                 if (get_nd() == 3)
668                 {
669                     return angle(scifir::acos_degree(float(values[2]/std::sqrt(std::pow(values[0],2) + std::pow(values[1],2) + std::pow(values[2],2)))));
670                 }
671                 else
672                 {
673                     return angle();
674                 }
675             }
.fi
.SS "float \fBscifir::point_nd\fP< float >::get_r () const\fC [inline]\fP"

.PP
Definition at line 653 of file point_nd\&.hpp\&.
.PP
.nf
654             {
655                 if (get_nd() == 2 or get_nd() == 3)
656                 {
657                     return float(std::sqrt(std::pow(values[0],2) + std::pow(values[1],2) + std::pow(values[2],2)));
658                 }
659                 else
660                 {
661                     return float();
662                 }
663             }
.fi
.SS "\fBangle\fP \fBscifir::point_nd\fP< float >::get_theta () const\fC [inline]\fP"

.PP
Definition at line 641 of file point_nd\&.hpp\&.
.PP
.nf
642             {
643                 if (get_nd() == 2 or get_nd() == 3)
644                 {
645                     return angle(scifir::atan_degree(float(values[1]/values[0])));
646                 }
647                 else
648                 {
649                     return angle();
650                 }
651             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::initialize_from_string (string init_point_nd)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line 978 of file point_nd\&.hpp\&.
.PP
.nf
979             {
980                 vector<string> init_values;
981                 if (init_point_nd\&.front() == '(')
982                 {
983                     init_point_nd\&.erase(0,1);
984                 }
985                 if (init_point_nd\&.back() == ')')
986                 {
987                     init_point_nd\&.erase(init_point_nd\&.size()-1,1);
988                 }
989                 boost::split(init_values,init_point_nd,boost::is_any_of(","));
990                 if (init_values\&.size() == 2)
991                 {
992                     if (is_angle(init_values[1]))
993                     {
994                         set_position(stof(init_values[0]),angle(init_values[1]));
995                     }
996                     else
997                     {
998                         set_position(stof(init_values[0]),stof(init_values[1]));
999                     }
1000                 }
1001                 else if (init_values\&.size() == 3)
1002                 {
1003                     if (is_angle(init_values[0]))
1004                     {
1005                         if (is_angle(init_values[1]))
1006                         {
1007                             if (!is_angle(init_values[2]))
1008                             {
1009                                 set_position(angle(init_values[0]),angle(init_values[1]),stof(init_values[2]));
1010                             }
1011                         }
1012                     }
1013                     else
1014                     {
1015                         if (is_angle(init_values[1]))
1016                         {
1017                             if (is_angle(init_values[2]))
1018                             {
1019                                 set_position(stof(init_values[0]),angle(init_values[1]),angle(init_values[2]));
1020                             }
1021                             else
1022                             {
1023                                 set_position(stof(init_values[0]),angle(init_values[1]),stof(init_values[2]));
1024                             }
1025                         }
1026                         else
1027                         {
1028                             if (!is_angle(init_values[2]))
1029                             {
1030                                 set_position(stof(init_values[0]),stof(init_values[1]),stof(init_values[2]));
1031                             }
1032                         }
1033                     }
1034                 }
1035                 else
1036                 {
1037                     for (const string& x_value : init_values)
1038                     {
1039                         values\&.push_back(stof(x_value));
1040                     }
1041                 }
1042             }
.fi
.SS "bool \fBscifir::point_nd\fP< float >::is_nd (unsigned int i) const\fC [inline]\fP"

.PP
Definition at line 619 of file point_nd\&.hpp\&.
.PP
.nf
620             {
621                 return values\&.size() == i;
622             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::move (const displacement_2d & x_displacement)\fC [inline]\fP"

.PP
Definition at line 797 of file point_nd\&.hpp\&.
.PP
.nf
798             {
799                 if (values\&.size() == 2)
800                 {
801                     values[0] += float(x_displacement\&.x_projection());
802                     values[1] += float(x_displacement\&.y_projection());
803                 }
804             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::move (const displacement_3d & x_displacement)\fC [inline]\fP"

.PP
Definition at line 824 of file point_nd\&.hpp\&.
.PP
.nf
825             {
826                 if (values\&.size() == 3)
827                 {
828                     values[0] += float(x_displacement\&.x_projection());
829                     values[1] += float(x_displacement\&.y_projection());
830                     values[2] += float(x_displacement\&.z_projection());
831                 }
832             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::move (const displacement_nd & x_displacement)\fC [inline]\fP"

.PP
Definition at line 864 of file point_nd\&.hpp\&.
.PP
.nf
865             {
866                 if (x_displacement\&.get_nd() == get_nd())
867                 {
868                     for (int i = 0; i < x_displacement\&.get_nd(); i++)
869                     {
870                         values[i] += float(x_displacement\&.n_projection(i));
871                     }
872                 }
873             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::move (float new_p, const \fBangle\fP & new_theta)\fC [inline]\fP"

.PP
Definition at line 815 of file point_nd\&.hpp\&.
.PP
.nf
816             {
817                 if (values\&.size() == 2)
818                 {
819                     values[0] += new_p * scifir::cos(new_theta);
820                     values[1] += new_p * scifir::sin(new_theta);
821                 }
822             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::move (float new_p, const \fBangle\fP & new_theta, float new_z)\fC [inline]\fP"

.PP
Definition at line 844 of file point_nd\&.hpp\&.
.PP
.nf
845             {
846                 if (values\&.size() == 3)
847                 {
848                     values[0] += new_p * scifir::cos(new_theta);
849                     values[1] += new_p * scifir::sin(new_theta);
850                     values[2] += new_z;
851                 }
852             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::move (float new_r, const \fBangle\fP & new_theta, const \fBangle\fP & new_phi)\fC [inline]\fP"

.PP
Definition at line 854 of file point_nd\&.hpp\&.
.PP
.nf
855             {
856                 if (values\&.size() == 3)
857                 {
858                     values[0] += new_r * scifir::cos(new_theta) * scifir::sin(new_phi);
859                     values[1] += new_r * scifir::sin(new_theta) * scifir::sin(new_phi);
860                     values[2] += new_r * scifir::cos(new_phi);
861                 }
862             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::move (float new_r, const vector< \fBangle\fP > & new_angles)\fC [inline]\fP"

.PP
Definition at line 875 of file point_nd\&.hpp\&.
.PP
.nf
876             {
877                 displacement_nd x_displacement = displacement_nd(new_r,"m",new_angles);
878                 move(x_displacement);
879             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::move (float new_x)\fC [inline]\fP"

.PP
Definition at line 789 of file point_nd\&.hpp\&.
.PP
.nf
790             {
791                 if (values\&.size() == 1)
792                 {
793                     values[0] += new_x;
794                 }
795             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::move (float new_x, float new_y)\fC [inline]\fP"

.PP
Definition at line 806 of file point_nd\&.hpp\&.
.PP
.nf
807             {
808                 if (values\&.size() == 2)
809                 {
810                     values[0] += new_x;
811                     values[1] += new_y;
812                 }
813             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::move (float new_x, float new_y, float new_z)\fC [inline]\fP"

.PP
Definition at line 834 of file point_nd\&.hpp\&.
.PP
.nf
835             {
836                 if (values\&.size() == 3)
837                 {
838                     values[0] += new_x;
839                     values[1] += new_y;
840                     values[2] += new_z;
841                 }
842             }
.fi
.SS "\fBpoint_nd\fP< float > & \fBscifir::point_nd\fP< float >::operator= (const \fBcoordinates_nd\fP< float > & x_coordinates)"

.PP
Definition at line 16 of file point_nd\&.cpp\&.
.PP
.nf
17     {
18         values = x_coordinates\&.values;
19         return *this;
20     }
.fi
.SS "\fBpoint_nd\fP<float>& \fBscifir::point_nd\fP< float >::operator= (const \fBpoint_nd\fP< float > & x_point)\fC [inline]\fP"

.PP
Definition at line 597 of file point_nd\&.hpp\&.
.PP
.nf
598             {
599                 values = x_point\&.values;
600                 return *this;
601             }
.fi
.SS "\fBpoint_nd\fP<float>& \fBscifir::point_nd\fP< float >::operator= (const string & init_point_nd)\fC [inline]\fP"

.PP
Definition at line 613 of file point_nd\&.hpp\&.
.PP
.nf
614             {
615                 initialize_from_string(init_point_nd);
616                 return *this;
617             }
.fi
.SS "\fBpoint_nd\fP< float > & \fBscifir::point_nd\fP< float >::operator= (\fBcoordinates_nd\fP< float > && x_coordinates)"

.PP
Definition at line 22 of file point_nd\&.cpp\&.
.PP
.nf
23     {
24         values = std::move(x_coordinates\&.values);
25         return *this;
26     }
.fi
.SS "\fBpoint_nd\fP<float>& \fBscifir::point_nd\fP< float >::operator= (\fBpoint_nd\fP< float > && x_point)\fC [inline]\fP"

.PP
Definition at line 603 of file point_nd\&.hpp\&.
.PP
.nf
604             {
605                 values = std::move(x_point\&.values);
606                 return *this;
607             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::rotate_in_2d (const \fBangle\fP & new_theta)\fC [inline]\fP"

.PP
Definition at line 750 of file point_nd\&.hpp\&.
.PP
.nf
751             {
752                 if (get_nd() == 2)
753                 {
754                     float x_coord = values[0];
755                     float y_coord = values[1];
756                     values[0] = x_coord * scifir::cos(new_theta) - y_coord * scifir::sin(new_theta);
757                     values[1] = x_coord * scifir::sin(new_theta) + y_coord * scifir::cos(new_theta);
758                 }
759             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::rotate_in_3d (int axis, const \fBangle\fP & new_theta)\fC [inline]\fP"

.PP
Definition at line 761 of file point_nd\&.hpp\&.
.PP
.nf
762             {
763                 if (get_nd() == 3)
764                 {
765                     if (axis == 1)
766                     {
767                         float y_coord = values[1];
768                         float z_coord = values[2];
769                         values[1] = y_coord * scifir::cos(new_theta) - z_coord * scifir::sin(new_theta);
770                         values[2] = y_coord * scifir::sin(new_theta) + z_coord * scifir::cos(new_theta);
771                     }
772                     else if (axis == 2)
773                     {
774                         float x_coord = values[0];
775                         float z_coord = values[2];
776                         values[0] = x_coord * scifir::cos(new_theta) - z_coord * scifir::sin(new_theta);
777                         values[2] = x_coord * scifir::sin(new_theta) + z_coord * scifir::cos(new_theta);
778                     }
779                     else if (axis == 3)
780                     {
781                         float x_coord = values[0];
782                         float y_coord = values[1];
783                         values[0] = x_coord * scifir::cos(new_theta) - y_coord * scifir::sin(new_theta);
784                         values[1] = x_coord * scifir::sin(new_theta) + y_coord * scifir::cos(new_theta);
785                     }
786                 }
787             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::set_position (const \fBangle\fP & new_latitude, const \fBangle\fP & new_longitude, float new_altitude)\fC [inline]\fP"

.PP
Definition at line 736 of file point_nd\&.hpp\&.
.PP
.nf
737             {
738                 values\&.clear();
739                 values\&.push_back(new_altitude * scifir::cos(new_latitude) * scifir::cos(new_longitude));
740                 values\&.push_back(new_altitude * scifir::cos(new_latitude) * scifir::sin(new_longitude));
741                 values\&.push_back(new_altitude * scifir::sin(new_latitude));
742             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::set_position (const vector< float > & new_values)\fC [inline]\fP"

.PP
Definition at line 744 of file point_nd\&.hpp\&.
.PP
.nf
745             {
746                 values\&.clear();
747                 values = new_values;
748             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::set_position (float new_p, const \fBangle\fP & new_theta)\fC [inline]\fP"

.PP
Definition at line 705 of file point_nd\&.hpp\&.
.PP
.nf
706             {
707                 values\&.clear();
708                 values\&.push_back(new_p * scifir::cos(new_theta));
709                 values\&.push_back(new_p * scifir::sin(new_theta));
710             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::set_position (float new_p, const \fBangle\fP & new_theta, float new_z)\fC [inline]\fP"

.PP
Definition at line 720 of file point_nd\&.hpp\&.
.PP
.nf
721             {
722                 values\&.clear();
723                 values\&.push_back(new_p * scifir::cos(new_theta));
724                 values\&.push_back(new_p * scifir::sin(new_theta));
725                 values\&.push_back(new_z);
726             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::set_position (float new_r, const \fBangle\fP & new_theta, const \fBangle\fP & new_phi)\fC [inline]\fP"

.PP
Definition at line 728 of file point_nd\&.hpp\&.
.PP
.nf
729             {
730                 values\&.clear();
731                 values\&.push_back(new_r * scifir::cos(new_theta) * scifir::sin(new_phi));
732                 values\&.push_back(new_r * scifir::sin(new_theta) * scifir::sin(new_phi));
733                 values\&.push_back(new_r * scifir::cos(new_phi));
734             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::set_position (float new_x)\fC [inline]\fP"

.PP
Definition at line 692 of file point_nd\&.hpp\&.
.PP
.nf
693             {
694                 values\&.clear();
695                 values\&.push_back(new_x);
696             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::set_position (float new_x, float new_y)\fC [inline]\fP"

.PP
Definition at line 698 of file point_nd\&.hpp\&.
.PP
.nf
699             {
700                 values\&.clear();
701                 values\&.push_back(new_x);
702                 values\&.push_back(new_y);
703             }
.fi
.SS "void \fBscifir::point_nd\fP< float >::set_position (float new_x, float new_y, float new_z)\fC [inline]\fP"

.PP
Definition at line 712 of file point_nd\&.hpp\&.
.PP
.nf
713             {
714                 values\&.clear();
715                 values\&.push_back(new_x);
716                 values\&.push_back(new_y);
717                 values\&.push_back(new_z);
718             }
.fi
.SH "Member Data Documentation"
.PP 
.SS "vector<float> \fBscifir::point_nd\fP< float >::values"

.PP
Definition at line 975 of file point_nd\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
