.TH "scifir::conversion" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::conversion
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconversion\fP (\fBconst\fP \fBstring\fP &\fBnew_unit_to\fP, \fBfloat\fP \fBnew_factor\fP)"
.br
.ti -1c
.RI "\fBconversion\fP (\fBconst\fP \fBstring\fP &\fBnew_unit_to\fP, \fBdouble\fP \fBnew_factor\fP)"
.br
.ti -1c
.RI "\fBconversion\fP (\fBconst\fP \fBstring\fP &\fBnew_unit_to\fP, \fBlong\fP \fBdouble\fP \fBnew_factor\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBlong\fP \fBdouble\fP & \fBget_factor\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBstring\fP & \fBget_unit_to\fP () \fBconst\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
