.TH "scifir::conversion" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::conversion
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <conversion\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconversion\fP ()"
.br
.ti -1c
.RI "\fBconversion\fP (const string &new_unit_to, float new_factor)"
.br
.ti -1c
.RI "\fBconversion\fP (const string &new_unit_to, double new_factor)"
.br
.ti -1c
.RI "\fBconversion\fP (const string &new_unit_to, long double new_factor)"
.br
.ti -1c
.RI "const long double & \fBget_factor\fP () const"
.br
.ti -1c
.RI "const string & \fBget_unit_to\fP () const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "string \fBunit_to\fP"
.br
.ti -1c
.RI "long double \fBfactor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file conversion\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "scifir::conversion::conversion ()"

.PP
Definition at line 10 of file conversion\&.cpp\&.
.PP
.nf
10                            : unit_to(),factor()
11     {}
.fi
.SS "scifir::conversion::conversion (const string & new_unit_to, float new_factor)\fC [explicit]\fP"

.PP
Definition at line 13 of file conversion\&.cpp\&.
.PP
.nf
13                                                                       : unit_to(new_unit_to),factor((long double)new_factor)
14     {}
.fi
.SS "scifir::conversion::conversion (const string & new_unit_to, double new_factor)\fC [explicit]\fP"

.PP
Definition at line 16 of file conversion\&.cpp\&.
.PP
.nf
16                                                                        : unit_to(new_unit_to),factor((long double)new_factor)
17     {}
.fi
.SS "scifir::conversion::conversion (const string & new_unit_to, long double new_factor)\fC [explicit]\fP"

.PP
Definition at line 19 of file conversion\&.cpp\&.
.PP
.nf
19                                                                             : unit_to(new_unit_to),factor(new_factor)
20     {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "const long double& scifir::conversion::get_factor () const\fC [inline]\fP"

.PP
Definition at line 20 of file conversion\&.hpp\&.
.PP
.nf
21             {
22                 return factor;
23             }
.fi
.SS "const string& scifir::conversion::get_unit_to () const\fC [inline]\fP"

.PP
Definition at line 25 of file conversion\&.hpp\&.
.PP
.nf
26             {
27                 return unit_to;
28             }
.fi
.SH "Member Data Documentation"
.PP 
.SS "long double scifir::conversion::factor\fC [private]\fP"

.PP
Definition at line 32 of file conversion\&.hpp\&.
.SS "string scifir::conversion::unit_to\fC [private]\fP"

.PP
Definition at line 31 of file conversion\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
