.TH "scifir::point_3d< T >" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::point_3d< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <point_3d\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpoint_3d\fP ()"
.br
.ti -1c
.RI "\fBpoint_3d\fP (\fBconst\fP \fBpoint_3d\fP< T > &\fBx_point\fP)"
.br
.ti -1c
.RI "\fBpoint_3d\fP (\fBpoint_3d\fP< T > &&\fBx_point\fP)"
.br
.ti -1c
.RI "\fBpoint_3d\fP (\fBconst\fP T &\fBnew_x\fP, \fBconst\fP T &\fBnew_y\fP, \fBconst\fP T &\fBnew_z\fP)"
.br
.ti -1c
.RI "\fBpoint_3d\fP (\fBconst\fP T &\fBnew_p\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP, T \fBnew_z\fP)"
.br
.ti -1c
.RI "\fBpoint_3d\fP (\fBconst\fP T &\fBnew_r\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP, \fBconst\fP \fBangle\fP &\fBnew_phi\fP)"
.br
.ti -1c
.RI "\fBpoint_3d\fP (\fBconst\fP \fBangle\fP &\fBnew_latitude\fP, \fBconst\fP \fBangle\fP &\fBnew_longitude\fP, \fBconst\fP T &\fBnew_altitude\fP)"
.br
.ti -1c
.RI "\fBpoint_3d\fP (\fBconst\fP \fBcoordinates_3d\fP< T > &\fBx_coordinates\fP)"
.br
.ti -1c
.RI "\fBpoint_3d\fP (\fBcoordinates_3d\fP< T > &&\fBx_coordinates\fP)"
.br
.ti -1c
.RI "\fBpoint_3d\fP (\fBconst\fP \fBstring\fP &\fBinit_point_3d\fP)"
.br
.ti -1c
.RI "\fBpoint_3d\fP< T > & \fBoperator=\fP (\fBconst\fP \fBpoint_3d\fP< T > &\fBx_point\fP)"
.br
.ti -1c
.RI "\fBpoint_3d\fP< T > & \fBoperator=\fP (\fBpoint_3d\fP< T > &&\fBx_point\fP)"
.br
.ti -1c
.RI "\fBpoint_3d\fP< T > & \fBoperator=\fP (\fBconst\fP \fBcoordinates_3d\fP< T > &)"
.br
.ti -1c
.RI "\fBpoint_3d\fP< T > & \fBoperator=\fP (\fBcoordinates_3d\fP< T > &&)"
.br
.ti -1c
.RI "\fBpoint_3d\fP< T > & \fBoperator=\fP (\fBconst\fP \fBstring\fP &\fBinit_point_3d\fP)"
.br
.ti -1c
.RI "T \fBget_p\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBangle\fP \fBget_theta\fP () \fBconst\fP"
.br
.ti -1c
.RI "T \fBget_r\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBangle\fP \fBget_phi\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBangle\fP \fBget_latitude\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBangle\fP \fBget_longitude\fP () \fBconst\fP"
.br
.ti -1c
.RI "T \fBget_altitude\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_position\fP (\fBconst\fP T &\fBnew_x\fP, \fBconst\fP T &\fBnew_y\fP, \fBconst\fP T &\fBnew_z\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_position\fP (\fBconst\fP T &\fBnew_p\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP, T \fBnew_z\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_position\fP (\fBconst\fP T &\fBnew_r\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP, \fBconst\fP \fBangle\fP &\fBnew_phi\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_position\fP (\fBconst\fP \fBangle\fP &\fBnew_latitude\fP, \fBconst\fP \fBangle\fP &\fBnew_longitude\fP, \fBconst\fP T &\fBnew_altitude\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBrotate_in_x\fP (\fBconst\fP \fBangle\fP &\fBx_angle\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBrotate_in_y\fP (\fBconst\fP \fBangle\fP &\fBx_angle\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBrotate_in_z\fP (\fBconst\fP \fBangle\fP &\fBx_angle\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBconst\fP \fBdisplacement_3d\fP &\fBx_displacement\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBconst\fP T &\fBnew_x\fP, \fBconst\fP T &\fBnew_y\fP, \fBconst\fP T &\fBnew_z\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBconst\fP T &\fBnew_p\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP, T \fBnew_z\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBconst\fP T &\fBnew_r\fP, \fBconst\fP \fBangle\fP &\fBnew_theta\fP, \fBconst\fP \fBangle\fP &\fBnew_phi\fP)"
.br
.ti -1c
.RI "T \fBdistance_to_origin\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay_cartesian\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay_cylindrical\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay_spherical\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay_geographical\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBx\fP"
.br
.ti -1c
.RI "T \fBy\fP"
.br
.ti -1c
.RI "T \fBz\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBinitialize_from_string\fP (\fBstring\fP \fBinit_point_3d\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<\fBtypename\fP T = length>
.br
class scifir::point_3d< T >"
.PP
Definition at line \fB19\fP of file \fBpoint_3d\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP T  = length> \fBscifir::point_3d\fP< T >::point_3d ()\fC [inline]\fP"

.PP
Definition at line \fB22\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
22                        : x(),y(),z()
23             {}
.fi

.SS "template<\fBtypename\fP T  = length> \fBscifir::point_3d\fP< T >::point_3d (\fBconst\fP \fBpoint_3d\fP< T > & x_point)\fC [inline]\fP"

.PP
Definition at line \fB25\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
25                                                  : x(x_point\&.x),y(x_point\&.y),z(x_point\&.z)
26             {}
.fi

.SS "template<\fBtypename\fP T  = length> \fBscifir::point_3d\fP< T >::point_3d (\fBpoint_3d\fP< T > && x_point)\fC [inline]\fP"

.PP
Definition at line \fB28\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
28                                             : x(std::move(x_point\&.x)),y(std::move(x_point\&.y)),z(std::move(x_point\&.z))
29             {}
.fi

.SS "template<\fBtypename\fP T  = length> \fBscifir::point_3d\fP< T >::point_3d (\fBconst\fP T & new_x, \fBconst\fP T & new_y, \fBconst\fP T & new_z)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line \fB31\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
31                                                                             : x(new_x),y(new_y),z(new_z)
32             {}
.fi

.SS "template<\fBtypename\fP T  = length> \fBscifir::point_3d\fP< T >::point_3d (\fBconst\fP T & new_p, \fBconst\fP \fBangle\fP & new_theta, T new_z)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line \fB34\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
35             {
36                 set_position(new_p,new_theta,new_z);
37             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBscifir::point_3d\fP< T >::point_3d (\fBconst\fP T & new_r, \fBconst\fP \fBangle\fP & new_theta, \fBconst\fP \fBangle\fP & new_phi)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line \fB39\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
40             {
41                 set_position(new_r,new_theta,new_phi);
42             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBscifir::point_3d\fP< T >::point_3d (\fBconst\fP \fBangle\fP & new_latitude, \fBconst\fP \fBangle\fP & new_longitude, \fBconst\fP T & new_altitude)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line \fB44\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
45             {
46                 set_position(new_latitude,new_longitude,new_altitude);
47             }
.fi

.SS "template<\fBtypename\fP T > \fBscifir::point_3d\fP< T >::point_3d (\fBconst\fP \fBcoordinates_3d\fP< T > & x_coordinates)\fC [explicit]\fP"

.PP
Definition at line \fB13\fP of file \fBpoint_3d_impl\&.hpp\fP\&..PP
.nf
13                                                                 : x(x_coordinates\&.x),y(x_coordinates\&.y),z(x_coordinates\&.z)
14     {}
.fi

.SS "template<\fBtypename\fP T > \fBscifir::point_3d\fP< T >::point_3d (\fBcoordinates_3d\fP< T > && x_coordinates)\fC [explicit]\fP"

.PP
Definition at line \fB17\fP of file \fBpoint_3d_impl\&.hpp\fP\&..PP
.nf
17                                                            : x(std::move(x_coordinates\&.x)),y(std::move(x_coordinates\&.y)),z(std::move(x_coordinates\&.z))
18     {}
.fi

.SS "template<\fBtypename\fP T  = length> \fBscifir::point_3d\fP< T >::point_3d (\fBconst\fP \fBstring\fP & init_point_3d)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line \fB53\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
53                                                            : point_3d()
54             {
55                 initialize_from_string(init_point_3d);
56             }
.fi

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP T  = length> \fBstring\fP \fBscifir::point_3d\fP< T >::display_cartesian () const\fC [inline]\fP"

.PP
Definition at line \fB206\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
207             {
208                 ostringstream out;
209                 out << "(" << x << "," << y << "," << z << ")";
210                 return out\&.str();
211             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBstring\fP \fBscifir::point_3d\fP< T >::display_cylindrical () const\fC [inline]\fP"

.PP
Definition at line \fB213\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
214             {
215                 ostringstream out;
216                 out << "(" << get_p() << "," << get_theta() << "," << z << ")";
217                 return out\&.str();
218             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBstring\fP \fBscifir::point_3d\fP< T >::display_geographical () const\fC [inline]\fP"

.PP
Definition at line \fB227\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
228             {
229                 ostringstream out;
230                 out << "(" << get_latitude() << "," << get_longitude() << "," << get_altitude() << ")";
231                 return out\&.str();
232             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBstring\fP \fBscifir::point_3d\fP< T >::display_spherical () const\fC [inline]\fP"

.PP
Definition at line \fB220\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
221             {
222                 ostringstream out;
223                 out << "(" << get_r() << "," << get_theta() << "," << get_phi() << ")";
224                 return out\&.str();
225             }
.fi

.SS "template<\fBtypename\fP T  = length> T \fBscifir::point_3d\fP< T >::distance_to_origin () const\fC [inline]\fP"

.PP
Definition at line \fB201\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
202             {
203                 return scifir::sqrt(scifir::pow(x,2) + scifir::pow(y,2) + scifir::pow(z,2));
204             }
.fi

.SS "template<\fBtypename\fP T  = length> T \fBscifir::point_3d\fP< T >::get_altitude () const\fC [inline]\fP"

.PP
Definition at line \fB114\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
115             {
116                 return T();
117             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBangle\fP \fBscifir::point_3d\fP< T >::get_latitude () const\fC [inline]\fP"

.PP
Definition at line \fB104\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
105             {
106                 return scifir::asin(float(z/T(6317,"km")));
107             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBangle\fP \fBscifir::point_3d\fP< T >::get_longitude () const\fC [inline]\fP"

.PP
Definition at line \fB109\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
110             {
111                 return scifir::atan(float(y/x));
112             }
.fi

.SS "template<\fBtypename\fP T  = length> T \fBscifir::point_3d\fP< T >::get_p () const\fC [inline]\fP"

.PP
Definition at line \fB84\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
85             {
86                 return scifir::sqrt(scifir::pow(x,2) + scifir::pow(y,2));
87             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBangle\fP \fBscifir::point_3d\fP< T >::get_phi () const\fC [inline]\fP"

.PP
Definition at line \fB99\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
100             {
101                 return angle(scifir::acos_grade(float(z/scifir::sqrt(scifir::pow(x,2) + scifir::pow(y,2) + scifir::pow(z,2)))));
102             }
.fi

.SS "template<\fBtypename\fP T  = length> T \fBscifir::point_3d\fP< T >::get_r () const\fC [inline]\fP"

.PP
Definition at line \fB94\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
95             {
96                 return scifir::sqrt(scifir::pow(x,2) + scifir::pow(y,2) + scifir::pow(z,2));
97             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBangle\fP \fBscifir::point_3d\fP< T >::get_theta () const\fC [inline]\fP"

.PP
Definition at line \fB89\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
90             {
91                 return scifir::atan(float(y/x));
92             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBvoid\fP \fBscifir::point_3d\fP< T >::initialize_from_string (\fBstring\fP init_point_3d)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line \fB239\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
240             {
241                 vector<string> values;
242                 if (init_point_3d\&.front() == '(')
243                 {
244                     init_point_3d\&.erase(0,1);
245                 }
246                 if (init_point_3d\&.back() == ')')
247                 {
248                     init_point_3d\&.erase(init_point_3d\&.size()\-1,1);
249                 }
250                 boost::split(values,init_point_3d,boost::is_any_of(","));
251                 if (values\&.size() == 3)
252                 {
253                     if (is_angle(values[0]))
254                     {
255                         if (is_angle(values[1]))
256                         {
257                             if (!is_angle(values[2]))
258                             {
259                                 set_position(angle(values[0]),angle(values[1]),T(values[2]));
260                             }
261                         }
262                     }
263                     else
264                     {
265                         if (is_angle(values[1]))
266                         {
267                             if (is_angle(values[2]))
268                             {
269                                 set_position(T(values[0]),angle(values[1]),angle(values[2]));
270                             }
271                             else
272                             {
273                                 set_position(T(values[0]),angle(values[1]),T(values[2]));
274                             }
275                         }
276                         else
277                         {
278                             if (!is_angle(values[2]))
279                             {
280                                 set_position(T(values[0]),T(values[1]),T(values[2]));
281                             }
282                         }
283                     }
284                 }
285             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBvoid\fP \fBscifir::point_3d\fP< T >::move (\fBconst\fP \fBdisplacement_3d\fP & x_displacement)\fC [inline]\fP"

.PP
Definition at line \fB172\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
173             {
174                 x += x_displacement\&.x_projection();
175                 y += x_displacement\&.y_projection();
176                 z += x_displacement\&.z_projection();
177             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBvoid\fP \fBscifir::point_3d\fP< T >::move (\fBconst\fP T & new_p, \fBconst\fP \fBangle\fP & new_theta, T new_z)\fC [inline]\fP"

.PP
Definition at line \fB186\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
187             {
188                 new_z\&.change_dimensions(new_p);
189                 x += T(new_p * scifir::cos(new_theta));
190                 y += T(new_p * scifir::sin(new_theta));
191                 z += new_z;
192             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBvoid\fP \fBscifir::point_3d\fP< T >::move (\fBconst\fP T & new_r, \fBconst\fP \fBangle\fP & new_theta, \fBconst\fP \fBangle\fP & new_phi)\fC [inline]\fP"

.PP
Definition at line \fB194\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
195             {
196                 x += T(new_r * scifir::cos(new_theta) * scifir::sin(new_phi));
197                 y += T(new_r * scifir::sin(new_theta) * scifir::sin(new_phi));
198                 z += T(new_r * scifir::cos(new_phi));
199             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBvoid\fP \fBscifir::point_3d\fP< T >::move (\fBconst\fP T & new_x, \fBconst\fP T & new_y, \fBconst\fP T & new_z)\fC [inline]\fP"

.PP
Definition at line \fB179\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
180             {
181                 x += new_x;
182                 y += new_y;
183                 z += new_z;
184             }
.fi

.SS "template<\fBtypename\fP T > \fBpoint_3d\fP< T > & \fBscifir::point_3d\fP< T >::operator= (\fBconst\fP \fBcoordinates_3d\fP< T > & x_coordinates)"

.PP
Definition at line \fB21\fP of file \fBpoint_3d_impl\&.hpp\fP\&..PP
.nf
22     {
23         x = x_coordinates\&.x;
24         y = x_coordinates\&.y;
25         z = x_coordinates\&.z;
26         return *this;
27     }
.fi

.SS "template<\fBtypename\fP T  = length> \fBpoint_3d\fP< T > & \fBscifir::point_3d\fP< T >::operator= (\fBconst\fP \fBpoint_3d\fP< T > & x_point)\fC [inline]\fP"

.PP
Definition at line \fB58\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
59             {
60                 x = x_point\&.x;
61                 y = x_point\&.y;
62                 z = x_point\&.z;
63                 return *this;
64             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBpoint_3d\fP< T > & \fBscifir::point_3d\fP< T >::operator= (\fBconst\fP \fBstring\fP & init_point_3d)\fC [inline]\fP"

.PP
Definition at line \fB78\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
79             {
80                 initialize_from_string(init_point_3d);
81                 return *this;
82             }
.fi

.SS "template<\fBtypename\fP T > \fBpoint_3d\fP< T > & \fBscifir::point_3d\fP< T >::operator= (\fBcoordinates_3d\fP< T > && x_coordinates)"

.PP
Definition at line \fB30\fP of file \fBpoint_3d_impl\&.hpp\fP\&..PP
.nf
31     {
32         x = std::move(x_coordinates\&.x);
33         y = std::move(x_coordinates\&.y);
34         z = std::move(x_coordinates\&.z);
35         return *this;
36     }
.fi

.SS "template<\fBtypename\fP T  = length> \fBpoint_3d\fP< T > & \fBscifir::point_3d\fP< T >::operator= (\fBpoint_3d\fP< T > && x_point)\fC [inline]\fP"

.PP
Definition at line \fB66\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
67             {
68                 x = std::move(x_point\&.x);
69                 y = std::move(x_point\&.y);
70                 z = std::move(x_point\&.z);
71                 return *this;
72             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBvoid\fP \fBscifir::point_3d\fP< T >::rotate_in_x (\fBconst\fP \fBangle\fP & x_angle)\fC [inline]\fP"

.PP
Definition at line \fB148\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
149             {
150                 T y_coord = y;
151                 T z_coord = z;
152                 y = y_coord * scifir::cos(x_angle) \- z_coord * scifir::sin(x_angle);
153                 z = y_coord * scifir::sin(x_angle) + z_coord * scifir::cos(x_angle);
154             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBvoid\fP \fBscifir::point_3d\fP< T >::rotate_in_y (\fBconst\fP \fBangle\fP & x_angle)\fC [inline]\fP"

.PP
Definition at line \fB156\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
157             {
158                 T x_coord = x;
159                 T z_coord = z;
160                 x = x_coord * scifir::cos(x_angle) \- z_coord * scifir::sin(x_angle);
161                 z = x_coord * scifir::sin(x_angle) + z_coord * scifir::cos(x_angle);
162             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBvoid\fP \fBscifir::point_3d\fP< T >::rotate_in_z (\fBconst\fP \fBangle\fP & x_angle)\fC [inline]\fP"

.PP
Definition at line \fB164\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
165             {
166                 T x_coord = x;
167                 T y_coord = y;
168                 x = x_coord * scifir::cos(x_angle) \- y_coord * scifir::sin(x_angle);
169                 y = x_coord * scifir::sin(x_angle) + y_coord * scifir::cos(x_angle);
170             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBvoid\fP \fBscifir::point_3d\fP< T >::set_position (\fBconst\fP \fBangle\fP & new_latitude, \fBconst\fP \fBangle\fP & new_longitude, \fBconst\fP T & new_altitude)\fC [inline]\fP"

.PP
Definition at line \fB141\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
142             {
143                 x = T(new_altitude * scifir::cos(new_latitude) * scifir::cos(new_longitude));
144                 y = T(new_altitude * scifir::cos(new_latitude) * scifir::sin(new_longitude));
145                 z = T(new_altitude * scifir::sin(new_latitude));
146             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBvoid\fP \fBscifir::point_3d\fP< T >::set_position (\fBconst\fP T & new_p, \fBconst\fP \fBangle\fP & new_theta, T new_z)\fC [inline]\fP"

.PP
Definition at line \fB126\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
127             {
128                 new_z\&.change_dimensions(new_p);
129                 x = T(new_p * scifir::cos(new_theta));
130                 y = T(new_p * scifir::sin(new_theta));
131                 z = new_z;
132             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBvoid\fP \fBscifir::point_3d\fP< T >::set_position (\fBconst\fP T & new_r, \fBconst\fP \fBangle\fP & new_theta, \fBconst\fP \fBangle\fP & new_phi)\fC [inline]\fP"

.PP
Definition at line \fB134\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
135             {
136                 x = T(new_r * scifir::cos(new_theta) * scifir::sin(new_phi));
137                 y = T(new_r * scifir::sin(new_theta) * scifir::sin(new_phi));
138                 z = T(new_r * scifir::cos(new_phi));
139             }
.fi

.SS "template<\fBtypename\fP T  = length> \fBvoid\fP \fBscifir::point_3d\fP< T >::set_position (\fBconst\fP T & new_x, \fBconst\fP T & new_y, \fBconst\fP T & new_z)\fC [inline]\fP"

.PP
Definition at line \fB119\fP of file \fBpoint_3d\&.hpp\fP\&..PP
.nf
120             {
121                 x = new_x;
122                 y = new_y;
123                 z = new_z;
124             }
.fi

.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP T  = length> T \fBscifir::point_3d\fP< T >::x"

.PP
Definition at line \fB234\fP of file \fBpoint_3d\&.hpp\fP\&.
.SS "template<\fBtypename\fP T  = length> T \fBscifir::point_3d\fP< T >::y"

.PP
Definition at line \fB235\fP of file \fBpoint_3d\&.hpp\fP\&.
.SS "template<\fBtypename\fP T  = length> T \fBscifir::point_3d\fP< T >::z"

.PP
Definition at line \fB236\fP of file \fBpoint_3d\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
