.TH "scifir::zid" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::zid
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBzid\fP (\fBconst\fP \fBzid\fP &x)"
.br
.ti -1c
.RI "\fBzid\fP (\fBzid\fP &&x)"
.br
.ti -1c
.RI "\fBzid\fP (\fBconst\fP \fBscifir::aid\fP &\fBnew_aid\fP, \fBconst\fP \fBstring\fP &\fBnew_country\fP, \fBconst\fP vector< \fBstring\fP > &\fBnew_regions\fP, \fBconst\fP \fBstring\fP &\fBnew_zone\fP)"
.br
.ti -1c
.RI "\fBzid\fP (\fBconst\fP \fBscifir::aid\fP &\fBnew_aid\fP, \fBconst\fP \fBstring\fP &\fBinit_zid\fP)"
.br
.ti -1c
.RI "\fBzid\fP (\fBconst\fP \fBstring\fP &\fBinit_zid_full\fP)"
.br
.ti -1c
.RI "\fBzid\fP & \fBoperator=\fP (\fBconst\fP \fBzid\fP &x)"
.br
.ti -1c
.RI "\fBzid\fP & \fBoperator=\fP (\fBzid\fP &&x)"
.br
.ti -1c
.RI "\fBzid\fP & \fBoperator=\fP (\fBconst\fP \fBstring\fP &\fBinit_zid_full\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBhas_no_country\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBhas_unknown_country\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBpartial_display\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBscifir::aid\fP \fBaid\fP"
.br
.ti -1c
.RI "vector< \fBstring\fP > \fBregions\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBcountry\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBzone\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
