.TH "scifir::coordinates_1d< float >" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::coordinates_1d< float >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <coordinates_1d\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcoordinates_1d\fP ()"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP (const \fBcoordinates_1d\fP< float > &x_coordinates)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP (\fBcoordinates_1d\fP< float > &&x_coordinates)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP (float new_x)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP (const \fBpoint_1d\fP< float > &new_point)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP (\fBpoint_1d\fP< float > &&new_point)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP (const string &init_coordinates_1d)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP< float > & \fBoperator=\fP (const \fBcoordinates_1d\fP< float > &x_coordinates)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP< float > & \fBoperator=\fP (\fBcoordinates_1d\fP< float > &&x_coordinates)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP< float > & \fBoperator=\fP (const \fBpoint_1d\fP< float > &x_point)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP< float > & \fBoperator=\fP (\fBpoint_1d\fP< float > &&x_point)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP< float > & \fBoperator=\fP (const string &init_coordinates_1d)"
.br
.ti -1c
.RI "void \fBset_position\fP (float new_x)"
.br
.ti -1c
.RI "void \fBmove\fP (float x_value)"
.br
.ti -1c
.RI "float \fBdistance_to_origin\fP () const"
.br
.ti -1c
.RI "string \fBdisplay_cartesian\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize_from_string\fP (string init_coordinates_1d)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 113 of file coordinates_1d\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBscifir::coordinates_1d\fP< float >::\fBcoordinates_1d\fP ()\fC [inline]\fP"

.PP
Definition at line 116 of file coordinates_1d\&.hpp\&.
.PP
.nf
116                              : x()
117             {}
.fi
.SS "\fBscifir::coordinates_1d\fP< float >::\fBcoordinates_1d\fP (const \fBcoordinates_1d\fP< float > & x_coordinates)\fC [inline]\fP"

.PP
Definition at line 119 of file coordinates_1d\&.hpp\&.
.PP
.nf
119                                                                        : x(x_coordinates\&.x)
120             {}
.fi
.SS "\fBscifir::coordinates_1d\fP< float >::\fBcoordinates_1d\fP (\fBcoordinates_1d\fP< float > && x_coordinates)\fC [inline]\fP"

.PP
Definition at line 122 of file coordinates_1d\&.hpp\&.
.PP
.nf
122                                                                   : x(std::move(x_coordinates\&.x))
123             {}
.fi
.SS "\fBscifir::coordinates_1d\fP< float >::\fBcoordinates_1d\fP (float new_x)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 125 of file coordinates_1d\&.hpp\&.
.PP
.nf
125                                                  : x(new_x)
126             {}
.fi
.SS "\fBscifir::coordinates_1d\fP< float >::\fBcoordinates_1d\fP (const \fBpoint_1d\fP< float > & new_point)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 128 of file coordinates_1d\&.hpp\&.
.PP
.nf
128                                                                       : x(new_point\&.x)
129             {}
.fi
.SS "\fBscifir::coordinates_1d\fP< float >::\fBcoordinates_1d\fP (\fBpoint_1d\fP< float > && new_point)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 131 of file coordinates_1d\&.hpp\&.
.PP
.nf
131                                                                  : x(std::move(new_point\&.x))
132             {}
.fi
.SS "\fBscifir::coordinates_1d\fP< float >::\fBcoordinates_1d\fP (const string & init_coordinates_1d)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 134 of file coordinates_1d\&.hpp\&.
.PP
.nf
134                                                                        : coordinates_1d()
135             {
136                 initialize_from_string(init_coordinates_1d);
137             }
.fi
.SH "Member Function Documentation"
.PP 
.SS "string \fBscifir::coordinates_1d\fP< float >::display_cartesian () const\fC [inline]\fP"

.PP
Definition at line 184 of file coordinates_1d\&.hpp\&.
.PP
.nf
185             {
186                 ostringstream out;
187                 out << "(" << display_float(x) <<  ")";
188                 return out\&.str();
189             }
.fi
.SS "float \fBscifir::coordinates_1d\fP< float >::distance_to_origin () const\fC [inline]\fP"

.PP
Definition at line 179 of file coordinates_1d\&.hpp\&.
.PP
.nf
180             {
181                 return float(std::abs(x));
182             }
.fi
.SS "void \fBscifir::coordinates_1d\fP< float >::initialize_from_string (string init_coordinates_1d)\fC [inline]\fP, \fC [private]\fP"

.PP
Definition at line 194 of file coordinates_1d\&.hpp\&.
.PP
.nf
195             {
196                 if (init_coordinates_1d\&.front() == '(')
197                 {
198                     init_coordinates_1d\&.erase(0,1);
199                 }
200                 if (init_coordinates_1d\&.back() == ')')
201                 {
202                     init_coordinates_1d\&.erase(init_coordinates_1d\&.size()-1,1);
203                 }
204                 x = stof(init_coordinates_1d);
205             }
.fi
.SS "void \fBscifir::coordinates_1d\fP< float >::move (float x_value)\fC [inline]\fP"

.PP
Definition at line 174 of file coordinates_1d\&.hpp\&.
.PP
.nf
175             {
176                 x += x_value;
177             }
.fi
.SS "\fBcoordinates_1d\fP<float>& \fBscifir::coordinates_1d\fP< float >::operator= (const \fBcoordinates_1d\fP< float > & x_coordinates)\fC [inline]\fP"

.PP
Definition at line 139 of file coordinates_1d\&.hpp\&.
.PP
.nf
140             {
141                 x = x_coordinates\&.x;
142                 return *this;
143             }
.fi
.SS "\fBcoordinates_1d\fP<float>& \fBscifir::coordinates_1d\fP< float >::operator= (const \fBpoint_1d\fP< float > & x_point)\fC [inline]\fP"

.PP
Definition at line 151 of file coordinates_1d\&.hpp\&.
.PP
.nf
152             {
153                 x = x_point\&.x;
154                 return *this;
155             }
.fi
.SS "\fBcoordinates_1d\fP<float>& \fBscifir::coordinates_1d\fP< float >::operator= (const string & init_coordinates_1d)\fC [inline]\fP"

.PP
Definition at line 163 of file coordinates_1d\&.hpp\&.
.PP
.nf
164             {
165                 initialize_from_string(init_coordinates_1d);
166                 return *this;
167             }
.fi
.SS "\fBcoordinates_1d\fP<float>& \fBscifir::coordinates_1d\fP< float >::operator= (\fBcoordinates_1d\fP< float > && x_coordinates)\fC [inline]\fP"

.PP
Definition at line 145 of file coordinates_1d\&.hpp\&.
.PP
.nf
146             {
147                 x = std::move(x_coordinates\&.x);
148                 return *this;
149             }
.fi
.SS "\fBcoordinates_1d\fP<float>& \fBscifir::coordinates_1d\fP< float >::operator= (\fBpoint_1d\fP< float > && x_point)\fC [inline]\fP"

.PP
Definition at line 157 of file coordinates_1d\&.hpp\&.
.PP
.nf
158             {
159                 x = std::move(x_point\&.x);
160                 return *this;
161             }
.fi
.SS "void \fBscifir::coordinates_1d\fP< float >::set_position (float new_x)\fC [inline]\fP"

.PP
Definition at line 169 of file coordinates_1d\&.hpp\&.
.PP
.nf
170             {
171                 x = new_x;
172             }
.fi
.SH "Member Data Documentation"
.PP 
.SS "float \fBscifir::coordinates_1d\fP< float >::x"

.PP
Definition at line 191 of file coordinates_1d\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
