.TH "scifir::aid" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::aid
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <aid\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBtype\fP : int8_t { \fBNONE\fP, \fBUNIVERSE\fP, \fBGALAXY\fP, \fBSOLAR_SYSTEM\fP, \fBPLANET\fP, \fBSTAR\fP, \fBASTEROID\fP, \fBMOON\fP, \fBMETEOR\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaid\fP ()"
.br
.ti -1c
.RI "\fBaid\fP (const \fBaid\fP &x)"
.br
.ti -1c
.RI "\fBaid\fP (\fBaid\fP &&x)"
.br
.ti -1c
.RI "\fBaid\fP (const \fBastronomical_body\fP &predefined_astronomical_body)"
.br
.ti -1c
.RI "\fBaid\fP (const string &new_universe, const string &new_galaxy)"
.br
.ti -1c
.RI "\fBaid\fP (const string &new_universe, const string &new_galaxy, const string &new_solar_system)"
.br
.ti -1c
.RI "\fBaid\fP (const \fBaid::type\fP &new_astronomical_type, const string &new_universe, const string &new_galaxy, const string &new_solar_system, const string &new_astronomical_body)"
.br
.ti -1c
.RI "\fBaid\fP (const string &init_aid)"
.br
.ti -1c
.RI "\fBaid\fP & \fBoperator=\fP (const \fBaid\fP &x)"
.br
.ti -1c
.RI "\fBaid\fP & \fBoperator=\fP (\fBaid\fP &&x)"
.br
.ti -1c
.RI "\fBaid\fP & \fBoperator=\fP (const string &init_aid)"
.br
.ti -1c
.RI "bool \fBhas_unknown_universe\fP () const"
.br
.ti -1c
.RI "bool \fBhas_unknown_galaxy\fP () const"
.br
.ti -1c
.RI "bool \fBhas_unknown_solar_system\fP () const"
.br
.ti -1c
.RI "bool \fBhas_unknown_planet\fP () const"
.br
.ti -1c
.RI "bool \fBhas_unknown_moon\fP () const"
.br
.ti -1c
.RI "bool \fBhas_unknown_star\fP () const"
.br
.ti -1c
.RI "bool \fBhas_unknown_asteroid\fP () const"
.br
.ti -1c
.RI "string \fBdisplay\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBuniverse\fP"
.br
.ti -1c
.RI "string \fBgalaxy\fP"
.br
.ti -1c
.RI "string \fBsolar_system\fP"
.br
.ti -1c
.RI "string \fBastronomical_body\fP"
.br
.ti -1c
.RI "\fBaid::type\fP \fBastronomical_type\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize_from_string\fP (const string &init_aid)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file aid\&.hpp\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBscifir::aid::type\fP : int8_t"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINONE \fP\fP
.TP
\fB\fIUNIVERSE \fP\fP
.TP
\fB\fIGALAXY \fP\fP
.TP
\fB\fISOLAR_SYSTEM \fP\fP
.TP
\fB\fIPLANET \fP\fP
.TP
\fB\fISTAR \fP\fP
.TP
\fB\fIASTEROID \fP\fP
.TP
\fB\fIMOON \fP\fP
.TP
\fB\fIMETEOR \fP\fP
.PP
Definition at line 16 of file aid\&.hpp\&.
.PP
.nf
16 : int8_t {NONE,UNIVERSE,GALAXY,SOLAR_SYSTEM,PLANET,STAR,ASTEROID,MOON,METEOR};
.fi
.SH "Constructor & Destructor Documentation"
.PP 
.SS "scifir::aid::aid ()"

.PP
Definition at line 13 of file aid\&.cpp\&.
.PP
.nf
13              : universe(),galaxy(),solar_system(),astronomical_body(),astronomical_type(aid::NONE)
14     {}
.fi
.SS "scifir::aid::aid (const \fBaid\fP & x)"

.PP
Definition at line 16 of file aid\&.cpp\&.
.PP
.nf
16                          : universe(x\&.universe),galaxy(x\&.galaxy),solar_system(x\&.solar_system),astronomical_body(x\&.astronomical_body),astronomical_type(x\&.astronomical_type)
17     {}
.fi
.SS "scifir::aid::aid (\fBaid\fP && x)"

.PP
Definition at line 19 of file aid\&.cpp\&.
.PP
.nf
19                     : universe(std::move(x\&.universe)),galaxy(std::move(x\&.galaxy)),solar_system(std::move(x\&.solar_system)),astronomical_body(std::move(x\&.astronomical_body)),astronomical_type(std::move(x\&.astronomical_type))
20     {}
.fi
.SS "scifir::aid::aid (const \fBastronomical_body\fP & predefined_astronomical_body)\fC [explicit]\fP"

.SS "scifir::aid::aid (const string & new_universe, const string & new_galaxy)\fC [explicit]\fP"

.PP
Definition at line 312 of file aid\&.cpp\&.
.PP
.nf
312                                                                 : universe(new_universe),galaxy(new_galaxy),solar_system(),astronomical_body(),astronomical_type(aid::GALAXY)
313     {}
.fi
.SS "scifir::aid::aid (const string & new_universe, const string & new_galaxy, const string & new_solar_system)\fC [explicit]\fP"

.PP
Definition at line 315 of file aid\&.cpp\&.
.PP
.nf
315                                                                                                : universe(new_universe),galaxy(new_galaxy),solar_system(new_solar_system),astronomical_body(),astronomical_type(aid::SOLAR_SYSTEM)
316     {}
.fi
.SS "scifir::aid::aid (const \fBaid::type\fP & new_astronomical_type, const string & new_universe, const string & new_galaxy, const string & new_solar_system, const string & new_astronomical_body)\fC [explicit]\fP"

.PP
Definition at line 318 of file aid\&.cpp\&.
.PP
.nf
318                                                                                                                                                                         : universe(new_universe),galaxy(new_galaxy),solar_system(new_solar_system),astronomical_body(new_astronomical_body),astronomical_type(new_astronomical_type)
319     {}
.fi
.SS "scifir::aid::aid (const string & init_aid)\fC [explicit]\fP"

.PP
Definition at line 321 of file aid\&.cpp\&.
.PP
.nf
321                                    : aid()
322     {
323         initialize_from_string(init_aid);
324     }
.fi
.SH "Member Function Documentation"
.PP 
.SS "string scifir::aid::display () const"

.PP
Definition at line 436 of file aid\&.cpp\&.
.PP
.nf
437     {
438         if (astronomical_type != aid::NONE)
439         {
440             ostringstream out;
441             out << "(" << to_string(astronomical_type) << ")";
442             if (astronomical_type == aid::UNIVERSE)
443             {
444                 out << universe;
445             }
446             else if (astronomical_type == aid::GALAXY)
447             {
448                 out << universe << ":" << galaxy;
449             }
450             else if (astronomical_type == aid::SOLAR_SYSTEM)
451             {
452                 out << universe << ":" << galaxy << ":" << solar_system;
453             }
454             else
455             {
456                 if (universe != "")
457                 {
458                     out << universe << ":";
459                 }
460                 out << galaxy << ":" << solar_system << ":" << astronomical_body;
461             }
462             return out\&.str();
463         }
464         else
465         {
466             return "";
467         }
468     }
.fi
.SS "bool scifir::aid::has_unknown_asteroid () const"

.PP
Definition at line 382 of file aid\&.cpp\&.
.PP
.nf
383     {
384         return (astronomical_body == "unknown-asteroid");
385     }
.fi
.SS "bool scifir::aid::has_unknown_galaxy () const"

.PP
Definition at line 357 of file aid\&.cpp\&.
.PP
.nf
358     {
359         return (galaxy == "unknown-galaxy");
360     }
.fi
.SS "bool scifir::aid::has_unknown_moon () const"

.PP
Definition at line 372 of file aid\&.cpp\&.
.PP
.nf
373     {
374         return (astronomical_body == "unknown-moon");
375     }
.fi
.SS "bool scifir::aid::has_unknown_planet () const"

.PP
Definition at line 367 of file aid\&.cpp\&.
.PP
.nf
368     {
369         return (astronomical_body == "unknown-planet");
370     }
.fi
.SS "bool scifir::aid::has_unknown_solar_system () const"

.PP
Definition at line 362 of file aid\&.cpp\&.
.PP
.nf
363     {
364         return (solar_system == "unknown-solar-system");
365     }
.fi
.SS "bool scifir::aid::has_unknown_star () const"

.PP
Definition at line 377 of file aid\&.cpp\&.
.PP
.nf
378     {
379         return (astronomical_body == "unknown-star");
380     }
.fi
.SS "bool scifir::aid::has_unknown_universe () const"

.PP
Definition at line 352 of file aid\&.cpp\&.
.PP
.nf
353     {
354         return (universe == "unknown-universe");
355     }
.fi
.SS "void scifir::aid::initialize_from_string (const string & init_aid)\fC [private]\fP"

.PP
Definition at line 387 of file aid\&.cpp\&.
.PP
.nf
388     {
389         vector<string> values;
390         boost::split(values,init_aid,boost::is_any_of(":"));
391         string aid_type;
392         if (values[0]\&.front() == '(' and isalpha(values[0][1]))
393         {
394             if (isalpha(values[0][2]))
395             {
396                 astronomical_type = create_astronomical_type(values[0]\&.substr(1,2));
397                 if (values[0][4] != ' ')
398                 {
399                     universe = values[0]\&.substr(4);
400                 }
401                 else
402                 {
403                     universe = values[0]\&.substr(5);
404                 }
405             }
406             else
407             {
408                 astronomical_type = create_astronomical_type(values[0]\&.substr(1,1));
409                 if (values[0][3] != ' ')
410                 {
411                     universe = values[0]\&.substr(3);
412                 }
413                 else
414                 {
415                     universe = values[0]\&.substr(4);
416                 }
417             }
418             if (values\&.size() == 4)
419             {
420                 galaxy = values[1];
421                 solar_system = values[2];
422                 astronomical_body = values[3];
423             }
424             else if (values\&.size() == 3)
425             {
426                 galaxy = values[1];
427                 solar_system = values[2];
428             }
429             else if (values\&.size() == 2)
430             {
431                 galaxy = values[1];
432             }
433         }
434     }
.fi
.SS "\fBaid\fP & scifir::aid::operator= (\fBaid\fP && x)"

.PP
Definition at line 336 of file aid\&.cpp\&.
.PP
.nf
337     {
338         universe = std::move(x\&.universe);
339         galaxy = std::move(x\&.galaxy);
340         solar_system = std::move(x\&.solar_system);
341         astronomical_body = std::move(x\&.astronomical_body);
342         astronomical_type = std::move(x\&.astronomical_type);
343         return *this;
344     }
.fi
.SS "\fBaid\fP & scifir::aid::operator= (const \fBaid\fP & x)"

.PP
Definition at line 326 of file aid\&.cpp\&.
.PP
.nf
327     {
328         universe = x\&.universe;
329         galaxy = x\&.galaxy;
330         solar_system = x\&.solar_system;
331         astronomical_body = x\&.astronomical_body;
332         astronomical_type = x\&.astronomical_type;
333         return *this;
334     }
.fi
.SS "\fBaid\fP & scifir::aid::operator= (const string & init_aid)"

.PP
Definition at line 346 of file aid\&.cpp\&.
.PP
.nf
347     {
348         initialize_from_string(init_aid);
349         return *this;
350     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "string scifir::aid::astronomical_body"

.PP
Definition at line 44 of file aid\&.hpp\&.
.SS "\fBaid::type\fP scifir::aid::astronomical_type"

.PP
Definition at line 45 of file aid\&.hpp\&.
.SS "string scifir::aid::galaxy"

.PP
Definition at line 42 of file aid\&.hpp\&.
.SS "string scifir::aid::solar_system"

.PP
Definition at line 43 of file aid\&.hpp\&.
.SS "string scifir::aid::universe"

.PP
Definition at line 41 of file aid\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
