.TH "scifir::tensor_unit< T >" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::tensor_unit< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBtype\fP { \fBSCALAR\fP, \fBVECTOR\fP, \fBMATRIX\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtensor_unit\fP (\fBconst\fP \fBtensor_unit\fP &x)"
.br
.ti -1c
.RI "\fBtensor_unit\fP (\fBtensor_unit\fP &&x)"
.br
.ti -1c
.RI "\fBtensor_unit\fP (\fBconst\fP vector< vector< T > > &x)"
.br
.ti -1c
.RI "\fBtensor_unit\fP (\fBconst\fP \fBscalar_unit\fP &x)"
.br
.ti -1c
.RI "\fBtensor_unit\fP (\fBconst\fP \fBvector_unit_2d\fP &x)"
.br
.ti -1c
.RI "\fBtensor_unit\fP (\fBconst\fP \fBvector_unit_3d\fP &x)"
.br
.ti -1c
.RI "\fBtensor_unit\fP (\fBconst\fP \fBvector_unit_nd\fP &x)"
.br
.ti -1c
.RI "\fBtensor_unit\fP & \fBoperator=\fP (\fBconst\fP \fBtensor_unit\fP &x)"
.br
.ti -1c
.RI "\fBtensor_unit\fP & \fBoperator=\fP (\fBtensor_unit\fP &&x)"
.br
.ti -1c
.RI "\fBint\fP \fBget_dimension\fP () \fBconst\fP"
.br
.ti -1c
.RI "tensor_unit::type \fBget_type\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_scalar\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_vector\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_matrix\fP () \fBconst\fP"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBU\fP > \fBtensor_unit\fP< \fBscalar_unit\fP > \fBoperator+\fP (\fBconst\fP \fBtensor_unit\fP< \fBU\fP > &x) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBU\fP > \fBtensor_unit\fP< \fBscalar_unit\fP > \fBoperator\-\fP (\fBconst\fP \fBtensor_unit\fP< \fBU\fP > &x) \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< vector< T > > \fBvalues\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
