.TH "scifir::coordinates_1d< T >" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::coordinates_1d< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcoordinates_1d\fP (\fBconst\fP \fBcoordinates_1d\fP< T > &\fBx_coordinates\fP)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP (\fBcoordinates_1d\fP< T > &&\fBx_coordinates\fP)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP (\fBconst\fP T &\fBnew_x\fP)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP (\fBconst\fP \fBpoint_1d\fP< T > &\fBnew_point\fP)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP (\fBpoint_1d\fP< T > &&\fBnew_point\fP)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP (\fBconst\fP \fBstring\fP &\fBinit_coordinates_1d\fP)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP< T > & \fBoperator=\fP (\fBconst\fP \fBcoordinates_1d\fP< T > &\fBx_coordinates\fP)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP< T > & \fBoperator=\fP (\fBcoordinates_1d\fP< T > &&\fBx_coordinates\fP)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP< T > & \fBoperator=\fP (\fBconst\fP \fBpoint_1d\fP< T > &\fBx_point\fP)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP< T > & \fBoperator=\fP (\fBpoint_1d\fP< T > &&\fBx_point\fP)"
.br
.ti -1c
.RI "\fBcoordinates_1d\fP< T > & \fBoperator=\fP (\fBconst\fP \fBstring\fP &\fBinit_coordinates_1d\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_position\fP (\fBconst\fP T &\fBnew_x\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBconst\fP T &\fBx_value\fP)"
.br
.ti -1c
.RI "T \fBdistance_to_origin\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay_cartesian\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBx\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
