.TH "scifir::material_vector_unit_2d< T, U >" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::material_vector_unit_2d< T, U >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmaterial_vector_unit_2d\fP (\fBconst\fP \fBmaterial_vector_unit_2d\fP< T, \fBU\fP > &x)"
.br
.ti -1c
.RI "\fBmaterial_vector_unit_2d\fP (\fBmaterial_vector_unit_2d\fP< T, \fBU\fP > &&x)"
.br
.ti -1c
.RI "\fBmaterial_vector_unit_2d\fP (\fBconst\fP T &\fBx_vector\fP, \fBconst\fP \fBcoordinates_2d\fP< \fBU\fP > &\fBx_coordinates\fP)"
.br
.ti -1c
.RI "\fBmaterial_vector_unit_2d\fP (\fBconst\fP \fBstring\fP &\fBinit_material_vector_unit_2d\fP)"
.br
.ti -1c
.RI "\fBmaterial_vector_unit_2d\fP & \fBoperator=\fP (\fBconst\fP \fBmaterial_vector_unit_2d\fP &x)"
.br
.ti -1c
.RI "\fBmaterial_vector_unit_2d\fP & \fBoperator=\fP (\fBmaterial_vector_unit_2d\fP &&x)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBvector\fP"
.br
.ti -1c
.RI "\fBcoordinates_2d\fP< \fBU\fP > \fBcoordinates\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
