.TH "scifir::cas_number" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::cas_number
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <chemistry_units\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcas_number\fP (\fBstring\fP)"
.br
.ti -1c
.RI "\fBstring\fP \fBget_value\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay\fP () \fBconst\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBstring\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB27\fP of file \fBchemistry_units\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "scifir::cas_number::cas_number (\fBstring\fP new_value)"

.PP
Definition at line \fB26\fP of file \fBchemistry_units\&.cpp\fP\&..PP
.nf
26                                            : value(new_value)
27     {
28     }
.fi

.SH "Member Function Documentation"
.PP 
.SS "\fBstring\fP scifir::cas_number::display () const"

.PP
Definition at line \fB30\fP of file \fBchemistry_units\&.cpp\fP\&..PP
.nf
31     {
32         return value;
33     }
.fi

.SS "\fBstring\fP scifir::cas_number::get_value () const\fC [inline]\fP"

.PP
Definition at line \fB32\fP of file \fBchemistry_units\&.hpp\fP\&..PP
.nf
33             {
34                 return value;
35             }
.fi

.SH "Member Data Documentation"
.PP 
.SS "\fBstring\fP scifir::cas_number::value\fC [private]\fP"

.PP
Definition at line \fB40\fP of file \fBchemistry_units\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
