.TH "scifir::lab_number< T >" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scifir::lab_number< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlab_number\fP (\fBconst\fP \fBlab_number\fP< T > &x)"
.br
.ti -1c
.RI "\fBlab_number\fP (\fBlab_number\fP< T > &&x)"
.br
.ti -1c
.RI "\fBlab_number\fP (T x, T y)"
.br
.ti -1c
.RI "\fBlab_number\fP< T > & \fBoperator=\fP (\fBconst\fP \fBlab_number\fP< T > &x)"
.br
.ti -1c
.RI "\fBlab_number\fP< T > & \fBoperator=\fP (\fBlab_number\fP< T > &&x)"
.br
.ti -1c
.RI "\fBlab_number\fP< T > \fBoperator+\fP (\fBconst\fP \fBlab_number\fP< T > &x) \fBconst\fP"
.br
.ti -1c
.RI "\fBlab_number\fP< T > \fBoperator\-\fP (\fBconst\fP \fBlab_number\fP< T > &x) \fBconst\fP"
.br
.ti -1c
.RI "\fBlab_number\fP< T > \fBoperator*\fP (\fBconst\fP \fBlab_number\fP< T > &x) \fBconst\fP"
.br
.ti -1c
.RI "\fBlab_number\fP< T > \fBoperator/\fP (\fBconst\fP \fBlab_number\fP< T > &x) \fBconst\fP"
.br
.ti -1c
.RI "\fBlab_number\fP< T > \fBoperator^\fP (\fBconst\fP \fBlab_number\fP< T > &x) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator+=\fP (\fBconst\fP \fBlab_number\fP< T > &x)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator\-=\fP (\fBconst\fP \fBlab_number\fP< T > &x)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator*=\fP (\fBconst\fP \fBlab_number\fP< T > &x)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator/=\fP (\fBconst\fP \fBlab_number\fP< T > &x)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator^=\fP (\fBconst\fP \fBlab_number\fP< T > &x)"
.br
.ti -1c
.RI "\fBstring\fP \fBdisplay\fP (\fBint\fP \fBnumber_of_decimals\fP=2) \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBvalue\fP"
.br
.ti -1c
.RI "T \fBerror_value\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
