.TH "util/types.hpp" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util/types.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBscifir\fP"
.br
.RI "The namespace scifir contains all scifir-units, excepting the string literals, which are outside\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBscifir::parse_float\fP (const string &x)"
.br
.ti -1c
.RI "int \fBscifir::parse_int\fP (const string &x)"
.br
.ti -1c
.RI "string \fBscifir::display_float\fP (const float &value, int number_of_decimals)"
.br
.ti -1c
.RI "string \fBscifir::display_double\fP (const double &value, int number_of_decimals)"
.br
.ti -1c
.RI "string \fBscifir::display_long_double\fP (const long double &value, int number_of_decimals)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
