.TH "units/unit_basic.cpp" 3 "Sat Jul 13 2024" "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units/unit_basic.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&./unit_basic\&.hpp'\fP
.br
\fC#include '\&./scalar_unit\&.hpp'\fP
.br
\fC#include '\&./dimension\&.hpp'\fP
.br
\fC#include '\&./prefix\&.hpp'\fP
.br
\fC#include '\&.\&./topology/constants\&.hpp'\fP
.br
\fC#include 'boost/algorithm/string\&.hpp'\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <cctype>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBscifir\fP"
.br
.RI "The namespace scifir contains all scifir-units, excepting the string literals, which are outside\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (length,'m')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (time_duration,'s')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (mass,'g')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (charge,'C')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (temperature,'K')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (mole,'mol')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (light,'cd')"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_CPP\fP (data,'B')"
.br
.ti -1c
.RI "scifir::length \fBoperator''_Ym\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_Zm\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_Em\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_Pm\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_Tm\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_Gm\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_Mm\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_km\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_hm\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_dam\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_m\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_dm\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_cm\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_mm\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_um\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_nm\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_pm\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_fm\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_am\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_zm\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_ym\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_s\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_ms\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_us\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_ns\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_ps\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_fs\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_as\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_zs\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_ys\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Yg\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Zg\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Eg\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Pg\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Tg\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Gg\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Mg\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_kg\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_hg\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_dag\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_g\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_dg\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_cg\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_mg\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_ug\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_ng\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_pg\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_fg\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_ag\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_zg\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_yg\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_YC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_ZC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_EC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_PC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_TC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_GC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_MC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_kC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_hC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_daC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_C\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_dC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_cC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_mC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_uC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_nC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_pC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_fC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_aC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_zC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_yC\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_YK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_ZK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_EK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_PK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_TK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_GK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_MK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_kK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_hK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_daK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_K\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_dK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_cK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_mK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_uK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_nK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_pK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_fK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_aK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_zK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_yK\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Ymol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Zmol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Emol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Pmol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Tmol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Gmol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Mmol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_kmol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_hmol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_damol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_mol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_dmol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_cmol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_mmol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_umol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_nmol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_pmol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_fmol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_amol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_zmol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_ymol\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_Ycd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_Zcd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_Ecd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_Pcd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_Tcd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_Gcd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_Mcd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_kcd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_hcd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_dacd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_cd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_dcd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_ccd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_mcd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_ucd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_ncd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_pcd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_fcd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_acd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_zcd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_ycd\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_YB\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_ZB\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_EB\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_PB\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_TB\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_GB\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_MB\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_kB\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_B\fP (unsigned long long int x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_Ym\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_Zm\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_Em\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_Pm\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_Tm\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_Gm\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_Mm\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_km\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_hm\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_dam\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_m\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_dm\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_cm\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_mm\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_um\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_nm\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_pm\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_fm\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_am\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_zm\fP (long double x)"
.br
.ti -1c
.RI "scifir::length \fBoperator''_ym\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_s\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_ms\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_us\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_ns\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_ps\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_fs\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_as\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_zs\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_ys\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Yg\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Zg\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Eg\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Pg\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Tg\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Gg\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Mg\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_kg\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_hg\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_dag\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_g\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_dg\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_cg\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_mg\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_ug\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_ng\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_pg\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_fg\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_ag\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_zg\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_yg\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_YC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_ZC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_EC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_PC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_TC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_GC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_MC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_kC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_hC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_daC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_C\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_dC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_cC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_mC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_uC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_nC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_pC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_fC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_aC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_zC\fP (long double x)"
.br
.ti -1c
.RI "scifir::charge \fBoperator''_yC\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_YK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_ZK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_EK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_PK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_TK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_GK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_MK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_kK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_hK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_daK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_K\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_dK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_cK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_mK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_uK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_nK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_pK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_fK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_aK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_zK\fP (long double x)"
.br
.ti -1c
.RI "scifir::temperature \fBoperator''_yK\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Ymol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Zmol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Emol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Pmol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Tmol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Gmol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Mmol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_kmol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_hmol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_damol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_mol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_dmol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_cmol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_mmol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_umol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_nmol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_pmol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_fmol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_amol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_zmol\fP (long double x)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_ymol\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_Ycd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_Zcd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_Ecd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_Pcd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_Tcd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_Gcd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_Mcd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_kcd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_hcd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_dacd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_cd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_dcd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_ccd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_mcd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_ucd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_ncd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_pcd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_fcd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_acd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_zcd\fP (long double x)"
.br
.ti -1c
.RI "scifir::light \fBoperator''_ycd\fP (long double x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_YB\fP (long double x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_ZB\fP (long double x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_EB\fP (long double x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_PB\fP (long double x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_TB\fP (long double x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_GB\fP (long double x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_MB\fP (long double x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_kB\fP (long double x)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_B\fP (long double x)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "scifir::charge operator''_aC (long double x)"

.PP
Definition at line 1420 of file unit_basic\&.cpp\&.
.PP
.nf
1421 {
1422     return scifir::charge(x, "aC");
1423 }
.fi
.SS "scifir::charge operator''_aC (unsigned long long int x)"

.PP
Definition at line 700 of file unit_basic\&.cpp\&.
.PP
.nf
701 {
702     return scifir::charge((long double)x, "aC");
703 }
.fi
.SS "scifir::light operator''_acd (long double x)"

.PP
Definition at line 1735 of file unit_basic\&.cpp\&.
.PP
.nf
1736 {
1737     return scifir::light(x, "acd");
1738 }
.fi
.SS "scifir::light operator''_acd (unsigned long long int x)"

.PP
Definition at line 1015 of file unit_basic\&.cpp\&.
.PP
.nf
1016 {
1017     return scifir::light((long double)x, "acd");
1018 }
.fi
.SS "\fBscifir::mass\fP operator''_ag (long double x)"

.PP
Definition at line 1315 of file unit_basic\&.cpp\&.
.PP
.nf
1316 {
1317     return scifir::mass(x, "ag");
1318 }
.fi
.SS "\fBscifir::mass\fP operator''_ag (unsigned long long int x)"

.PP
Definition at line 595 of file unit_basic\&.cpp\&.
.PP
.nf
596 {
597     return scifir::mass((long double)x, "ag");
598 }
.fi
.SS "scifir::temperature operator''_aK (long double x)"

.PP
Definition at line 1525 of file unit_basic\&.cpp\&.
.PP
.nf
1526 {
1527     return scifir::temperature(x, "aK");
1528 }
.fi
.SS "scifir::temperature operator''_aK (unsigned long long int x)"

.PP
Definition at line 805 of file unit_basic\&.cpp\&.
.PP
.nf
806 {
807     return scifir::temperature((long double)x, "aK");
808 }
.fi
.SS "scifir::length operator''_am (long double x)"

.PP
Definition at line 1165 of file unit_basic\&.cpp\&.
.PP
.nf
1166 {
1167     return scifir::length(x, "am");
1168 }
.fi
.SS "scifir::length operator''_am (unsigned long long int x)"

.PP
Definition at line 445 of file unit_basic\&.cpp\&.
.PP
.nf
446 {
447     return scifir::length((long double)x, "am");
448 }
.fi
.SS "\fBscifir::mole\fP operator''_amol (long double x)"

.PP
Definition at line 1630 of file unit_basic\&.cpp\&.
.PP
.nf
1631 {
1632     return scifir::mole(x, "amol");
1633 }
.fi
.SS "\fBscifir::mole\fP operator''_amol (unsigned long long int x)"

.PP
Definition at line 910 of file unit_basic\&.cpp\&.
.PP
.nf
911 {
912     return scifir::mole((long double)x, "amol");
913 }
.fi
.SS "\fBscifir::time_duration\fP operator''_as (long double x)"

.PP
Definition at line 1210 of file unit_basic\&.cpp\&.
.PP
.nf
1211 {
1212     return scifir::time_duration(x, "as");
1213 }
.fi
.SS "\fBscifir::time_duration\fP operator''_as (unsigned long long int x)"

.PP
Definition at line 490 of file unit_basic\&.cpp\&.
.PP
.nf
491 {
492     return scifir::time_duration((long double)x, "as");
493 }
.fi
.SS "scifir::data operator''_B (long double x)"

.PP
Definition at line 1790 of file unit_basic\&.cpp\&.
.PP
.nf
1791 {
1792     return scifir::data(x, "B");
1793 }
.fi
.SS "scifir::data operator''_B (unsigned long long int x)"

.PP
Definition at line 1070 of file unit_basic\&.cpp\&.
.PP
.nf
1071 {
1072     return scifir::data((long double)x, "B");
1073 }
.fi
.SS "scifir::charge operator''_C (long double x)"

.PP
Definition at line 1380 of file unit_basic\&.cpp\&.
.PP
.nf
1381 {
1382     return scifir::charge(x, "C");
1383 }
.fi
.SS "scifir::charge operator''_C (unsigned long long int x)"

.PP
Definition at line 660 of file unit_basic\&.cpp\&.
.PP
.nf
661 {
662     return scifir::charge((long double)x, "C");
663 }
.fi
.SS "scifir::charge operator''_cC (long double x)"

.PP
Definition at line 1390 of file unit_basic\&.cpp\&.
.PP
.nf
1391 {
1392     return scifir::charge(x, "cC");
1393 }
.fi
.SS "scifir::charge operator''_cC (unsigned long long int x)"

.PP
Definition at line 670 of file unit_basic\&.cpp\&.
.PP
.nf
671 {
672     return scifir::charge((long double)x, "cC");
673 }
.fi
.SS "scifir::light operator''_ccd (long double x)"

.PP
Definition at line 1705 of file unit_basic\&.cpp\&.
.PP
.nf
1706 {
1707     return scifir::light(x, "ccd");
1708 }
.fi
.SS "scifir::light operator''_ccd (unsigned long long int x)"

.PP
Definition at line 985 of file unit_basic\&.cpp\&.
.PP
.nf
986 {
987     return scifir::light((long double)x, "ccd");
988 }
.fi
.SS "scifir::light operator''_cd (long double x)"

.PP
Definition at line 1695 of file unit_basic\&.cpp\&.
.PP
.nf
1696 {
1697     return scifir::light(x, "cd");
1698 }
.fi
.SS "scifir::light operator''_cd (unsigned long long int x)"

.PP
Definition at line 975 of file unit_basic\&.cpp\&.
.PP
.nf
976 {
977     return scifir::light((long double)x, "cd");
978 }
.fi
.SS "\fBscifir::mass\fP operator''_cg (long double x)"

.PP
Definition at line 1285 of file unit_basic\&.cpp\&.
.PP
.nf
1286 {
1287     return scifir::mass(x, "cg");
1288 }
.fi
.SS "\fBscifir::mass\fP operator''_cg (unsigned long long int x)"

.PP
Definition at line 565 of file unit_basic\&.cpp\&.
.PP
.nf
566 {
567     return scifir::mass((long double)x, "cg");
568 }
.fi
.SS "scifir::temperature operator''_cK (long double x)"

.PP
Definition at line 1495 of file unit_basic\&.cpp\&.
.PP
.nf
1496 {
1497     return scifir::temperature(x, "cK");
1498 }
.fi
.SS "scifir::temperature operator''_cK (unsigned long long int x)"

.PP
Definition at line 775 of file unit_basic\&.cpp\&.
.PP
.nf
776 {
777     return scifir::temperature((long double)x, "cK");
778 }
.fi
.SS "scifir::length operator''_cm (long double x)"

.PP
Definition at line 1135 of file unit_basic\&.cpp\&.
.PP
.nf
1136 {
1137     return scifir::length(x, "cm");
1138 }
.fi
.SS "scifir::length operator''_cm (unsigned long long int x)"

.PP
Definition at line 415 of file unit_basic\&.cpp\&.
.PP
.nf
416 {
417     return scifir::length((long double)x, "cm");
418 }
.fi
.SS "\fBscifir::mole\fP operator''_cmol (long double x)"

.PP
Definition at line 1600 of file unit_basic\&.cpp\&.
.PP
.nf
1601 {
1602     return scifir::mole(x, "cmol");
1603 }
.fi
.SS "\fBscifir::mole\fP operator''_cmol (unsigned long long int x)"

.PP
Definition at line 880 of file unit_basic\&.cpp\&.
.PP
.nf
881 {
882     return scifir::mole((long double)x, "cmol");
883 }
.fi
.SS "scifir::charge operator''_daC (long double x)"

.PP
Definition at line 1375 of file unit_basic\&.cpp\&.
.PP
.nf
1376 {
1377     return scifir::charge(x, "daC");
1378 }
.fi
.SS "scifir::charge operator''_daC (unsigned long long int x)"

.PP
Definition at line 655 of file unit_basic\&.cpp\&.
.PP
.nf
656 {
657     return scifir::charge((long double)x, "daC");
658 }
.fi
.SS "scifir::light operator''_dacd (long double x)"

.PP
Definition at line 1690 of file unit_basic\&.cpp\&.
.PP
.nf
1691 {
1692     return scifir::light(x, "dacd");
1693 }
.fi
.SS "scifir::light operator''_dacd (unsigned long long int x)"

.PP
Definition at line 970 of file unit_basic\&.cpp\&.
.PP
.nf
971 {
972     return scifir::light((long double)x, "dacd");
973 }
.fi
.SS "\fBscifir::mass\fP operator''_dag (long double x)"

.PP
Definition at line 1270 of file unit_basic\&.cpp\&.
.PP
.nf
1271 {
1272     return scifir::mass(x, "dag");
1273 }
.fi
.SS "\fBscifir::mass\fP operator''_dag (unsigned long long int x)"

.PP
Definition at line 550 of file unit_basic\&.cpp\&.
.PP
.nf
551 {
552     return scifir::mass((long double)x, "dag");
553 }
.fi
.SS "scifir::temperature operator''_daK (long double x)"

.PP
Definition at line 1480 of file unit_basic\&.cpp\&.
.PP
.nf
1481 {
1482     return scifir::temperature(x, "daK");
1483 }
.fi
.SS "scifir::temperature operator''_daK (unsigned long long int x)"

.PP
Definition at line 760 of file unit_basic\&.cpp\&.
.PP
.nf
761 {
762     return scifir::temperature((long double)x, "daK");
763 }
.fi
.SS "scifir::length operator''_dam (long double x)"

.PP
Definition at line 1120 of file unit_basic\&.cpp\&.
.PP
.nf
1121 {
1122     return scifir::length(x, "dam");
1123 }
.fi
.SS "scifir::length operator''_dam (unsigned long long int x)"

.PP
Definition at line 400 of file unit_basic\&.cpp\&.
.PP
.nf
401 {
402     return scifir::length((long double)x, "dam");
403 }
.fi
.SS "\fBscifir::mole\fP operator''_damol (long double x)"

.PP
Definition at line 1585 of file unit_basic\&.cpp\&.
.PP
.nf
1586 {
1587     return scifir::mole(x, "damol");
1588 }
.fi
.SS "\fBscifir::mole\fP operator''_damol (unsigned long long int x)"

.PP
Definition at line 865 of file unit_basic\&.cpp\&.
.PP
.nf
866 {
867     return scifir::mole((long double)x, "damol");
868 }
.fi
.SS "scifir::charge operator''_dC (long double x)"

.PP
Definition at line 1385 of file unit_basic\&.cpp\&.
.PP
.nf
1386 {
1387     return scifir::charge(x, "dC");
1388 }
.fi
.SS "scifir::charge operator''_dC (unsigned long long int x)"

.PP
Definition at line 665 of file unit_basic\&.cpp\&.
.PP
.nf
666 {
667     return scifir::charge((long double)x, "dC");
668 }
.fi
.SS "scifir::light operator''_dcd (long double x)"

.PP
Definition at line 1700 of file unit_basic\&.cpp\&.
.PP
.nf
1701 {
1702     return scifir::light(x, "dcd");
1703 }
.fi
.SS "scifir::light operator''_dcd (unsigned long long int x)"

.PP
Definition at line 980 of file unit_basic\&.cpp\&.
.PP
.nf
981 {
982     return scifir::light((long double)x, "dcd");
983 }
.fi
.SS "\fBscifir::mass\fP operator''_dg (long double x)"

.PP
Definition at line 1280 of file unit_basic\&.cpp\&.
.PP
.nf
1281 {
1282     return scifir::mass(x, "dg");
1283 }
.fi
.SS "\fBscifir::mass\fP operator''_dg (unsigned long long int x)"

.PP
Definition at line 560 of file unit_basic\&.cpp\&.
.PP
.nf
561 {
562     return scifir::mass((long double)x, "dg");
563 }
.fi
.SS "scifir::temperature operator''_dK (long double x)"

.PP
Definition at line 1490 of file unit_basic\&.cpp\&.
.PP
.nf
1491 {
1492     return scifir::temperature(x, "dK");
1493 }
.fi
.SS "scifir::temperature operator''_dK (unsigned long long int x)"

.PP
Definition at line 770 of file unit_basic\&.cpp\&.
.PP
.nf
771 {
772     return scifir::temperature((long double)x, "dK");
773 }
.fi
.SS "scifir::length operator''_dm (long double x)"

.PP
Definition at line 1130 of file unit_basic\&.cpp\&.
.PP
.nf
1131 {
1132     return scifir::length(x, "dm");
1133 }
.fi
.SS "scifir::length operator''_dm (unsigned long long int x)"

.PP
Definition at line 410 of file unit_basic\&.cpp\&.
.PP
.nf
411 {
412     return scifir::length((long double)x, "dm");
413 }
.fi
.SS "\fBscifir::mole\fP operator''_dmol (long double x)"

.PP
Definition at line 1595 of file unit_basic\&.cpp\&.
.PP
.nf
1596 {
1597     return scifir::mole(x, "dmol");
1598 }
.fi
.SS "\fBscifir::mole\fP operator''_dmol (unsigned long long int x)"

.PP
Definition at line 875 of file unit_basic\&.cpp\&.
.PP
.nf
876 {
877     return scifir::mole((long double)x, "dmol");
878 }
.fi
.SS "scifir::data operator''_EB (long double x)"

.PP
Definition at line 1760 of file unit_basic\&.cpp\&.
.PP
.nf
1761 {
1762     return scifir::data(x, "EB");
1763 }
.fi
.SS "scifir::data operator''_EB (unsigned long long int x)"

.PP
Definition at line 1040 of file unit_basic\&.cpp\&.
.PP
.nf
1041 {
1042     return scifir::data((long double)x, "EB");
1043 }
.fi
.SS "scifir::charge operator''_EC (long double x)"

.PP
Definition at line 1340 of file unit_basic\&.cpp\&.
.PP
.nf
1341 {
1342     return scifir::charge(x, "EC");
1343 }
.fi
.SS "scifir::charge operator''_EC (unsigned long long int x)"

.PP
Definition at line 620 of file unit_basic\&.cpp\&.
.PP
.nf
621 {
622     return scifir::charge((long double)x, "EC");
623 }
.fi
.SS "scifir::light operator''_Ecd (long double x)"

.PP
Definition at line 1655 of file unit_basic\&.cpp\&.
.PP
.nf
1656 {
1657     return scifir::light(x, "Ecd");
1658 }
.fi
.SS "scifir::light operator''_Ecd (unsigned long long int x)"

.PP
Definition at line 935 of file unit_basic\&.cpp\&.
.PP
.nf
936 {
937     return scifir::light((long double)x, "Ecd");
938 }
.fi
.SS "\fBscifir::mass\fP operator''_Eg (long double x)"

.PP
Definition at line 1235 of file unit_basic\&.cpp\&.
.PP
.nf
1236 {
1237     return scifir::mass(x, "Eg");
1238 }
.fi
.SS "\fBscifir::mass\fP operator''_Eg (unsigned long long int x)"

.PP
Definition at line 515 of file unit_basic\&.cpp\&.
.PP
.nf
516 {
517     return scifir::mass((long double)x, "Eg");
518 }
.fi
.SS "scifir::temperature operator''_EK (long double x)"

.PP
Definition at line 1445 of file unit_basic\&.cpp\&.
.PP
.nf
1446 {
1447     return scifir::temperature(x, "EK");
1448 }
.fi
.SS "scifir::temperature operator''_EK (unsigned long long int x)"

.PP
Definition at line 725 of file unit_basic\&.cpp\&.
.PP
.nf
726 {
727     return scifir::temperature((long double)x, "EK");
728 }
.fi
.SS "scifir::length operator''_Em (long double x)"

.PP
Definition at line 1085 of file unit_basic\&.cpp\&.
.PP
.nf
1086 {
1087     return scifir::length(x, "Em");
1088 }
.fi
.SS "scifir::length operator''_Em (unsigned long long int x)"

.PP
Definition at line 365 of file unit_basic\&.cpp\&.
.PP
.nf
366 {
367     return scifir::length((long double)x, "Em");
368 }
.fi
.SS "\fBscifir::mole\fP operator''_Emol (long double x)"

.PP
Definition at line 1550 of file unit_basic\&.cpp\&.
.PP
.nf
1551 {
1552     return scifir::mole(x, "Emol");
1553 }
.fi
.SS "\fBscifir::mole\fP operator''_Emol (unsigned long long int x)"

.PP
Definition at line 830 of file unit_basic\&.cpp\&.
.PP
.nf
831 {
832     return scifir::mole((long double)x, "Emol");
833 }
.fi
.SS "scifir::charge operator''_fC (long double x)"

.PP
Definition at line 1415 of file unit_basic\&.cpp\&.
.PP
.nf
1416 {
1417     return scifir::charge(x, "fC");
1418 }
.fi
.SS "scifir::charge operator''_fC (unsigned long long int x)"

.PP
Definition at line 695 of file unit_basic\&.cpp\&.
.PP
.nf
696 {
697     return scifir::charge((long double)x, "fC");
698 }
.fi
.SS "scifir::light operator''_fcd (long double x)"

.PP
Definition at line 1730 of file unit_basic\&.cpp\&.
.PP
.nf
1731 {
1732     return scifir::light(x, "fcd");
1733 }
.fi
.SS "scifir::light operator''_fcd (unsigned long long int x)"

.PP
Definition at line 1010 of file unit_basic\&.cpp\&.
.PP
.nf
1011 {
1012     return scifir::light((long double)x, "fcd");
1013 }
.fi
.SS "\fBscifir::mass\fP operator''_fg (long double x)"

.PP
Definition at line 1310 of file unit_basic\&.cpp\&.
.PP
.nf
1311 {
1312     return scifir::mass(x, "fg");
1313 }
.fi
.SS "\fBscifir::mass\fP operator''_fg (unsigned long long int x)"

.PP
Definition at line 590 of file unit_basic\&.cpp\&.
.PP
.nf
591 {
592     return scifir::mass((long double)x, "fg");
593 }
.fi
.SS "scifir::temperature operator''_fK (long double x)"

.PP
Definition at line 1520 of file unit_basic\&.cpp\&.
.PP
.nf
1521 {
1522     return scifir::temperature(x, "fK");
1523 }
.fi
.SS "scifir::temperature operator''_fK (unsigned long long int x)"

.PP
Definition at line 800 of file unit_basic\&.cpp\&.
.PP
.nf
801 {
802     return scifir::temperature((long double)x, "fK");
803 }
.fi
.SS "scifir::length operator''_fm (long double x)"

.PP
Definition at line 1160 of file unit_basic\&.cpp\&.
.PP
.nf
1161 {
1162     return scifir::length(x, "fm");
1163 }
.fi
.SS "scifir::length operator''_fm (unsigned long long int x)"

.PP
Definition at line 440 of file unit_basic\&.cpp\&.
.PP
.nf
441 {
442     return scifir::length((long double)x, "fm");
443 }
.fi
.SS "\fBscifir::mole\fP operator''_fmol (long double x)"

.PP
Definition at line 1625 of file unit_basic\&.cpp\&.
.PP
.nf
1626 {
1627     return scifir::mole(x, "fmol");
1628 }
.fi
.SS "\fBscifir::mole\fP operator''_fmol (unsigned long long int x)"

.PP
Definition at line 905 of file unit_basic\&.cpp\&.
.PP
.nf
906 {
907     return scifir::mole((long double)x, "fmol");
908 }
.fi
.SS "\fBscifir::time_duration\fP operator''_fs (long double x)"

.PP
Definition at line 1205 of file unit_basic\&.cpp\&.
.PP
.nf
1206 {
1207     return scifir::time_duration(x, "fs");
1208 }
.fi
.SS "\fBscifir::time_duration\fP operator''_fs (unsigned long long int x)"

.PP
Definition at line 485 of file unit_basic\&.cpp\&.
.PP
.nf
486 {
487     return scifir::time_duration((long double)x, "fs");
488 }
.fi
.SS "\fBscifir::mass\fP operator''_g (long double x)"

.PP
Definition at line 1275 of file unit_basic\&.cpp\&.
.PP
.nf
1276 {
1277     return scifir::mass(x, "g");
1278 }
.fi
.SS "\fBscifir::mass\fP operator''_g (unsigned long long int x)"

.PP
Definition at line 555 of file unit_basic\&.cpp\&.
.PP
.nf
556 {
557     return scifir::mass((long double)x, "g");
558 }
.fi
.SS "scifir::data operator''_GB (long double x)"

.PP
Definition at line 1775 of file unit_basic\&.cpp\&.
.PP
.nf
1776 {
1777     return scifir::data(x, "GB");
1778 }
.fi
.SS "scifir::data operator''_GB (unsigned long long int x)"

.PP
Definition at line 1055 of file unit_basic\&.cpp\&.
.PP
.nf
1056 {
1057     return scifir::data((long double)x, "GB");
1058 }
.fi
.SS "scifir::charge operator''_GC (long double x)"

.PP
Definition at line 1355 of file unit_basic\&.cpp\&.
.PP
.nf
1356 {
1357     return scifir::charge(x, "GC");
1358 }
.fi
.SS "scifir::charge operator''_GC (unsigned long long int x)"

.PP
Definition at line 635 of file unit_basic\&.cpp\&.
.PP
.nf
636 {
637     return scifir::charge((long double)x, "GC");
638 }
.fi
.SS "scifir::light operator''_Gcd (long double x)"

.PP
Definition at line 1670 of file unit_basic\&.cpp\&.
.PP
.nf
1671 {
1672     return scifir::light(x, "Gcd");
1673 }
.fi
.SS "scifir::light operator''_Gcd (unsigned long long int x)"

.PP
Definition at line 950 of file unit_basic\&.cpp\&.
.PP
.nf
951 {
952     return scifir::light((long double)x, "Gcd");
953 }
.fi
.SS "\fBscifir::mass\fP operator''_Gg (long double x)"

.PP
Definition at line 1250 of file unit_basic\&.cpp\&.
.PP
.nf
1251 {
1252     return scifir::mass(x, "Gg");
1253 }
.fi
.SS "\fBscifir::mass\fP operator''_Gg (unsigned long long int x)"

.PP
Definition at line 530 of file unit_basic\&.cpp\&.
.PP
.nf
531 {
532     return scifir::mass((long double)x, "Gg");
533 }
.fi
.SS "scifir::temperature operator''_GK (long double x)"

.PP
Definition at line 1460 of file unit_basic\&.cpp\&.
.PP
.nf
1461 {
1462     return scifir::temperature(x, "GK");
1463 }
.fi
.SS "scifir::temperature operator''_GK (unsigned long long int x)"

.PP
Definition at line 740 of file unit_basic\&.cpp\&.
.PP
.nf
741 {
742     return scifir::temperature((long double)x, "GK");
743 }
.fi
.SS "scifir::length operator''_Gm (long double x)"

.PP
Definition at line 1100 of file unit_basic\&.cpp\&.
.PP
.nf
1101 {
1102     return scifir::length(x, "Gm");
1103 }
.fi
.SS "scifir::length operator''_Gm (unsigned long long int x)"

.PP
Definition at line 380 of file unit_basic\&.cpp\&.
.PP
.nf
381 {
382     return scifir::length((long double)x, "Gm");
383 }
.fi
.SS "\fBscifir::mole\fP operator''_Gmol (long double x)"

.PP
Definition at line 1565 of file unit_basic\&.cpp\&.
.PP
.nf
1566 {
1567     return scifir::mole(x, "Gmol");
1568 }
.fi
.SS "\fBscifir::mole\fP operator''_Gmol (unsigned long long int x)"

.PP
Definition at line 845 of file unit_basic\&.cpp\&.
.PP
.nf
846 {
847     return scifir::mole((long double)x, "Gmol");
848 }
.fi
.SS "scifir::charge operator''_hC (long double x)"

.PP
Definition at line 1370 of file unit_basic\&.cpp\&.
.PP
.nf
1371 {
1372     return scifir::charge(x, "hC");
1373 }
.fi
.SS "scifir::charge operator''_hC (unsigned long long int x)"

.PP
Definition at line 650 of file unit_basic\&.cpp\&.
.PP
.nf
651 {
652     return scifir::charge((long double)x, "hC");
653 }
.fi
.SS "scifir::light operator''_hcd (long double x)"

.PP
Definition at line 1685 of file unit_basic\&.cpp\&.
.PP
.nf
1686 {
1687     return scifir::light(x, "hcd");
1688 }
.fi
.SS "scifir::light operator''_hcd (unsigned long long int x)"

.PP
Definition at line 965 of file unit_basic\&.cpp\&.
.PP
.nf
966 {
967     return scifir::light((long double)x, "hcd");
968 }
.fi
.SS "\fBscifir::mass\fP operator''_hg (long double x)"

.PP
Definition at line 1265 of file unit_basic\&.cpp\&.
.PP
.nf
1266 {
1267     return scifir::mass(x, "hg");
1268 }
.fi
.SS "\fBscifir::mass\fP operator''_hg (unsigned long long int x)"

.PP
Definition at line 545 of file unit_basic\&.cpp\&.
.PP
.nf
546 {
547     return scifir::mass((long double)x, "hg");
548 }
.fi
.SS "scifir::temperature operator''_hK (long double x)"

.PP
Definition at line 1475 of file unit_basic\&.cpp\&.
.PP
.nf
1476 {
1477     return scifir::temperature(x, "hK");
1478 }
.fi
.SS "scifir::temperature operator''_hK (unsigned long long int x)"

.PP
Definition at line 755 of file unit_basic\&.cpp\&.
.PP
.nf
756 {
757     return scifir::temperature((long double)x, "hK");
758 }
.fi
.SS "scifir::length operator''_hm (long double x)"

.PP
Definition at line 1115 of file unit_basic\&.cpp\&.
.PP
.nf
1116 {
1117     return scifir::length(x, "hm");
1118 }
.fi
.SS "scifir::length operator''_hm (unsigned long long int x)"

.PP
Definition at line 395 of file unit_basic\&.cpp\&.
.PP
.nf
396 {
397     return scifir::length((long double)x, "hm");
398 }
.fi
.SS "\fBscifir::mole\fP operator''_hmol (long double x)"

.PP
Definition at line 1580 of file unit_basic\&.cpp\&.
.PP
.nf
1581 {
1582     return scifir::mole(x, "hmol");
1583 }
.fi
.SS "\fBscifir::mole\fP operator''_hmol (unsigned long long int x)"

.PP
Definition at line 860 of file unit_basic\&.cpp\&.
.PP
.nf
861 {
862     return scifir::mole((long double)x, "hmol");
863 }
.fi
.SS "scifir::temperature operator''_K (long double x)"

.PP
Definition at line 1485 of file unit_basic\&.cpp\&.
.PP
.nf
1486 {
1487     return scifir::temperature(x, "K");
1488 }
.fi
.SS "scifir::temperature operator''_K (unsigned long long int x)"

.PP
Definition at line 765 of file unit_basic\&.cpp\&.
.PP
.nf
766 {
767     return scifir::temperature((long double)x, "K");
768 }
.fi
.SS "scifir::data operator''_kB (long double x)"

.PP
Definition at line 1785 of file unit_basic\&.cpp\&.
.PP
.nf
1786 {
1787     return scifir::data(x, "kB");
1788 }
.fi
.SS "scifir::data operator''_kB (unsigned long long int x)"

.PP
Definition at line 1065 of file unit_basic\&.cpp\&.
.PP
.nf
1066 {
1067     return scifir::data((long double)x, "kB");
1068 }
.fi
.SS "scifir::charge operator''_kC (long double x)"

.PP
Definition at line 1365 of file unit_basic\&.cpp\&.
.PP
.nf
1366 {
1367     return scifir::charge(x, "kC");
1368 }
.fi
.SS "scifir::charge operator''_kC (unsigned long long int x)"

.PP
Definition at line 645 of file unit_basic\&.cpp\&.
.PP
.nf
646 {
647     return scifir::charge((long double)x, "kC");
648 }
.fi
.SS "scifir::light operator''_kcd (long double x)"

.PP
Definition at line 1680 of file unit_basic\&.cpp\&.
.PP
.nf
1681 {
1682     return scifir::light(x, "kcd");
1683 }
.fi
.SS "scifir::light operator''_kcd (unsigned long long int x)"

.PP
Definition at line 960 of file unit_basic\&.cpp\&.
.PP
.nf
961 {
962     return scifir::light((long double)x, "kcd");
963 }
.fi
.SS "\fBscifir::mass\fP operator''_kg (long double x)"

.PP
Definition at line 1260 of file unit_basic\&.cpp\&.
.PP
.nf
1261 {
1262     return scifir::mass(x, "kg");
1263 }
.fi
.SS "\fBscifir::mass\fP operator''_kg (unsigned long long int x)"

.PP
Definition at line 540 of file unit_basic\&.cpp\&.
.PP
.nf
541 {
542     return scifir::mass((long double)x, "kg");
543 }
.fi
.SS "scifir::temperature operator''_kK (long double x)"

.PP
Definition at line 1470 of file unit_basic\&.cpp\&.
.PP
.nf
1471 {
1472     return scifir::temperature(x, "kK");
1473 }
.fi
.SS "scifir::temperature operator''_kK (unsigned long long int x)"

.PP
Definition at line 750 of file unit_basic\&.cpp\&.
.PP
.nf
751 {
752     return scifir::temperature((long double)x, "kK");
753 }
.fi
.SS "scifir::length operator''_km (long double x)"

.PP
Definition at line 1110 of file unit_basic\&.cpp\&.
.PP
.nf
1111 {
1112     return scifir::length(x, "km");
1113 }
.fi
.SS "scifir::length operator''_km (unsigned long long int x)"

.PP
Definition at line 390 of file unit_basic\&.cpp\&.
.PP
.nf
391 {
392     return scifir::length((long double)x, "km");
393 }
.fi
.SS "\fBscifir::mole\fP operator''_kmol (long double x)"

.PP
Definition at line 1575 of file unit_basic\&.cpp\&.
.PP
.nf
1576 {
1577     return scifir::mole(x, "kmol");
1578 }
.fi
.SS "\fBscifir::mole\fP operator''_kmol (unsigned long long int x)"

.PP
Definition at line 855 of file unit_basic\&.cpp\&.
.PP
.nf
856 {
857     return scifir::mole((long double)x, "kmol");
858 }
.fi
.SS "scifir::length operator''_m (long double x)"

.PP
Definition at line 1125 of file unit_basic\&.cpp\&.
.PP
.nf
1126 {
1127     return scifir::length(x, "m");
1128 }
.fi
.SS "scifir::length operator''_m (unsigned long long int x)"

.PP
Definition at line 405 of file unit_basic\&.cpp\&.
.PP
.nf
406 {
407     return scifir::length((long double)x, "m");
408 }
.fi
.SS "scifir::data operator''_MB (long double x)"

.PP
Definition at line 1780 of file unit_basic\&.cpp\&.
.PP
.nf
1781 {
1782     return scifir::data(x, "MB");
1783 }
.fi
.SS "scifir::data operator''_MB (unsigned long long int x)"

.PP
Definition at line 1060 of file unit_basic\&.cpp\&.
.PP
.nf
1061 {
1062     return scifir::data((long double)x, "MB");
1063 }
.fi
.SS "scifir::charge operator''_MC (long double x)"

.PP
Definition at line 1360 of file unit_basic\&.cpp\&.
.PP
.nf
1361 {
1362     return scifir::charge(x, "MC");
1363 }
.fi
.SS "scifir::charge operator''_mC (long double x)"

.PP
Definition at line 1395 of file unit_basic\&.cpp\&.
.PP
.nf
1396 {
1397     return scifir::charge(x, "mC");
1398 }
.fi
.SS "scifir::charge operator''_MC (unsigned long long int x)"

.PP
Definition at line 640 of file unit_basic\&.cpp\&.
.PP
.nf
641 {
642     return scifir::charge((long double)x, "MC");
643 }
.fi
.SS "scifir::charge operator''_mC (unsigned long long int x)"

.PP
Definition at line 675 of file unit_basic\&.cpp\&.
.PP
.nf
676 {
677     return scifir::charge((long double)x, "mC");
678 }
.fi
.SS "scifir::light operator''_Mcd (long double x)"

.PP
Definition at line 1675 of file unit_basic\&.cpp\&.
.PP
.nf
1676 {
1677     return scifir::light(x, "Mcd");
1678 }
.fi
.SS "scifir::light operator''_mcd (long double x)"

.PP
Definition at line 1710 of file unit_basic\&.cpp\&.
.PP
.nf
1711 {
1712     return scifir::light(x, "mcd");
1713 }
.fi
.SS "scifir::light operator''_Mcd (unsigned long long int x)"

.PP
Definition at line 955 of file unit_basic\&.cpp\&.
.PP
.nf
956 {
957     return scifir::light((long double)x, "Mcd");
958 }
.fi
.SS "scifir::light operator''_mcd (unsigned long long int x)"

.PP
Definition at line 990 of file unit_basic\&.cpp\&.
.PP
.nf
991 {
992     return scifir::light((long double)x, "mcd");
993 }
.fi
.SS "\fBscifir::mass\fP operator''_Mg (long double x)"

.PP
Definition at line 1255 of file unit_basic\&.cpp\&.
.PP
.nf
1256 {
1257     return scifir::mass(x, "Mg");
1258 }
.fi
.SS "\fBscifir::mass\fP operator''_mg (long double x)"

.PP
Definition at line 1290 of file unit_basic\&.cpp\&.
.PP
.nf
1291 {
1292     return scifir::mass(x, "mg");
1293 }
.fi
.SS "\fBscifir::mass\fP operator''_Mg (unsigned long long int x)"

.PP
Definition at line 535 of file unit_basic\&.cpp\&.
.PP
.nf
536 {
537     return scifir::mass((long double)x, "Mg");
538 }
.fi
.SS "\fBscifir::mass\fP operator''_mg (unsigned long long int x)"

.PP
Definition at line 570 of file unit_basic\&.cpp\&.
.PP
.nf
571 {
572     return scifir::mass((long double)x, "mg");
573 }
.fi
.SS "scifir::temperature operator''_MK (long double x)"

.PP
Definition at line 1465 of file unit_basic\&.cpp\&.
.PP
.nf
1466 {
1467     return scifir::temperature(x, "MK");
1468 }
.fi
.SS "scifir::temperature operator''_mK (long double x)"

.PP
Definition at line 1500 of file unit_basic\&.cpp\&.
.PP
.nf
1501 {
1502     return scifir::temperature(x, "mK");
1503 }
.fi
.SS "scifir::temperature operator''_MK (unsigned long long int x)"

.PP
Definition at line 745 of file unit_basic\&.cpp\&.
.PP
.nf
746 {
747     return scifir::temperature((long double)x, "MK");
748 }
.fi
.SS "scifir::temperature operator''_mK (unsigned long long int x)"

.PP
Definition at line 780 of file unit_basic\&.cpp\&.
.PP
.nf
781 {
782     return scifir::temperature((long double)x, "mK");
783 }
.fi
.SS "scifir::length operator''_Mm (long double x)"

.PP
Definition at line 1105 of file unit_basic\&.cpp\&.
.PP
.nf
1106 {
1107     return scifir::length(x, "Mm");
1108 }
.fi
.SS "scifir::length operator''_mm (long double x)"

.PP
Definition at line 1140 of file unit_basic\&.cpp\&.
.PP
.nf
1141 {
1142     return scifir::length(x, "mm");
1143 }
.fi
.SS "scifir::length operator''_Mm (unsigned long long int x)"

.PP
Definition at line 385 of file unit_basic\&.cpp\&.
.PP
.nf
386 {
387     return scifir::length((long double)x, "Mm");
388 }
.fi
.SS "scifir::length operator''_mm (unsigned long long int x)"

.PP
Definition at line 420 of file unit_basic\&.cpp\&.
.PP
.nf
421 {
422     return scifir::length((long double)x, "mm");
423 }
.fi
.SS "\fBscifir::mole\fP operator''_Mmol (long double x)"

.PP
Definition at line 1570 of file unit_basic\&.cpp\&.
.PP
.nf
1571 {
1572     return scifir::mole(x, "Mmol");
1573 }
.fi
.SS "\fBscifir::mole\fP operator''_mmol (long double x)"

.PP
Definition at line 1605 of file unit_basic\&.cpp\&.
.PP
.nf
1606 {
1607     return scifir::mole(x, "mmol");
1608 }
.fi
.SS "\fBscifir::mole\fP operator''_Mmol (unsigned long long int x)"

.PP
Definition at line 850 of file unit_basic\&.cpp\&.
.PP
.nf
851 {
852     return scifir::mole((long double)x, "Mmol");
853 }
.fi
.SS "\fBscifir::mole\fP operator''_mmol (unsigned long long int x)"

.PP
Definition at line 885 of file unit_basic\&.cpp\&.
.PP
.nf
886 {
887     return scifir::mole((long double)x, "mmol");
888 }
.fi
.SS "\fBscifir::mole\fP operator''_mol (long double x)"

.PP
Definition at line 1590 of file unit_basic\&.cpp\&.
.PP
.nf
1591 {
1592     return scifir::mole(x, "mol");
1593 }
.fi
.SS "\fBscifir::mole\fP operator''_mol (unsigned long long int x)"

.PP
Definition at line 870 of file unit_basic\&.cpp\&.
.PP
.nf
871 {
872     return scifir::mole((long double)x, "mol");
873 }
.fi
.SS "\fBscifir::time_duration\fP operator''_ms (long double x)"

.PP
Definition at line 1185 of file unit_basic\&.cpp\&.
.PP
.nf
1186 {
1187     return scifir::time_duration(x, "ms");
1188 }
.fi
.SS "\fBscifir::time_duration\fP operator''_ms (unsigned long long int x)"

.PP
Definition at line 465 of file unit_basic\&.cpp\&.
.PP
.nf
466 {
467     return scifir::time_duration((long double)x, "ms");
468 }
.fi
.SS "scifir::charge operator''_nC (long double x)"

.PP
Definition at line 1405 of file unit_basic\&.cpp\&.
.PP
.nf
1406 {
1407     return scifir::charge(x, "nC");
1408 }
.fi
.SS "scifir::charge operator''_nC (unsigned long long int x)"

.PP
Definition at line 685 of file unit_basic\&.cpp\&.
.PP
.nf
686 {
687     return scifir::charge((long double)x, "nC");
688 }
.fi
.SS "scifir::light operator''_ncd (long double x)"

.PP
Definition at line 1720 of file unit_basic\&.cpp\&.
.PP
.nf
1721 {
1722     return scifir::light(x, "ncd");
1723 }
.fi
.SS "scifir::light operator''_ncd (unsigned long long int x)"

.PP
Definition at line 1000 of file unit_basic\&.cpp\&.
.PP
.nf
1001 {
1002     return scifir::light((long double)x, "ncd");
1003 }
.fi
.SS "\fBscifir::mass\fP operator''_ng (long double x)"

.PP
Definition at line 1300 of file unit_basic\&.cpp\&.
.PP
.nf
1301 {
1302     return scifir::mass(x, "ng");
1303 }
.fi
.SS "\fBscifir::mass\fP operator''_ng (unsigned long long int x)"

.PP
Definition at line 580 of file unit_basic\&.cpp\&.
.PP
.nf
581 {
582     return scifir::mass((long double)x, "ng");
583 }
.fi
.SS "scifir::temperature operator''_nK (long double x)"

.PP
Definition at line 1510 of file unit_basic\&.cpp\&.
.PP
.nf
1511 {
1512     return scifir::temperature(x, "nK");
1513 }
.fi
.SS "scifir::temperature operator''_nK (unsigned long long int x)"

.PP
Definition at line 790 of file unit_basic\&.cpp\&.
.PP
.nf
791 {
792     return scifir::temperature((long double)x, "nK");
793 }
.fi
.SS "scifir::length operator''_nm (long double x)"

.PP
Definition at line 1150 of file unit_basic\&.cpp\&.
.PP
.nf
1151 {
1152     return scifir::length(x, "nm");
1153 }
.fi
.SS "scifir::length operator''_nm (unsigned long long int x)"

.PP
Definition at line 430 of file unit_basic\&.cpp\&.
.PP
.nf
431 {
432     return scifir::length((long double)x, "nm");
433 }
.fi
.SS "\fBscifir::mole\fP operator''_nmol (long double x)"

.PP
Definition at line 1615 of file unit_basic\&.cpp\&.
.PP
.nf
1616 {
1617     return scifir::mole(x, "nmol");
1618 }
.fi
.SS "\fBscifir::mole\fP operator''_nmol (unsigned long long int x)"

.PP
Definition at line 895 of file unit_basic\&.cpp\&.
.PP
.nf
896 {
897     return scifir::mole((long double)x, "nmol");
898 }
.fi
.SS "\fBscifir::time_duration\fP operator''_ns (long double x)"

.PP
Definition at line 1195 of file unit_basic\&.cpp\&.
.PP
.nf
1196 {
1197     return scifir::time_duration(x, "ns");
1198 }
.fi
.SS "\fBscifir::time_duration\fP operator''_ns (unsigned long long int x)"

.PP
Definition at line 475 of file unit_basic\&.cpp\&.
.PP
.nf
476 {
477     return scifir::time_duration((long double)x, "ns");
478 }
.fi
.SS "scifir::data operator''_PB (long double x)"

.PP
Definition at line 1765 of file unit_basic\&.cpp\&.
.PP
.nf
1766 {
1767     return scifir::data(x, "PB");
1768 }
.fi
.SS "scifir::data operator''_PB (unsigned long long int x)"

.PP
Definition at line 1045 of file unit_basic\&.cpp\&.
.PP
.nf
1046 {
1047     return scifir::data((long double)x, "PB");
1048 }
.fi
.SS "scifir::charge operator''_PC (long double x)"

.PP
Definition at line 1345 of file unit_basic\&.cpp\&.
.PP
.nf
1346 {
1347     return scifir::charge(x, "PC");
1348 }
.fi
.SS "scifir::charge operator''_pC (long double x)"

.PP
Definition at line 1410 of file unit_basic\&.cpp\&.
.PP
.nf
1411 {
1412     return scifir::charge(x, "pC");
1413 }
.fi
.SS "scifir::charge operator''_PC (unsigned long long int x)"

.PP
Definition at line 625 of file unit_basic\&.cpp\&.
.PP
.nf
626 {
627     return scifir::charge((long double)x, "PC");
628 }
.fi
.SS "scifir::charge operator''_pC (unsigned long long int x)"

.PP
Definition at line 690 of file unit_basic\&.cpp\&.
.PP
.nf
691 {
692     return scifir::charge((long double)x, "pC");
693 }
.fi
.SS "scifir::light operator''_Pcd (long double x)"

.PP
Definition at line 1660 of file unit_basic\&.cpp\&.
.PP
.nf
1661 {
1662     return scifir::light(x, "Pcd");
1663 }
.fi
.SS "scifir::light operator''_pcd (long double x)"

.PP
Definition at line 1725 of file unit_basic\&.cpp\&.
.PP
.nf
1726 {
1727     return scifir::light(x, "pcd");
1728 }
.fi
.SS "scifir::light operator''_Pcd (unsigned long long int x)"

.PP
Definition at line 940 of file unit_basic\&.cpp\&.
.PP
.nf
941 {
942     return scifir::light((long double)x, "Pcd");
943 }
.fi
.SS "scifir::light operator''_pcd (unsigned long long int x)"

.PP
Definition at line 1005 of file unit_basic\&.cpp\&.
.PP
.nf
1006 {
1007     return scifir::light((long double)x, "pcd");
1008 }
.fi
.SS "\fBscifir::mass\fP operator''_Pg (long double x)"

.PP
Definition at line 1240 of file unit_basic\&.cpp\&.
.PP
.nf
1241 {
1242     return scifir::mass(x, "Pg");
1243 }
.fi
.SS "\fBscifir::mass\fP operator''_pg (long double x)"

.PP
Definition at line 1305 of file unit_basic\&.cpp\&.
.PP
.nf
1306 {
1307     return scifir::mass(x, "pg");
1308 }
.fi
.SS "\fBscifir::mass\fP operator''_Pg (unsigned long long int x)"

.PP
Definition at line 520 of file unit_basic\&.cpp\&.
.PP
.nf
521 {
522     return scifir::mass((long double)x, "Pg");
523 }
.fi
.SS "\fBscifir::mass\fP operator''_pg (unsigned long long int x)"

.PP
Definition at line 585 of file unit_basic\&.cpp\&.
.PP
.nf
586 {
587     return scifir::mass((long double)x, "pg");
588 }
.fi
.SS "scifir::temperature operator''_PK (long double x)"

.PP
Definition at line 1450 of file unit_basic\&.cpp\&.
.PP
.nf
1451 {
1452     return scifir::temperature(x, "PK");
1453 }
.fi
.SS "scifir::temperature operator''_pK (long double x)"

.PP
Definition at line 1515 of file unit_basic\&.cpp\&.
.PP
.nf
1516 {
1517     return scifir::temperature(x, "pK");
1518 }
.fi
.SS "scifir::temperature operator''_PK (unsigned long long int x)"

.PP
Definition at line 730 of file unit_basic\&.cpp\&.
.PP
.nf
731 {
732     return scifir::temperature((long double)x, "PK");
733 }
.fi
.SS "scifir::temperature operator''_pK (unsigned long long int x)"

.PP
Definition at line 795 of file unit_basic\&.cpp\&.
.PP
.nf
796 {
797     return scifir::temperature((long double)x, "pK");
798 }
.fi
.SS "scifir::length operator''_Pm (long double x)"

.PP
Definition at line 1090 of file unit_basic\&.cpp\&.
.PP
.nf
1091 {
1092     return scifir::length(x, "Pm");
1093 }
.fi
.SS "scifir::length operator''_pm (long double x)"

.PP
Definition at line 1155 of file unit_basic\&.cpp\&.
.PP
.nf
1156 {
1157     return scifir::length(x, "pm");
1158 }
.fi
.SS "scifir::length operator''_Pm (unsigned long long int x)"

.PP
Definition at line 370 of file unit_basic\&.cpp\&.
.PP
.nf
371 {
372     return scifir::length((long double)x, "Pm");
373 }
.fi
.SS "scifir::length operator''_pm (unsigned long long int x)"

.PP
Definition at line 435 of file unit_basic\&.cpp\&.
.PP
.nf
436 {
437     return scifir::length((long double)x, "pm");
438 }
.fi
.SS "\fBscifir::mole\fP operator''_Pmol (long double x)"

.PP
Definition at line 1555 of file unit_basic\&.cpp\&.
.PP
.nf
1556 {
1557     return scifir::mole(x, "Pmol");
1558 }
.fi
.SS "\fBscifir::mole\fP operator''_pmol (long double x)"

.PP
Definition at line 1620 of file unit_basic\&.cpp\&.
.PP
.nf
1621 {
1622     return scifir::mole(x, "pmol");
1623 }
.fi
.SS "\fBscifir::mole\fP operator''_Pmol (unsigned long long int x)"

.PP
Definition at line 835 of file unit_basic\&.cpp\&.
.PP
.nf
836 {
837     return scifir::mole((long double)x, "Pmol");
838 }
.fi
.SS "\fBscifir::mole\fP operator''_pmol (unsigned long long int x)"

.PP
Definition at line 900 of file unit_basic\&.cpp\&.
.PP
.nf
901 {
902     return scifir::mole((long double)x, "pmol");
903 }
.fi
.SS "\fBscifir::time_duration\fP operator''_ps (long double x)"

.PP
Definition at line 1200 of file unit_basic\&.cpp\&.
.PP
.nf
1201 {
1202     return scifir::time_duration(x, "ps");
1203 }
.fi
.SS "\fBscifir::time_duration\fP operator''_ps (unsigned long long int x)"

.PP
Definition at line 480 of file unit_basic\&.cpp\&.
.PP
.nf
481 {
482     return scifir::time_duration((long double)x, "ps");
483 }
.fi
.SS "\fBscifir::time_duration\fP operator''_s (long double x)"

.PP
Definition at line 1180 of file unit_basic\&.cpp\&.
.PP
.nf
1181 {
1182     return scifir::time_duration(x, "s");
1183 }
.fi
.SS "\fBscifir::time_duration\fP operator''_s (unsigned long long int x)"

.PP
Definition at line 460 of file unit_basic\&.cpp\&.
.PP
.nf
461 {
462     return scifir::time_duration((long double)x, "s");
463 }
.fi
.SS "scifir::data operator''_TB (long double x)"

.PP
Definition at line 1770 of file unit_basic\&.cpp\&.
.PP
.nf
1771 {
1772     return scifir::data(x, "TB");
1773 }
.fi
.SS "scifir::data operator''_TB (unsigned long long int x)"

.PP
Definition at line 1050 of file unit_basic\&.cpp\&.
.PP
.nf
1051 {
1052     return scifir::data((long double)x, "TB");
1053 }
.fi
.SS "scifir::charge operator''_TC (long double x)"

.PP
Definition at line 1350 of file unit_basic\&.cpp\&.
.PP
.nf
1351 {
1352     return scifir::charge(x, "TC");
1353 }
.fi
.SS "scifir::charge operator''_TC (unsigned long long int x)"

.PP
Definition at line 630 of file unit_basic\&.cpp\&.
.PP
.nf
631 {
632     return scifir::charge((long double)x, "TC");
633 }
.fi
.SS "scifir::light operator''_Tcd (long double x)"

.PP
Definition at line 1665 of file unit_basic\&.cpp\&.
.PP
.nf
1666 {
1667     return scifir::light(x, "Tcd");
1668 }
.fi
.SS "scifir::light operator''_Tcd (unsigned long long int x)"

.PP
Definition at line 945 of file unit_basic\&.cpp\&.
.PP
.nf
946 {
947     return scifir::light((long double)x, "Tcd");
948 }
.fi
.SS "\fBscifir::mass\fP operator''_Tg (long double x)"

.PP
Definition at line 1245 of file unit_basic\&.cpp\&.
.PP
.nf
1246 {
1247     return scifir::mass(x, "Tg");
1248 }
.fi
.SS "\fBscifir::mass\fP operator''_Tg (unsigned long long int x)"

.PP
Definition at line 525 of file unit_basic\&.cpp\&.
.PP
.nf
526 {
527     return scifir::mass((long double)x, "Tg");
528 }
.fi
.SS "scifir::temperature operator''_TK (long double x)"

.PP
Definition at line 1455 of file unit_basic\&.cpp\&.
.PP
.nf
1456 {
1457     return scifir::temperature(x, "TK");
1458 }
.fi
.SS "scifir::temperature operator''_TK (unsigned long long int x)"

.PP
Definition at line 735 of file unit_basic\&.cpp\&.
.PP
.nf
736 {
737     return scifir::temperature((long double)x, "TK");
738 }
.fi
.SS "scifir::length operator''_Tm (long double x)"

.PP
Definition at line 1095 of file unit_basic\&.cpp\&.
.PP
.nf
1096 {
1097     return scifir::length(x, "Tm");
1098 }
.fi
.SS "scifir::length operator''_Tm (unsigned long long int x)"

.PP
Definition at line 375 of file unit_basic\&.cpp\&.
.PP
.nf
376 {
377     return scifir::length((long double)x, "Tm");
378 }
.fi
.SS "\fBscifir::mole\fP operator''_Tmol (long double x)"

.PP
Definition at line 1560 of file unit_basic\&.cpp\&.
.PP
.nf
1561 {
1562     return scifir::mole(x, "Tmol");
1563 }
.fi
.SS "\fBscifir::mole\fP operator''_Tmol (unsigned long long int x)"

.PP
Definition at line 840 of file unit_basic\&.cpp\&.
.PP
.nf
841 {
842     return scifir::mole((long double)x, "Tmol");
843 }
.fi
.SS "scifir::charge operator''_uC (long double x)"

.PP
Definition at line 1400 of file unit_basic\&.cpp\&.
.PP
.nf
1401 {
1402     return scifir::charge(x, "uC");
1403 }
.fi
.SS "scifir::charge operator''_uC (unsigned long long int x)"

.PP
Definition at line 680 of file unit_basic\&.cpp\&.
.PP
.nf
681 {
682     return scifir::charge((long double)x, "uC");
683 }
.fi
.SS "scifir::light operator''_ucd (long double x)"

.PP
Definition at line 1715 of file unit_basic\&.cpp\&.
.PP
.nf
1716 {
1717     return scifir::light(x, "ucd");
1718 }
.fi
.SS "scifir::light operator''_ucd (unsigned long long int x)"

.PP
Definition at line 995 of file unit_basic\&.cpp\&.
.PP
.nf
996 {
997     return scifir::light((long double)x, "ucd");
998 }
.fi
.SS "\fBscifir::mass\fP operator''_ug (long double x)"

.PP
Definition at line 1295 of file unit_basic\&.cpp\&.
.PP
.nf
1296 {
1297     return scifir::mass(x, "ug");
1298 }
.fi
.SS "\fBscifir::mass\fP operator''_ug (unsigned long long int x)"

.PP
Definition at line 575 of file unit_basic\&.cpp\&.
.PP
.nf
576 {
577     return scifir::mass((long double)x, "ug");
578 }
.fi
.SS "scifir::temperature operator''_uK (long double x)"

.PP
Definition at line 1505 of file unit_basic\&.cpp\&.
.PP
.nf
1506 {
1507     return scifir::temperature(x, "uK");
1508 }
.fi
.SS "scifir::temperature operator''_uK (unsigned long long int x)"

.PP
Definition at line 785 of file unit_basic\&.cpp\&.
.PP
.nf
786 {
787     return scifir::temperature((long double)x, "uK");
788 }
.fi
.SS "scifir::length operator''_um (long double x)"

.PP
Definition at line 1145 of file unit_basic\&.cpp\&.
.PP
.nf
1146 {
1147     return scifir::length(x, "um");
1148 }
.fi
.SS "scifir::length operator''_um (unsigned long long int x)"

.PP
Definition at line 425 of file unit_basic\&.cpp\&.
.PP
.nf
426 {
427     return scifir::length((long double)x, "um");
428 }
.fi
.SS "\fBscifir::mole\fP operator''_umol (long double x)"

.PP
Definition at line 1610 of file unit_basic\&.cpp\&.
.PP
.nf
1611 {
1612     return scifir::mole(x, "umol");
1613 }
.fi
.SS "\fBscifir::mole\fP operator''_umol (unsigned long long int x)"

.PP
Definition at line 890 of file unit_basic\&.cpp\&.
.PP
.nf
891 {
892     return scifir::mole((long double)x, "umol");
893 }
.fi
.SS "\fBscifir::time_duration\fP operator''_us (long double x)"

.PP
Definition at line 1190 of file unit_basic\&.cpp\&.
.PP
.nf
1191 {
1192     return scifir::time_duration(x, "us");
1193 }
.fi
.SS "\fBscifir::time_duration\fP operator''_us (unsigned long long int x)"

.PP
Definition at line 470 of file unit_basic\&.cpp\&.
.PP
.nf
471 {
472     return scifir::time_duration((long double)x, "us");
473 }
.fi
.SS "scifir::data operator''_YB (long double x)"

.PP
Definition at line 1750 of file unit_basic\&.cpp\&.
.PP
.nf
1751 {
1752     return scifir::data(x, "YB");
1753 }
.fi
.SS "scifir::data operator''_YB (unsigned long long int x)"

.PP
Definition at line 1030 of file unit_basic\&.cpp\&.
.PP
.nf
1031 {
1032     return scifir::data((long double)x, "YB");
1033 }
.fi
.SS "scifir::charge operator''_YC (long double x)"

.PP
Definition at line 1330 of file unit_basic\&.cpp\&.
.PP
.nf
1331 {
1332     return scifir::charge(x, "YC");
1333 }
.fi
.SS "scifir::charge operator''_yC (long double x)"

.PP
Definition at line 1430 of file unit_basic\&.cpp\&.
.PP
.nf
1431 {
1432     return scifir::charge(x, "yC");
1433 }
.fi
.SS "scifir::charge operator''_YC (unsigned long long int x)"

.PP
Definition at line 610 of file unit_basic\&.cpp\&.
.PP
.nf
611 {
612     return scifir::charge((long double)x, "YC");
613 }
.fi
.SS "scifir::charge operator''_yC (unsigned long long int x)"

.PP
Definition at line 710 of file unit_basic\&.cpp\&.
.PP
.nf
711 {
712     return scifir::charge((long double)x, "yC");
713 }
.fi
.SS "scifir::light operator''_Ycd (long double x)"

.PP
Definition at line 1645 of file unit_basic\&.cpp\&.
.PP
.nf
1646 {
1647     return scifir::light(x, "Ycd");
1648 }
.fi
.SS "scifir::light operator''_ycd (long double x)"

.PP
Definition at line 1745 of file unit_basic\&.cpp\&.
.PP
.nf
1746 {
1747     return scifir::light(x, "ycd");
1748 }
.fi
.SS "scifir::light operator''_Ycd (unsigned long long int x)"

.PP
Definition at line 925 of file unit_basic\&.cpp\&.
.PP
.nf
926 {
927     return scifir::light((long double)x, "Ycd");
928 }
.fi
.SS "scifir::light operator''_ycd (unsigned long long int x)"

.PP
Definition at line 1025 of file unit_basic\&.cpp\&.
.PP
.nf
1026 {
1027     return scifir::light((long double)x, "ycd");
1028 }
.fi
.SS "\fBscifir::mass\fP operator''_Yg (long double x)"

.PP
Definition at line 1225 of file unit_basic\&.cpp\&.
.PP
.nf
1226 {
1227     return scifir::mass(x, "Yg");
1228 }
.fi
.SS "\fBscifir::mass\fP operator''_yg (long double x)"

.PP
Definition at line 1325 of file unit_basic\&.cpp\&.
.PP
.nf
1326 {
1327     return scifir::mass(x, "yg");
1328 }
.fi
.SS "\fBscifir::mass\fP operator''_Yg (unsigned long long int x)"

.PP
Definition at line 505 of file unit_basic\&.cpp\&.
.PP
.nf
506 {
507     return scifir::mass((long double)x, "Yg");
508 }
.fi
.SS "\fBscifir::mass\fP operator''_yg (unsigned long long int x)"

.PP
Definition at line 605 of file unit_basic\&.cpp\&.
.PP
.nf
606 {
607     return scifir::mass((long double)x, "yg");
608 }
.fi
.SS "scifir::temperature operator''_YK (long double x)"

.PP
Definition at line 1435 of file unit_basic\&.cpp\&.
.PP
.nf
1436 {
1437     return scifir::temperature(x, "YK");
1438 }
.fi
.SS "scifir::temperature operator''_yK (long double x)"

.PP
Definition at line 1535 of file unit_basic\&.cpp\&.
.PP
.nf
1536 {
1537     return scifir::temperature(x, "yK");
1538 }
.fi
.SS "scifir::temperature operator''_YK (unsigned long long int x)"

.PP
Definition at line 715 of file unit_basic\&.cpp\&.
.PP
.nf
716 {
717     return scifir::temperature((long double)x, "YK");
718 }
.fi
.SS "scifir::temperature operator''_yK (unsigned long long int x)"

.PP
Definition at line 815 of file unit_basic\&.cpp\&.
.PP
.nf
816 {
817     return scifir::temperature((long double)x, "yK");
818 }
.fi
.SS "scifir::length operator''_Ym (long double x)"

.PP
Definition at line 1075 of file unit_basic\&.cpp\&.
.PP
.nf
1076 {
1077     return scifir::length(x, "Ym");
1078 }
.fi
.SS "scifir::length operator''_ym (long double x)"

.PP
Definition at line 1175 of file unit_basic\&.cpp\&.
.PP
.nf
1176 {
1177     return scifir::length(x, "ym");
1178 }
.fi
.SS "scifir::length operator''_Ym (unsigned long long int x)"

.PP
Definition at line 355 of file unit_basic\&.cpp\&.
.PP
.nf
356 {
357     return scifir::length((long double)x, "Ym");
358 }
.fi
.SS "scifir::length operator''_ym (unsigned long long int x)"

.PP
Definition at line 455 of file unit_basic\&.cpp\&.
.PP
.nf
456 {
457     return scifir::length((long double)x, "ym");
458 }
.fi
.SS "\fBscifir::mole\fP operator''_Ymol (long double x)"

.PP
Definition at line 1540 of file unit_basic\&.cpp\&.
.PP
.nf
1541 {
1542     return scifir::mole(x, "Ymol");
1543 }
.fi
.SS "\fBscifir::mole\fP operator''_ymol (long double x)"

.PP
Definition at line 1640 of file unit_basic\&.cpp\&.
.PP
.nf
1641 {
1642     return scifir::mole(x, "ymol");
1643 }
.fi
.SS "\fBscifir::mole\fP operator''_Ymol (unsigned long long int x)"

.PP
Definition at line 820 of file unit_basic\&.cpp\&.
.PP
.nf
821 {
822     return scifir::mole((long double)x, "Ymol");
823 }
.fi
.SS "\fBscifir::mole\fP operator''_ymol (unsigned long long int x)"

.PP
Definition at line 920 of file unit_basic\&.cpp\&.
.PP
.nf
921 {
922     return scifir::mole((long double)x, "ymol");
923 }
.fi
.SS "\fBscifir::time_duration\fP operator''_ys (long double x)"

.PP
Definition at line 1220 of file unit_basic\&.cpp\&.
.PP
.nf
1221 {
1222     return scifir::time_duration(x, "ys");
1223 }
.fi
.SS "\fBscifir::time_duration\fP operator''_ys (unsigned long long int x)"

.PP
Definition at line 500 of file unit_basic\&.cpp\&.
.PP
.nf
501 {
502     return scifir::time_duration((long double)x, "ys");
503 }
.fi
.SS "scifir::data operator''_ZB (long double x)"

.PP
Definition at line 1755 of file unit_basic\&.cpp\&.
.PP
.nf
1756 {
1757     return scifir::data(x, "ZB");
1758 }
.fi
.SS "scifir::data operator''_ZB (unsigned long long int x)"

.PP
Definition at line 1035 of file unit_basic\&.cpp\&.
.PP
.nf
1036 {
1037     return scifir::data((long double)x, "ZB");
1038 }
.fi
.SS "scifir::charge operator''_ZC (long double x)"

.PP
Definition at line 1335 of file unit_basic\&.cpp\&.
.PP
.nf
1336 {
1337     return scifir::charge(x, "ZC");
1338 }
.fi
.SS "scifir::charge operator''_zC (long double x)"

.PP
Definition at line 1425 of file unit_basic\&.cpp\&.
.PP
.nf
1426 {
1427     return scifir::charge(x, "zC");
1428 }
.fi
.SS "scifir::charge operator''_ZC (unsigned long long int x)"

.PP
Definition at line 615 of file unit_basic\&.cpp\&.
.PP
.nf
616 {
617     return scifir::charge((long double)x, "ZC");
618 }
.fi
.SS "scifir::charge operator''_zC (unsigned long long int x)"

.PP
Definition at line 705 of file unit_basic\&.cpp\&.
.PP
.nf
706 {
707     return scifir::charge((long double)x, "zC");
708 }
.fi
.SS "scifir::light operator''_Zcd (long double x)"

.PP
Definition at line 1650 of file unit_basic\&.cpp\&.
.PP
.nf
1651 {
1652     return scifir::light(x, "Zcd");
1653 }
.fi
.SS "scifir::light operator''_zcd (long double x)"

.PP
Definition at line 1740 of file unit_basic\&.cpp\&.
.PP
.nf
1741 {
1742     return scifir::light(x, "zcd");
1743 }
.fi
.SS "scifir::light operator''_Zcd (unsigned long long int x)"

.PP
Definition at line 930 of file unit_basic\&.cpp\&.
.PP
.nf
931 {
932     return scifir::light((long double)x, "Zcd");
933 }
.fi
.SS "scifir::light operator''_zcd (unsigned long long int x)"

.PP
Definition at line 1020 of file unit_basic\&.cpp\&.
.PP
.nf
1021 {
1022     return scifir::light((long double)x, "zcd");
1023 }
.fi
.SS "\fBscifir::mass\fP operator''_Zg (long double x)"

.PP
Definition at line 1230 of file unit_basic\&.cpp\&.
.PP
.nf
1231 {
1232     return scifir::mass(x, "Zg");
1233 }
.fi
.SS "\fBscifir::mass\fP operator''_zg (long double x)"

.PP
Definition at line 1320 of file unit_basic\&.cpp\&.
.PP
.nf
1321 {
1322     return scifir::mass(x, "zg");
1323 }
.fi
.SS "\fBscifir::mass\fP operator''_Zg (unsigned long long int x)"

.PP
Definition at line 510 of file unit_basic\&.cpp\&.
.PP
.nf
511 {
512     return scifir::mass((long double)x, "Zg");
513 }
.fi
.SS "\fBscifir::mass\fP operator''_zg (unsigned long long int x)"

.PP
Definition at line 600 of file unit_basic\&.cpp\&.
.PP
.nf
601 {
602     return scifir::mass((long double)x, "zg");
603 }
.fi
.SS "scifir::temperature operator''_ZK (long double x)"

.PP
Definition at line 1440 of file unit_basic\&.cpp\&.
.PP
.nf
1441 {
1442     return scifir::temperature(x, "ZK");
1443 }
.fi
.SS "scifir::temperature operator''_zK (long double x)"

.PP
Definition at line 1530 of file unit_basic\&.cpp\&.
.PP
.nf
1531 {
1532     return scifir::temperature(x, "zK");
1533 }
.fi
.SS "scifir::temperature operator''_ZK (unsigned long long int x)"

.PP
Definition at line 720 of file unit_basic\&.cpp\&.
.PP
.nf
721 {
722     return scifir::temperature((long double)x, "ZK");
723 }
.fi
.SS "scifir::temperature operator''_zK (unsigned long long int x)"

.PP
Definition at line 810 of file unit_basic\&.cpp\&.
.PP
.nf
811 {
812     return scifir::temperature((long double)x, "zK");
813 }
.fi
.SS "scifir::length operator''_Zm (long double x)"

.PP
Definition at line 1080 of file unit_basic\&.cpp\&.
.PP
.nf
1081 {
1082     return scifir::length(x, "Zm");
1083 }
.fi
.SS "scifir::length operator''_zm (long double x)"

.PP
Definition at line 1170 of file unit_basic\&.cpp\&.
.PP
.nf
1171 {
1172     return scifir::length(x, "zm");
1173 }
.fi
.SS "scifir::length operator''_Zm (unsigned long long int x)"

.PP
Definition at line 360 of file unit_basic\&.cpp\&.
.PP
.nf
361 {
362     return scifir::length((long double)x, "Zm");
363 }
.fi
.SS "scifir::length operator''_zm (unsigned long long int x)"

.PP
Definition at line 450 of file unit_basic\&.cpp\&.
.PP
.nf
451 {
452     return scifir::length((long double)x, "zm");
453 }
.fi
.SS "\fBscifir::mole\fP operator''_Zmol (long double x)"

.PP
Definition at line 1545 of file unit_basic\&.cpp\&.
.PP
.nf
1546 {
1547     return scifir::mole(x, "Zmol");
1548 }
.fi
.SS "\fBscifir::mole\fP operator''_zmol (long double x)"

.PP
Definition at line 1635 of file unit_basic\&.cpp\&.
.PP
.nf
1636 {
1637     return scifir::mole(x, "zmol");
1638 }
.fi
.SS "\fBscifir::mole\fP operator''_Zmol (unsigned long long int x)"

.PP
Definition at line 825 of file unit_basic\&.cpp\&.
.PP
.nf
826 {
827     return scifir::mole((long double)x, "Zmol");
828 }
.fi
.SS "\fBscifir::mole\fP operator''_zmol (unsigned long long int x)"

.PP
Definition at line 915 of file unit_basic\&.cpp\&.
.PP
.nf
916 {
917     return scifir::mole((long double)x, "zmol");
918 }
.fi
.SS "\fBscifir::time_duration\fP operator''_zs (long double x)"

.PP
Definition at line 1215 of file unit_basic\&.cpp\&.
.PP
.nf
1216 {
1217     return scifir::time_duration(x, "zs");
1218 }
.fi
.SS "\fBscifir::time_duration\fP operator''_zs (unsigned long long int x)"

.PP
Definition at line 495 of file unit_basic\&.cpp\&.
.PP
.nf
496 {
497     return scifir::time_duration((long double)x, "zs");
498 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
