.TH "units/unit_basic.hpp" 3 "Version 2.0.0" "scifir-units" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units/unit_basic.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./units/prefix\&.hpp'\fP
.br
\fC#include '\&.\&./units/scalar_unit\&.hpp'\fP
.br
\fC#include '\&.\&./special_units/percentage\&.hpp'\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBscifir\fP"
.br
.RI "The namespace scifir contains all scifir-units, excepting the string literals, which are outside\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBlength\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP_BEGIN\fP (\fBtime_duration\fP)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP (\fBconst\fP \fBstring\fP &\fBinit_time\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBscifir::get_years\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBint\fP \fBscifir::get_months\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBint\fP \fBscifir::get_weeks\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBint\fP \fBscifir::get_days\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBint\fP \fBscifir::get_hours\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBint\fP \fBscifir::get_minutes\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBint\fP \fBscifir::get_seconds\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBscifir::get_finish_date\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBscifir::display_as_time\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBscifir::display_years\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBscifir::display_months\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBscifir::display_weeks\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBscifir::display_days\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBscifir::display_hours\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBscifir::display_minutes\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBscifir::display_seconds\fP () \fBconst\fP"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT1\fP , \fBtypename\fP \fBT2\fP > \fBscifir::time_duration\fP & \fBscifir::operator+=\fP (chrono::duration< \fBT1\fP, \fBT2\fP > x)"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT1\fP , \fBtypename\fP \fBT2\fP > \fBscifir::time_duration\fP & \fBscifir::operator\-=\fP (chrono::duration< \fBT1\fP, \fBT2\fP > x)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP_END\fP ()"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP_BEGIN\fP (\fBmass\fP)"
.br
.ti -1c
.RI "\fBscifir::mass\fP (\fBconst\fP \fBpercentage\fP &\fBnew_percentage\fP, \fBconst\fP mass &\fBnew_mass\fP)"
.br
.ti -1c
.RI "\fBscifir::mass\fP (\fBconst\fP \fBstring\fP &\fBinit_percentage\fP, \fBconst\fP \fBstring\fP &\fBinit_mass\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBcharge\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBtemperature\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP_BEGIN\fP (\fBmole\fP)"
.br
.ti -1c
.RI "\fBscifir::mole\fP (\fBconst\fP \fBpercentage\fP &\fBnew_percentage\fP, \fBconst\fP mole &\fBnew_mole\fP)"
.br
.ti -1c
.RI "\fBscifir::mole\fP (\fBconst\fP \fBstring\fP &\fBinit_percentage\fP, \fBconst\fP \fBstring\fP &\fBinit_mole\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBscifir::number_of_particles\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (\fBlight\fP)"
.br
.ti -1c
.RI "\fBscifir::SCALAR_UNIT_HPP\fP (data)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_Ym\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_Zm\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_Em\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_Pm\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_Tm\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_Gm\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_Mm\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_km\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_hm\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_dam\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_m\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_dm\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_cm\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_mm\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_um\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_nm\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_pm\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_fm\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_am\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_zm\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_ym\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_s\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_ms\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_us\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_ns\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_ps\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_fs\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_as\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_zs\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_ys\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Yg\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Zg\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Eg\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Pg\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Tg\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Gg\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Mg\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_kg\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_hg\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_dag\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_g\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_dg\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_cg\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_mg\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_ug\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_ng\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_pg\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_fg\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_ag\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_zg\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_yg\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_YC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_ZC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_EC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_PC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_TC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_GC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_MC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_kC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_hC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_daC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_C\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_dC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_cC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_mC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_uC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_nC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_pC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_fC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_aC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_zC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_yC\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_YK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_ZK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_EK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_PK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_TK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_GK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_MK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_kK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_hK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_daK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_K\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_dK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_cK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_mK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_uK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_nK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_pK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_fK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_aK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_zK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_yK\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Ymol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Zmol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Emol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Pmol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Tmol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Gmol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Mmol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_kmol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_hmol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_damol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_mol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_dmol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_cmol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_mmol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_umol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_nmol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_pmol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_fmol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_amol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_zmol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_ymol\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_Ycd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_Zcd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_Ecd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_Pcd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_Tcd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_Gcd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_Mcd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_kcd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_hcd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_dacd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_cd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_dcd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_ccd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_mcd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_ucd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_ncd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_pcd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_fcd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_acd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_zcd\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_ycd\fP (unsigned long long int)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_YB\fP (unsigned long long int)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_ZB\fP (unsigned long long int)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_EB\fP (unsigned long long int)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_PB\fP (unsigned long long int)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_TB\fP (unsigned long long int)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_GB\fP (unsigned long long int)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_MB\fP (unsigned long long int)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_kB\fP (unsigned long long int)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_B\fP (unsigned long long int)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_Ym\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_Zm\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_Em\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_Pm\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_Tm\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_Gm\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_Mm\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_km\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_hm\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_dam\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_m\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_dm\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_cm\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_mm\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_um\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_nm\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_pm\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_fm\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_am\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_zm\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::length\fP \fBoperator''_ym\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_s\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_ms\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_us\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_ns\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_ps\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_fs\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_as\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_zs\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::time_duration\fP \fBoperator''_ys\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Yg\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Zg\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Eg\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Pg\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Tg\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Gg\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_Mg\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_kg\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_hg\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_dag\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_g\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_dg\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_cg\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_mg\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_ug\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_ng\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_pg\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_fg\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_ag\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_zg\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mass\fP \fBoperator''_yg\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_YC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_ZC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_EC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_PC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_TC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_GC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_MC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_kC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_hC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_daC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_C\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_dC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_cC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_mC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_uC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_nC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_pC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_fC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_aC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_zC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::charge\fP \fBoperator''_yC\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_YK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_ZK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_EK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_PK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_TK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_GK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_MK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_kK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_hK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_daK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_K\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_dK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_cK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_mK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_uK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_nK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_pK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_fK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_aK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_zK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::temperature\fP \fBoperator''_yK\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Ymol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Zmol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Emol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Pmol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Tmol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Gmol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_Mmol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_kmol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_hmol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_damol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_mol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_dmol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_cmol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_mmol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_umol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_nmol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_pmol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_fmol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_amol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_zmol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::mole\fP \fBoperator''_ymol\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_Ycd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_Zcd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_Ecd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_Pcd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_Tcd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_Gcd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_Mcd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_kcd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_hcd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_dacd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_cd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_dcd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_ccd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_mcd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_ucd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_ncd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_pcd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_fcd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_acd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_zcd\fP (long double)"
.br
.ti -1c
.RI "\fBscifir::light\fP \fBoperator''_ycd\fP (long double)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_YB\fP (long double)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_ZB\fP (long double)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_EB\fP (long double)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_PB\fP (long double)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_TB\fP (long double)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_GB\fP (long double)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_MB\fP (long double)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_kB\fP (long double)"
.br
.ti -1c
.RI "scifir::data \fBoperator''_B\fP (long double)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBscifir::charge\fP operator''_aC (long double x)"

.PP
Definition at line \fB1420\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1421 {
1422     return scifir::charge(x, "aC");
1423 }
.fi

.SS "\fBscifir::charge\fP operator''_aC (unsigned long long int x)"

.PP
Definition at line \fB700\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
701 {
702     return scifir::charge((long double)x, "aC");
703 }
.fi

.SS "\fBscifir::light\fP operator''_acd (long double x)"

.PP
Definition at line \fB1735\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1736 {
1737     return scifir::light(x, "acd");
1738 }
.fi

.SS "\fBscifir::light\fP operator''_acd (unsigned long long int x)"

.PP
Definition at line \fB1015\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1016 {
1017     return scifir::light((long double)x, "acd");
1018 }
.fi

.SS "\fBscifir::mass\fP operator''_ag (long double x)"

.PP
Definition at line \fB1315\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1316 {
1317     return scifir::mass(x, "ag");
1318 }
.fi

.SS "\fBscifir::mass\fP operator''_ag (unsigned long long int x)"

.PP
Definition at line \fB595\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
596 {
597     return scifir::mass((long double)x, "ag");
598 }
.fi

.SS "\fBscifir::temperature\fP operator''_aK (long double x)"

.PP
Definition at line \fB1525\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1526 {
1527     return scifir::temperature(x, "aK");
1528 }
.fi

.SS "\fBscifir::temperature\fP operator''_aK (unsigned long long int x)"

.PP
Definition at line \fB805\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
806 {
807     return scifir::temperature((long double)x, "aK");
808 }
.fi

.SS "\fBscifir::length\fP operator''_am (long double x)"

.PP
Definition at line \fB1165\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1166 {
1167     return scifir::length(x, "am");
1168 }
.fi

.SS "\fBscifir::length\fP operator''_am (unsigned long long int x)"

.PP
Definition at line \fB445\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
446 {
447     return scifir::length((long double)x, "am");
448 }
.fi

.SS "\fBscifir::mole\fP operator''_amol (long double x)"

.PP
Definition at line \fB1630\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1631 {
1632     return scifir::mole(x, "amol");
1633 }
.fi

.SS "\fBscifir::mole\fP operator''_amol (unsigned long long int x)"

.PP
Definition at line \fB910\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
911 {
912     return scifir::mole((long double)x, "amol");
913 }
.fi

.SS "\fBscifir::time_duration\fP operator''_as (long double x)"

.PP
Definition at line \fB1210\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1211 {
1212     return scifir::time_duration(x, "as");
1213 }
.fi

.SS "\fBscifir::time_duration\fP operator''_as (unsigned long long int x)"

.PP
Definition at line \fB490\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
491 {
492     return scifir::time_duration((long double)x, "as");
493 }
.fi

.SS "scifir::data operator''_B (long double x)"

.PP
Definition at line \fB1790\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1791 {
1792     return scifir::data(x, "B");
1793 }
.fi

.SS "scifir::data operator''_B (unsigned long long int x)"

.PP
Definition at line \fB1070\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1071 {
1072     return scifir::data((long double)x, "B");
1073 }
.fi

.SS "\fBscifir::charge\fP operator''_C (long double x)"

.PP
Definition at line \fB1380\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1381 {
1382     return scifir::charge(x, "C");
1383 }
.fi

.SS "\fBscifir::charge\fP operator''_C (unsigned long long int x)"

.PP
Definition at line \fB660\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
661 {
662     return scifir::charge((long double)x, "C");
663 }
.fi

.SS "\fBscifir::charge\fP operator''_cC (long double x)"

.PP
Definition at line \fB1390\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1391 {
1392     return scifir::charge(x, "cC");
1393 }
.fi

.SS "\fBscifir::charge\fP operator''_cC (unsigned long long int x)"

.PP
Definition at line \fB670\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
671 {
672     return scifir::charge((long double)x, "cC");
673 }
.fi

.SS "\fBscifir::light\fP operator''_ccd (long double x)"

.PP
Definition at line \fB1705\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1706 {
1707     return scifir::light(x, "ccd");
1708 }
.fi

.SS "\fBscifir::light\fP operator''_ccd (unsigned long long int x)"

.PP
Definition at line \fB985\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
986 {
987     return scifir::light((long double)x, "ccd");
988 }
.fi

.SS "\fBscifir::light\fP operator''_cd (long double x)"

.PP
Definition at line \fB1695\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1696 {
1697     return scifir::light(x, "cd");
1698 }
.fi

.SS "\fBscifir::light\fP operator''_cd (unsigned long long int x)"

.PP
Definition at line \fB975\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
976 {
977     return scifir::light((long double)x, "cd");
978 }
.fi

.SS "\fBscifir::mass\fP operator''_cg (long double x)"

.PP
Definition at line \fB1285\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1286 {
1287     return scifir::mass(x, "cg");
1288 }
.fi

.SS "\fBscifir::mass\fP operator''_cg (unsigned long long int x)"

.PP
Definition at line \fB565\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
566 {
567     return scifir::mass((long double)x, "cg");
568 }
.fi

.SS "\fBscifir::temperature\fP operator''_cK (long double x)"

.PP
Definition at line \fB1495\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1496 {
1497     return scifir::temperature(x, "cK");
1498 }
.fi

.SS "\fBscifir::temperature\fP operator''_cK (unsigned long long int x)"

.PP
Definition at line \fB775\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
776 {
777     return scifir::temperature((long double)x, "cK");
778 }
.fi

.SS "\fBscifir::length\fP operator''_cm (long double x)"

.PP
Definition at line \fB1135\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1136 {
1137     return scifir::length(x, "cm");
1138 }
.fi

.SS "\fBscifir::length\fP operator''_cm (unsigned long long int x)"

.PP
Definition at line \fB415\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
416 {
417     return scifir::length((long double)x, "cm");
418 }
.fi

.SS "\fBscifir::mole\fP operator''_cmol (long double x)"

.PP
Definition at line \fB1600\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1601 {
1602     return scifir::mole(x, "cmol");
1603 }
.fi

.SS "\fBscifir::mole\fP operator''_cmol (unsigned long long int x)"

.PP
Definition at line \fB880\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
881 {
882     return scifir::mole((long double)x, "cmol");
883 }
.fi

.SS "\fBscifir::charge\fP operator''_daC (long double x)"

.PP
Definition at line \fB1375\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1376 {
1377     return scifir::charge(x, "daC");
1378 }
.fi

.SS "\fBscifir::charge\fP operator''_daC (unsigned long long int x)"

.PP
Definition at line \fB655\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
656 {
657     return scifir::charge((long double)x, "daC");
658 }
.fi

.SS "\fBscifir::light\fP operator''_dacd (long double x)"

.PP
Definition at line \fB1690\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1691 {
1692     return scifir::light(x, "dacd");
1693 }
.fi

.SS "\fBscifir::light\fP operator''_dacd (unsigned long long int x)"

.PP
Definition at line \fB970\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
971 {
972     return scifir::light((long double)x, "dacd");
973 }
.fi

.SS "\fBscifir::mass\fP operator''_dag (long double x)"

.PP
Definition at line \fB1270\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1271 {
1272     return scifir::mass(x, "dag");
1273 }
.fi

.SS "\fBscifir::mass\fP operator''_dag (unsigned long long int x)"

.PP
Definition at line \fB550\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
551 {
552     return scifir::mass((long double)x, "dag");
553 }
.fi

.SS "\fBscifir::temperature\fP operator''_daK (long double x)"

.PP
Definition at line \fB1480\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1481 {
1482     return scifir::temperature(x, "daK");
1483 }
.fi

.SS "\fBscifir::temperature\fP operator''_daK (unsigned long long int x)"

.PP
Definition at line \fB760\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
761 {
762     return scifir::temperature((long double)x, "daK");
763 }
.fi

.SS "\fBscifir::length\fP operator''_dam (long double x)"

.PP
Definition at line \fB1120\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1121 {
1122     return scifir::length(x, "dam");
1123 }
.fi

.SS "\fBscifir::length\fP operator''_dam (unsigned long long int x)"

.PP
Definition at line \fB400\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
401 {
402     return scifir::length((long double)x, "dam");
403 }
.fi

.SS "\fBscifir::mole\fP operator''_damol (long double x)"

.PP
Definition at line \fB1585\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1586 {
1587     return scifir::mole(x, "damol");
1588 }
.fi

.SS "\fBscifir::mole\fP operator''_damol (unsigned long long int x)"

.PP
Definition at line \fB865\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
866 {
867     return scifir::mole((long double)x, "damol");
868 }
.fi

.SS "\fBscifir::charge\fP operator''_dC (long double x)"

.PP
Definition at line \fB1385\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1386 {
1387     return scifir::charge(x, "dC");
1388 }
.fi

.SS "\fBscifir::charge\fP operator''_dC (unsigned long long int x)"

.PP
Definition at line \fB665\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
666 {
667     return scifir::charge((long double)x, "dC");
668 }
.fi

.SS "\fBscifir::light\fP operator''_dcd (long double x)"

.PP
Definition at line \fB1700\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1701 {
1702     return scifir::light(x, "dcd");
1703 }
.fi

.SS "\fBscifir::light\fP operator''_dcd (unsigned long long int x)"

.PP
Definition at line \fB980\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
981 {
982     return scifir::light((long double)x, "dcd");
983 }
.fi

.SS "\fBscifir::mass\fP operator''_dg (long double x)"

.PP
Definition at line \fB1280\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1281 {
1282     return scifir::mass(x, "dg");
1283 }
.fi

.SS "\fBscifir::mass\fP operator''_dg (unsigned long long int x)"

.PP
Definition at line \fB560\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
561 {
562     return scifir::mass((long double)x, "dg");
563 }
.fi

.SS "\fBscifir::temperature\fP operator''_dK (long double x)"

.PP
Definition at line \fB1490\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1491 {
1492     return scifir::temperature(x, "dK");
1493 }
.fi

.SS "\fBscifir::temperature\fP operator''_dK (unsigned long long int x)"

.PP
Definition at line \fB770\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
771 {
772     return scifir::temperature((long double)x, "dK");
773 }
.fi

.SS "\fBscifir::length\fP operator''_dm (long double x)"

.PP
Definition at line \fB1130\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1131 {
1132     return scifir::length(x, "dm");
1133 }
.fi

.SS "\fBscifir::length\fP operator''_dm (unsigned long long int x)"

.PP
Definition at line \fB410\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
411 {
412     return scifir::length((long double)x, "dm");
413 }
.fi

.SS "\fBscifir::mole\fP operator''_dmol (long double x)"

.PP
Definition at line \fB1595\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1596 {
1597     return scifir::mole(x, "dmol");
1598 }
.fi

.SS "\fBscifir::mole\fP operator''_dmol (unsigned long long int x)"

.PP
Definition at line \fB875\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
876 {
877     return scifir::mole((long double)x, "dmol");
878 }
.fi

.SS "scifir::data operator''_EB (long double x)"

.PP
Definition at line \fB1760\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1761 {
1762     return scifir::data(x, "EB");
1763 }
.fi

.SS "scifir::data operator''_EB (unsigned long long int x)"

.PP
Definition at line \fB1040\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1041 {
1042     return scifir::data((long double)x, "EB");
1043 }
.fi

.SS "\fBscifir::charge\fP operator''_EC (long double x)"

.PP
Definition at line \fB1340\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1341 {
1342     return scifir::charge(x, "EC");
1343 }
.fi

.SS "\fBscifir::charge\fP operator''_EC (unsigned long long int x)"

.PP
Definition at line \fB620\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
621 {
622     return scifir::charge((long double)x, "EC");
623 }
.fi

.SS "\fBscifir::light\fP operator''_Ecd (long double x)"

.PP
Definition at line \fB1655\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1656 {
1657     return scifir::light(x, "Ecd");
1658 }
.fi

.SS "\fBscifir::light\fP operator''_Ecd (unsigned long long int x)"

.PP
Definition at line \fB935\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
936 {
937     return scifir::light((long double)x, "Ecd");
938 }
.fi

.SS "\fBscifir::mass\fP operator''_Eg (long double x)"

.PP
Definition at line \fB1235\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1236 {
1237     return scifir::mass(x, "Eg");
1238 }
.fi

.SS "\fBscifir::mass\fP operator''_Eg (unsigned long long int x)"

.PP
Definition at line \fB515\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
516 {
517     return scifir::mass((long double)x, "Eg");
518 }
.fi

.SS "\fBscifir::temperature\fP operator''_EK (long double x)"

.PP
Definition at line \fB1445\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1446 {
1447     return scifir::temperature(x, "EK");
1448 }
.fi

.SS "\fBscifir::temperature\fP operator''_EK (unsigned long long int x)"

.PP
Definition at line \fB725\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
726 {
727     return scifir::temperature((long double)x, "EK");
728 }
.fi

.SS "\fBscifir::length\fP operator''_Em (long double x)"

.PP
Definition at line \fB1085\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1086 {
1087     return scifir::length(x, "Em");
1088 }
.fi

.SS "\fBscifir::length\fP operator''_Em (unsigned long long int x)"

.PP
Definition at line \fB365\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
366 {
367     return scifir::length((long double)x, "Em");
368 }
.fi

.SS "\fBscifir::mole\fP operator''_Emol (long double x)"

.PP
Definition at line \fB1550\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1551 {
1552     return scifir::mole(x, "Emol");
1553 }
.fi

.SS "\fBscifir::mole\fP operator''_Emol (unsigned long long int x)"

.PP
Definition at line \fB830\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
831 {
832     return scifir::mole((long double)x, "Emol");
833 }
.fi

.SS "\fBscifir::charge\fP operator''_fC (long double x)"

.PP
Definition at line \fB1415\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1416 {
1417     return scifir::charge(x, "fC");
1418 }
.fi

.SS "\fBscifir::charge\fP operator''_fC (unsigned long long int x)"

.PP
Definition at line \fB695\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
696 {
697     return scifir::charge((long double)x, "fC");
698 }
.fi

.SS "\fBscifir::light\fP operator''_fcd (long double x)"

.PP
Definition at line \fB1730\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1731 {
1732     return scifir::light(x, "fcd");
1733 }
.fi

.SS "\fBscifir::light\fP operator''_fcd (unsigned long long int x)"

.PP
Definition at line \fB1010\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1011 {
1012     return scifir::light((long double)x, "fcd");
1013 }
.fi

.SS "\fBscifir::mass\fP operator''_fg (long double x)"

.PP
Definition at line \fB1310\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1311 {
1312     return scifir::mass(x, "fg");
1313 }
.fi

.SS "\fBscifir::mass\fP operator''_fg (unsigned long long int x)"

.PP
Definition at line \fB590\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
591 {
592     return scifir::mass((long double)x, "fg");
593 }
.fi

.SS "\fBscifir::temperature\fP operator''_fK (long double x)"

.PP
Definition at line \fB1520\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1521 {
1522     return scifir::temperature(x, "fK");
1523 }
.fi

.SS "\fBscifir::temperature\fP operator''_fK (unsigned long long int x)"

.PP
Definition at line \fB800\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
801 {
802     return scifir::temperature((long double)x, "fK");
803 }
.fi

.SS "\fBscifir::length\fP operator''_fm (long double x)"

.PP
Definition at line \fB1160\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1161 {
1162     return scifir::length(x, "fm");
1163 }
.fi

.SS "\fBscifir::length\fP operator''_fm (unsigned long long int x)"

.PP
Definition at line \fB440\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
441 {
442     return scifir::length((long double)x, "fm");
443 }
.fi

.SS "\fBscifir::mole\fP operator''_fmol (long double x)"

.PP
Definition at line \fB1625\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1626 {
1627     return scifir::mole(x, "fmol");
1628 }
.fi

.SS "\fBscifir::mole\fP operator''_fmol (unsigned long long int x)"

.PP
Definition at line \fB905\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
906 {
907     return scifir::mole((long double)x, "fmol");
908 }
.fi

.SS "\fBscifir::time_duration\fP operator''_fs (long double x)"

.PP
Definition at line \fB1205\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1206 {
1207     return scifir::time_duration(x, "fs");
1208 }
.fi

.SS "\fBscifir::time_duration\fP operator''_fs (unsigned long long int x)"

.PP
Definition at line \fB485\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
486 {
487     return scifir::time_duration((long double)x, "fs");
488 }
.fi

.SS "\fBscifir::mass\fP operator''_g (long double x)"

.PP
Definition at line \fB1275\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1276 {
1277     return scifir::mass(x, "g");
1278 }
.fi

.SS "\fBscifir::mass\fP operator''_g (unsigned long long int x)"

.PP
Definition at line \fB555\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
556 {
557     return scifir::mass((long double)x, "g");
558 }
.fi

.SS "scifir::data operator''_GB (long double x)"

.PP
Definition at line \fB1775\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1776 {
1777     return scifir::data(x, "GB");
1778 }
.fi

.SS "scifir::data operator''_GB (unsigned long long int x)"

.PP
Definition at line \fB1055\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1056 {
1057     return scifir::data((long double)x, "GB");
1058 }
.fi

.SS "\fBscifir::charge\fP operator''_GC (long double x)"

.PP
Definition at line \fB1355\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1356 {
1357     return scifir::charge(x, "GC");
1358 }
.fi

.SS "\fBscifir::charge\fP operator''_GC (unsigned long long int x)"

.PP
Definition at line \fB635\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
636 {
637     return scifir::charge((long double)x, "GC");
638 }
.fi

.SS "\fBscifir::light\fP operator''_Gcd (long double x)"

.PP
Definition at line \fB1670\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1671 {
1672     return scifir::light(x, "Gcd");
1673 }
.fi

.SS "\fBscifir::light\fP operator''_Gcd (unsigned long long int x)"

.PP
Definition at line \fB950\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
951 {
952     return scifir::light((long double)x, "Gcd");
953 }
.fi

.SS "\fBscifir::mass\fP operator''_Gg (long double x)"

.PP
Definition at line \fB1250\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1251 {
1252     return scifir::mass(x, "Gg");
1253 }
.fi

.SS "\fBscifir::mass\fP operator''_Gg (unsigned long long int x)"

.PP
Definition at line \fB530\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
531 {
532     return scifir::mass((long double)x, "Gg");
533 }
.fi

.SS "\fBscifir::temperature\fP operator''_GK (long double x)"

.PP
Definition at line \fB1460\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1461 {
1462     return scifir::temperature(x, "GK");
1463 }
.fi

.SS "\fBscifir::temperature\fP operator''_GK (unsigned long long int x)"

.PP
Definition at line \fB740\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
741 {
742     return scifir::temperature((long double)x, "GK");
743 }
.fi

.SS "\fBscifir::length\fP operator''_Gm (long double x)"

.PP
Definition at line \fB1100\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1101 {
1102     return scifir::length(x, "Gm");
1103 }
.fi

.SS "\fBscifir::length\fP operator''_Gm (unsigned long long int x)"

.PP
Definition at line \fB380\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
381 {
382     return scifir::length((long double)x, "Gm");
383 }
.fi

.SS "\fBscifir::mole\fP operator''_Gmol (long double x)"

.PP
Definition at line \fB1565\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1566 {
1567     return scifir::mole(x, "Gmol");
1568 }
.fi

.SS "\fBscifir::mole\fP operator''_Gmol (unsigned long long int x)"

.PP
Definition at line \fB845\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
846 {
847     return scifir::mole((long double)x, "Gmol");
848 }
.fi

.SS "\fBscifir::charge\fP operator''_hC (long double x)"

.PP
Definition at line \fB1370\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1371 {
1372     return scifir::charge(x, "hC");
1373 }
.fi

.SS "\fBscifir::charge\fP operator''_hC (unsigned long long int x)"

.PP
Definition at line \fB650\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
651 {
652     return scifir::charge((long double)x, "hC");
653 }
.fi

.SS "\fBscifir::light\fP operator''_hcd (long double x)"

.PP
Definition at line \fB1685\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1686 {
1687     return scifir::light(x, "hcd");
1688 }
.fi

.SS "\fBscifir::light\fP operator''_hcd (unsigned long long int x)"

.PP
Definition at line \fB965\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
966 {
967     return scifir::light((long double)x, "hcd");
968 }
.fi

.SS "\fBscifir::mass\fP operator''_hg (long double x)"

.PP
Definition at line \fB1265\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1266 {
1267     return scifir::mass(x, "hg");
1268 }
.fi

.SS "\fBscifir::mass\fP operator''_hg (unsigned long long int x)"

.PP
Definition at line \fB545\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
546 {
547     return scifir::mass((long double)x, "hg");
548 }
.fi

.SS "\fBscifir::temperature\fP operator''_hK (long double x)"

.PP
Definition at line \fB1475\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1476 {
1477     return scifir::temperature(x, "hK");
1478 }
.fi

.SS "\fBscifir::temperature\fP operator''_hK (unsigned long long int x)"

.PP
Definition at line \fB755\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
756 {
757     return scifir::temperature((long double)x, "hK");
758 }
.fi

.SS "\fBscifir::length\fP operator''_hm (long double x)"

.PP
Definition at line \fB1115\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1116 {
1117     return scifir::length(x, "hm");
1118 }
.fi

.SS "\fBscifir::length\fP operator''_hm (unsigned long long int x)"

.PP
Definition at line \fB395\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
396 {
397     return scifir::length((long double)x, "hm");
398 }
.fi

.SS "\fBscifir::mole\fP operator''_hmol (long double x)"

.PP
Definition at line \fB1580\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1581 {
1582     return scifir::mole(x, "hmol");
1583 }
.fi

.SS "\fBscifir::mole\fP operator''_hmol (unsigned long long int x)"

.PP
Definition at line \fB860\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
861 {
862     return scifir::mole((long double)x, "hmol");
863 }
.fi

.SS "\fBscifir::temperature\fP operator''_K (long double x)"

.PP
Definition at line \fB1485\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1486 {
1487     return scifir::temperature(x, "K");
1488 }
.fi

.SS "\fBscifir::temperature\fP operator''_K (unsigned long long int x)"

.PP
Definition at line \fB765\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
766 {
767     return scifir::temperature((long double)x, "K");
768 }
.fi

.SS "scifir::data operator''_kB (long double x)"

.PP
Definition at line \fB1785\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1786 {
1787     return scifir::data(x, "kB");
1788 }
.fi

.SS "scifir::data operator''_kB (unsigned long long int x)"

.PP
Definition at line \fB1065\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1066 {
1067     return scifir::data((long double)x, "kB");
1068 }
.fi

.SS "\fBscifir::charge\fP operator''_kC (long double x)"

.PP
Definition at line \fB1365\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1366 {
1367     return scifir::charge(x, "kC");
1368 }
.fi

.SS "\fBscifir::charge\fP operator''_kC (unsigned long long int x)"

.PP
Definition at line \fB645\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
646 {
647     return scifir::charge((long double)x, "kC");
648 }
.fi

.SS "\fBscifir::light\fP operator''_kcd (long double x)"

.PP
Definition at line \fB1680\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1681 {
1682     return scifir::light(x, "kcd");
1683 }
.fi

.SS "\fBscifir::light\fP operator''_kcd (unsigned long long int x)"

.PP
Definition at line \fB960\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
961 {
962     return scifir::light((long double)x, "kcd");
963 }
.fi

.SS "\fBscifir::mass\fP operator''_kg (long double x)"

.PP
Definition at line \fB1260\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1261 {
1262     return scifir::mass(x, "kg");
1263 }
.fi

.SS "\fBscifir::mass\fP operator''_kg (unsigned long long int x)"

.PP
Definition at line \fB540\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
541 {
542     return scifir::mass((long double)x, "kg");
543 }
.fi

.SS "\fBscifir::temperature\fP operator''_kK (long double x)"

.PP
Definition at line \fB1470\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1471 {
1472     return scifir::temperature(x, "kK");
1473 }
.fi

.SS "\fBscifir::temperature\fP operator''_kK (unsigned long long int x)"

.PP
Definition at line \fB750\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
751 {
752     return scifir::temperature((long double)x, "kK");
753 }
.fi

.SS "\fBscifir::length\fP operator''_km (long double x)"

.PP
Definition at line \fB1110\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1111 {
1112     return scifir::length(x, "km");
1113 }
.fi

.SS "\fBscifir::length\fP operator''_km (unsigned long long int x)"

.PP
Definition at line \fB390\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
391 {
392     return scifir::length((long double)x, "km");
393 }
.fi

.SS "\fBscifir::mole\fP operator''_kmol (long double x)"

.PP
Definition at line \fB1575\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1576 {
1577     return scifir::mole(x, "kmol");
1578 }
.fi

.SS "\fBscifir::mole\fP operator''_kmol (unsigned long long int x)"

.PP
Definition at line \fB855\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
856 {
857     return scifir::mole((long double)x, "kmol");
858 }
.fi

.SS "\fBscifir::length\fP operator''_m (long double x)"

.PP
Definition at line \fB1125\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1126 {
1127     return scifir::length(x, "m");
1128 }
.fi

.SS "\fBscifir::length\fP operator''_m (unsigned long long int x)"

.PP
Definition at line \fB405\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
406 {
407     return scifir::length((long double)x, "m");
408 }
.fi

.SS "scifir::data operator''_MB (long double x)"

.PP
Definition at line \fB1780\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1781 {
1782     return scifir::data(x, "MB");
1783 }
.fi

.SS "scifir::data operator''_MB (unsigned long long int x)"

.PP
Definition at line \fB1060\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1061 {
1062     return scifir::data((long double)x, "MB");
1063 }
.fi

.SS "\fBscifir::charge\fP operator''_MC (long double x)"

.PP
Definition at line \fB1360\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1361 {
1362     return scifir::charge(x, "MC");
1363 }
.fi

.SS "\fBscifir::charge\fP operator''_mC (long double x)"

.PP
Definition at line \fB1395\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1396 {
1397     return scifir::charge(x, "mC");
1398 }
.fi

.SS "\fBscifir::charge\fP operator''_MC (unsigned long long int x)"

.PP
Definition at line \fB640\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
641 {
642     return scifir::charge((long double)x, "MC");
643 }
.fi

.SS "\fBscifir::charge\fP operator''_mC (unsigned long long int x)"

.PP
Definition at line \fB675\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
676 {
677     return scifir::charge((long double)x, "mC");
678 }
.fi

.SS "\fBscifir::light\fP operator''_Mcd (long double x)"

.PP
Definition at line \fB1675\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1676 {
1677     return scifir::light(x, "Mcd");
1678 }
.fi

.SS "\fBscifir::light\fP operator''_mcd (long double x)"

.PP
Definition at line \fB1710\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1711 {
1712     return scifir::light(x, "mcd");
1713 }
.fi

.SS "\fBscifir::light\fP operator''_Mcd (unsigned long long int x)"

.PP
Definition at line \fB955\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
956 {
957     return scifir::light((long double)x, "Mcd");
958 }
.fi

.SS "\fBscifir::light\fP operator''_mcd (unsigned long long int x)"

.PP
Definition at line \fB990\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
991 {
992     return scifir::light((long double)x, "mcd");
993 }
.fi

.SS "\fBscifir::mass\fP operator''_Mg (long double x)"

.PP
Definition at line \fB1255\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1256 {
1257     return scifir::mass(x, "Mg");
1258 }
.fi

.SS "\fBscifir::mass\fP operator''_mg (long double x)"

.PP
Definition at line \fB1290\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1291 {
1292     return scifir::mass(x, "mg");
1293 }
.fi

.SS "\fBscifir::mass\fP operator''_Mg (unsigned long long int x)"

.PP
Definition at line \fB535\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
536 {
537     return scifir::mass((long double)x, "Mg");
538 }
.fi

.SS "\fBscifir::mass\fP operator''_mg (unsigned long long int x)"

.PP
Definition at line \fB570\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
571 {
572     return scifir::mass((long double)x, "mg");
573 }
.fi

.SS "\fBscifir::temperature\fP operator''_MK (long double x)"

.PP
Definition at line \fB1465\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1466 {
1467     return scifir::temperature(x, "MK");
1468 }
.fi

.SS "\fBscifir::temperature\fP operator''_mK (long double x)"

.PP
Definition at line \fB1500\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1501 {
1502     return scifir::temperature(x, "mK");
1503 }
.fi

.SS "\fBscifir::temperature\fP operator''_MK (unsigned long long int x)"

.PP
Definition at line \fB745\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
746 {
747     return scifir::temperature((long double)x, "MK");
748 }
.fi

.SS "\fBscifir::temperature\fP operator''_mK (unsigned long long int x)"

.PP
Definition at line \fB780\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
781 {
782     return scifir::temperature((long double)x, "mK");
783 }
.fi

.SS "\fBscifir::length\fP operator''_Mm (long double x)"

.PP
Definition at line \fB1105\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1106 {
1107     return scifir::length(x, "Mm");
1108 }
.fi

.SS "\fBscifir::length\fP operator''_mm (long double x)"

.PP
Definition at line \fB1140\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1141 {
1142     return scifir::length(x, "mm");
1143 }
.fi

.SS "\fBscifir::length\fP operator''_Mm (unsigned long long int x)"

.PP
Definition at line \fB385\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
386 {
387     return scifir::length((long double)x, "Mm");
388 }
.fi

.SS "\fBscifir::length\fP operator''_mm (unsigned long long int x)"

.PP
Definition at line \fB420\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
421 {
422     return scifir::length((long double)x, "mm");
423 }
.fi

.SS "\fBscifir::mole\fP operator''_Mmol (long double x)"

.PP
Definition at line \fB1570\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1571 {
1572     return scifir::mole(x, "Mmol");
1573 }
.fi

.SS "\fBscifir::mole\fP operator''_mmol (long double x)"

.PP
Definition at line \fB1605\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1606 {
1607     return scifir::mole(x, "mmol");
1608 }
.fi

.SS "\fBscifir::mole\fP operator''_Mmol (unsigned long long int x)"

.PP
Definition at line \fB850\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
851 {
852     return scifir::mole((long double)x, "Mmol");
853 }
.fi

.SS "\fBscifir::mole\fP operator''_mmol (unsigned long long int x)"

.PP
Definition at line \fB885\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
886 {
887     return scifir::mole((long double)x, "mmol");
888 }
.fi

.SS "\fBscifir::mole\fP operator''_mol (long double x)"

.PP
Definition at line \fB1590\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1591 {
1592     return scifir::mole(x, "mol");
1593 }
.fi

.SS "\fBscifir::mole\fP operator''_mol (unsigned long long int x)"

.PP
Definition at line \fB870\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
871 {
872     return scifir::mole((long double)x, "mol");
873 }
.fi

.SS "\fBscifir::time_duration\fP operator''_ms (long double x)"

.PP
Definition at line \fB1185\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1186 {
1187     return scifir::time_duration(x, "ms");
1188 }
.fi

.SS "\fBscifir::time_duration\fP operator''_ms (unsigned long long int x)"

.PP
Definition at line \fB465\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
466 {
467     return scifir::time_duration((long double)x, "ms");
468 }
.fi

.SS "\fBscifir::charge\fP operator''_nC (long double x)"

.PP
Definition at line \fB1405\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1406 {
1407     return scifir::charge(x, "nC");
1408 }
.fi

.SS "\fBscifir::charge\fP operator''_nC (unsigned long long int x)"

.PP
Definition at line \fB685\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
686 {
687     return scifir::charge((long double)x, "nC");
688 }
.fi

.SS "\fBscifir::light\fP operator''_ncd (long double x)"

.PP
Definition at line \fB1720\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1721 {
1722     return scifir::light(x, "ncd");
1723 }
.fi

.SS "\fBscifir::light\fP operator''_ncd (unsigned long long int x)"

.PP
Definition at line \fB1000\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1001 {
1002     return scifir::light((long double)x, "ncd");
1003 }
.fi

.SS "\fBscifir::mass\fP operator''_ng (long double x)"

.PP
Definition at line \fB1300\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1301 {
1302     return scifir::mass(x, "ng");
1303 }
.fi

.SS "\fBscifir::mass\fP operator''_ng (unsigned long long int x)"

.PP
Definition at line \fB580\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
581 {
582     return scifir::mass((long double)x, "ng");
583 }
.fi

.SS "\fBscifir::temperature\fP operator''_nK (long double x)"

.PP
Definition at line \fB1510\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1511 {
1512     return scifir::temperature(x, "nK");
1513 }
.fi

.SS "\fBscifir::temperature\fP operator''_nK (unsigned long long int x)"

.PP
Definition at line \fB790\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
791 {
792     return scifir::temperature((long double)x, "nK");
793 }
.fi

.SS "\fBscifir::length\fP operator''_nm (long double x)"

.PP
Definition at line \fB1150\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1151 {
1152     return scifir::length(x, "nm");
1153 }
.fi

.SS "\fBscifir::length\fP operator''_nm (unsigned long long int x)"

.PP
Definition at line \fB430\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
431 {
432     return scifir::length((long double)x, "nm");
433 }
.fi

.SS "\fBscifir::mole\fP operator''_nmol (long double x)"

.PP
Definition at line \fB1615\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1616 {
1617     return scifir::mole(x, "nmol");
1618 }
.fi

.SS "\fBscifir::mole\fP operator''_nmol (unsigned long long int x)"

.PP
Definition at line \fB895\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
896 {
897     return scifir::mole((long double)x, "nmol");
898 }
.fi

.SS "\fBscifir::time_duration\fP operator''_ns (long double x)"

.PP
Definition at line \fB1195\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1196 {
1197     return scifir::time_duration(x, "ns");
1198 }
.fi

.SS "\fBscifir::time_duration\fP operator''_ns (unsigned long long int x)"

.PP
Definition at line \fB475\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
476 {
477     return scifir::time_duration((long double)x, "ns");
478 }
.fi

.SS "scifir::data operator''_PB (long double x)"

.PP
Definition at line \fB1765\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1766 {
1767     return scifir::data(x, "PB");
1768 }
.fi

.SS "scifir::data operator''_PB (unsigned long long int x)"

.PP
Definition at line \fB1045\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1046 {
1047     return scifir::data((long double)x, "PB");
1048 }
.fi

.SS "\fBscifir::charge\fP operator''_PC (long double x)"

.PP
Definition at line \fB1345\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1346 {
1347     return scifir::charge(x, "PC");
1348 }
.fi

.SS "\fBscifir::charge\fP operator''_pC (long double x)"

.PP
Definition at line \fB1410\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1411 {
1412     return scifir::charge(x, "pC");
1413 }
.fi

.SS "\fBscifir::charge\fP operator''_PC (unsigned long long int x)"

.PP
Definition at line \fB625\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
626 {
627     return scifir::charge((long double)x, "PC");
628 }
.fi

.SS "\fBscifir::charge\fP operator''_pC (unsigned long long int x)"

.PP
Definition at line \fB690\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
691 {
692     return scifir::charge((long double)x, "pC");
693 }
.fi

.SS "\fBscifir::light\fP operator''_Pcd (long double x)"

.PP
Definition at line \fB1660\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1661 {
1662     return scifir::light(x, "Pcd");
1663 }
.fi

.SS "\fBscifir::light\fP operator''_pcd (long double x)"

.PP
Definition at line \fB1725\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1726 {
1727     return scifir::light(x, "pcd");
1728 }
.fi

.SS "\fBscifir::light\fP operator''_Pcd (unsigned long long int x)"

.PP
Definition at line \fB940\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
941 {
942     return scifir::light((long double)x, "Pcd");
943 }
.fi

.SS "\fBscifir::light\fP operator''_pcd (unsigned long long int x)"

.PP
Definition at line \fB1005\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1006 {
1007     return scifir::light((long double)x, "pcd");
1008 }
.fi

.SS "\fBscifir::mass\fP operator''_Pg (long double x)"

.PP
Definition at line \fB1240\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1241 {
1242     return scifir::mass(x, "Pg");
1243 }
.fi

.SS "\fBscifir::mass\fP operator''_pg (long double x)"

.PP
Definition at line \fB1305\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1306 {
1307     return scifir::mass(x, "pg");
1308 }
.fi

.SS "\fBscifir::mass\fP operator''_Pg (unsigned long long int x)"

.PP
Definition at line \fB520\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
521 {
522     return scifir::mass((long double)x, "Pg");
523 }
.fi

.SS "\fBscifir::mass\fP operator''_pg (unsigned long long int x)"

.PP
Definition at line \fB585\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
586 {
587     return scifir::mass((long double)x, "pg");
588 }
.fi

.SS "\fBscifir::temperature\fP operator''_PK (long double x)"

.PP
Definition at line \fB1450\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1451 {
1452     return scifir::temperature(x, "PK");
1453 }
.fi

.SS "\fBscifir::temperature\fP operator''_pK (long double x)"

.PP
Definition at line \fB1515\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1516 {
1517     return scifir::temperature(x, "pK");
1518 }
.fi

.SS "\fBscifir::temperature\fP operator''_PK (unsigned long long int x)"

.PP
Definition at line \fB730\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
731 {
732     return scifir::temperature((long double)x, "PK");
733 }
.fi

.SS "\fBscifir::temperature\fP operator''_pK (unsigned long long int x)"

.PP
Definition at line \fB795\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
796 {
797     return scifir::temperature((long double)x, "pK");
798 }
.fi

.SS "\fBscifir::length\fP operator''_Pm (long double x)"

.PP
Definition at line \fB1090\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1091 {
1092     return scifir::length(x, "Pm");
1093 }
.fi

.SS "\fBscifir::length\fP operator''_pm (long double x)"

.PP
Definition at line \fB1155\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1156 {
1157     return scifir::length(x, "pm");
1158 }
.fi

.SS "\fBscifir::length\fP operator''_Pm (unsigned long long int x)"

.PP
Definition at line \fB370\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
371 {
372     return scifir::length((long double)x, "Pm");
373 }
.fi

.SS "\fBscifir::length\fP operator''_pm (unsigned long long int x)"

.PP
Definition at line \fB435\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
436 {
437     return scifir::length((long double)x, "pm");
438 }
.fi

.SS "\fBscifir::mole\fP operator''_Pmol (long double x)"

.PP
Definition at line \fB1555\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1556 {
1557     return scifir::mole(x, "Pmol");
1558 }
.fi

.SS "\fBscifir::mole\fP operator''_pmol (long double x)"

.PP
Definition at line \fB1620\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1621 {
1622     return scifir::mole(x, "pmol");
1623 }
.fi

.SS "\fBscifir::mole\fP operator''_Pmol (unsigned long long int x)"

.PP
Definition at line \fB835\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
836 {
837     return scifir::mole((long double)x, "Pmol");
838 }
.fi

.SS "\fBscifir::mole\fP operator''_pmol (unsigned long long int x)"

.PP
Definition at line \fB900\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
901 {
902     return scifir::mole((long double)x, "pmol");
903 }
.fi

.SS "\fBscifir::time_duration\fP operator''_ps (long double x)"

.PP
Definition at line \fB1200\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1201 {
1202     return scifir::time_duration(x, "ps");
1203 }
.fi

.SS "\fBscifir::time_duration\fP operator''_ps (unsigned long long int x)"

.PP
Definition at line \fB480\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
481 {
482     return scifir::time_duration((long double)x, "ps");
483 }
.fi

.SS "\fBscifir::time_duration\fP operator''_s (long double x)"

.PP
Definition at line \fB1180\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1181 {
1182     return scifir::time_duration(x, "s");
1183 }
.fi

.SS "\fBscifir::time_duration\fP operator''_s (unsigned long long int x)"

.PP
Definition at line \fB460\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
461 {
462     return scifir::time_duration((long double)x, "s");
463 }
.fi

.SS "scifir::data operator''_TB (long double x)"

.PP
Definition at line \fB1770\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1771 {
1772     return scifir::data(x, "TB");
1773 }
.fi

.SS "scifir::data operator''_TB (unsigned long long int x)"

.PP
Definition at line \fB1050\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1051 {
1052     return scifir::data((long double)x, "TB");
1053 }
.fi

.SS "\fBscifir::charge\fP operator''_TC (long double x)"

.PP
Definition at line \fB1350\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1351 {
1352     return scifir::charge(x, "TC");
1353 }
.fi

.SS "\fBscifir::charge\fP operator''_TC (unsigned long long int x)"

.PP
Definition at line \fB630\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
631 {
632     return scifir::charge((long double)x, "TC");
633 }
.fi

.SS "\fBscifir::light\fP operator''_Tcd (long double x)"

.PP
Definition at line \fB1665\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1666 {
1667     return scifir::light(x, "Tcd");
1668 }
.fi

.SS "\fBscifir::light\fP operator''_Tcd (unsigned long long int x)"

.PP
Definition at line \fB945\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
946 {
947     return scifir::light((long double)x, "Tcd");
948 }
.fi

.SS "\fBscifir::mass\fP operator''_Tg (long double x)"

.PP
Definition at line \fB1245\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1246 {
1247     return scifir::mass(x, "Tg");
1248 }
.fi

.SS "\fBscifir::mass\fP operator''_Tg (unsigned long long int x)"

.PP
Definition at line \fB525\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
526 {
527     return scifir::mass((long double)x, "Tg");
528 }
.fi

.SS "\fBscifir::temperature\fP operator''_TK (long double x)"

.PP
Definition at line \fB1455\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1456 {
1457     return scifir::temperature(x, "TK");
1458 }
.fi

.SS "\fBscifir::temperature\fP operator''_TK (unsigned long long int x)"

.PP
Definition at line \fB735\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
736 {
737     return scifir::temperature((long double)x, "TK");
738 }
.fi

.SS "\fBscifir::length\fP operator''_Tm (long double x)"

.PP
Definition at line \fB1095\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1096 {
1097     return scifir::length(x, "Tm");
1098 }
.fi

.SS "\fBscifir::length\fP operator''_Tm (unsigned long long int x)"

.PP
Definition at line \fB375\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
376 {
377     return scifir::length((long double)x, "Tm");
378 }
.fi

.SS "\fBscifir::mole\fP operator''_Tmol (long double x)"

.PP
Definition at line \fB1560\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1561 {
1562     return scifir::mole(x, "Tmol");
1563 }
.fi

.SS "\fBscifir::mole\fP operator''_Tmol (unsigned long long int x)"

.PP
Definition at line \fB840\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
841 {
842     return scifir::mole((long double)x, "Tmol");
843 }
.fi

.SS "\fBscifir::charge\fP operator''_uC (long double x)"

.PP
Definition at line \fB1400\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1401 {
1402     return scifir::charge(x, "uC");
1403 }
.fi

.SS "\fBscifir::charge\fP operator''_uC (unsigned long long int x)"

.PP
Definition at line \fB680\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
681 {
682     return scifir::charge((long double)x, "uC");
683 }
.fi

.SS "\fBscifir::light\fP operator''_ucd (long double x)"

.PP
Definition at line \fB1715\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1716 {
1717     return scifir::light(x, "ucd");
1718 }
.fi

.SS "\fBscifir::light\fP operator''_ucd (unsigned long long int x)"

.PP
Definition at line \fB995\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
996 {
997     return scifir::light((long double)x, "ucd");
998 }
.fi

.SS "\fBscifir::mass\fP operator''_ug (long double x)"

.PP
Definition at line \fB1295\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1296 {
1297     return scifir::mass(x, "ug");
1298 }
.fi

.SS "\fBscifir::mass\fP operator''_ug (unsigned long long int x)"

.PP
Definition at line \fB575\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
576 {
577     return scifir::mass((long double)x, "ug");
578 }
.fi

.SS "\fBscifir::temperature\fP operator''_uK (long double x)"

.PP
Definition at line \fB1505\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1506 {
1507     return scifir::temperature(x, "uK");
1508 }
.fi

.SS "\fBscifir::temperature\fP operator''_uK (unsigned long long int x)"

.PP
Definition at line \fB785\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
786 {
787     return scifir::temperature((long double)x, "uK");
788 }
.fi

.SS "\fBscifir::length\fP operator''_um (long double x)"

.PP
Definition at line \fB1145\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1146 {
1147     return scifir::length(x, "um");
1148 }
.fi

.SS "\fBscifir::length\fP operator''_um (unsigned long long int x)"

.PP
Definition at line \fB425\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
426 {
427     return scifir::length((long double)x, "um");
428 }
.fi

.SS "\fBscifir::mole\fP operator''_umol (long double x)"

.PP
Definition at line \fB1610\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1611 {
1612     return scifir::mole(x, "umol");
1613 }
.fi

.SS "\fBscifir::mole\fP operator''_umol (unsigned long long int x)"

.PP
Definition at line \fB890\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
891 {
892     return scifir::mole((long double)x, "umol");
893 }
.fi

.SS "\fBscifir::time_duration\fP operator''_us (long double x)"

.PP
Definition at line \fB1190\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1191 {
1192     return scifir::time_duration(x, "us");
1193 }
.fi

.SS "\fBscifir::time_duration\fP operator''_us (unsigned long long int x)"

.PP
Definition at line \fB470\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
471 {
472     return scifir::time_duration((long double)x, "us");
473 }
.fi

.SS "scifir::data operator''_YB (long double x)"

.PP
Definition at line \fB1750\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1751 {
1752     return scifir::data(x, "YB");
1753 }
.fi

.SS "scifir::data operator''_YB (unsigned long long int x)"

.PP
Definition at line \fB1030\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1031 {
1032     return scifir::data((long double)x, "YB");
1033 }
.fi

.SS "\fBscifir::charge\fP operator''_YC (long double x)"

.PP
Definition at line \fB1330\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1331 {
1332     return scifir::charge(x, "YC");
1333 }
.fi

.SS "\fBscifir::charge\fP operator''_yC (long double x)"

.PP
Definition at line \fB1430\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1431 {
1432     return scifir::charge(x, "yC");
1433 }
.fi

.SS "\fBscifir::charge\fP operator''_YC (unsigned long long int x)"

.PP
Definition at line \fB610\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
611 {
612     return scifir::charge((long double)x, "YC");
613 }
.fi

.SS "\fBscifir::charge\fP operator''_yC (unsigned long long int x)"

.PP
Definition at line \fB710\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
711 {
712     return scifir::charge((long double)x, "yC");
713 }
.fi

.SS "\fBscifir::light\fP operator''_Ycd (long double x)"

.PP
Definition at line \fB1645\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1646 {
1647     return scifir::light(x, "Ycd");
1648 }
.fi

.SS "\fBscifir::light\fP operator''_ycd (long double x)"

.PP
Definition at line \fB1745\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1746 {
1747     return scifir::light(x, "ycd");
1748 }
.fi

.SS "\fBscifir::light\fP operator''_Ycd (unsigned long long int x)"

.PP
Definition at line \fB925\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
926 {
927     return scifir::light((long double)x, "Ycd");
928 }
.fi

.SS "\fBscifir::light\fP operator''_ycd (unsigned long long int x)"

.PP
Definition at line \fB1025\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1026 {
1027     return scifir::light((long double)x, "ycd");
1028 }
.fi

.SS "\fBscifir::mass\fP operator''_Yg (long double x)"

.PP
Definition at line \fB1225\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1226 {
1227     return scifir::mass(x, "Yg");
1228 }
.fi

.SS "\fBscifir::mass\fP operator''_yg (long double x)"

.PP
Definition at line \fB1325\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1326 {
1327     return scifir::mass(x, "yg");
1328 }
.fi

.SS "\fBscifir::mass\fP operator''_Yg (unsigned long long int x)"

.PP
Definition at line \fB505\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
506 {
507     return scifir::mass((long double)x, "Yg");
508 }
.fi

.SS "\fBscifir::mass\fP operator''_yg (unsigned long long int x)"

.PP
Definition at line \fB605\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
606 {
607     return scifir::mass((long double)x, "yg");
608 }
.fi

.SS "\fBscifir::temperature\fP operator''_YK (long double x)"

.PP
Definition at line \fB1435\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1436 {
1437     return scifir::temperature(x, "YK");
1438 }
.fi

.SS "\fBscifir::temperature\fP operator''_yK (long double x)"

.PP
Definition at line \fB1535\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1536 {
1537     return scifir::temperature(x, "yK");
1538 }
.fi

.SS "\fBscifir::temperature\fP operator''_YK (unsigned long long int x)"

.PP
Definition at line \fB715\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
716 {
717     return scifir::temperature((long double)x, "YK");
718 }
.fi

.SS "\fBscifir::temperature\fP operator''_yK (unsigned long long int x)"

.PP
Definition at line \fB815\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
816 {
817     return scifir::temperature((long double)x, "yK");
818 }
.fi

.SS "\fBscifir::length\fP operator''_Ym (long double x)"

.PP
Definition at line \fB1075\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1076 {
1077     return scifir::length(x, "Ym");
1078 }
.fi

.SS "\fBscifir::length\fP operator''_ym (long double x)"

.PP
Definition at line \fB1175\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1176 {
1177     return scifir::length(x, "ym");
1178 }
.fi

.SS "\fBscifir::length\fP operator''_Ym (unsigned long long int x)"

.PP
Definition at line \fB355\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
356 {
357     return scifir::length((long double)x, "Ym");
358 }
.fi

.SS "\fBscifir::length\fP operator''_ym (unsigned long long int x)"

.PP
Definition at line \fB455\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
456 {
457     return scifir::length((long double)x, "ym");
458 }
.fi

.SS "\fBscifir::mole\fP operator''_Ymol (long double x)"

.PP
Definition at line \fB1540\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1541 {
1542     return scifir::mole(x, "Ymol");
1543 }
.fi

.SS "\fBscifir::mole\fP operator''_ymol (long double x)"

.PP
Definition at line \fB1640\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1641 {
1642     return scifir::mole(x, "ymol");
1643 }
.fi

.SS "\fBscifir::mole\fP operator''_Ymol (unsigned long long int x)"

.PP
Definition at line \fB820\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
821 {
822     return scifir::mole((long double)x, "Ymol");
823 }
.fi

.SS "\fBscifir::mole\fP operator''_ymol (unsigned long long int x)"

.PP
Definition at line \fB920\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
921 {
922     return scifir::mole((long double)x, "ymol");
923 }
.fi

.SS "\fBscifir::time_duration\fP operator''_ys (long double x)"

.PP
Definition at line \fB1220\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1221 {
1222     return scifir::time_duration(x, "ys");
1223 }
.fi

.SS "\fBscifir::time_duration\fP operator''_ys (unsigned long long int x)"

.PP
Definition at line \fB500\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
501 {
502     return scifir::time_duration((long double)x, "ys");
503 }
.fi

.SS "scifir::data operator''_ZB (long double x)"

.PP
Definition at line \fB1755\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1756 {
1757     return scifir::data(x, "ZB");
1758 }
.fi

.SS "scifir::data operator''_ZB (unsigned long long int x)"

.PP
Definition at line \fB1035\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1036 {
1037     return scifir::data((long double)x, "ZB");
1038 }
.fi

.SS "\fBscifir::charge\fP operator''_ZC (long double x)"

.PP
Definition at line \fB1335\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1336 {
1337     return scifir::charge(x, "ZC");
1338 }
.fi

.SS "\fBscifir::charge\fP operator''_zC (long double x)"

.PP
Definition at line \fB1425\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1426 {
1427     return scifir::charge(x, "zC");
1428 }
.fi

.SS "\fBscifir::charge\fP operator''_ZC (unsigned long long int x)"

.PP
Definition at line \fB615\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
616 {
617     return scifir::charge((long double)x, "ZC");
618 }
.fi

.SS "\fBscifir::charge\fP operator''_zC (unsigned long long int x)"

.PP
Definition at line \fB705\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
706 {
707     return scifir::charge((long double)x, "zC");
708 }
.fi

.SS "\fBscifir::light\fP operator''_Zcd (long double x)"

.PP
Definition at line \fB1650\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1651 {
1652     return scifir::light(x, "Zcd");
1653 }
.fi

.SS "\fBscifir::light\fP operator''_zcd (long double x)"

.PP
Definition at line \fB1740\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1741 {
1742     return scifir::light(x, "zcd");
1743 }
.fi

.SS "\fBscifir::light\fP operator''_Zcd (unsigned long long int x)"

.PP
Definition at line \fB930\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
931 {
932     return scifir::light((long double)x, "Zcd");
933 }
.fi

.SS "\fBscifir::light\fP operator''_zcd (unsigned long long int x)"

.PP
Definition at line \fB1020\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1021 {
1022     return scifir::light((long double)x, "zcd");
1023 }
.fi

.SS "\fBscifir::mass\fP operator''_Zg (long double x)"

.PP
Definition at line \fB1230\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1231 {
1232     return scifir::mass(x, "Zg");
1233 }
.fi

.SS "\fBscifir::mass\fP operator''_zg (long double x)"

.PP
Definition at line \fB1320\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1321 {
1322     return scifir::mass(x, "zg");
1323 }
.fi

.SS "\fBscifir::mass\fP operator''_Zg (unsigned long long int x)"

.PP
Definition at line \fB510\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
511 {
512     return scifir::mass((long double)x, "Zg");
513 }
.fi

.SS "\fBscifir::mass\fP operator''_zg (unsigned long long int x)"

.PP
Definition at line \fB600\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
601 {
602     return scifir::mass((long double)x, "zg");
603 }
.fi

.SS "\fBscifir::temperature\fP operator''_ZK (long double x)"

.PP
Definition at line \fB1440\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1441 {
1442     return scifir::temperature(x, "ZK");
1443 }
.fi

.SS "\fBscifir::temperature\fP operator''_zK (long double x)"

.PP
Definition at line \fB1530\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1531 {
1532     return scifir::temperature(x, "zK");
1533 }
.fi

.SS "\fBscifir::temperature\fP operator''_ZK (unsigned long long int x)"

.PP
Definition at line \fB720\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
721 {
722     return scifir::temperature((long double)x, "ZK");
723 }
.fi

.SS "\fBscifir::temperature\fP operator''_zK (unsigned long long int x)"

.PP
Definition at line \fB810\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
811 {
812     return scifir::temperature((long double)x, "zK");
813 }
.fi

.SS "\fBscifir::length\fP operator''_Zm (long double x)"

.PP
Definition at line \fB1080\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1081 {
1082     return scifir::length(x, "Zm");
1083 }
.fi

.SS "\fBscifir::length\fP operator''_zm (long double x)"

.PP
Definition at line \fB1170\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1171 {
1172     return scifir::length(x, "zm");
1173 }
.fi

.SS "\fBscifir::length\fP operator''_Zm (unsigned long long int x)"

.PP
Definition at line \fB360\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
361 {
362     return scifir::length((long double)x, "Zm");
363 }
.fi

.SS "\fBscifir::length\fP operator''_zm (unsigned long long int x)"

.PP
Definition at line \fB450\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
451 {
452     return scifir::length((long double)x, "zm");
453 }
.fi

.SS "\fBscifir::mole\fP operator''_Zmol (long double x)"

.PP
Definition at line \fB1545\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1546 {
1547     return scifir::mole(x, "Zmol");
1548 }
.fi

.SS "\fBscifir::mole\fP operator''_zmol (long double x)"

.PP
Definition at line \fB1635\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1636 {
1637     return scifir::mole(x, "zmol");
1638 }
.fi

.SS "\fBscifir::mole\fP operator''_Zmol (unsigned long long int x)"

.PP
Definition at line \fB825\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
826 {
827     return scifir::mole((long double)x, "Zmol");
828 }
.fi

.SS "\fBscifir::mole\fP operator''_zmol (unsigned long long int x)"

.PP
Definition at line \fB915\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
916 {
917     return scifir::mole((long double)x, "zmol");
918 }
.fi

.SS "\fBscifir::time_duration\fP operator''_zs (long double x)"

.PP
Definition at line \fB1215\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
1216 {
1217     return scifir::time_duration(x, "zs");
1218 }
.fi

.SS "\fBscifir::time_duration\fP operator''_zs (unsigned long long int x)"

.PP
Definition at line \fB495\fP of file \fBunit_basic\&.cpp\fP\&..PP
.nf
496 {
497     return scifir::time_duration((long double)x, "zs");
498 }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for scifir-units from the source code\&.
