#ifndef SCIFIR_UNITS_UNITS_SPECIAL_NAMES_HPP_INCLUDED
#define SCIFIR_UNITS_UNITS_SPECIAL_NAMES_HPP_INCLUDED

#include "./base_units.hpp"

#include "../derived_units/electronics_units.hpp"
#include "../derived_units/physics_units.hpp"
#include "../derived_units/radiometry_units.hpp"
#include "../derived_units/space_units.hpp"
#include "../derived_units/chemistry_units.hpp"

scifir::frequency operator"" _QHz(unsigned long long int);
scifir::frequency operator"" _RHz(unsigned long long int);
scifir::frequency operator"" _YHz(unsigned long long int);
scifir::frequency operator"" _ZHz(unsigned long long int);
scifir::frequency operator"" _EHz(unsigned long long int);
scifir::frequency operator"" _PHz(unsigned long long int);
scifir::frequency operator"" _THz(unsigned long long int);
scifir::frequency operator"" _GHz(unsigned long long int);
scifir::frequency operator"" _MHz(unsigned long long int);
scifir::frequency operator"" _kHz(unsigned long long int);
scifir::frequency operator"" _hHz(unsigned long long int);
scifir::frequency operator"" _daHz(unsigned long long int);
scifir::frequency operator"" _Hz(unsigned long long int);
scifir::frequency operator"" _dHz(unsigned long long int);
scifir::frequency operator"" _cHz(unsigned long long int);
scifir::frequency operator"" _mHz(unsigned long long int);
scifir::frequency operator"" _µHz(unsigned long long int);
scifir::frequency operator"" _nHz(unsigned long long int);
scifir::frequency operator"" _pHz(unsigned long long int);
scifir::frequency operator"" _fHz(unsigned long long int);
scifir::frequency operator"" _aHz(unsigned long long int);
scifir::frequency operator"" _zHz(unsigned long long int);
scifir::frequency operator"" _yHz(unsigned long long int);
scifir::frequency operator"" _rHz(unsigned long long int);
scifir::frequency operator"" _qHz(unsigned long long int);

scifir::force operator"" _QN(unsigned long long int);
scifir::force operator"" _RN(unsigned long long int);
scifir::force operator"" _YN(unsigned long long int);
scifir::force operator"" _ZN(unsigned long long int);
scifir::force operator"" _EN(unsigned long long int);
scifir::force operator"" _PN(unsigned long long int);
scifir::force operator"" _TN(unsigned long long int);
scifir::force operator"" _GN(unsigned long long int);
scifir::force operator"" _MN(unsigned long long int);
scifir::force operator"" _kN(unsigned long long int);
scifir::force operator"" _hN(unsigned long long int);
scifir::force operator"" _daN(unsigned long long int);
scifir::force operator"" _N(unsigned long long int);
scifir::force operator"" _dN(unsigned long long int);
scifir::force operator"" _cN(unsigned long long int);
scifir::force operator"" _mN(unsigned long long int);
scifir::force operator"" _µN(unsigned long long int);
scifir::force operator"" _nN(unsigned long long int);
scifir::force operator"" _pN(unsigned long long int);
scifir::force operator"" _fN(unsigned long long int);
scifir::force operator"" _aN(unsigned long long int);
scifir::force operator"" _zN(unsigned long long int);
scifir::force operator"" _yN(unsigned long long int);
scifir::force operator"" _rN(unsigned long long int);
scifir::force operator"" _qN(unsigned long long int);

scifir::pressure operator"" _QPa(unsigned long long int);
scifir::pressure operator"" _RPa(unsigned long long int);
scifir::pressure operator"" _YPa(unsigned long long int);
scifir::pressure operator"" _ZPa(unsigned long long int);
scifir::pressure operator"" _EPa(unsigned long long int);
scifir::pressure operator"" _PPa(unsigned long long int);
scifir::pressure operator"" _TPa(unsigned long long int);
scifir::pressure operator"" _GPa(unsigned long long int);
scifir::pressure operator"" _MPa(unsigned long long int);
scifir::pressure operator"" _kPa(unsigned long long int);
scifir::pressure operator"" _hPa(unsigned long long int);
scifir::pressure operator"" _daPa(unsigned long long int);
scifir::pressure operator"" _Pa(unsigned long long int);
scifir::pressure operator"" _dPa(unsigned long long int);
scifir::pressure operator"" _cPa(unsigned long long int);
scifir::pressure operator"" _mPa(unsigned long long int);
scifir::pressure operator"" _µPa(unsigned long long int);
scifir::pressure operator"" _nPa(unsigned long long int);
scifir::pressure operator"" _pPa(unsigned long long int);
scifir::pressure operator"" _fPa(unsigned long long int);
scifir::pressure operator"" _aPa(unsigned long long int);
scifir::pressure operator"" _zPa(unsigned long long int);
scifir::pressure operator"" _yPa(unsigned long long int);
scifir::pressure operator"" _rPa(unsigned long long int);
scifir::pressure operator"" _qPa(unsigned long long int);

scifir::energy operator"" _QJ(unsigned long long int);
scifir::energy operator"" _RJ(unsigned long long int);
scifir::energy operator"" _YJ(unsigned long long int);
scifir::energy operator"" _ZJ(unsigned long long int);
scifir::energy operator"" _EJ(unsigned long long int);
scifir::energy operator"" _PJ(unsigned long long int);
scifir::energy operator"" _TJ(unsigned long long int);
scifir::energy operator"" _GJ(unsigned long long int);
scifir::energy operator"" _MJ(unsigned long long int);
scifir::energy operator"" _kJ(unsigned long long int);
scifir::energy operator"" _hJ(unsigned long long int);
scifir::energy operator"" _daJ(unsigned long long int);
scifir::energy operator"" _J(unsigned long long int);
scifir::energy operator"" _dJ(unsigned long long int);
scifir::energy operator"" _cJ(unsigned long long int);
scifir::energy operator"" _mJ(unsigned long long int);
scifir::energy operator"" _µJ(unsigned long long int);
scifir::energy operator"" _nJ(unsigned long long int);
scifir::energy operator"" _pJ(unsigned long long int);
scifir::energy operator"" _fJ(unsigned long long int);
scifir::energy operator"" _aJ(unsigned long long int);
scifir::energy operator"" _zJ(unsigned long long int);
scifir::energy operator"" _yJ(unsigned long long int);
scifir::energy operator"" _rJ(unsigned long long int);
scifir::energy operator"" _qJ(unsigned long long int);

scifir::power operator"" _QW(unsigned long long int);
scifir::power operator"" _RW(unsigned long long int);
scifir::power operator"" _YW(unsigned long long int);
scifir::power operator"" _ZW(unsigned long long int);
scifir::power operator"" _EW(unsigned long long int);
scifir::power operator"" _PW(unsigned long long int);
scifir::power operator"" _TW(unsigned long long int);
scifir::power operator"" _GW(unsigned long long int);
scifir::power operator"" _MW(unsigned long long int);
scifir::power operator"" _kW(unsigned long long int);
scifir::power operator"" _hW(unsigned long long int);
scifir::power operator"" _daW(unsigned long long int);
scifir::power operator"" _W(unsigned long long int);
scifir::power operator"" _dW(unsigned long long int);
scifir::power operator"" _cW(unsigned long long int);
scifir::power operator"" _mW(unsigned long long int);
scifir::power operator"" _µW(unsigned long long int);
scifir::power operator"" _nW(unsigned long long int);
scifir::power operator"" _pW(unsigned long long int);
scifir::power operator"" _fW(unsigned long long int);
scifir::power operator"" _aW(unsigned long long int);
scifir::power operator"" _zW(unsigned long long int);
scifir::power operator"" _yW(unsigned long long int);
scifir::power operator"" _rW(unsigned long long int);
scifir::power operator"" _qW(unsigned long long int);

scifir::electric_current operator"" _QA(unsigned long long int);
scifir::electric_current operator"" _RA(unsigned long long int);
scifir::electric_current operator"" _YA(unsigned long long int);
scifir::electric_current operator"" _ZA(unsigned long long int);
scifir::electric_current operator"" _EA(unsigned long long int);
scifir::electric_current operator"" _PA(unsigned long long int);
scifir::electric_current operator"" _TA(unsigned long long int);
scifir::electric_current operator"" _GA(unsigned long long int);
scifir::electric_current operator"" _MA(unsigned long long int);
scifir::electric_current operator"" _kA(unsigned long long int);
scifir::electric_current operator"" _hA(unsigned long long int);
scifir::electric_current operator"" _daA(unsigned long long int);
scifir::electric_current operator"" _A(unsigned long long int);
scifir::electric_current operator"" _dA(unsigned long long int);
scifir::electric_current operator"" _cA(unsigned long long int);
scifir::electric_current operator"" _mA(unsigned long long int);
scifir::electric_current operator"" _µA(unsigned long long int);
scifir::electric_current operator"" _nA(unsigned long long int);
scifir::electric_current operator"" _pA(unsigned long long int);
scifir::electric_current operator"" _fA(unsigned long long int);
scifir::electric_current operator"" _aA(unsigned long long int);
scifir::electric_current operator"" _zA(unsigned long long int);
scifir::electric_current operator"" _yA(unsigned long long int);
scifir::electric_current operator"" _rA(unsigned long long int);
scifir::electric_current operator"" _qA(unsigned long long int);

scifir::voltage operator"" _QV(unsigned long long int);
scifir::voltage operator"" _RV(unsigned long long int);
scifir::voltage operator"" _YV(unsigned long long int);
scifir::voltage operator"" _ZV(unsigned long long int);
scifir::voltage operator"" _EV(unsigned long long int);
scifir::voltage operator"" _PV(unsigned long long int);
scifir::voltage operator"" _TV(unsigned long long int);
scifir::voltage operator"" _GV(unsigned long long int);
scifir::voltage operator"" _MV(unsigned long long int);
scifir::voltage operator"" _kV(unsigned long long int);
scifir::voltage operator"" _hV(unsigned long long int);
scifir::voltage operator"" _daV(unsigned long long int);
scifir::voltage operator"" _V(unsigned long long int);
scifir::voltage operator"" _dV(unsigned long long int);
scifir::voltage operator"" _cV(unsigned long long int);
scifir::voltage operator"" _mV(unsigned long long int);
scifir::voltage operator"" _µV(unsigned long long int);
scifir::voltage operator"" _nV(unsigned long long int);
scifir::voltage operator"" _pV(unsigned long long int);
scifir::voltage operator"" _fV(unsigned long long int);
scifir::voltage operator"" _aV(unsigned long long int);
scifir::voltage operator"" _zV(unsigned long long int);
scifir::voltage operator"" _yV(unsigned long long int);
scifir::voltage operator"" _rV(unsigned long long int);
scifir::voltage operator"" _qV(unsigned long long int);

scifir::capacitance operator"" _QF(unsigned long long int);
scifir::capacitance operator"" _RF(unsigned long long int);
scifir::capacitance operator"" _YF(unsigned long long int);
scifir::capacitance operator"" _ZF(unsigned long long int);
scifir::capacitance operator"" _EF(unsigned long long int);
scifir::capacitance operator"" _PF(unsigned long long int);
scifir::capacitance operator"" _TF(unsigned long long int);
scifir::capacitance operator"" _GF(unsigned long long int);
scifir::capacitance operator"" _MF(unsigned long long int);
scifir::capacitance operator"" _kF(unsigned long long int);
scifir::capacitance operator"" _hF(unsigned long long int);
scifir::capacitance operator"" _daF(unsigned long long int);
scifir::capacitance operator"" _F(unsigned long long int);
scifir::capacitance operator"" _dF(unsigned long long int);
scifir::capacitance operator"" _cF(unsigned long long int);
scifir::capacitance operator"" _mF(unsigned long long int);
scifir::capacitance operator"" _µF(unsigned long long int);
scifir::capacitance operator"" _nF(unsigned long long int);
scifir::capacitance operator"" _pF(unsigned long long int);
scifir::capacitance operator"" _fF(unsigned long long int);
scifir::capacitance operator"" _aF(unsigned long long int);
scifir::capacitance operator"" _zF(unsigned long long int);
scifir::capacitance operator"" _yF(unsigned long long int);
scifir::capacitance operator"" _rF(unsigned long long int);
scifir::capacitance operator"" _qF(unsigned long long int);

#ifdef IS_UNIX
scifir::resistance operator"" _QΩ(unsigned long long int);
scifir::resistance operator"" _RΩ(unsigned long long int);
scifir::resistance operator"" _YΩ(unsigned long long int);
scifir::resistance operator"" _ZΩ(unsigned long long int);
scifir::resistance operator"" _EΩ(unsigned long long int);
scifir::resistance operator"" _PΩ(unsigned long long int);
scifir::resistance operator"" _TΩ(unsigned long long int);
scifir::resistance operator"" _GΩ(unsigned long long int);
scifir::resistance operator"" _MΩ(unsigned long long int);
scifir::resistance operator"" _kΩ(unsigned long long int);
scifir::resistance operator"" _hΩ(unsigned long long int);
scifir::resistance operator"" _daΩ(unsigned long long int);
scifir::resistance operator"" _Ω(unsigned long long int);
scifir::resistance operator"" _dΩ(unsigned long long int);
scifir::resistance operator"" _cΩ(unsigned long long int);
scifir::resistance operator"" _mΩ(unsigned long long int);
scifir::resistance operator"" _µΩ(unsigned long long int);
scifir::resistance operator"" _nΩ(unsigned long long int);
scifir::resistance operator"" _pΩ(unsigned long long int);
scifir::resistance operator"" _fΩ(unsigned long long int);
scifir::resistance operator"" _aΩ(unsigned long long int);
scifir::resistance operator"" _zΩ(unsigned long long int);
scifir::resistance operator"" _yΩ(unsigned long long int);
scifir::resistance operator"" _rΩ(unsigned long long int);
scifir::resistance operator"" _qΩ(unsigned long long int);
#endif

scifir::electric_conductance operator"" _QS(unsigned long long int);
scifir::electric_conductance operator"" _RS(unsigned long long int);
scifir::electric_conductance operator"" _YS(unsigned long long int);
scifir::electric_conductance operator"" _ZS(unsigned long long int);
scifir::electric_conductance operator"" _ES(unsigned long long int);
scifir::electric_conductance operator"" _PS(unsigned long long int);
scifir::electric_conductance operator"" _TS(unsigned long long int);
scifir::electric_conductance operator"" _GS(unsigned long long int);
scifir::electric_conductance operator"" _MS(unsigned long long int);
scifir::electric_conductance operator"" _kS(unsigned long long int);
scifir::electric_conductance operator"" _hS(unsigned long long int);
scifir::electric_conductance operator"" _daS(unsigned long long int);
scifir::electric_conductance operator"" _S(unsigned long long int);
scifir::electric_conductance operator"" _dS(unsigned long long int);
scifir::electric_conductance operator"" _cS(unsigned long long int);
scifir::electric_conductance operator"" _mS(unsigned long long int);
scifir::electric_conductance operator"" _µS(unsigned long long int);
scifir::electric_conductance operator"" _nS(unsigned long long int);
scifir::electric_conductance operator"" _pS(unsigned long long int);
scifir::electric_conductance operator"" _fS(unsigned long long int);
scifir::electric_conductance operator"" _aS(unsigned long long int);
scifir::electric_conductance operator"" _zS(unsigned long long int);
scifir::electric_conductance operator"" _yS(unsigned long long int);
scifir::electric_conductance operator"" _rS(unsigned long long int);
scifir::electric_conductance operator"" _qS(unsigned long long int);

scifir::magnetic_flux operator"" _QWb(unsigned long long int);
scifir::magnetic_flux operator"" _RWb(unsigned long long int);
scifir::magnetic_flux operator"" _YWb(unsigned long long int);
scifir::magnetic_flux operator"" _ZWb(unsigned long long int);
scifir::magnetic_flux operator"" _EWb(unsigned long long int);
scifir::magnetic_flux operator"" _PWb(unsigned long long int);
scifir::magnetic_flux operator"" _TWb(unsigned long long int);
scifir::magnetic_flux operator"" _GWb(unsigned long long int);
scifir::magnetic_flux operator"" _MWb(unsigned long long int);
scifir::magnetic_flux operator"" _kWb(unsigned long long int);
scifir::magnetic_flux operator"" _hWb(unsigned long long int);
scifir::magnetic_flux operator"" _daWb(unsigned long long int);
scifir::magnetic_flux operator"" _Wb(unsigned long long int);
scifir::magnetic_flux operator"" _dWb(unsigned long long int);
scifir::magnetic_flux operator"" _cWb(unsigned long long int);
scifir::magnetic_flux operator"" _mWb(unsigned long long int);
scifir::magnetic_flux operator"" _µWb(unsigned long long int);
scifir::magnetic_flux operator"" _nWb(unsigned long long int);
scifir::magnetic_flux operator"" _pWb(unsigned long long int);
scifir::magnetic_flux operator"" _fWb(unsigned long long int);
scifir::magnetic_flux operator"" _aWb(unsigned long long int);
scifir::magnetic_flux operator"" _zWb(unsigned long long int);
scifir::magnetic_flux operator"" _yWb(unsigned long long int);
scifir::magnetic_flux operator"" _rWb(unsigned long long int);
scifir::magnetic_flux operator"" _qWb(unsigned long long int);

scifir::magnetic_flux_density operator"" _QT(unsigned long long int);
scifir::magnetic_flux_density operator"" _RT(unsigned long long int);
scifir::magnetic_flux_density operator"" _YT(unsigned long long int);
scifir::magnetic_flux_density operator"" _ZT(unsigned long long int);
scifir::magnetic_flux_density operator"" _ET(unsigned long long int);
scifir::magnetic_flux_density operator"" _PT(unsigned long long int);
scifir::magnetic_flux_density operator"" _TT(unsigned long long int);
scifir::magnetic_flux_density operator"" _GT(unsigned long long int);
//scifir::magnetic_flux_density operator"" _MT(unsigned long long int);
scifir::magnetic_flux_density operator"" _kT(unsigned long long int);
scifir::magnetic_flux_density operator"" _hT(unsigned long long int);
scifir::magnetic_flux_density operator"" _daT(unsigned long long int);
//scifir::magnetic_flux_density operator"" _T(unsigned long long int);
scifir::magnetic_flux_density operator"" _dT(unsigned long long int);
scifir::magnetic_flux_density operator"" _cT(unsigned long long int);
scifir::magnetic_flux_density operator"" _mT(unsigned long long int);
scifir::magnetic_flux_density operator"" _µT(unsigned long long int);
scifir::magnetic_flux_density operator"" _nT(unsigned long long int);
scifir::magnetic_flux_density operator"" _pT(unsigned long long int);
scifir::magnetic_flux_density operator"" _fT(unsigned long long int);
scifir::magnetic_flux_density operator"" _aT(unsigned long long int);
scifir::magnetic_flux_density operator"" _zT(unsigned long long int);
scifir::magnetic_flux_density operator"" _yT(unsigned long long int);
scifir::magnetic_flux_density operator"" _rT(unsigned long long int);
scifir::magnetic_flux_density operator"" _qT(unsigned long long int);

scifir::inductance operator"" _QH(unsigned long long int);
scifir::inductance operator"" _RH(unsigned long long int);
scifir::inductance operator"" _YH(unsigned long long int);
scifir::inductance operator"" _ZH(unsigned long long int);
scifir::inductance operator"" _EH(unsigned long long int);
scifir::inductance operator"" _PH(unsigned long long int);
scifir::inductance operator"" _TH(unsigned long long int);
scifir::inductance operator"" _GH(unsigned long long int);
scifir::inductance operator"" _MH(unsigned long long int);
scifir::inductance operator"" _kH(unsigned long long int);
scifir::inductance operator"" _hH(unsigned long long int);
scifir::inductance operator"" _daH(unsigned long long int);
scifir::inductance operator"" _H(unsigned long long int);
scifir::inductance operator"" _dH(unsigned long long int);
scifir::inductance operator"" _cH(unsigned long long int);
scifir::inductance operator"" _mH(unsigned long long int);
scifir::inductance operator"" _µH(unsigned long long int);
scifir::inductance operator"" _nH(unsigned long long int);
scifir::inductance operator"" _pH(unsigned long long int);
scifir::inductance operator"" _fH(unsigned long long int);
scifir::inductance operator"" _aH(unsigned long long int);
scifir::inductance operator"" _zH(unsigned long long int);
scifir::inductance operator"" _yH(unsigned long long int);
scifir::inductance operator"" _rH(unsigned long long int);
scifir::inductance operator"" _qH(unsigned long long int);

scifir::temperature operator"" _celsius(unsigned long long int);

scifir::luminous_flux operator"" _Qlm(unsigned long long int);
scifir::luminous_flux operator"" _Rlm(unsigned long long int);
scifir::luminous_flux operator"" _Ylm(unsigned long long int);
scifir::luminous_flux operator"" _Zlm(unsigned long long int);
scifir::luminous_flux operator"" _Elm(unsigned long long int);
scifir::luminous_flux operator"" _Plm(unsigned long long int);
scifir::luminous_flux operator"" _Tlm(unsigned long long int);
scifir::luminous_flux operator"" _Glm(unsigned long long int);
scifir::luminous_flux operator"" _Mlm(unsigned long long int);
scifir::luminous_flux operator"" _klm(unsigned long long int);
scifir::luminous_flux operator"" _hlm(unsigned long long int);
scifir::luminous_flux operator"" _dalm(unsigned long long int);
scifir::luminous_flux operator"" _lm(unsigned long long int);
scifir::luminous_flux operator"" _dlm(unsigned long long int);
scifir::luminous_flux operator"" _clm(unsigned long long int);
scifir::luminous_flux operator"" _mlm(unsigned long long int);
scifir::luminous_flux operator"" _µlm(unsigned long long int);
scifir::luminous_flux operator"" _nlm(unsigned long long int);
scifir::luminous_flux operator"" _plm(unsigned long long int);
scifir::luminous_flux operator"" _flm(unsigned long long int);
scifir::luminous_flux operator"" _alm(unsigned long long int);
scifir::luminous_flux operator"" _zlm(unsigned long long int);
scifir::luminous_flux operator"" _ylm(unsigned long long int);
scifir::luminous_flux operator"" _rlm(unsigned long long int);
scifir::luminous_flux operator"" _qlm(unsigned long long int);

scifir::illuminance operator"" _Qlx(unsigned long long int);
scifir::illuminance operator"" _Rlx(unsigned long long int);
scifir::illuminance operator"" _Ylx(unsigned long long int);
scifir::illuminance operator"" _Zlx(unsigned long long int);
scifir::illuminance operator"" _Elx(unsigned long long int);
scifir::illuminance operator"" _Plx(unsigned long long int);
scifir::illuminance operator"" _Tlx(unsigned long long int);
scifir::illuminance operator"" _Glx(unsigned long long int);
scifir::illuminance operator"" _Mlx(unsigned long long int);
scifir::illuminance operator"" _klx(unsigned long long int);
scifir::illuminance operator"" _hlx(unsigned long long int);
scifir::illuminance operator"" _dalx(unsigned long long int);
scifir::illuminance operator"" _lx(unsigned long long int);
scifir::illuminance operator"" _dlx(unsigned long long int);
scifir::illuminance operator"" _clx(unsigned long long int);
scifir::illuminance operator"" _mlx(unsigned long long int);
scifir::illuminance operator"" _µlx(unsigned long long int);
scifir::illuminance operator"" _nlx(unsigned long long int);
scifir::illuminance operator"" _plx(unsigned long long int);
scifir::illuminance operator"" _flx(unsigned long long int);
scifir::illuminance operator"" _alx(unsigned long long int);
scifir::illuminance operator"" _zlx(unsigned long long int);
scifir::illuminance operator"" _ylx(unsigned long long int);
scifir::illuminance operator"" _rlx(unsigned long long int);
scifir::illuminance operator"" _qlx(unsigned long long int);

scifir::radioactivity operator"" _QBq(unsigned long long int);
scifir::radioactivity operator"" _RBq(unsigned long long int);
scifir::radioactivity operator"" _YBq(unsigned long long int);
scifir::radioactivity operator"" _ZBq(unsigned long long int);
scifir::radioactivity operator"" _EBq(unsigned long long int);
scifir::radioactivity operator"" _PBq(unsigned long long int);
scifir::radioactivity operator"" _TBq(unsigned long long int);
scifir::radioactivity operator"" _GBq(unsigned long long int);
scifir::radioactivity operator"" _MBq(unsigned long long int);
scifir::radioactivity operator"" _kBq(unsigned long long int);
scifir::radioactivity operator"" _hBq(unsigned long long int);
scifir::radioactivity operator"" _daBq(unsigned long long int);
scifir::radioactivity operator"" _Bq(unsigned long long int);
scifir::radioactivity operator"" _dBq(unsigned long long int);
scifir::radioactivity operator"" _cBq(unsigned long long int);
scifir::radioactivity operator"" _mBq(unsigned long long int);
scifir::radioactivity operator"" _µBq(unsigned long long int);
scifir::radioactivity operator"" _nBq(unsigned long long int);
scifir::radioactivity operator"" _pBq(unsigned long long int);
scifir::radioactivity operator"" _fBq(unsigned long long int);
scifir::radioactivity operator"" _aBq(unsigned long long int);
scifir::radioactivity operator"" _zBq(unsigned long long int);
scifir::radioactivity operator"" _yBq(unsigned long long int);
scifir::radioactivity operator"" _rBq(unsigned long long int);
scifir::radioactivity operator"" _qBq(unsigned long long int);

scifir::ionizing_radiation operator"" _QGy(unsigned long long int);
scifir::ionizing_radiation operator"" _RGy(unsigned long long int);
scifir::ionizing_radiation operator"" _YGy(unsigned long long int);
scifir::ionizing_radiation operator"" _ZGy(unsigned long long int);
scifir::ionizing_radiation operator"" _EGy(unsigned long long int);
scifir::ionizing_radiation operator"" _PGy(unsigned long long int);
scifir::ionizing_radiation operator"" _TGy(unsigned long long int);
scifir::ionizing_radiation operator"" _GGy(unsigned long long int);
scifir::ionizing_radiation operator"" _MGy(unsigned long long int);
scifir::ionizing_radiation operator"" _kGy(unsigned long long int);
scifir::ionizing_radiation operator"" _hGy(unsigned long long int);
scifir::ionizing_radiation operator"" _daGy(unsigned long long int);
scifir::ionizing_radiation operator"" _Gy(unsigned long long int);
scifir::ionizing_radiation operator"" _dGy(unsigned long long int);
scifir::ionizing_radiation operator"" _cGy(unsigned long long int);
scifir::ionizing_radiation operator"" _mGy(unsigned long long int);
scifir::ionizing_radiation operator"" _µGy(unsigned long long int);
scifir::ionizing_radiation operator"" _nGy(unsigned long long int);
scifir::ionizing_radiation operator"" _pGy(unsigned long long int);
scifir::ionizing_radiation operator"" _fGy(unsigned long long int);
scifir::ionizing_radiation operator"" _aGy(unsigned long long int);
scifir::ionizing_radiation operator"" _zGy(unsigned long long int);
scifir::ionizing_radiation operator"" _yGy(unsigned long long int);
scifir::ionizing_radiation operator"" _rGy(unsigned long long int);
scifir::ionizing_radiation operator"" _qGy(unsigned long long int);

scifir::ionizing_radiation operator"" _QSv(unsigned long long int);
scifir::ionizing_radiation operator"" _RSv(unsigned long long int);
scifir::ionizing_radiation operator"" _YSv(unsigned long long int);
scifir::ionizing_radiation operator"" _ZSv(unsigned long long int);
scifir::ionizing_radiation operator"" _ESv(unsigned long long int);
scifir::ionizing_radiation operator"" _PSv(unsigned long long int);
scifir::ionizing_radiation operator"" _TSv(unsigned long long int);
scifir::ionizing_radiation operator"" _GSv(unsigned long long int);
scifir::ionizing_radiation operator"" _MSv(unsigned long long int);
scifir::ionizing_radiation operator"" _kSv(unsigned long long int);
scifir::ionizing_radiation operator"" _hSv(unsigned long long int);
scifir::ionizing_radiation operator"" _daSv(unsigned long long int);
scifir::ionizing_radiation operator"" _Sv(unsigned long long int);
scifir::ionizing_radiation operator"" _dSv(unsigned long long int);
scifir::ionizing_radiation operator"" _cSv(unsigned long long int);
scifir::ionizing_radiation operator"" _mSv(unsigned long long int);
scifir::ionizing_radiation operator"" _µSv(unsigned long long int);
scifir::ionizing_radiation operator"" _nSv(unsigned long long int);
scifir::ionizing_radiation operator"" _pSv(unsigned long long int);
scifir::ionizing_radiation operator"" _fSv(unsigned long long int);
scifir::ionizing_radiation operator"" _aSv(unsigned long long int);
scifir::ionizing_radiation operator"" _zSv(unsigned long long int);
scifir::ionizing_radiation operator"" _ySv(unsigned long long int);
scifir::ionizing_radiation operator"" _rSv(unsigned long long int);
scifir::ionizing_radiation operator"" _qSv(unsigned long long int);

scifir::catalytic_activity operator"" _Qkat(unsigned long long int);
scifir::catalytic_activity operator"" _Rkat(unsigned long long int);
scifir::catalytic_activity operator"" _Ykat(unsigned long long int);
scifir::catalytic_activity operator"" _Zkat(unsigned long long int);
scifir::catalytic_activity operator"" _Ekat(unsigned long long int);
scifir::catalytic_activity operator"" _Pkat(unsigned long long int);
scifir::catalytic_activity operator"" _Tkat(unsigned long long int);
scifir::catalytic_activity operator"" _Gkat(unsigned long long int);
scifir::catalytic_activity operator"" _Mkat(unsigned long long int);
scifir::catalytic_activity operator"" _kkat(unsigned long long int);
scifir::catalytic_activity operator"" _hkat(unsigned long long int);
scifir::catalytic_activity operator"" _dakat(unsigned long long int);
scifir::catalytic_activity operator"" _kat(unsigned long long int);
scifir::catalytic_activity operator"" _dkat(unsigned long long int);
scifir::catalytic_activity operator"" _ckat(unsigned long long int);
scifir::catalytic_activity operator"" _mkat(unsigned long long int);
scifir::catalytic_activity operator"" _µkat(unsigned long long int);
scifir::catalytic_activity operator"" _nkat(unsigned long long int);
scifir::catalytic_activity operator"" _pkat(unsigned long long int);
scifir::catalytic_activity operator"" _fkat(unsigned long long int);
scifir::catalytic_activity operator"" _akat(unsigned long long int);
scifir::catalytic_activity operator"" _zkat(unsigned long long int);
scifir::catalytic_activity operator"" _ykat(unsigned long long int);
scifir::catalytic_activity operator"" _rkat(unsigned long long int);
scifir::catalytic_activity operator"" _qkat(unsigned long long int);

scifir::frequency operator"" _QHz(long double);
scifir::frequency operator"" _RHz(long double);
scifir::frequency operator"" _YHz(long double);
scifir::frequency operator"" _ZHz(long double);
scifir::frequency operator"" _EHz(long double);
scifir::frequency operator"" _PHz(long double);
scifir::frequency operator"" _THz(long double);
scifir::frequency operator"" _GHz(long double);
scifir::frequency operator"" _MHz(long double);
scifir::frequency operator"" _kHz(long double);
scifir::frequency operator"" _hHz(long double);
scifir::frequency operator"" _daHz(long double);
scifir::frequency operator"" _Hz(long double);
scifir::frequency operator"" _dHz(long double);
scifir::frequency operator"" _cHz(long double);
scifir::frequency operator"" _mHz(long double);
scifir::frequency operator"" _µHz(long double);
scifir::frequency operator"" _nHz(long double);
scifir::frequency operator"" _pHz(long double);
scifir::frequency operator"" _fHz(long double);
scifir::frequency operator"" _aHz(long double);
scifir::frequency operator"" _zHz(long double);
scifir::frequency operator"" _yHz(long double);
scifir::frequency operator"" _rHz(long double);
scifir::frequency operator"" _qHz(long double);

scifir::force operator"" _QN(long double);
scifir::force operator"" _RN(long double);
scifir::force operator"" _YN(long double);
scifir::force operator"" _ZN(long double);
scifir::force operator"" _EN(long double);
scifir::force operator"" _PN(long double);
scifir::force operator"" _TN(long double);
scifir::force operator"" _GN(long double);
scifir::force operator"" _MN(long double);
scifir::force operator"" _kN(long double);
scifir::force operator"" _hN(long double);
scifir::force operator"" _daN(long double);
scifir::force operator"" _N(long double);
scifir::force operator"" _dN(long double);
scifir::force operator"" _cN(long double);
scifir::force operator"" _mN(long double);
scifir::force operator"" _µN(long double);
scifir::force operator"" _nN(long double);
scifir::force operator"" _pN(long double);
scifir::force operator"" _fN(long double);
scifir::force operator"" _aN(long double);
scifir::force operator"" _zN(long double);
scifir::force operator"" _yN(long double);
scifir::force operator"" _rN(long double);
scifir::force operator"" _qN(long double);

scifir::pressure operator"" _QPa(long double);
scifir::pressure operator"" _RPa(long double);
scifir::pressure operator"" _YPa(long double);
scifir::pressure operator"" _ZPa(long double);
scifir::pressure operator"" _EPa(long double);
scifir::pressure operator"" _PPa(long double);
scifir::pressure operator"" _TPa(long double);
scifir::pressure operator"" _GPa(long double);
scifir::pressure operator"" _MPa(long double);
scifir::pressure operator"" _kPa(long double);
scifir::pressure operator"" _hPa(long double);
scifir::pressure operator"" _daPa(long double);
scifir::pressure operator"" _Pa(long double);
scifir::pressure operator"" _dPa(long double);
scifir::pressure operator"" _cPa(long double);
scifir::pressure operator"" _mPa(long double);
scifir::pressure operator"" _µPa(long double);
scifir::pressure operator"" _nPa(long double);
scifir::pressure operator"" _pPa(long double);
scifir::pressure operator"" _fPa(long double);
scifir::pressure operator"" _aPa(long double);
scifir::pressure operator"" _zPa(long double);
scifir::pressure operator"" _yPa(long double);
scifir::pressure operator"" _rPa(long double);
scifir::pressure operator"" _qPa(long double);

scifir::energy operator"" _QJ(long double);
scifir::energy operator"" _RJ(long double);
scifir::energy operator"" _YJ(long double);
scifir::energy operator"" _ZJ(long double);
scifir::energy operator"" _EJ(long double);
scifir::energy operator"" _PJ(long double);
scifir::energy operator"" _TJ(long double);
scifir::energy operator"" _GJ(long double);
scifir::energy operator"" _MJ(long double);
scifir::energy operator"" _kJ(long double);
scifir::energy operator"" _hJ(long double);
scifir::energy operator"" _daJ(long double);
scifir::energy operator"" _J(long double);
scifir::energy operator"" _dJ(long double);
scifir::energy operator"" _cJ(long double);
scifir::energy operator"" _mJ(long double);
scifir::energy operator"" _µJ(long double);
scifir::energy operator"" _nJ(long double);
scifir::energy operator"" _pJ(long double);
scifir::energy operator"" _fJ(long double);
scifir::energy operator"" _aJ(long double);
scifir::energy operator"" _zJ(long double);
scifir::energy operator"" _yJ(long double);
scifir::energy operator"" _rJ(long double);
scifir::energy operator"" _qJ(long double);

scifir::power operator"" _QW(long double);
scifir::power operator"" _RW(long double);
scifir::power operator"" _YW(long double);
scifir::power operator"" _ZW(long double);
scifir::power operator"" _EW(long double);
scifir::power operator"" _PW(long double);
scifir::power operator"" _TW(long double);
scifir::power operator"" _GW(long double);
scifir::power operator"" _MW(long double);
scifir::power operator"" _kW(long double);
scifir::power operator"" _hW(long double);
scifir::power operator"" _daW(long double);
scifir::power operator"" _W(long double);
scifir::power operator"" _dW(long double);
scifir::power operator"" _cW(long double);
scifir::power operator"" _mW(long double);
scifir::power operator"" _µW(long double);
scifir::power operator"" _nW(long double);
scifir::power operator"" _pW(long double);
scifir::power operator"" _fW(long double);
scifir::power operator"" _aW(long double);
scifir::power operator"" _zW(long double);
scifir::power operator"" _yW(long double);
scifir::power operator"" _rW(long double);
scifir::power operator"" _qW(long double);

scifir::electric_current operator"" _QA(long double);
scifir::electric_current operator"" _RA(long double);
scifir::electric_current operator"" _YA(long double);
scifir::electric_current operator"" _ZA(long double);
scifir::electric_current operator"" _EA(long double);
scifir::electric_current operator"" _PA(long double);
scifir::electric_current operator"" _TA(long double);
scifir::electric_current operator"" _GA(long double);
scifir::electric_current operator"" _MA(long double);
scifir::electric_current operator"" _kA(long double);
scifir::electric_current operator"" _hA(long double);
scifir::electric_current operator"" _daA(long double);
scifir::electric_current operator"" _A(long double);
scifir::electric_current operator"" _dA(long double);
scifir::electric_current operator"" _cA(long double);
scifir::electric_current operator"" _mA(long double);
scifir::electric_current operator"" _µA(long double);
scifir::electric_current operator"" _nA(long double);
scifir::electric_current operator"" _pA(long double);
scifir::electric_current operator"" _fA(long double);
scifir::electric_current operator"" _aA(long double);
scifir::electric_current operator"" _zA(long double);
scifir::electric_current operator"" _yA(long double);
scifir::electric_current operator"" _rA(long double);
scifir::electric_current operator"" _qA(long double);

scifir::voltage operator"" _QV(long double);
scifir::voltage operator"" _RV(long double);
scifir::voltage operator"" _YV(long double);
scifir::voltage operator"" _ZV(long double);
scifir::voltage operator"" _EV(long double);
scifir::voltage operator"" _PV(long double);
scifir::voltage operator"" _TV(long double);
scifir::voltage operator"" _GV(long double);
scifir::voltage operator"" _MV(long double);
scifir::voltage operator"" _kV(long double);
scifir::voltage operator"" _hV(long double);
scifir::voltage operator"" _daV(long double);
scifir::voltage operator"" _V(long double);
scifir::voltage operator"" _dV(long double);
scifir::voltage operator"" _cV(long double);
scifir::voltage operator"" _mV(long double);
scifir::voltage operator"" _µV(long double);
scifir::voltage operator"" _nV(long double);
scifir::voltage operator"" _pV(long double);
scifir::voltage operator"" _fV(long double);
scifir::voltage operator"" _aV(long double);
scifir::voltage operator"" _zV(long double);
scifir::voltage operator"" _yV(long double);
scifir::voltage operator"" _rV(long double);
scifir::voltage operator"" _qV(long double);

scifir::capacitance operator"" _QF(long double);
scifir::capacitance operator"" _RF(long double);
scifir::capacitance operator"" _YF(long double);
scifir::capacitance operator"" _ZF(long double);
scifir::capacitance operator"" _EF(long double);
scifir::capacitance operator"" _PF(long double);
scifir::capacitance operator"" _TF(long double);
scifir::capacitance operator"" _GF(long double);
scifir::capacitance operator"" _MF(long double);
scifir::capacitance operator"" _kF(long double);
scifir::capacitance operator"" _hF(long double);
scifir::capacitance operator"" _daF(long double);
scifir::capacitance operator"" _F(long double);
scifir::capacitance operator"" _dF(long double);
scifir::capacitance operator"" _cF(long double);
scifir::capacitance operator"" _mF(long double);
scifir::capacitance operator"" _µF(long double);
scifir::capacitance operator"" _nF(long double);
scifir::capacitance operator"" _pF(long double);
scifir::capacitance operator"" _fF(long double);
scifir::capacitance operator"" _aF(long double);
scifir::capacitance operator"" _zF(long double);
scifir::capacitance operator"" _yF(long double);
scifir::capacitance operator"" _rF(long double);
scifir::capacitance operator"" _qF(long double);

#ifdef IS_UNIX
scifir::resistance operator"" _QΩ(long double);
scifir::resistance operator"" _RΩ(long double);
scifir::resistance operator"" _YΩ(long double);
scifir::resistance operator"" _ZΩ(long double);
scifir::resistance operator"" _EΩ(long double);
scifir::resistance operator"" _PΩ(long double);
scifir::resistance operator"" _TΩ(long double);
scifir::resistance operator"" _GΩ(long double);
scifir::resistance operator"" _MΩ(long double);
scifir::resistance operator"" _kΩ(long double);
scifir::resistance operator"" _hΩ(long double);
scifir::resistance operator"" _daΩ(long double);
scifir::resistance operator"" _Ω(long double);
scifir::resistance operator"" _dΩ(long double);
scifir::resistance operator"" _cΩ(long double);
scifir::resistance operator"" _mΩ(long double);
scifir::resistance operator"" _µΩ(long double);
scifir::resistance operator"" _nΩ(long double);
scifir::resistance operator"" _pΩ(long double);
scifir::resistance operator"" _fΩ(long double);
scifir::resistance operator"" _aΩ(long double);
scifir::resistance operator"" _zΩ(long double);
scifir::resistance operator"" _yΩ(long double);
scifir::resistance operator"" _rΩ(long double);
scifir::resistance operator"" _qΩ(long double);
#endif

scifir::electric_conductance operator"" _QS(long double);
scifir::electric_conductance operator"" _RS(long double);
scifir::electric_conductance operator"" _YS(long double);
scifir::electric_conductance operator"" _ZS(long double);
scifir::electric_conductance operator"" _ES(long double);
scifir::electric_conductance operator"" _PS(long double);
scifir::electric_conductance operator"" _TS(long double);
scifir::electric_conductance operator"" _GS(long double);
scifir::electric_conductance operator"" _MS(long double);
scifir::electric_conductance operator"" _kS(long double);
scifir::electric_conductance operator"" _hS(long double);
scifir::electric_conductance operator"" _daS(long double);
scifir::electric_conductance operator"" _S(long double);
scifir::electric_conductance operator"" _dS(long double);
scifir::electric_conductance operator"" _cS(long double);
scifir::electric_conductance operator"" _mS(long double);
scifir::electric_conductance operator"" _µS(long double);
scifir::electric_conductance operator"" _nS(long double);
scifir::electric_conductance operator"" _pS(long double);
scifir::electric_conductance operator"" _fS(long double);
scifir::electric_conductance operator"" _aS(long double);
scifir::electric_conductance operator"" _zS(long double);
scifir::electric_conductance operator"" _yS(long double);
scifir::electric_conductance operator"" _rS(long double);
scifir::electric_conductance operator"" _qS(long double);

scifir::magnetic_flux operator"" _QWb(long double);
scifir::magnetic_flux operator"" _RWb(long double);
scifir::magnetic_flux operator"" _YWb(long double);
scifir::magnetic_flux operator"" _ZWb(long double);
scifir::magnetic_flux operator"" _EWb(long double);
scifir::magnetic_flux operator"" _PWb(long double);
scifir::magnetic_flux operator"" _TWb(long double);
scifir::magnetic_flux operator"" _GWb(long double);
scifir::magnetic_flux operator"" _MWb(long double);
scifir::magnetic_flux operator"" _kWb(long double);
scifir::magnetic_flux operator"" _hWb(long double);
scifir::magnetic_flux operator"" _daWb(long double);
scifir::magnetic_flux operator"" _Wb(long double);
scifir::magnetic_flux operator"" _dWb(long double);
scifir::magnetic_flux operator"" _cWb(long double);
scifir::magnetic_flux operator"" _mWb(long double);
scifir::magnetic_flux operator"" _µWb(long double);
scifir::magnetic_flux operator"" _nWb(long double);
scifir::magnetic_flux operator"" _pWb(long double);
scifir::magnetic_flux operator"" _fWb(long double);
scifir::magnetic_flux operator"" _aWb(long double);
scifir::magnetic_flux operator"" _zWb(long double);
scifir::magnetic_flux operator"" _yWb(long double);
scifir::magnetic_flux operator"" _rWb(long double);
scifir::magnetic_flux operator"" _qWb(long double);

scifir::magnetic_flux_density operator"" _QT(long double);
scifir::magnetic_flux_density operator"" _RT(long double);
scifir::magnetic_flux_density operator"" _YT(long double);
scifir::magnetic_flux_density operator"" _ZT(long double);
scifir::magnetic_flux_density operator"" _ET(long double);
scifir::magnetic_flux_density operator"" _PT(long double);
scifir::magnetic_flux_density operator"" _TT(long double);
scifir::magnetic_flux_density operator"" _GT(long double);
//scifir::magnetic_flux_density operator"" _MT(long double);
scifir::magnetic_flux_density operator"" _kT(long double);
scifir::magnetic_flux_density operator"" _hT(long double);
scifir::magnetic_flux_density operator"" _daT(long double);
//scifir::magnetic_flux_density operator"" _T(long double);
scifir::magnetic_flux_density operator"" _dT(long double);
scifir::magnetic_flux_density operator"" _cT(long double);
scifir::magnetic_flux_density operator"" _mT(long double);
scifir::magnetic_flux_density operator"" _µT(long double);
scifir::magnetic_flux_density operator"" _nT(long double);
scifir::magnetic_flux_density operator"" _pT(long double);
scifir::magnetic_flux_density operator"" _fT(long double);
scifir::magnetic_flux_density operator"" _aT(long double);
scifir::magnetic_flux_density operator"" _zT(long double);
scifir::magnetic_flux_density operator"" _yT(long double);
scifir::magnetic_flux_density operator"" _rT(long double);
scifir::magnetic_flux_density operator"" _qT(long double);

scifir::inductance operator"" _QH(long double);
scifir::inductance operator"" _RH(long double);
scifir::inductance operator"" _YH(long double);
scifir::inductance operator"" _ZH(long double);
scifir::inductance operator"" _EH(long double);
scifir::inductance operator"" _PH(long double);
scifir::inductance operator"" _TH(long double);
scifir::inductance operator"" _GH(long double);
scifir::inductance operator"" _MH(long double);
scifir::inductance operator"" _kH(long double);
scifir::inductance operator"" _hH(long double);
scifir::inductance operator"" _daH(long double);
scifir::inductance operator"" _H(long double);
scifir::inductance operator"" _dH(long double);
scifir::inductance operator"" _cH(long double);
scifir::inductance operator"" _mH(long double);
scifir::inductance operator"" _µH(long double);
scifir::inductance operator"" _nH(long double);
scifir::inductance operator"" _pH(long double);
scifir::inductance operator"" _fH(long double);
scifir::inductance operator"" _aH(long double);
scifir::inductance operator"" _zH(long double);
scifir::inductance operator"" _yH(long double);
scifir::inductance operator"" _rH(long double);
scifir::inductance operator"" _qH(long double);

scifir::temperature operator"" _celsius(long double);

scifir::luminous_flux operator"" _Qlm(long double);
scifir::luminous_flux operator"" _Rlm(long double);
scifir::luminous_flux operator"" _Ylm(long double);
scifir::luminous_flux operator"" _Zlm(long double);
scifir::luminous_flux operator"" _Elm(long double);
scifir::luminous_flux operator"" _Plm(long double);
scifir::luminous_flux operator"" _Tlm(long double);
scifir::luminous_flux operator"" _Glm(long double);
scifir::luminous_flux operator"" _Mlm(long double);
scifir::luminous_flux operator"" _klm(long double);
scifir::luminous_flux operator"" _hlm(long double);
scifir::luminous_flux operator"" _dalm(long double);
scifir::luminous_flux operator"" _lm(long double);
scifir::luminous_flux operator"" _dlm(long double);
scifir::luminous_flux operator"" _clm(long double);
scifir::luminous_flux operator"" _mlm(long double);
scifir::luminous_flux operator"" _µlm(long double);
scifir::luminous_flux operator"" _nlm(long double);
scifir::luminous_flux operator"" _plm(long double);
scifir::luminous_flux operator"" _flm(long double);
scifir::luminous_flux operator"" _alm(long double);
scifir::luminous_flux operator"" _zlm(long double);
scifir::luminous_flux operator"" _ylm(long double);
scifir::luminous_flux operator"" _rlm(long double);
scifir::luminous_flux operator"" _qlm(long double);

scifir::illuminance operator"" _Qlx(long double);
scifir::illuminance operator"" _Rlx(long double);
scifir::illuminance operator"" _Ylx(long double);
scifir::illuminance operator"" _Zlx(long double);
scifir::illuminance operator"" _Elx(long double);
scifir::illuminance operator"" _Plx(long double);
scifir::illuminance operator"" _Tlx(long double);
scifir::illuminance operator"" _Glx(long double);
scifir::illuminance operator"" _Mlx(long double);
scifir::illuminance operator"" _klx(long double);
scifir::illuminance operator"" _hlx(long double);
scifir::illuminance operator"" _dalx(long double);
scifir::illuminance operator"" _lx(long double);
scifir::illuminance operator"" _dlx(long double);
scifir::illuminance operator"" _clx(long double);
scifir::illuminance operator"" _mlx(long double);
scifir::illuminance operator"" _µlx(long double);
scifir::illuminance operator"" _nlx(long double);
scifir::illuminance operator"" _plx(long double);
scifir::illuminance operator"" _flx(long double);
scifir::illuminance operator"" _alx(long double);
scifir::illuminance operator"" _zlx(long double);
scifir::illuminance operator"" _ylx(long double);
scifir::illuminance operator"" _rlx(long double);
scifir::illuminance operator"" _qlx(long double);

scifir::radioactivity operator"" _QBq(long double);
scifir::radioactivity operator"" _RBq(long double);
scifir::radioactivity operator"" _YBq(long double);
scifir::radioactivity operator"" _ZBq(long double);
scifir::radioactivity operator"" _EBq(long double);
scifir::radioactivity operator"" _PBq(long double);
scifir::radioactivity operator"" _TBq(long double);
scifir::radioactivity operator"" _GBq(long double);
scifir::radioactivity operator"" _MBq(long double);
scifir::radioactivity operator"" _kBq(long double);
scifir::radioactivity operator"" _hBq(long double);
scifir::radioactivity operator"" _daBq(long double);
scifir::radioactivity operator"" _Bq(long double);
scifir::radioactivity operator"" _dBq(long double);
scifir::radioactivity operator"" _cBq(long double);
scifir::radioactivity operator"" _mBq(long double);
scifir::radioactivity operator"" _µBq(long double);
scifir::radioactivity operator"" _nBq(long double);
scifir::radioactivity operator"" _pBq(long double);
scifir::radioactivity operator"" _fBq(long double);
scifir::radioactivity operator"" _aBq(long double);
scifir::radioactivity operator"" _zBq(long double);
scifir::radioactivity operator"" _yBq(long double);
scifir::radioactivity operator"" _rBq(long double);
scifir::radioactivity operator"" _qBq(long double);

scifir::ionizing_radiation operator"" _QGy(long double);
scifir::ionizing_radiation operator"" _RGy(long double);
scifir::ionizing_radiation operator"" _YGy(long double);
scifir::ionizing_radiation operator"" _ZGy(long double);
scifir::ionizing_radiation operator"" _EGy(long double);
scifir::ionizing_radiation operator"" _PGy(long double);
scifir::ionizing_radiation operator"" _TGy(long double);
scifir::ionizing_radiation operator"" _GGy(long double);
scifir::ionizing_radiation operator"" _MGy(long double);
scifir::ionizing_radiation operator"" _kGy(long double);
scifir::ionizing_radiation operator"" _hGy(long double);
scifir::ionizing_radiation operator"" _daGy(long double);
scifir::ionizing_radiation operator"" _Gy(long double);
scifir::ionizing_radiation operator"" _dGy(long double);
scifir::ionizing_radiation operator"" _cGy(long double);
scifir::ionizing_radiation operator"" _mGy(long double);
scifir::ionizing_radiation operator"" _µGy(long double);
scifir::ionizing_radiation operator"" _nGy(long double);
scifir::ionizing_radiation operator"" _pGy(long double);
scifir::ionizing_radiation operator"" _fGy(long double);
scifir::ionizing_radiation operator"" _aGy(long double);
scifir::ionizing_radiation operator"" _zGy(long double);
scifir::ionizing_radiation operator"" _yGy(long double);
scifir::ionizing_radiation operator"" _rGy(long double);
scifir::ionizing_radiation operator"" _qGy(long double);

scifir::ionizing_radiation operator"" _QSv(long double);
scifir::ionizing_radiation operator"" _RSv(long double);
scifir::ionizing_radiation operator"" _YSv(long double);
scifir::ionizing_radiation operator"" _ZSv(long double);
scifir::ionizing_radiation operator"" _ESv(long double);
scifir::ionizing_radiation operator"" _PSv(long double);
scifir::ionizing_radiation operator"" _TSv(long double);
scifir::ionizing_radiation operator"" _GSv(long double);
scifir::ionizing_radiation operator"" _MSv(long double);
scifir::ionizing_radiation operator"" _kSv(long double);
scifir::ionizing_radiation operator"" _hSv(long double);
scifir::ionizing_radiation operator"" _daSv(long double);
scifir::ionizing_radiation operator"" _Sv(long double);
scifir::ionizing_radiation operator"" _dSv(long double);
scifir::ionizing_radiation operator"" _cSv(long double);
scifir::ionizing_radiation operator"" _mSv(long double);
scifir::ionizing_radiation operator"" _µSv(long double);
scifir::ionizing_radiation operator"" _nSv(long double);
scifir::ionizing_radiation operator"" _pSv(long double);
scifir::ionizing_radiation operator"" _fSv(long double);
scifir::ionizing_radiation operator"" _aSv(long double);
scifir::ionizing_radiation operator"" _zSv(long double);
scifir::ionizing_radiation operator"" _ySv(long double);
scifir::ionizing_radiation operator"" _rSv(long double);
scifir::ionizing_radiation operator"" _qSv(long double);

scifir::catalytic_activity operator"" _Qkat(long double);
scifir::catalytic_activity operator"" _Rkat(long double);
scifir::catalytic_activity operator"" _Ykat(long double);
scifir::catalytic_activity operator"" _Zkat(long double);
scifir::catalytic_activity operator"" _Ekat(long double);
scifir::catalytic_activity operator"" _Pkat(long double);
scifir::catalytic_activity operator"" _Tkat(long double);
scifir::catalytic_activity operator"" _Gkat(long double);
scifir::catalytic_activity operator"" _Mkat(long double);
scifir::catalytic_activity operator"" _kkat(long double);
scifir::catalytic_activity operator"" _hkat(long double);
scifir::catalytic_activity operator"" _dakat(long double);
scifir::catalytic_activity operator"" _kat(long double);
scifir::catalytic_activity operator"" _dkat(long double);
scifir::catalytic_activity operator"" _ckat(long double);
scifir::catalytic_activity operator"" _mkat(long double);
scifir::catalytic_activity operator"" _µkat(long double);
scifir::catalytic_activity operator"" _nkat(long double);
scifir::catalytic_activity operator"" _pkat(long double);
scifir::catalytic_activity operator"" _fkat(long double);
scifir::catalytic_activity operator"" _akat(long double);
scifir::catalytic_activity operator"" _zkat(long double);
scifir::catalytic_activity operator"" _ykat(long double);
scifir::catalytic_activity operator"" _rkat(long double);
scifir::catalytic_activity operator"" _qkat(long double);

#endif // SCIFIR_UNITS_UNITS_SPECIAL_NAMES_HPP_INCLUDED