#ifndef SCIFIR_UNITS_PREDEFINED_UNITS_BIOCHEMISTRY_UNITS_HPP_INCLUDED
#define SCIFIR_UNITS_PREDEFINED_UNITS_BIOCHEMISTRY_UNITS_HPP_INCLUDED

#include "units/scalar_unit.hpp"

using namespace std;

namespace scifir
{
	SCALAR_UNIT_HPP(catalytic_efficiency);
}

#endif // SCIFIR_UNITS_PREDEFINED_UNITS_BIOCHEMISTRY_UNITS_HPP_INCLUDED
