#ifndef MSCI_UNITS_PREDEFINED_UNITS_BIOCHEMISTRY_UNITS_HPP_INCLUDED
#define MSCI_UNITS_PREDEFINED_UNITS_BIOCHEMISTRY_UNITS_HPP_INCLUDED

#include "units/scalar_unit.hpp"

using namespace std;

namespace msci
{
	SCALAR_UNIT_HPP(catalytic_efficiency);
}

#endif // MSCI_UNITS_PREDEFINED_UNITS_BIOCHEMISTRY_UNITS_HPP_INCLUDED
