#ifndef SCIFIR_UNITS_PREDEFINED_UNITS_INFORMATICS_UNITS_HPP_INCLUDED
#define SCIFIR_UNITS_PREDEFINED_UNITS_INFORMATICS_UNITS_HPP_INCLUDED

#include "../units/scalar_unit.hpp"

using namespace std;

namespace scifir
{
	SCALAR_UNIT_HPP(transfer_speed);
}

#endif // SCIFIR_UNITS_PREDEFINED_UNITS_INFORMATICS_UNITS_HPP_INCLUDED
